design/use_cases/_template_use_case.md
design/use_cases/collision_avoidance_use_case.md
design/use_cases/indoor_localization_use_case.md
design/use_cases/indoor_navigation_use_case.md
design/use_cases/keep_out_zones_use_case.md
design/use_cases/multi-story-building_use_case.md
design/use_cases/outdoor_localization_use_case.md
design/use_cases/outdoor_navigation_use_case.md

Added the first set of use cases for review

First use cases for review and discussion

---

README.md

This overview is based on the current understanding of the existing ROS navigation system and the expected behavior of the new system to be the same. Feedback welcome.

Added Overview section to README

---

.gitignore
src/control/CMakeLists.txt
src/control/package.xml
src/mission_execution/CMakeLists.txt
src/mission_execution/package.xml
src/nav2_msgs/package.xml
src/navigation/CMakeLists.txt
src/navigation/package.xml
src/planning/CMakeLists.txt
src/planning/package.xml
src/robot/CMakeLists.txt
src/robot/package.xml
src/task/CMakeLists.txt
src/task/package.xml

I turned task and robot into actual packages that export their header files so that the other packages could pick them up without needing explicit paths. This seems to be more like the ros2 standard.
The rest is just cleanup to remove unnecessary statements given the new packages.

Cleaning up build exports and imports.

---

src/control/nav2_dwa_controller/CMakeLists.txt
src/control/nav2_dwa_controller/package.xml
src/libs/nav2_libs_msgs/CMakeLists.txt
src/libs/nav2_robot/CMakeLists.txt
src/libs/nav2_robot/package.xml
src/libs/nav2_tasks/CMakeLists.txt
src/libs/nav2_tasks/package.xml
src/libs/nav2_util/CMakeLists.txt
src/libs/nav2_util/package.xml
src/localization/nav2_amcl/CMakeLists.txt
src/localization/nav2_amcl/package.xml
src/mission_execution/nav2_mission_execution_msgs/CMakeLists.txt
src/mission_execution/nav2_mission_executor/CMakeLists.txt
src/mission_execution/nav2_mission_executor/package.xml
src/navigation/nav2_bt_navigator/CMakeLists.txt
src/navigation/nav2_bt_navigator/package.xml
src/navigation/nav2_simple_navigator/CMakeLists.txt
src/navigation/nav2_simple_navigator/package.xml
src/planning/nav2_astar_planner/CMakeLists.txt
src/planning/nav2_astar_planner/package.xml
src/planning/nav2_dijkstra_planner/CMakeLists.txt
src/planning/nav2_dijkstra_planner/package.xml
src/planning/nav2_planning_msgs/CMakeLists.txt
src/world_model/nav2_costmap_world_model/CMakeLists.txt
src/world_model/nav2_costmap_world_model/package.xml
src/world_model/nav2_world_model_msgs/CMakeLists.txt

There is a an existing set of ament packages that perform all the standard tests (eg uncrustify, cppcheck, etc) automatically.
Updating the code to use this new version.
I'll wait on starting a review until after I rebase from some of the other PRs that are about to go in.

Simplifying CMakelists to use the standard test suite.

---

src/control/nav2_dwa_controller/CMakeLists.txt
src/libs/nav2_libs_msgs/CMakeLists.txt
src/libs/nav2_robot/CMakeLists.txt
src/libs/nav2_tasks/CMakeLists.txt
src/libs/nav2_util/CMakeLists.txt
src/localization/nav2_amcl/CMakeLists.txt
src/mapping/nav2_map_server/CMakeLists.txt
src/mission_execution/nav2_mission_execution_msgs/CMakeLists.txt
src/mission_execution/nav2_mission_executor/CMakeLists.txt
src/navigation/nav2_bt_navigator/CMakeLists.txt
src/navigation/nav2_simple_navigator/CMakeLists.txt
src/planning/nav2_astar_planner/CMakeLists.txt
src/planning/nav2_dijkstra_planner/CMakeLists.txt
src/planning/nav2_planning_msgs/CMakeLists.txt
src/world_model/nav2_costmap_world_model/CMakeLists.txt
src/world_model/nav2_world_model_msgs/CMakeLists.txt

Addresses issue #68. Adds -Werror flag to all CMakeLists.txt.
Need to rebase before merging.

Add werror flag to CMakelists files

---

src/control/costmap_queue/package.xml
src/control/dwb_core/package.xml
src/control/dwb_critics/package.xml
src/control/dwb_plugins/package.xml
src/control/nav_2d_utils/package.xml

Due to a difference in the wording of the copyright template in the
linter and the one actually used in the source, the linter fails
these files. 
To resolve that problem, I'm removing the copyright
linter from the test set.Unfortunately, the only way to do that is to 
include every linter but the copyright one.

Removing ament_copyright linter from test set

---

src/libs/costmap_2d/CMakeLists.txt
src/libs/costmap_2d/include/costmap_2d/costmap_2d.h
src/libs/costmap_2d/include/costmap_2d/costmap_2d_ros.h
src/libs/costmap_2d/include/costmap_2d/inflation_layer.h
src/libs/costmap_2d/include/costmap_2d/observation.h
src/libs/costmap_2d/include/costmap_2d/observation_buffer.h
src/libs/costmap_2d/include/costmap_2d/obstacle_layer.h
src/libs/costmap_2d/include/costmap_2d/static_layer.h
src/libs/costmap_2d/include/costmap_2d/testing_helper.h
src/libs/costmap_2d/package.xml
src/libs/costmap_2d/plugins/inflation_layer.cpp
src/libs/costmap_2d/plugins/obstacle_layer.cpp
src/libs/costmap_2d/plugins/static_layer.cpp
src/libs/costmap_2d/plugins/voxel_layer.cpp
src/libs/costmap_2d/src/costmap_2d.cpp
src/libs/costmap_2d/src/costmap_2d_cloud.cpp
src/libs/costmap_2d/src/costmap_2d_markers.cpp
src/libs/costmap_2d/src/costmap_2d_publisher.cpp
src/libs/costmap_2d/src/costmap_2d_ros.cpp
src/libs/costmap_2d/src/footprint.cpp
src/libs/costmap_2d/src/layered_costmap.cpp
src/libs/costmap_2d/src/observation_buffer.cpp

In this PR, the static layer & inflation layer plugins have been ported and compile properly. After a manual inspection of the plugins, they appear to work fine and generate reasonable results, though some additional work needs to be done in order to incorporate the plugins properly in the Costmap2DROS class (particularly with parameters). 
Some intial work on the observation buffer was done but was blocked from completion until tf2_sensor_msgs is also ported (will file an issue). 
Also, Boost dependencies have been removed from costmap_2d.

Costmap_2d Static & Inflation plugin layer port & Removing Boost dependencies 

---

src/control/nav2_controller_example/CMakeLists.txt
src/localization/nav2_amcl/CMakeLists.txt
src/mission_execution/nav2_mission_executor/CMakeLists.txt
src/navigation/nav2_bt_navigator/CMakeLists.txt
src/navigation/nav2_simple_navigator/CMakeLists.txt
src/planning/nav2_astar_planner/CMakeLists.txt
src/planning/nav2_dijkstra_planner/CMakeLists.txt
src/world_model/nav2_costmap_world_model/CMakeLists.txt

Fixes #126 
This fixes the CMakeLists.txt throughout the repo so the executable targets depend on the library targets instead of including the library source files directly.

Changing executable build to use library instead of object files.

---

launch/core.launch.py
tools/ros2_dependencies.repos

To use this updated launch file, you need to update your ros2/launch repo to point to the version specified in the change to the repos file.
We can change the repo back when ros2/launch#144 is fixed.

Adding time delays to launch script.

---

nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d.h
nav2_costmap_2d/test/costmap_tester.cpp
nav2_costmap_2d/test/inflation_tests.cpp

For some reason, on Ubuntu 18.04, cmath functions are no longer
being added to the global namespace by default. To fix this, the
cmath header needs to be added and the hypot function scoped.
This should fix the CI build.

Declaring use of hypot function.

---

nav2_tasks/include/nav2_tasks/task_server.hpp

This problem would cause TaskServer to immediately call the execute
process, even before a command was received. Whether you were
affected by this bug depended on the state of the stack when the
Task Server was constructed.

Fixing uninitialized variable in Task Server.

---

nav2_controller/nav2_controller/package.xml
nav2_costmap_2d/include/nav2_costmap_2d/array_parser.h
nav2_costmap_2d/include/nav2_costmap_2d/cost_values.h
nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d.h
nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_publisher.h
nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.h
nav2_costmap_2d/include/nav2_costmap_2d/costmap_layer.h
nav2_costmap_2d/include/nav2_costmap_2d/costmap_math.h
nav2_costmap_2d/include/nav2_costmap_2d/footprint.h
nav2_costmap_2d/include/nav2_costmap_2d/inflation_layer.h
nav2_costmap_2d/include/nav2_costmap_2d/layer.h
nav2_costmap_2d/include/nav2_costmap_2d/layered_costmap.h
nav2_costmap_2d/include/nav2_costmap_2d/observation.h
nav2_costmap_2d/include/nav2_costmap_2d/observation_buffer.h
nav2_costmap_2d/include/nav2_costmap_2d/obstacle_layer.h
nav2_costmap_2d/include/nav2_costmap_2d/static_layer.h
nav2_costmap_2d/include/nav2_costmap_2d/testing_helper.h
nav2_costmap_2d/include/nav2_costmap_2d/voxel_layer.h

- changing emails for Oregon team
- fixing header guards from search replace on costmap_2d remap
I _believe_ that's the end of that PR. Let me know if there's anything else I missed. 
S

Cleanup from #107 

---

nav2_robot/CMakeLists.txt
nav2_robot/src/ros_robot.cpp
nav2_robot/test/CMakeLists.txt
nav2_robot/test/test_robot_class.cpp

- Created unit test to test Robot class:
The test class publishes fake odometry and pose messages and it will also listen to commended velocity to test all the methods of Robot class.
- Disabled parsing URDF file from robot class since we haven't figure out where to put the file yet.  Also, we still don't have a use for it.

Adding unit test to robot class and disable parsing URDF file

---

nav2_amcl/src/amcl_node.cpp
nav2_controller/dwb_core/include/dwb_core/dwb_core.h
nav2_controller/dwb_core/include/dwb_core/publisher.h
nav2_controller/dwb_core/src/dwb_core.cpp
nav2_controller/dwb_core/src/publisher.cpp
nav2_controller/dwb_critics/src/oscillation.cpp
nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.h
nav2_costmap_2d/include/nav2_costmap_2d/observation_buffer.h
nav2_costmap_2d/plugins/voxel_layer.cpp
nav2_costmap_2d/src/costmap_2d_ros.cpp
nav2_costmap_2d/src/observation_buffer.cpp
nav2_map_server/src/map_reps/occ_grid_server.cpp

To properly work with simulation_time, all calls to now() to get the current time need to be called on the node.
In several places in the code, where a node reference is not readily available, we use the pattern of creating a Clock() and calling now() on it. This is wrong. This pattern always returns wall time, even if the simulator is running.
Resolves #165

Changing calls to now() to always use a node reference instead of instantiating a clock object

---

nav2_mission_executor/src/mission_executor.cpp
nav2_robot/src/ros_robot.cpp
nav2_simple_navigator/src/simple_navigator.cpp
nav2_tasks/include/nav2_tasks/task_server.hpp

1). In the TaskServer template/base class, catch any exceptions generated by the derived class and return a failure status. 
2). Propagate this exception to the thread owning the object. 
3). Update the output messages in the SimpleNavigator to use the correct INFO, DEBUG, and ERROR macros instead of all using INFO. 
Fixes #142. Fixes #145.

Propagate task exceptions

---

nav2_util/CMakeLists.txt
nav2_util/include/nav2_util/duration_conversions.h
nav2_util/include/nav2_util/map_loader/map_loader.hpp
nav2_util/package.xml
nav2_util/src/costmap.cpp
nav2_util/src/map_loader/map_loader.cpp

Fixing linter failures in nav2_util

---

nav2_amcl/CMakeLists.txt
nav2_amcl/package.xml
nav2_amcl/test/integration/test_localization_launch.py
nav2_amcl/test/test_launch_files/localization_node.launch.py
nav2_controller/costmap_queue/CMakeLists.txt
nav2_controller/costmap_queue/package.xml
nav2_controller/costmap_queue/src/limited_costmap_queue.cpp
nav2_controller/costmap_queue/test/utest.cpp
nav2_controller/dwb_core/CMakeLists.txt
nav2_controller/dwb_core/package.xml
nav2_controller/dwb_critics/CMakeLists.txt
nav2_controller/dwb_critics/package.xml
nav2_controller/dwb_critics/src/base_obstacle.cpp
nav2_controller/dwb_critics/src/map_grid.cpp
nav2_controller/dwb_plugins/CMakeLists.txt
nav2_controller/dwb_plugins/package.xml
nav2_controller/nav2_controller_dwb/src/dwb_controller.cpp
nav2_controller/nav2_controller_example/include/nav2_controller_example/dwa_controller.hpp
nav2_controller/nav_2d_utils/CMakeLists.txt
nav2_controller/nav_2d_utils/package.xml
nav2_dijkstra_planner/package.xml
nav2_map_server/CMakeLists.txt
nav2_map_server/package.xml
nav2_util/package.xml

This fixes linter failures in all the controller packages, nav2_amcl and nav2_map_server.
This also fixes the way we remove the copyright linter from those packages and resolves #149

Fixing several linter failures

---

nav2_costmap_2d/plugins/static_layer.cpp
nav2_costmap_2d/src/costmap_2d_ros.cpp

This change makes use of the rclcpp Time and duration classes to simplify time conversion. The time conversions can be done with one step instead of multiple.
I'm not sure if it is strictly necessary, however, I think the result is a bit easier to understand

Cleanup of some time math and conversions between type.

---

nav2_amcl/src/amcl_node.cpp

Need to handle situation when amcl node is loaded but laser messages are not yet available.

Fixing small bug within AMCL: checking for the last laser message

---

tools/build_all.sh

Hit this issue when was following [https://github.com/ros-planning/navigation2/blob/master/doc/BUILD.md](https://github.com/ros-planning/navigation2/blob/master/doc/BUILD.md) on a clean machine.

Fail build if ROS1_DISTRO setup file does not exist 

---

nav2_costmap_2d/CMakeLists.txt
nav2_costmap_2d/include/nav2_costmap_2d/observation.h
nav2_costmap_2d/include/nav2_costmap_2d/observation_buffer.h
nav2_costmap_2d/include/nav2_costmap_2d/obstacle_layer.h
nav2_costmap_2d/src/observation_buffer.cpp
tools/ros2_dependencies.repos

tf2_sensor_msgs once merged into geometry2 should move back to their fork rather than mine which is identical except for this commit.
Deals with #132 as well as ports correctly the observation_buffer. This deals with elements needed to fully port obstacle layer

Port costmap2d buffer + tf_sensor_msgs local port 

---

nav2_costmap_2d/CMakeLists.txt
nav2_costmap_2d/plugins/inflation_layer.cpp
nav2_costmap_world_model/CMakeLists.txt
nav2_costmap_world_model/include/nav2_costmap_world_model/costmap_world_model.hpp
nav2_costmap_world_model/package.xml
nav2_costmap_world_model/src/costmap_world_model.cpp

The costmap stubbed code has now been replaced with an implementation using the costmap_2d package. In this change, a LayeredCostmap object is created and a static & inflation layer are manually added during the CostmapWorldModel construction. The static layer plugin is responsible for grabbing the static map from the map_server via the map topic.

Replacing  costmap stub with costmap_2d package in WorldModel

---

tools/ros2_dependencies.repos

It builds in the `ros_ws` directory which I believe is part of the daily builds. Should wait a day or two before removing to make sure its reflected.

remove my fork used for geometry2 after upstream merge

---

nav2_astar_planner/package.xml
nav2_bringup/package.xml
nav2_bt_navigator/package.xml
nav2_controller/dwb_core/package.xml
nav2_controller/nav2_controller_dwb/package.xml
nav2_costmap_world_model/package.xml
nav2_dijkstra_planner/package.xml
nav2_mission_executor/package.xml
nav2_msgs/package.xml
nav2_robot/package.xml
nav2_simple_navigator/package.xml
nav2_system_tests/package.xml
nav2_util/package.xml

Some of the packages used [http://download.ros.org/schema/package_format2.xsd](http://download.ros.org/schema/package_format2.xsd)
that requires package format to be set to `2`, but package format was
set to 3 instead.
This change makes them consistent.  As a result linter for packages
won't complain on this error.  Version 3 picked up because it is a superset of
version 2 with the addition of optional fields.

Consistent package format

---

.github/ISSUE_TEMPLATE.md

The OSRF template seems like a reasonable starting point for us too.
I think the first step is to create a template file in the repo, then it can be assigned as the default template in the github settings.
This should address #161

Adding initial issue template copied from OSRF RCLCPP template

---

nav2_tasks/CMakeLists.txt
nav2_tasks/include/nav2_tasks/bt_action_node.hpp
nav2_tasks/test/test_tasks.cpp

Adding a unit test for the TaskClient & TaskServer templates. The unit test is a bit unorthodox because we can't call rclcpp::init and rclcpp::shutdown multiple times in succession. Therefore, there is one test object that holds the context and multiple tests performed, but only one TEST_F. 
In another PR, I'll add tests for the Behavior Tree-related templates.

Add a unit test for the task client/server

---

nav2_bringup/README.md
nav2_bringup/launch/gazebo_rviz2_launch.py
nav2_bringup/launch/nav2_bringup_launch.py
nav2_world_model/src/world_model.cpp

---
| Primary platform tested on | Turtlebot3 |
--- 
With this change, the entire stack can more easily be run with two launch files.
* Added nav2_bringup_launch.py for launching the stack
* Added gazebo_rviz2_launch.py for launching Gazebo and RVIZ2 easily
* Fixed a bug where "GetCostmap" service was called "WorldModel_GetCostmap". This was causing the stack to hang
* Updated the nav2_bringup readme for running the new launch files
--- 
* Could change the parameters to be read in from a YAML file instead. I tried this but for some nodes it caused them to crash, I don't know why yet, so I decided to submit this as-is for now and we can enhance it …

Integration launch files

---

.gitignore

* Using Visual Studio Code, I've been opening just the directories that I'm interested in, avoiding the output directories - install, build, and log - because VS Code can't track this many files. In this configuration, when debugging various modules, the VS Code app will put .vscode files around the source hierarchy, in each source directory being debugged. This causes the directories to be highlighted in the editor indicating that files have been added to the directory. With this addition to .gitignore, these files will be ignored and the VS Code editor will more accurately reflect any changes to the workspace.

Ignore Visual Studio Code files

---

nav2_bt_navigator/include/nav2_bt_navigator/navigate_to_pose_behavior_tree.hpp
nav2_bt_navigator/src/bt_navigator.cpp
nav2_bt_navigator/src/navigate_to_pose_behavior_tree.cpp
nav2_simple_navigator/src/simple_navigator.cpp
nav2_tasks/include/nav2_tasks/bt_action_node.hpp
nav2_tasks/include/nav2_tasks/bt_conversions.hpp
nav2_tasks/include/nav2_tasks/compute_path_to_pose_action.hpp
nav2_tasks/include/nav2_tasks/costmap_service_client.hpp

* In this PR, the BT navigator code is now using the shared blackboard to communicate the input to the global planner and the output of the global planner (which is then the input for the local planner). This change requires that the blackboard be created before the run method (and passed to it) so that the variables can be put on the blackboard before the tree is built
* The BtNode base class now has an init() method that derive classes can override to read values off of the blackboard. This typically is used to set the input and output parameters for the task.
* The next PR will be to factor out the common code in the bt_navigator and mission_executor that executes the behavior tree. There is already a BehaviorTreeEngine class for this. Just need to update the two files to use it.
* …

Wire bt params

---

nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp
nav2_costmap_2d/src/costmap_2d_ros.cpp

| Primary platform tested on | Gazebo Turtlebot 3 |
--- 
* Removes the costmap_2d_ros movement callback. This call back would check every 1/10s to see if the robot had moved, and would set a flag. Nobody used the flag, so this removes the flag and the callback.
* Also accidentally cleans up trailing whitespace in the associated files.
---

Remove costmap movement callback

---

nav2_amcl/src/amcl_node.cpp

| Primary platform tested on | gazebo simulation  turtlebot |
--- 
* Disabling transform timeout in AMCL. The current ROS2 transform code deadlocks when there is a transform timeout and use_sim_time is active. The timeout clock can't advance because the transform code is in a tight loop, preventing the node from spinning and servicing clock messages. 
* It seems it doesn't matter much that AMCL fails to process the laser scans due to missing transform, because occasionally the transform is available, and we can get a fix.
--- 
Fix AMCL by re-introducing message filters, or finding some other wait to ensure a transform is available when there is laser …

Disabling transform timeout

---

nav2_dwb_controller/dwb_core/include/dwb_core/trajectory_critic.hpp
nav2_dwb_controller/dwb_core/src/dwb_core.cpp
nav2_dwb_controller/dwb_core/src/publisher.cpp
nav2_dwb_controller/dwb_critics/src/base_obstacle.cpp
nav2_dwb_controller/dwb_critics/src/map_grid.cpp
nav2_dwb_controller/dwb_critics/src/oscillation.cpp
nav2_dwb_controller/dwb_critics/src/prefer_forward.cpp
nav2_dwb_controller/dwb_critics/src/twirling.cpp

| Primary OS tested on |  Ubuntu  |
| Primary platform tested on | gazebo simulation of turtlebot) |
--- 
* Fixes dwb critic parameter naming such that each critic gets a prefix for it's parameters
* Adds back in the `debug_trajectory_details` parameter which had been accidentally deleted.
* Initializes all three color components of an invalid path, such that they always appear black. Sometimes they were showing up yellow, depending on initial conditions of the red and green components.
* Separates parameter prefixes with a `.` instead of a `/` because that is what the ROS2 parameter server seems to expect.

Dwb fixes to get reliable motion

---

nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp
nav2_costmap_2d/src/costmap_2d_publisher.cpp
nav2_costmap_2d/src/costmap_2d_ros.cpp
nav2_util/CMakeLists.txt
nav2_util/include/nav2_util/execution_timer.hpp
nav2_util/test/CMakeLists.txt
nav2_util/test/test_execution_timer.cpp

| Primary platform tested on | gazebo simulation of Turtlebot |
--- 
* The code to determine when to publish a new costmap was using ROS time. This caused the costmap to never get published if we changed to sim_time after the `last_publish_` value had been set. I changed it use std::chrono time instead. This way, the costmap always gets published at a regular interval, even if the simulation is paused, which IMHO is desirable.
* Fixed a bug in the logic that checks whether there are subscribers to the costmap topic before publishing. The logic was reversed.

Fix costmap publishing loop

---

nav2_costmap_2d/src/costmap_2d_ros.cpp

* There was a bug in #307 that would cause the mapUpdateLoop to throw an exception on the intial pass when it compared `last_publish_` to `now()`. The time from `now()` is RCL_ROS_TIME as expected, but the default time for `last_publish_` was `RCL_SYSTEM_TIME`. This fix makes sure the initial version of last_publish is `RCL_ROS_TIME`

Fixing last_publish_ time to be RCL_ROS_TIME by default.

---

nav2_world_model/include/nav2_world_model/world_model.hpp
nav2_world_model/src/main.cpp
nav2_world_model/src/world_model.cpp

---
| Ticket(s) this addresses   | #252  |
| Primary platform tested on | NUC |
--- 
- replaces the manual creation of the `layeredcostmap_` with the `costmap2DROS` node object
--- 
- Grab correct orientation information from costmap to put in service map metadata (currently a TODO)
---

Replace manual layered costmap with costmap2dROS object

---

nav2_costmap_2d/CMakeLists.txt
nav2_costmap_2d/include/nav2_costmap_2d/obstacle_layer.hpp
nav2_costmap_2d/package.xml
nav2_costmap_2d/plugins/inflation_layer.cpp
nav2_costmap_2d/plugins/obstacle_layer.cpp
nav2_costmap_2d/plugins/static_layer.cpp
nav2_costmap_2d/src/costmap_2d_ros.cpp

---
| Ticket(s) this addresses   | #192  |
| Primary platform tested on | NUC |
--- 
- port of obstacle layer
--- 
- re-enable message filters topic subscriptions when upstream changes in [ros2/geometry2/81](https://github.com/ros2/geometry2/pull/81) and [ros2/message_filters/pull/13](https://github.com/ros2/message_filters/pull/13) are merged 
---

Obstacle Layer Port

---

tools/initial_ros_setup.sh

Print a message that a function is skipped if a checkpoint file exists.
Hit this when was trying to repair a broken enlistment.  When I run `inital_ros_setup.sh` I got the error below and it was not immediately clear why the other steps are missing. 
```
$ ./initial_ros_setup.sh 
<...>
Are you sure you want to continue? [yN]
y
./initial_ros_setup.sh: line 102: /home/user/nav2/navigation2_ws/src/navigation2/tools/build_all.sh: No such file or directory
```
Adding printing in the `else` portion of `checkpoint` provides a clue of what's happening:
```
$ ./initial_ros_setup.sh 
<...>
Are you sure you want to continue? [yN]
y
.INITIAL_SETUP_download_navstack exists. Skipping download_navstack
.INITIAL_SETUP_download_ros2_dependencies exists. Skipping download_ros2_dependencies …
```

Improve output in initial_ros_setup.sh

---

nav2_amcl/src/amcl_node.cpp
nav2_amcl/src/amcl_node.hpp

This is a change to the default behavior of AMCL to subscribe to the map topic instead of trying to use the service to get the map. Currently getting the map through the service seems to hang. Not sure why that is. 
This change is needed to get the robot to move.
I also changed a couple of messages from INFO to DEBUG and changed the ERROR message for the laser scan transform to only report when 20 successive fails occur. This reduces the spew of ERRORS to the screen since this happens a lot (100's of times per second sometimes). This at least helps with debugging what's happening, it may or may not also free up some cycles for other work to get done.

Amcl use map topic

---

nav2_smart_planner/include/nav2_smart_planner/smart_planner.hpp
nav2_smart_planner/src/smart_planner.cpp

| Ticket(s) this addresses   | #304 |
| Primary platform tested on | (gazebo turtlebot) |
--- 
The artifact observed at the end of the path is originated from rounding errors when translating the goal and start poses from world continuous space to the discretized map representation.
The figure below shows an example. To the left we have a path generated with a 'hook' artifact on one end, to the right is a path (connecting the same start and end poses) but without artifact.

Planner hook fix

---

nav2_bringup/launch/nav2_bringup_launch.py

The latest turtlebot 3 and gazebo ros packages have changed the names of the frames they publish, the topics they publish/subscribe on. This updates the default launch file with the latest mappings.
Do not merge to master till you update your turtlebot packages.
---
Here are the current versions I'm running for comparison:
turtlebot3: 3423b19e5e (Friday Oct 26)
turtlebot3_msg: 6813d307f3d921 (Aug 16)
turtlebot3_simulations: 15aee4e4c (Nov 15)
gazebo_ros_pkgs: 73a12b7c9b (Sep 12)
Looking at those dates, it seems it must be the turtlebot3_simulations package only that really matters for this change.

Remapping fixes for the lastest Turtlebot 3 models

---

tools/ros2_dependencies.repos

currently the Travis build of master is failing. I can reproduce this on my system by building the dockerfile locally. 
Error:
--- stderr: dwb_plugins
/ros2_ws/navigation2_ws/src/navigation2/nav2_dwb_controller/dwb_plugins/src/simple_goal_checker.cpp:38:10: fatal error: angles/angles.h: No such file or directory
#include "angles/angles.h"
^~~~~~~~~~~~~~~~~

Add angles back to ros2_dependencies to fix master build

---

nav2_amcl/src/amcl_node.cpp
nav2_amcl/src/amcl_node.hpp
nav2_amcl/src/main.cpp

This change addresses #339 and should be removed when message filters are available again (Issue #171)
---
| Ticket(s) this addresses   |#171, #339  |
| Primary OS tested on | Ubuntu) |
| Primary platform tested on | Gazebo turtlebot 3 |
--- 
* Adds a separate node that can be spun independently of the amcl node, for the sole purpose of allowing the clock to advance when waiting for a transform timeout.
* Adds a transform timeout to AMCL transform calls so they don't fail as often as the sometimes do currently.

Amcl  workaround for lack of message_filters

---

nav2_costmap_2d/src/costmap_2d_ros.cpp

Bug Fix: The robot footprint was never being updated when setting the "footprint" or "robot_radius" parameters during run-time, thus it remained at its initial value. This bug was due to an incorrect logical operator checking whether the dynamic parameter was part of the parameter event.
I mistakenly had used the wrong logical operator (OR instead of AND), preventing the footprint to be updated dynamically.

fixing costmap_2d_ros logic operator bug

---

nav2_robot/src/robot.cpp

One line change to fix robot class. Instead of "cmdVelocity" it is fixed to "cmd_vel" which is the standard.

Fix robot class to use cmd_vel topic

---

nav2_amcl/CMakeLists.txt
nav2_bt_navigator/CMakeLists.txt
nav2_costmap_2d/CMakeLists.txt
nav2_dynamic_params/CMakeLists.txt
nav2_map_server/CMakeLists.txt
nav2_mission_executor/CMakeLists.txt
nav2_robot/CMakeLists.txt
nav2_simple_navigator/CMakeLists.txt
nav2_smart_planner/CMakeLists.txt
nav2_tasks/CMakeLists.txt
nav2_util/CMakeLists.txt
nav2_voxel_grid/CMakeLists.txt
nav2_world_model/CMakeLists.txt

| Ticket(s) this addresses   | Action item from weekly Navigation WG meeting |
| Primary platform tested on | Gazebo 9 |
--- 
* Use position-independent code (-fPIC) for code that's in shared libraries.
* Make other non-node libraries SHARED as well since they could be used by nodes
in node libraries and this code also needs to be position independent.

Make node libraries SHARED objects instead of static link libraries.

---

nav2_costmap_2d/CMakeLists.txt

Per our previous discussions. 
The smart planner PR contains the planners' conversion over to this mantra as well

changing last *_node executable and adding library as *_core

---

nav2_dwb_controller/dwb_plugins/CMakeLists.txt

The `stopped_goal_checker` library was not getting the dependency on the `libsimple_goal_checker.so` set by the `ament_target_dependencies` call. That call is only appropriate for external package dependencies. Dependencies that internal to the same package need to be specified using standard cmake.
The symptom of this bug was that plugin lib failed to load `libstopped_goal_checker.so`
I wasn't able to properly test that this plug in stops the robot at the end due to the current defect in AMCL localization. There is a commit ( 91f47ec ) on the integtation-debug2 branch where I've enabled this by default, but I'm not sure if we want to put this on master. I figure on master, we should just set this parameter through the launch file

Fix loading of stopped goal checker.

---

nav2_bringup/launch/nav2_bringup_launch.py

---
| Robotic platform tested on |gazebo simulation of TB3 |
---
* Updates the bringup launch file to be compatible with the latest Turtlebot 3 topic and frame names.
* This should be compatible with turtlebot3_simulations  ROBOTIS-GIT/turtlebot3_simulations@41db458a5 or newer. In other words, newer than Nov 18, 2018.

Tb3 latest remappings

---

nav2_costmap_2d/plugins/inflation_layer.cpp
nav2_costmap_2d/plugins/obstacle_layer.cpp
nav2_costmap_2d/plugins/static_layer.cpp
nav2_costmap_2d/plugins/voxel_layer.cpp
nav2_costmap_2d/src/costmap_2d_ros.cpp

| Robotic platform tested on | Gazebo simulation of TB 3  |
---
* This change effectively disables dynamic reconfigure in costmap and forces it to get parameters directly off the node.
* This is needed due to race conditions in dynamic parameter client due to the use of a seperate SyncParametersClient. When working with parameters on the same node, this has issues when run in a blocking thread.

Disable dynamic parameters to allow stable costmap startup.

---

nav2_amcl/src/amcl_node.cpp

| Robotic platform tested on | Gazebo TB3 |
---
* Frequently when AMCL starts up it complains about transform data being too old
```
[amcl]: Failed to transform initial pose in time (Lookup would require extrapolation into the future.  Requested time 1543368480.84859 but the latest data is at time 1135.54000, when looking up transform from frame [odom] to frame [base_footprint]
```
* Watching the actual time stamps of the laser scans being put out by Gazebo and the AMCL error message, it appeared AMCL was trying to transform laser scans that were 30s old.
* This change limits the queue depth so we only process current data
* This seems to make bring up much …

Fixing problem with AMCL trying to transform old data.

---

nav2_costmap_2d/plugins/obstacle_layer.cpp

---
| Robotic platform tested on |  Gazebo Turtlebot 3|
---
* The obstacle layer listens to laser scan messages and accepts two types: PointCloud2 or LaserScan. The type gets specified in a parameter, however, the default value for that parameter is PointCloud, which is invalid. This change makes the default value a valid type. I've chosen the type provided by Turtlebot 3 which is LaserScan
---
* Add obstacle layer parameters to the launch file. I've got a change for that locally.
* Add message filters back to obstacle layer.

Default to a valid laser scan message type.

---

nav2_bringup/README.md
nav2_bringup/launch/nav2_bringup_1st_launch.py
nav2_bringup/launch/nav2_bringup_2nd_launch.py

This updates the readme with instructions for testing on a robot

Update nav2_bringup readme for robot

---

.travis.yml
Dockerfile

| Ticket(s) this addresses   | (N/A) |
| Robotic platform tested on | (N/A) |
---
It is the response to the discussion in #389.  I updated Travis, so it errors if it runs in any repo but ros-planning/navigation2.  Added retries for `wget`.  For some reasons, I cannot download the entire archive without retries, probably due to my physical location.  The other changes are about the ability to customize GitHub username and branch while running Docker.  The default has not been changed.
Hope this is a better PR than the previous one.
@SteveMacenski, @mkhansen-intel

Define USER and BRANCH in the Docker image

---

tools/ros2_dependencies.repos

| Ticket(s) this addresses   | Resolves #274 |
| Robotic platform tested on | TB3 in gazebo |
---
* Removes message filters from the additional ROS 2 dependencies. It is part of base ROS 2 now.

Remove the old message filters dependency.

---

nav2_bt_navigator/CMakeLists.txt
nav2_bt_navigator/behavior_trees/parallel.xml
nav2_bt_navigator/src/bt_navigator.cpp
nav2_bt_navigator/src/navigate_to_pose_behavior_tree.cpp
nav2_mission_executor/CMakeLists.txt
nav2_tasks/CMakeLists.txt
nav2_tasks/include/nav2_tasks/behavior_tree_engine.hpp
nav2_tasks/include/nav2_tasks/bt_action_node.hpp
nav2_tasks/include/nav2_tasks/bt_conversions.hpp
nav2_tasks/include/nav2_tasks/rate_controller_node.hpp
nav2_tasks/src/behavior_tree_engine.cpp
tools/ros2_dependencies.repos

| Primary platform tested on | NUC, HP Envy |
--- 
* Update the BehaviorTree.CPP library to the latest version. This version fixes a few issues
- M_PI macro undefined on Ubuntu 18.04
- New ParallelNode constructor added so that it can be registered with the bt_factory 
- ParallelNode is registered in the library so that it can be used in XML
--- 
* What remains is to provide a PR to the BehaviorTree repo for the colcon-enabled CMakeLists.txt
* Work with @SteveMacenski to understand how we can incorporate this library into our official build

Update behavior tree cpp

---

nav2_costmap_2d/plugins/inflation_layer.cpp
nav2_costmap_2d/plugins/obstacle_layer.cpp
nav2_costmap_2d/plugins/static_layer.cpp
nav2_costmap_2d/plugins/voxel_layer.cpp
nav2_costmap_2d/src/costmap_2d_ros.cpp
nav2_dynamic_params/include/nav2_dynamic_params/dynamic_params_client.hpp

---
| Ticket(s) this addresses   | #352  |
---
- Addresses potential issue of race condition in creating a SyncParameterClient inside of the DynamicParamsClient when adding a new parameter from its own node in the constructor
- reverts the `get_parameter` calls in the reconfigureCB() back to `get_event_param`
- Since the dynamic reconfigureCB() are now grabbing parameters from DynamicParamsClient again, they are sensitive to duplicate parameter names in the same namespace. This should be resolved by #394. Will also be resolved with closing of issue #337

List/Get parameters from node instead of SyncParameterClient if using own node

---

nav2_dynamic_params/include/nav2_dynamic_params/dynamic_params_client.hpp

---
---
- The `get_event_param` call would assume the root namespace if not specified, which would lookup the incorrect parameter name in the internal parameter map for nodes with namespaces. This PR fixes this to grab the namespace of the member node if not specified otherwise in the function call

get namespace from node for get_event_param() variant

---

nav2_amcl/package.xml
nav2_costmap_2d/package.xml
nav2_dwb_controller/dwb_controller/package.xml
nav2_dwb_controller/nav2_dwb_controller/package.xml
nav2_dwb_controller/nav_2d_utils/package.xml
nav2_map_server/package.xml
nav2_voxel_grid/package.xml
navigation2/package.xml

| Ticket(s) this addresses   | #334 |
---
* Ensures all package.xml files are self-consistent and consistent across the repo.
* Standardizes on version 3 of the package.xml format.
* This fixes some xmllint errors

Make all package.xml files consistently use format 3.

---

navigation2/package.xml

---
| Ticket(s) this addresses   | #334 |
| Robotic platform tested on | (N/A) |
---
Fix the warning below.  The discussion [https://github.com/ros2/ros2/issues/408](https://github.com/ros2/ros2/issues/408) describes the recommended way for fixing it in ROS2. 
```
WARNING: Metapackage "navigation2" must buildtool_depend on catkin.
WARNING: Metapackage "navigation2" should not have other dependencies besides a buildtool_depend on catkin and run_depends.
```
Note that this is just a warning, so techically it is not a failing issue, but it helps keep the output clean.

Don't use metapackage, since it is not recommended in ROS2

---

nav2_motion_primitives/src/spin.cpp

---
| Ticket(s) this addresses   | (NA) |
---
---
Master fails to compile due to ```tf2/impl/utils.h:114:2: error: extra ‘;’ [-Werror=pedantic]
};```

Ignoring pedantic to fix compilation error

---

nav2_motion_primitives/package.xml

| Ticket(s) this addresses   | Resolves #431 |
---
* Bumps nav2_motion_primitives version to 0.1.1 to match others. Required for bloom release.

Fix nav2_motion_primitives version to match other packages

---

tools/ros2_dependencies.repos

* Use the newly-created 'ros2' branch of the BehaviorTree.CPP library

Use new ros2 branch of the BehaviorTree.CPP library

---

nav2_dwb_controller/dwb_plugins/CMakeLists.txt
nav2_dwb_controller/dwb_plugins/test/CMakeLists.txt
nav2_dwb_controller/dwb_plugins/test/goal_checker.launch
nav2_dwb_controller/dwb_plugins/test/twist_gen.cpp
nav2_dwb_controller/dwb_plugins/test/twist_gen.launch

| Ticket(s) this addresses   | Resolves #353. Resolves #365 |
| Robotic platform tested on |  NA  |
---
* Fixed build failures that sometimes occurred in dwb_plugins tests. They are now built as gtest executables instead of just executables.
* The tests no longer require rostest. They are just standard gtest executables and can be launched without a launch file or other support.
* Enabled the goal_checker test so it will be run by `colcon test`
---
* Need to re-enable the `twist_gen_test` however it is dependent on getting kinematic parameters as node parameters. Right now they are hard coded.
---

Fix dwb_plugin test build

---

nav2_navfn_planner/include/nav2_navfn_planner/navfn.hpp
nav2_navfn_planner/src/navfn.cpp
nav2_navfn_planner/src/navfn_planner.cpp

| Ticket(s) this addresses   | #334 |
---
* Fixing uncrustify failure.
* Copyright format had to be modified to pass linter. More on this [here](https://github.com/ament/ament_lint/issues/72).

Fixing linter issues on nav2_navfn_planner

---

nav2_bringup/README.md
nav2_bringup/config/nav2_default_view.rviz
nav2_bringup/launch/nav2_bringup_2nd_launch.py
nav2_bringup/launch/nav2_bringup_launch.py
nav2_bringup/launch/nav2_params.yaml
nav2_costmap_2d/plugins/static_layer.cpp
nav2_costmap_2d/src/costmap_2d_ros.cpp

| Robotic platform tested on |  Gazebo Turtlebot 3 |
---
* Costmaps now put themselves into a namespace that is the same as the node name assigned in code.
* Updates the RVIZ default config to map the new topic names, so both global and local costmap topics can be displayed independently.
* Adds a nav2_params.yaml file to the launch directory and sets a couple of parameters on the DwbController node and the local_costmap node.
* Due to the way parameter events work, each namespace in use needs to have the `use_sim_time` variable set to switch the nodes in that namespace. Since this change causes us to have 3 namespaces (`root`, `global_costmap`, and …

Put local and global costmaps into separate namespaces

---

nav2_bringup/launch/nav2_bringup_launch.py

---
Removes the static transform publishers from the nav2_bringup_launch.py file.
These were a work-around since we didn't have a fully working tf tree. We now have one available (turtlebot3) and documented as an example in the bringup README. 
We've already removed this from the "bringup_1st" launch file also, so this was an oversight.

Remove static tf publishers from bringup launch file

---

nav2_tasks/include/nav2_tasks/bt_conversions.hpp

Previously, the BT Library required (incorrectly) that any item used on the blackboard must also have a function for reading it from a string. This should have only been required for items that were used as parameters (not items on the blackboard). Davide has fixed this and the fix is present in the ros2 branch of the library that we're using, rendering this code unnecessary.

Remove bt_conversions work around (now fixed)

---

nav2_bringup/launch/nav2_params.yaml
nav2_costmap_2d/plugins/obstacle_layer.cpp

| Robotic platform tested on | Turtlebot3 Gazebo |
---
- sets default for observation_layer sensor marking observations to True
- adds clearing observation parameter set to True for scan sensor
- fixes `raytrace_range` assignment bug/error
- with above changes, obstacles can be detected and cleared in real time 
---
- Though obstacles were detected, sometimes the local planner failed to find a valid path even though global planner would create a valid path. Should further test to see why this would be the case given a valid costmap.

Enable obstacle_layer marking/clearing observations

---

nav2_system_tests/CMakeLists.txt
nav2_system_tests/package.xml
tools/ros2_dependencies.repos

---
Removes gazebo_ros_pkgs from the dependencies for nav2_system_tests. They should still build fine but won't run without those packages installed. This should hopefully fix the build and we can find another solution later.

Fix Travis build - remove gazebo_ros_pkgs dependency

---

nav2_tasks/CMakeLists.txt
nav2_tasks/package.xml

---
| Ticket(s) this addresses   | Failing package builds on build.ros2.org |
| Primary OS tested on | Ubuntu Bionic |
---
This change attempts to address build failures of packages which depend on nav2_tasks.
The nav2_tasks CMake currently exports dependencies that are not declared as `build_export_depend` in its package.xml. I'm not familiar with the nav2_tasks package but a cursory inspection suggests it doesn't need to be exporting these dependencies.
Exporting dependencies is not required in all situations.
The documentation escapes me right now but exporting dependencies is
used for:
* Dependencies whose C/C++ types will be present in your package's
* Dependencies whose interfaces …

Update dependencies exported by nav2_tasks.

---

nav2_bringup/CMakeLists.txt
nav2_bringup/package.xml

---
| Ticket(s) this addresses   | #477 Update Exported Dependencies|
| Robotic platform tested on | NA - made sure the launch files are still installed and working |
---
---
Removes extra dependencies from nav2_bringup CMakeLists and package.xml

Remove unneeded depends from nav2_bringup

---

nav2_map_server/CMakeLists.txt
nav2_map_server/include/nav2_map_server/map_generator.hpp
nav2_map_server/src/map_generator.cpp
nav2_map_server/src/map_saver.cpp

Follow on PR to #462 - Port Map Saver
Refactors the MapGenerator class out of map_saver.cpp into map_generator.cpp
There's still a bug to fix where the wrong values for occupied threshold and free threshold are written to the yaml file - that will have to be a separate PR - I'll file an issue for it

Refactor map saver

---

nav2_costmap_2d/src/costmap_2d_ros.cpp

It seems the Costmap plugins run in order, so if you want the obstacles to
be inflated, then obstacle needs to come before inflation in the
list.
This changes the default ordering for that to happen, because that
seems to be the preferred default behavior

Inflate obstacles by default.

---

nav2_dwb_controller/costmap_queue/include/costmap_queue/costmap_queue.hpp

| Ticket(s) this addresses   |  NA  |
---
* Since originally writing these pragmas, I've learned a better way of disabling the unused parameter warning from @orduno This change just cleans up the code a smidge.

Cleaner way to disable unused param warning.

---

nav2_motion_primitives/include/nav2_motion_primitives/motion_primitive.hpp

---
| Ticket(s) this addresses   | (#491 ) |
| Robotic platform tested on | ( gazebo simulation of turtlebot) |
---
* Fixed a bug with motion primitive base class. After a primitive is cancelled, velocity should be set to zero.

Robot velocity should be set to zero after primitive is cancelled

---

nav2_dynamic_params/README.md
nav2_dynamic_params/include/nav2_dynamic_params/dynamic_params_client.hpp
nav2_dynamic_params/src/example_dynamic_params_client.cpp

| Ticket(s) this addresses   | #337  |
---
- Since the update to parameter events now containing full path to node inside the event message, this PR updates the `DynamicParamsClient` to add and resolve the full path of the parameter by node path.
- Now, duplicate parameters may exist across different nodes in any namespace without conflict when receiving a parameter event
- This also fixes an apparent bug from a recent PR where getting parameters from the node (as opposed to the parameter client) does not return a PARAMETER_NOT_SET value for parameters that have yet to be set on the node, but skips it entirely when adding to internal map. Since we want to track all parameters added …

Resolve full node path for parameter events

---

.travis.yml
nav2_robot/include/nav2_robot/robot.hpp
nav2_robot/src/robot.cpp
nav2_robot/test/test_robot_class.cpp

---
| Ticket(s) this addresses   | (#163) |
---
Addressing first TODO items of issue #163.
- Renamed `getCurrentVelocity` to `getOdometry` which contains both odometry pose and twist.
- Renamed `getCurrentPose` to `getGlobalLocalizerPose`.  This way we know this is the estimated pose from the localizer and not the odometry.
---
- Do the remaining of the TODO's.

Renaming getCurrentVelocity and getCurrentPose to address #163

---

nav2_bt_navigator/CMakeLists.txt
nav2_bt_navigator/behavior_trees/auto_localization.xml
nav2_bt_navigator/behavior_trees/auto_localization_w_parallel_recovery.xml
nav2_bt_navigator/include/nav2_bt_navigator/navigate_to_pose_behavior_tree.hpp
nav2_bt_navigator/package.xml
nav2_bt_navigator/src/bt_navigator.cpp
nav2_bt_navigator/src/navigate_to_pose_behavior_tree.cpp
nav2_robot/src/robot.cpp
nav2_tasks/CMakeLists.txt
nav2_tasks/include/nav2_tasks/global_localization_service_client.hpp
nav2_tasks/include/nav2_tasks/is_localized_condition.hpp
nav2_tasks/include/nav2_tasks/navigate_to_pose_task.hpp
nav2_tasks/package.xml

---
| Ticket(s) this addresses   | #503  |
| Robotic platform tested on | gazebo simulation with turtlebot |
---
Note: I will fix the CI failure before merge. 
- Implemented Simple AutoLocalization with BT for differential type robots.
- Figure below shows the AutoLocalization BT branch.
---
- Expand it to other type of robots
- Currently the spin and back_up motion primitives are time based. Will need to modify the tree once the motion primitives support distance and angle.
---

Amcl auto localization

---

nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp

| Robotic platform tested on | Turtlebot 3 on Gazebo |
---
* DWB main loop was just using a constant sleep at the end of the loop. Replaced this with a rclcpp::Rate object.
* DWB main loop was while(true). This prevented a clean shutdown. Replaced it with while(rclcpp::ok())
* Printing out a time as part of the publishing velocity message to see the real publishing rate.
---
* Optimization of DWB. The real publishing rate always fails to achieve the desired rate, at least with a debug build.

DWB main loop fixes

---

nav2_dwb_controller/dwb_core/include/dwb_core/publisher.hpp
nav2_dwb_controller/dwb_core/src/publisher.cpp

| Ticket(s) this addresses   | fixes #447  |
| Robotic platform tested on | TB3 on Gazebo |
---
* Code now ensures all markers are properly deleted. The trajectory markers are divided into two namespaces, one for valid trajectories and the other for invalid. Marker IDs are independent in the two namespaces, so both namespaces need to be cleaned up separately.
* Changed the valid trajectory color scheme to be solid blue for good trajectories, fading away for poor trajectories.
---
* The color scheme might need tweaking to better see what's going on. It seems trajectory scores right now are all clustered around the really good score and it is hard to see any difference. However, I think the …

Fix DWB trajectory visualization

---

nav2_dwb_controller/costmap_queue/src/costmap_queue.cpp

| Ticket(s) this addresses   | fixes #451  |
| Robotic platform tested on | Turtlebot 3 on Gazebo |
---
* Fix costmap queue. The getNextCell function pulls off the head of the queue, but also enqueues adjacent cells. The previous implementation would reference the head of the, add adjacent cells, and then pop the head. Unfortunately, under certain circumstances, the newly enqueued cells would become the new head of the queue and get popped instead of the cell that was just processed. This change fixes that problem

Fix costmap queue expansion

---

Dockerfile

A couple of things changed, rosdistro2 has been homologated with its upstream + container may have been updated and didn't remove the rosdep initialization cache

removing rosdep cache for new initialization

---

nav2_dynamic_params/CMakeLists.txt
nav2_dynamic_params/include/nav2_dynamic_params/dynamic_params_client.hpp
nav2_dynamic_params/test/CMakeLists.txt
nav2_dynamic_params/test/dynamic_params_test.launch.py
nav2_dynamic_params/test/test_dynamic_params_client.cpp
nav2_dynamic_params/test/test_dynamic_params_helper.cpp
nav2_dynamic_params/test/test_dynamic_params_validator.cpp

---
| Ticket(s) this addresses   | #251  |
- Added gtests for `DynamicParamsValidator` and `DynamicParamsClient`
- added interfaces to `is_in_event` to scope by node path
- changed event callback to class member function instead of lambda function
- added `get_param_from_node` function to fix hanging bug with `SyncParameterClient` which was occasionaly hanging when listing or getting parameters, now uses `AsyncParameterClient` with a timeout and a variable number of re-attempts

Add Dynamic params tests

---

nav2_amcl/src/amcl_node.cpp
nav2_dwb_controller/dwb_plugins/test/twist_gen.cpp
nav2_tasks/include/nav2_tasks/service_client.hpp
tools/ros2_dependencies.repos

| Ticket(s) this addresses   |  NA  |
| Robotic platform tested on | Turtlebot 3 on Gazebo |
---
* The build is broken due to ros2/rclcpp#622. This PR fixes the build.
* I temporarily changed the upstream gazebo_ros_pkgs repo to point to my fork until ros-simulation/gazebo_ros_pkgs#887 is integrated.
* I added the gazebo_ros_pkgs dependencies to the `ros2_dependencies.repos` files to make it easier to work with them locally. No need to use rosdep to build them. This will help avoid bringing in lots of ros-crystal dependencies in the future if their dependency list every changes as noted in #558.
* I changed the image_common repo to point to my fork until ros-perception/image_common#120 is …

Fixing the broken build

---

Dockerfile.crystal

| Ticket(s) this addresses   | related to #421 |
---
* This new docker file builds against the Cyrstal release instead of ROS2 master, and relies entirely on `rosdep` to bring in dependencies. It is intended to be used to test the crystal-devel branch, and maybe make a crystal dockerhub image.

Add docker file that builds against crystal release for use in testing the crystal-devel branch

---

nav2_bt_navigator/CMakeLists.txt
nav2_system_tests/src/system/CMakeLists.txt
nav2_system_tests/src/system/test_system_launch.py
tools/ctest_retry.bash
tools/run_test_suite.bash

| Ticket(s) this addresses   | fixes #542 |
---
* Creates a new system test that runs the BT Navigator node.
* Installs the XML bt navigator config files.
* Enhances the `ctest_retry.bash` script to:
* avoid the need to copy it in to the nav2_system_test build folder.
* display test output
* allow running only one system test at a time so they can be retried individually instead of all together.

Add BT Navigator System Test

---

nav2_tasks/include/nav2_tasks/back_up_action.hpp
nav2_tasks/include/nav2_tasks/bt_action_node.hpp
nav2_tasks/include/nav2_tasks/compute_path_to_pose_action.hpp
nav2_tasks/include/nav2_tasks/follow_path_action.hpp
nav2_tasks/include/nav2_tasks/navigate_to_pose_action.hpp
nav2_tasks/include/nav2_tasks/spin_action.hpp
nav2_tasks/include/nav2_tasks/stop_action.hpp

* At our request, Davide added an onInit function to the BT node base class. We can now use this to initialize BT nodes since the blackboard is available when onInit is called.
* This replaces our own onInit; effectively this "first time" checking in the tick() method is now moved into the library itself.
* Since Davide has shared with us a method to use complex constructors for BT nodes instead of the standard two-argument constructor, we can avoid using the blackboard for some data and pass it directly to the node constructors.
* Might want to avoid making the classes derived from BtActionNode have to call BtActionNode::onInit. Could avoid this by renaming our own initialize function. That way, the BtActionNode base class would be called from the BT framework it would in turn call the …

Use the new onInit method from BT library

---

nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp

| Ticket(s) this addresses   | fixes #564  |
| Robotic platform tested on | TB3 on Gazebo |
---
* Moved the DWB initialize call from the Execute method to the constructor.
* I ran Valgrind and saw a bunch of leaks related to loading the plugins in DWB and Costmap. By moving this code to the constructor, it only runs once. This makes more sense logically and makes DWB a bit faster to start moving.

Fix DWB memory leak

---

nav2_bt_navigator/package.xml
nav2_tasks/package.xml

These two packages were missing a dependency on `std_srvs` in their package.xml. This PR fixes that.

Fixing missing dependencies

---

nav2_bringup/launch/nav2_params.yaml

| Ticket(s) this addresses   | fixes #514  |
| Robotic platform tested on | Turtlebot 3 on Gazebo |
---
* I set the XY speed limit to a large value. This way even if the Y speed is high in the odom data, the robot continues to have X speed to maneuver with. The robot will still think it is slipping sideways resulting in a maneuver that tries to compensate, but it at least won't fail saying there are no valid trajectories.
* There is maybe an increased chance of collision due to the robot continuing to maneuver with faulty data, however, I see no increase in system test failures.
This can be reverted if ROBOTIS-GIT/turtlebot3_simulations#75 is fixed

Workaround for sliding sideways bug

---

nav2_costmap_2d/include/nav2_costmap_2d/inflation_layer.hpp
nav2_costmap_2d/plugins/inflation_layer.cpp

---
| Ticket(s) this addresses   | #581  |
| Robotic platform tested on | gazebo sim of turtlebot |
---
The `seen_` was being used as a container for bool values and implemented as a dynamically allocated array (raw pointer), however, it was never deleted on the inflation layer destructor.
This PR implements using std::vector<bool>.
There's been [discussion](https://isocpp.org/blog/2012/11/on-vectorbool) on whether `vector<bool>` should be used at all. In this case looks fine, let me know what you think.

Fixing memory leak within Costmap2D Inflation Layer

---

tools/run_test_suite.bash

| Ticket(s) this addresses   | fixes #556 |
---
* The dynamic params test fails when run concurrently with other packages' tests. This changes runs the dynamic_params tests independently in CI.
* This is part two of PR #568

Run dynamic params test independently. (flaky dynamic params test fix part 2)

---

nav2_tasks/include/nav2_tasks/is_stuck_condition.hpp

**This PR should be merged after the new version of the BT library, which incorporates the onInit() method, has been added to ROS**
Addressing issue #469.
* Removed thread from isStuckCondition BT node
* Pulling ROS node from BT Blackboard

Modifications to isStuckCondition node

---

nav2_costmap_2d/include/nav2_costmap_2d/clear_costmap_service.hpp
nav2_costmap_2d/plugins/static_layer.cpp
nav2_costmap_2d/src/clear_costmap_service.cpp
nav2_msgs/CMakeLists.txt
nav2_msgs/package.xml
nav2_msgs/srv/ClearEntireCostmap.srv

| Ticket(s) this addresses   | #551  |
| Robotic platform tested on |Gazebo simulation of Turtlebot |
---
This is a continuation of #551. A service for clearing all locations outside of a region was already incorporated in #559. This new PR adds service for clearing the costmap entirely, similar to the [big reset service](https://github.com/ros-planning/navigation/blob/a6f3d4b49335b6de5c33044dd2123df0f491453f/move_base/src/move_base.cpp#L330-L338) available in ROS1 move base.

Add service to fully clear costmap

---

nav2_map_server/CMakeLists.txt
nav2_map_server/package.xml
nav2_map_server/src/occ_grid_loader.cpp

---
| Robotic platform tested on | Gazebo  |
---
* Removed `Bullet` dependency from `map_server` as it was only used to convert RPY to quaternions.
---

removed bullet dependency from map_server

---

nav2_costmap_2d/test/integration/costmap_tests_launch.py
nav2_dynamic_params/test/dynamic_params_test.launch.py
nav2_map_server/test/component/test_occ_grid_launch.py
nav2_system_tests/src/localization/test_localization_launch.py
nav2_system_tests/src/planning/test_planner_launch.py
nav2_system_tests/src/system/test_system_launch.py

---
* A bunch of tests were failing CI as can be seen in this build [log](https://travis-ci.org/ros-planning/navigation2/builds/502734132?utm_source=github_status&utm_medium=notification)
* This started happening due to a change in the `launch_testing` package.
* Seems we were using the package wrong and the change exposed that problem as described in ros2/launch#194
* This change removes a duplicate addition of the test action from the launch description.

Fix latest failing tests in CI

---

nav2_motion_primitives/CMakeLists.txt
nav2_motion_primitives/include/nav2_motion_primitives/motion_primitive.hpp
nav2_motion_primitives/test/CMakeLists.txt
nav2_motion_primitives/test/test_motion_primitives.cpp
nav2_navfn_planner/src/navfn_planner.cpp
nav2_system_tests/src/dummy_controller/dummy_controller.cpp
nav2_system_tests/src/dummy_planner/dummy_planner.cpp
nav2_tasks/include/nav2_tasks/task_server.hpp

This PR adds some unit tests for the `MotionPrimitive` base class. Addressing #384.
In the process of making the tests, I found a need for adding a stop method to the task server base class.

Motion primitives unit tests

---

nav2_bringup/launch/nav2_params.yaml
nav2_dwb_controller/dwb_critics/include/dwb_critics/oscillation.hpp
nav2_dwb_controller/dwb_critics/src/oscillation.cpp
nav2_system_tests/params/nav2_params.yaml

| Ticket(s) this addresses   | fixes #520, fixes #570  |
| Robotic platform tested on |Turtlebot 3 in gazebo |
---
* Disables oscillation detection on the Y-axis if the robot is not capable of Y-axis motion (eg. a differential drive robot) . See #520 for reasoning.
* Rough tuning of the DWB critics to get reliable motion. I upped the obstacle avoidance critic and the rotate to goal critic based on observed motion.
* Decreased the radius of the robot based on measurements of the model in gazebo.
---
* Need to sync the oscillation critic changes with @DLu

Fix oscillation problem and tune DWB critics

---

nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp

---
* If we fail to find a valid trajectory, the message should be an error, not just an info.

Printout should be error instead of info (trivial change)

---

nav2_costmap_2d/plugins/static_layer.cpp

This changes the map subscriber QOS settings from custom to default for the static layer. This is already done in AMCL, so this is consistent with AMCL. 
The benefit of this is that now the static layer can be updated by other map publishers such as cartographer.
---
I'm not sure if other QOS changes are needed elsewhere in the stack. There are some other places where custom QOS settings are set.

Costmap static layer to subscribe to map with default QOS settings

---

nav2_dwb_controller/dwb_plugins/src/limited_accel_generator.cpp
nav2_dwb_controller/dwb_plugins/src/standard_traj_generator.cpp
nav2_dwb_controller/dwb_plugins/test/twist_gen.cpp

---
* The trajectories generated in DWB should include the start pose and the end pose. Instead, the end pose was being left off. This was particularly problematic because sometimes there are no intermediate poses. This PR fixes that problem

Add last pose to DWB trajectory

---

nav2_dwb_controller/dwb_core/src/publisher.cpp

---
* Changed the color of DWB trajectories to be change from red for worst trajectory to green for best, with intermediate trajectories being some mix of the colors in-between.
The old color scheme was intense blue for the best with the blue fading away for the worst. This made it hard to see the worst against the background, or to tell if they were just missing.
Invalid trajectories are still black.

Change DWB trajectories displayed in RViz to be on the red-green spectrum instead.

---

nav2_system_tests/src/localization/test_localization_node.cpp

| Robotic platform tested on | System tests |
---
* test_localization was publish intial pose in a tight loop. It should only publish once and then wait for a result. This was resulting in huge amounts of messages like below in the log output
```
[amcl-5] [INFO] [amcl]: Setting pose (1553299060.487872): -2.000 -0.500 0.000
```

Localization test should publish only once.

---

nav2_dwb_controller/dwb_critics/include/dwb_critics/rotate_to_goal.hpp
nav2_dwb_controller/dwb_critics/src/rotate_to_goal.cpp

| Ticket(s) this addresses   | NA  |
---
1. Scores need to be positive, so this takes the absolute value of the angle error.
2. Ignores Y velocity on differential drive robots. It's just IMU noise.
3. Reset flag that enables this critic once we are in range again.
1 and 3 are already fixed in @Dlu's repo, but in a different way. Soon I hope to rebase and I'll take the upstream changes instead.
2 is related to our noisy IMU in simulation (see #603) but should probably be upstreamed in some way.

Rotate to goal fixes

---

nav2_amcl/include/nav2_amcl/amcl_node.hpp
nav2_amcl/src/amcl_node.cpp
nav2_bringup/launch/nav2_params.yaml
nav2_system_tests/src/system/test_system_node.py

---
| Ticket(s) this addresses   | (fixes #613) |
| Robotic platform tested on | () |
---
- Changed AMCL to not broadcast transforms before initial pose is received either via initialpose topic or later when pose from server is available.
- This way robot knows it location with respect to map before putting obstacles on map.
- Enabled obstacle layers for both global and local costmaps
---

Enable Obstacle Layer on Global and Local costmaps

---

nav2_bringup/launch/nav2_bringup_2nd_launch.py
nav2_bringup/launch/nav2_bringup_launch.py
nav2_bringup/launch/nav2_params.yaml

---
| Robotic platform tested on | Turtlebot 3 |
---
* Switches the default navigator to bt_navigator with the parallel replan configuration
* Enables obstacle layer in both global and local costmaps. This part duplicates what's in #630.

Add parallel planning and obstacle layer.

---

nav2_lifecycle/CMakeLists.txt
nav2_lifecycle/README.md
nav2_lifecycle/include/nav2_lifecycle/lifecycle_helper_interface.hpp
nav2_lifecycle/include/nav2_lifecycle/lifecycle_node.hpp
nav2_lifecycle/package.xml
nav2_lifecycle/src/lifecycle_node.cpp
nav2_simple_navigator/include/nav2_simple_navigator/simple_navigator.hpp
nav2_simple_navigator/package.xml
nav2_simple_navigator/src/main.cpp
nav2_simple_navigator/src/simple_navigator.cpp

This is the first PR in a series where we will integrate lifecycle functionality into the `navigation2/lifecycle` branch. The intention is to submit the work in reviewable chunks. The result won't compile until several PRs are integrated in this series. 
This PR has a (temporary) nav2_lifecycle directory and an example lifecycle node, the nav2_simple navigator. The nav2_lifecycle directory will be obsolete once we get several fixes introduced into ROS2 (see #608). 
* There will be several subsequent PRs in this series to lifecycle-enable all of the nodes in the navigation 2 stack

Temporary nav2_lifecycle and an example lifecycle node

---

nav2_tasks/include/nav2_tasks/bt_action_node.hpp
nav2_tasks/include/nav2_tasks/rate_controller_node.hpp

* When changing the BtActionNode class to use the BehaviorTree library's CoroActionNode the BtActionNode::halt method was not updated correctly. 
* When a child node of the RateController fails, wait until the next time interval to try again (instead of re-trying immedately)
* When a BtActionNode finishes (with SUCCEEDED, FAILED, or CANCELED) set the node state to IDLE

Fix empty path re-sent to the local planner

---

tools/run_test_suite.bash

---
* Disabling the motion primitives and dynamic params tests. They are constantly failing in CI for yet undetermined reasons.
* If you run colcon test from the command line on the workspace the tests will still be run. They just won't get run through the run_test_suite.sh script.

Disable failing dynamic params and motion primitives tests.

---

nav2_costmap_2d/include/nav2_costmap_2d/static_layer.hpp
nav2_costmap_2d/plugins/static_layer.cpp

Signed-off-by: vinnamkim <vinnam.kim@gmail.com>
---
| Ticket(s) this addresses   | (add tickets here #636 ) |
| Robotic platform tested on | (gazebo simulation) |
---
Fix data race condition between map update thread and ROS callback thread.
---
---

Set atomic_bool on StaticLayer::has_updated_data_

---

nav2_amcl/include/nav2_amcl/amcl_node.hpp
nav2_amcl/src/amcl_node.cpp

---
| Ticket(s) this addresses   | fixes #169  |
| Primary platform tested on | HP Desktop |
--- 
--- 
**Will merge after internal release.**
This PR re-opens PR #310 which addresses issue #169.
- AMCL's `laserReceived` CB is long and hard to follow.  In this PR, I've created few helper functions for `laserReceived` to improve the readability. 
---

Amcl laser received callback

---

nav2_bringup/launch/nav2_params.yaml

---
| Primary OS tested on | Ubuntu 18 |
| Robotic platform tested on | Turtlebot 3 in Gazebo |
---
* Default linear_granularity was 0.5m. This seemed too long a distance to look for obstacles. The turtlebot seemed to clip corners with the setting at the default.
* Replace the obstacle footprint critic with base obstacle. When using the inflation layer in costmap to make obstacles bigger, base obstacle should be sufficient to prevent obstacles. We also saw strange behavior with obstacle footprint that needs to be investigated further. It reported the robot had collided when it clearly hadn't, even according to the costmap data.
* The turtlebot3 waffle is our main model we test with. Make …

Tuning parameters for turtlebot 3.

---

nav2_costmap_2d/src/costmap_2d_ros.cpp

---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation/issues/885 |
| Primary OS tested on | Ubuntu 18.04|
| Robotic platform tested on | turtlebot3 simulation in Gazebo |
---
The footprint subscriber in the costmap is subscribing to the footprint topic with a different message type (geometry_msgs::Polygon) than is being published (geometry_msgs::PolygonStamped). Due to this, running with the Opensplice DDS implementation causes the costmaps to crash. This change makes the default subscriber topic "dynamic_footprint" instead of just "footprint". 
According to this issue:
https://github.com/ros-planning/navigation/issues/885
These publishers and subscribers are performing 2 different things. The …

Change footprint_sub topic to dynamic_footprint

---

nav2_bt_navigator/include/nav2_bt_navigator/navigate_to_pose_behavior_tree.hpp
nav2_bt_navigator/src/navigate_to_pose_behavior_tree.cpp
nav2_tasks/include/nav2_tasks/clear_entirely_costmap_service_client.hpp

---
| Robotic platform tested on | (Gazebo simulation) |
---
- Created a service client in nav2_tasks to invoke a service call to clear entire costmap.
- Created a simple action node in BT to be able to clear entire costmap
- To clear global costmap from BT:
`<clearEntirelyCostmapServiceRequest service_name="/global_costmap/clear_entirely_global_costmap"/>`
- To clear local costmap BT:
`<clearEntirelyCostmapServiceRequest service_name="/local_costmap/clear_entirely_local_costmap"/>`

Clear entire costmap from BT

---

nav2_bringup/launch/nav2_bringup_2nd_launch.py
nav2_bringup/launch/nav2_bringup_launch.py
nav2_bringup/launch/nav2_params.yaml
nav2_bt_navigator/behavior_trees/navigate_w_recovery_retry.xml
nav2_motion_primitives/src/spin.cpp
nav2_system_tests/src/system/CMakeLists.txt

---
| Ticket(s) this addresses   | #642 Enable Recovery Actions |
| Primary OS tested on | Ubuntu 18.04) |
| Robotic platform tested on | Turtlebot3 in simulation |
---
This changes the default navigator to the bt_navigator and adds a behavior tree for running with the backup and spin recovery behaviors, and a retry set to 7. I know that's high but in simulation, it seemed to work most reliably that way.
---
- Add parameter to the launch files for changing the behavior tree XML file. I tried to do this but was getting errors from launch
- Change backup and spin motion primitives to check for clear space and ensure no collisions occur
- Add a clear costmap motion primitive and enable it as part of this 
---

Enable Behavior Tree navigator with recovery and retry

---

nav2_dwb_controller/dwb_controller/CMakeLists.txt
nav2_dwb_controller/dwb_controller/include/dwb_controller/dwb_controller.hpp
nav2_dwb_controller/dwb_controller/include/dwb_controller/progress_checker.hpp
nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp
nav2_dwb_controller/dwb_controller/src/main.cpp
nav2_dwb_controller/dwb_controller/src/progress_checker.cpp

---
* The main controller loop checks that the robot has moved at least 0.5m every 10s or else it returns failure so that recovery actions can be attempted.
* The distance and time are configurable parameters.
---
* There is nothing DWB specific about this check. I think it should be a BT node once we figure out how to cancel an action from another node.

Adding a check to DWB controller to return failure if it can't make progress.

---

nav2_robot/CMakeLists.txt
nav2_robot/include/nav2_robot/robot.hpp
nav2_robot/package.xml
nav2_robot/src/robot.cpp
nav2_robot/test/CMakeLists.txt
nav2_robot/test/test_robot_class.cpp

* Enabling nav2_robot for lifecycle nodes
* Remove COLCON_IGNORE in SimpleNavigator. Now that nav2_robot is enabled, Simple Navigator from the previous PR will compile.

Port nav2_robot to lifecycle nodes

---

nav2_bt_navigator/CMakeLists.txt
nav2_bt_navigator/include/nav2_bt_navigator/bt_navigator.hpp
nav2_bt_navigator/include/nav2_bt_navigator/navigate_to_pose_behavior_tree.hpp
nav2_bt_navigator/package.xml
nav2_bt_navigator/src/bt_navigator.cpp
nav2_bt_navigator/src/main.cpp
nav2_bt_navigator/src/navigate_to_pose_behavior_tree.cpp

* Port the BT Navigator to lifecycle nodes
* Implement a ROS2 Action server instead of task server
* The task clients still need to be converted to action clients once the other task servers are converted to action servers

Port BT Navigator to lifecycle nodes

---

README.md

To make build issues from Dockerhub repo used for CI more visible.

Add build badge for Docker Hub

---

nav2_mission_executor/CMakeLists.txt
nav2_mission_executor/include/nav2_mission_executor/execute_mission_behavior_tree.hpp
nav2_mission_executor/include/nav2_mission_executor/mission_executor.hpp
nav2_mission_executor/package.xml
nav2_mission_executor/src/execute_mission_behavior_tree.cpp
nav2_mission_executor/src/main.cpp
nav2_mission_executor/src/mission_executor.cpp
nav2_mission_executor/test/CMakeLists.txt
nav2_mission_executor/test/test_mission_executor.cpp

* Update the MissionExecutor for lifecycle nodes
* Add a test action client that can be used to send a mission plan to the mission executor.
* Convert the test to a gtest-based unit test

Update the MissionExecutor for lifecycle nodes

---

nav2_amcl/src/amcl_node.cpp
nav2_bt_navigator/CMakeLists.txt
nav2_bt_navigator/package.xml
nav2_bt_navigator/src/bt_navigator.cpp
nav2_common/cmake/nav2_package.cmake
nav2_costmap_2d/src/costmap_2d_ros.cpp
nav2_costmap_2d/test/integration/inflation_tests.cpp
nav2_costmap_2d/test/integration/obstacle_tests.cpp
nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp
nav2_dwb_controller/dwb_plugins/test/twist_gen.cpp
nav2_dynamic_params/test/test_dynamic_params_client.cpp
nav2_dynamic_params/test/test_dynamic_params_helper.cpp
nav2_dynamic_params/test/test_dynamic_params_validator.cpp
nav2_map_server/CMakeLists.txt
nav2_map_server/package.xml
nav2_map_server/src/map_server.cpp
nav2_navfn_planner/src/navfn_planner.cpp
nav2_util/include/nav2_util/node_utils.hpp
nav2_util/src/node_utils.cpp

- Temporarily fixes master branch after rclcpp parameter changes
- Adds default NodeOptions to nav2 Nodes with parameters
- Defaults to automatically declare initial parameters (from yaml) and to allow undeclared parameters
- added function in nav2_util to return default NodeOptions object
- Temporarily removed error for warnings to allow for deprecated parameter functions while we are in transition
- These changes can be removed (or modified) after we integrate lifecycle nodes with parameter changes

Add default NodeOptions to fix new parameter changes

---

nav2_costmap_2d/test/integration/costmap_tests_launch.py
nav2_dynamic_params/test/dynamic_params_test.launch.py
nav2_map_server/test/component/test_occ_grid_launch.py
nav2_system_tests/src/localization/test_localization_launch.py
nav2_system_tests/src/planning/test_planner_launch.py
nav2_system_tests/src/system/test_system_launch.py

---
* ros2/launch#215 changed the launch test facilities. The old LaunchTestService is now a legacy interface and needs to be imported in a new way. These tests are broken without this change.

Fix launch test service import.

---

nav2_util/CMakeLists.txt

---
| Ticket(s) this addresses   | fixes #656 |
| Primary OS tested on | OS X |
---
* The nav2_util CMake file is missing some `add_target_dependencies` statements. Shared libraries need to link with their dependencies. Sensors_lib has a dependency on pf_lib that was not specified. For some reason this did not cause a problem on Ubuntu 18.04 building with GCC but does cause a problem for Clang on OS X.

Adding missing dependencies in the nav2_util CMakeLists.txt

---

nav2_costmap_2d/include/nav2_costmap_2d/clear_costmap_service.hpp
nav2_costmap_2d/src/clear_costmap_service.cpp
nav2_msgs/CMakeLists.txt
nav2_msgs/srv/ClearCostmapAroundRobot.srv

| Ticket(s) this addresses   | #551  |
| Robotic platform tested on |Gazebo simulation of Turtlebot |
---
This PR adds a service for clearing a window around the robot, similar to the [clear costmap window service](https://github.com/ros-planning/navigation/blob/a6f3d4b49335b6de5c33044dd2123df0f491453f/move_base/src/move_base.cpp#L330-L338) available in ROS1 move base.
This is the last item pending from #551.

Adding a service to clear a costmap around the robot

---

nav2_controller/CMakeLists.txt
nav2_controller/include/nav2_controller/nav2_controller.hpp
nav2_controller/include/nav2_controller/nav2_controller_client.hpp
nav2_controller/package.xml
nav2_controller/src/main.cpp
nav2_controller/src/nav2_controller.cpp
nav2_controller/src/nav2_controller_client.cpp

* Adds a controller node for the various lifecycle nodes. This node walks the lifecycle node through their various states for startup and shutdown. It also does pause (getting the nodes back into a configurable state) and resume. 
* This node will be renamed to nav2_lifecycle_manager once all of the lifecycle changes are integrated into the lifecycle branch
* Not all nodes correctly support being paused and resumed (that is, de-activate + cleanup and then configure + activate). In particular, those nodes that rely on plug-ins, which don't have a lifecycle-style interface (yet), still need more work.

Nav2 lifecycle controller

---

nav2_lifecycle_manager/CMakeLists.txt
nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager.hpp
nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager_client.hpp
nav2_lifecycle_manager/package.xml
nav2_lifecycle_manager/src/lifecycle_manager.cpp
nav2_lifecycle_manager/src/lifecycle_manager_client.cpp
nav2_lifecycle_manager/src/main.cpp
nav2_rviz_plugins/CMakeLists.txt
nav2_rviz_plugins/include/nav2_rviz_plugins/nav2_panel.hpp
nav2_rviz_plugins/package.xml
nav2_rviz_plugins/src/nav2_panel.cpp
nav2_rviz_plugins/src/navigation_dialog.cpp

* Per review feedback, to avoid potential confusion, rename the nav2_controller to be nav2_lifecycle_manger. 
* Will integrate the headers that are currently in nav2_lifecycle into nav2_util. There are only a couple there and they will eventually become obsolete. This will help keep down the number of directories.

Rename the nav2_controller to nav2_lifecycle_manager

---

nav2_bt_navigator/behavior_trees/parallel.xml
nav2_bt_navigator/src/navigate_to_pose_behavior_tree.cpp
nav2_tasks/include/nav2_tasks/goal_reached_condition.hpp

---
| Ticket(s) this addresses   | (fixes #641) |
| Robotic platform tested on | (Turtlebot3 simulation) |
---
- Created BT tree to enable parallel planning
- The global planner will not replan if the robot is within a close proximity to goal. The user can decide what the tolerance should be.
---
- Currently the goal checker is being used in DWB, BT, and system tests. We need to factor out goal checker to utils so that it can be used in other modules
- Probably a better approach would be to create  a "goal checker" node and have other modules to listen to it via topics. This way, the goal checker would be modular and can easily be replaced with something else.
---

Enabled parallel global planner

---

nav2_amcl/include/nav2_amcl/amcl_node.hpp
nav2_amcl/src/amcl_node.cpp

---
---
* An upstream PR seems to have added an extra semicolon in one of the tf2 headers. This PR disables the warning generated by that file

Get the build working again

---

nav2_common/cmake/nav2_package.cmake

---
* Sets the CMAKE_BUILD_TYPE flag to Release if it was unspecifed. Without this, if the user doesn't specify, they get an unoptimized build with no debug info - the worst of both worlds. I'm defaulting to Release because if someone just downloads the source, builds and runs it, we want their code to run as fast as possible to avoid them reporting performance related issues; robot motion can become unstable if the controller doesn't run fast enough.
---
---

Default to a release build if unspecified.

---

nav2_bringup/launch/nav2_params.yaml
nav2_dwb_controller/dwb_critics/include/dwb_critics/oscillation.hpp
nav2_dwb_controller/dwb_critics/src/oscillation.cpp
nav2_dwb_controller/dwb_critics/src/rotate_to_goal.cpp
nav2_dwb_controller/nav_2d_utils/include/nav_2d_utils/odom_subscriber.hpp

| Ticket(s) this addresses   | #514  |
| Robotic platform tested on | Turtlebot 3 |
---
* Velocities from an IMU are likely to have a small noise component. This noise was getting filtered out in individual trajectory critics by removing any values below a threshold value.
* This PR removes the filtering from every critic that cares and replaces it with a single place to filter the noise out.
* This PR also makes the noise filter threshold configurable in X, Y and theta.

Filter out IMU noise

---

nav2_amcl/src/amcl_node.cpp

---
| Ticket(s) this addresses   | (fixes #635 ) |
| Robotic platform tested on | (TB3 Gazebo simulation) |
---
In PR #630 if 'initial_pose_received' flag is not set, amcl will not publish a pose.   Therefore, for Auto Localization we have to set this flag manually in global localization callback since the initial pose is never expected to be received. 
---

Fixed for auto localization 

---

nav2_bringup/launch/nav2_params.yaml
nav2_costmap_2d/src/costmap_2d_ros.cpp
nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp
nav2_lifecycle/src/lifecycle_node.cpp
nav2_system_tests/params/nav2_params.yaml
nav2_world_model/src/world_model.cpp

* When implementing lifecycle nodes I removed the namespace from the costmap(s) not realizing that the namespaces are required so that the publishers and subscribers from each costmap instance remain separate. This PR restores the namespaces and costmap node names as before. 
* Not using namespaces for the utility nodes (those that are created simply for the purpose of calling a service, for example)
* Updated the lifecycle manager node name
* There will be subsequent changes to the nav2_params.yaml file as we rebase with the master branch and get things in sync

Use namespaces on costmap nodes so that pub/subs can co-exist

---

nav2_dwb_controller/dwb_plugins/src/limited_accel_generator.cpp
nav2_dwb_controller/dwb_plugins/src/standard_traj_generator.cpp
nav2_dwb_controller/nav_2d_utils/include/nav_2d_utils/parameters.hpp

* In the release build, there were a few occurances of uninitialized variables. These values are set by the get_parameter call, but the compiler doesn't know that, and issues a warning. With warnings treated as errors, this resulted in a release build failure.

Initialize variables to avoid errors in the release build

---

nav2_dwb_controller/dwb_core/package.xml
nav2_motion_primitives/package.xml
nav2_navfn_planner/package.xml

| Ticket(s) this addresses   | fixes #755  |
---
* Dependencies on nav2_lifecycle package had typos in various places. This fixes them.

Fix typos in dependencies

---

nav2_bringup/launch/bt_navigator.xml
nav2_bt_navigator/src/bt_navigator.cpp
nav2_tasks/include/nav2_tasks/bt_action_node.hpp

* The Behavior Tree library's CoroActionNode uses coroutines, while AsyncActionNode uses separate threads. When using coroutines, there was a race condition where the result of an action was occasionally missed. This happens when one coroutine is executing, such as ComputePathToPose, while the FollowPath coroutine is not executing. When it gets a chance to run again, FollowPath does not properly receive the result, even though the Action server has sent it. 
* Using separate threads for the actions means that they can no longer share the same node when invoking the actions. Therefore, removed the node from the blackboard and each bt_action has its own node, generated with nav2_util::generate_internal_node(). 
* Also update the bt_navigator.xml Behavior Tree so that FollowPath is wrapped …

Use AsyncActionNode instead of CoroActionNode

---

nav2_amcl/src/amcl_node.cpp
nav2_bt_navigator/src/bt_navigator.cpp
nav2_costmap_2d/src/costmap_2d_ros.cpp
nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp
nav2_map_server/src/map_server.cpp
nav2_mission_executor/src/mission_executor.cpp
nav2_navfn_planner/src/navfn_planner.cpp
nav2_world_model/src/world_model.cpp

Previous review feedback recommended having the lifecycle nodes exit upon entering an error state since we're not doing any error handling yet. So, this PR converts the messages to RCLCPP_FATAL.

Use RCLCPP_FATAL upon a lifecycle node entering error state

---

nav2_bringup/launch/nav2_bringup_launch.py

We get too much output from the RVIZ logger, most of it related to some errors around message filters.
By increasing the severity level to `fatal` we don't log these messages.
We can set it back to `info` once the message filters on RVIZ have been resolved.

Increase RVIZ logging severity level

---

nav2_amcl/src/amcl_node.cpp

---
* Changes AMCL to use the QOS profile for sensor data when subscribing to the 'scan' topic.
This was suggested by @miguelcompany in this issue: https://github.com/ros2/rmw_fastrtps/issues/280
I tested this change and see our tests pass now with the latest FastRTPS.

AMCL to use sensor data qos for scan topic

---

nav2_dwb_controller/dwb_plugins/test/CMakeLists.txt
nav2_dwb_controller/dwb_plugins/test/twist_gen.cpp
nav2_util/src/node_utils.cpp

This PR un-breaks the lifecycle branch to adapt for the recent API change in the NodeOptions functions for parameter_overrides and automatically_declare_parameters_from_overrides.
For the lifecycle branch, the `twist_gen_test` fails due to parameter declaration conflicts within the test. This is a circular problem I've encountered before, where in the test we'd like to set a parameter in a test case before it is declared in the constructor of another class outside the test, however this cannot be done via `set_parameter`  because it implicitly declares a parameter (if allowed via `allow_undeclared_parameters`. The only way I know to prepare a parameter before `declare_parameter` is through a yaml file or the `parameter_overrides` option in `NodeOptions`. For multiple test cases with …

Fix Lifecycle NodeOptions API rename

---

nav2_bringup/launch/nav2_params.yaml
nav2_costmap_2d/plugins/obstacle_layer.cpp

This PR re-enables the obstacle layer in the lifecycle branch. The obstacle behavior seems to behave normally in adding observations to the costmap. The qos setting in the obstacle layer laser scan subscriber is also changed to `rmw_qos_profile_sensor_data` which appears to resolve issues with not receiving laser scan topic.

Re-enable obstacle layer 

---

nav2_dwb_controller/dwb_plugins/test/twist_gen.cpp
nav2_util/src/node_utils.cpp

This PR un-breaks master to adapt for the recent API change in the NodeOptions functions for `parameter_overrides` and `automatically_declare_parameters_from_overrides`.

Update NodeOptions API rename

---

nav2_util/include/nav2_util/lifecycle_node.hpp
nav2_util/src/lifecycle_node.cpp

This PR addresses an issue I've had with threads in gtests. In particular, the `nav2_lifecycle::LifecycleNode` optionally creates a `rclcpp_node_` with its own thread spinning the node. In normal operation, the thread would be killed and destroyed along with the node when `rclcpp_shudown` is called. However, in gtests, I've observed these threads to hang at the end of a test case, preventing termination and causing a timeout, likely because no `rclcpp::shutdown` is called until after all the tests are through completion. 
I've added an atomic bool check in the thread that is set to stop the thread from spinning the node when the destructor of the class is called.

Stop spinning rclcpp_node thread in LifecycleNode destructor

---

nav2_lifecycle_manager/package.xml
nav2_map_server/package.xml
nav2_mission_executor/package.xml
nav2_navfn_planner/package.xml
nav2_robot/package.xml
nav2_tasks/package.xml
nav2_world_model/package.xml

---
* Adds missing nav2_common dependencies to package.xml files.

package.xml files are missing nav2_common dependency

---

nav2_bringup/launch/nav2_params.yaml
nav2_dwb_controller/dwb_core/include/dwb_core/trajectory_critic.hpp

The `BaseObstacle` critic was commented out during the rebase, so it is now enabled. The scale parameters were not seen on the node but given a default in the code, so this PR declares them so they can be tuned in the system yaml file. Now, the robot should actually avoid obstacles and make progress towards the goal with the right critic scale values.
- Re-enables BaseObstacle critic in `nav2_params.yaml`
- Declares trajectory critic scale parameters

Enable BaseObstacle critic and declare critic scale parameters

---

Dockerfile

Per this Discourse thread the apt-key for the ros2 build farm has changed:
https://discourse.ros.org/t/key-rotation-for-ros-2-apt-repositories/9363
This broke our CI builds, with a GPG key error. 
This PR updates to the new key and should fix this problem.

Remove apt key from Dockerfile

---

nav2_navfn_planner/src/navfn_planner.cpp

This PR fixes an apparent oversight where the navfn_planner doesn't update its costmap when given a new `computePathToPose` action, which previously caused failures when attempting to navigate to areas that were considered illegal from the initial costmap it received.

Update costmap on new computePathToPose

---

nav2_tasks/include/nav2_tasks/bt_action_node.hpp

* Now that the BT nodes are derived from AsyncActionNode instead of CoroActionNode, it is possible for halt() to be called from a different thread while tick() is active. This PR ensures that only one spin_until_future_complete is active at a time. Without this, there is a race condition that can result in an "already on an executor" error. 
* This should fix the error we're seeing occasionally with the rviz action-based goal pose tool (since it's intermittent, it's hard to test. I've run many times without encountering the error again).

Only allow one spin_until_future_complete at a time

---

Dockerfile

See #797 - this is the same change for the lifecycle branch
~~THIS SHOULD BE MERGED ASAP before any other PRs so that we can unblock the build (again)~~
Correction - the build works without this change because the key already exists in the upstream OSRF docker image.

lifecycle branch - remove apt key from Dockerfile

---

nav2_bt_navigator/include/nav2_bt_navigator/bt_navigator.hpp
nav2_bt_navigator/src/bt_navigator.cpp
nav2_tasks/include/nav2_tasks/behavior_tree_engine.hpp
nav2_tasks/include/nav2_tasks/bt_action_node.hpp
nav2_tasks/src/behavior_tree_engine.cpp
nav2_util/include/nav2_util/simple_action_server.hpp

Addressing #801
* Updated `bt_navigator` in order to replace a previous goal with any new one received.
Here's a short description of how the preemption happens. Each new pose provided in RVIZ by the `Navigation2 Goal` tool creates a new ROS2 action request. The action server (`BtNavigator::action_server_`) callback captures the new goal handle. The `BtNavigator::navigateToPose` thread is checking periodically (at each behavior tree tick) for any new goals. If a new goal is received, the previous is canceled (informing back to the RVIZ action client) and the goal pose updated.
The new goal propagation happens automatically for the planner and controller without having to preempt their respective actions.
*This feature will not work if continuous replanning is not enabled.*
---
* Update …

Enable navigation goal preemption

---

nav2_tasks/include/nav2_tasks/goal_reached_condition.hpp
nav2_tasks/include/nav2_tasks/is_localized_condition.hpp

* The node on the blackboard is not on an executor. Before calling getRobotPose, we must spin_some so that it processes incoming messages.

Spin the node from the blackboard before calling getCurrentPose

---

nav2_bringup/launch/developer_launch.py
nav2_bringup/launch/nav2_simulation_launch.py

* This PR adds a launch script that attempts to make it easy for nav2 developers to launch everything required to run the nav2 stack in simulation. There are a number of command-line options to control the launch behavior. This script isn't intended for use be end-users, who should use nav2_bringup_launch.py instead. 
* Deleted the bt_navigator.xml as agreed. Instead reference the XML file in the nav2_bt_navigator/behavior_trees directory directly.

Add an all-in-one launch file for nav2 developers

---

nav2_tasks/include/nav2_tasks/compute_path_to_pose_action.hpp

* In the ComputePathToPose BT action, the code was setting path_updated on the blackboard the first time it was called. This results in the path being sent to the Action server and, immediately, the same path being sent as a pre-emption/update. This change avoids setting the path_updated flag on the blackboard the first time through.

Don't set the path_updated flag the first time through

---

nav2_tasks/include/nav2_tasks/bt_action_node.hpp

When a BT action node is halted, the (ROS) action client should cancel the goal and check for successful cancellation.

Adding check for successful action cancellation after halting a bt action node

---

nav2_dwb_controller/dwb_core/src/dwb_local_planner.cpp
nav2_system_tests/params/nav2_params.yaml
nav2_system_tests/src/system/CMakeLists.txt
nav2_system_tests/src/system/test_system_launch.py
nav2_system_tests/src/system/test_system_node.py
tools/ctest_retry.bash
tools/run_test_suite.bash

---
- Enables the bt_navigator system test on the lifecycle branch
- UPDATE: Now uses the `navigate_w_replanning_and_recovery.xml` behavior tree
- DISABLES the linters for some packages temporarily
- Enable other behavior trees and change the test to use the default  (DONE)
- Enable the localization test (#795)
- Enable the Planner test (was already disabled prior to this PR)
- Enable the linters again - #812 
- Clean up the nav2_params.yaml - #813

Enable bt_navigator system test on lifecycle branch

---

nav2_bringup/launch/nav2_params.yaml

Probably lost these in the recent rebasing of lifecycle against master. In any case, all nodes in the nav2 system should have use_sim_time set. The use_sim_time value can be modified with a command-line parameter to the launch script(s).

Use_sim_time missing from a couple nodes in the params file

---

nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager.hpp
nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager_client.hpp
nav2_lifecycle_manager/src/lifecycle_manager.cpp
nav2_lifecycle_manager/src/lifecycle_manager_client.cpp
nav2_rviz_plugins/include/nav2_rviz_plugins/nav2_panel.hpp
nav2_rviz_plugins/src/nav2_panel.cpp

We don't yet have a full solution for bringing nodes into a state where
their parameters can be reconfigured and then the nodes reactivated. So,
we don't want to expose a partial solution for the Dashing release that
could potentially be confusing for users, so we will only expose startup
and shutdown for now. 
Currently, all lifecycle node parameters are read during on_configure.
Going forward, we will re-assess all parameters to allow for other
options, such as on_activate. Once parameters are associated with different
state transitions, we'll then have to clearly document the parameters and
their state associations and/or come up with an automated way to allow for
node reconfiguration.

Delete pause/resume buttons and services

---

nav2_amcl/src/amcl_node.cpp
nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp
nav2_costmap_2d/src/costmap_2d_ros.cpp

Now that lifecycle nodes properly support use_sim_time, we can get the
current time from the node itself rather than relying on the rclcpp_node
(which is a temporary bridging solution to interface to ROS2 functionality
that doesn't yet support lifecycle nodes). This PR is one of several steps
that we'll take in order to remove the rclcpp_nodes from the navigation
code, thereby reducing the overall number of nodes in the system and
therefore the overall number of topics and services, which should relieve
some stress on Fast-RTPS. 
NOTE: #843 should be integrated before this one. 843 adds a couple missing
occurances of use_sim_time to the nav2_params file. These ommisions
didn't previously cause a problem, because sim time was retrieved from
the rclcpp_node instead of the main lifecycle …

Call now on the main lifecycle nodes instead of rclcpp_nodes

---

nav2_tasks/include/nav2_tasks/bt_action_node.hpp

| Ticket(s) this addresses   | #820  |
---
* This PR changes the bt_action_node template class to derive from the Behavior Tree library's CoroActionNode instead of AsyncActionNode. The async version spins up threads for the client side of a BT action, while the Coro version uses coroutines. With BT actions, the client side is doing spin_until_future_complete (with a timeout), so a coroutine rather than a dedicated thread is ligher-weight as well as simpler, since there aren't multi-threading concerns between the various client nodes (such as serializing access to the blackboard); only one is active at a time.
* Previously we had changed from Coro …

Revert back to CoroActionNodes instead of AsyncActionNodes

---

nav2_bringup/launch/nav2_params.yaml

The navigation2 launch implements rewriting of the input parameter file in
order to change some values, such as use_sim_time, based on command line
input. This is currently required to work around some node renaming that
occurs if we use the Node class in the launch system.
The input nav2_params.yaml file had separate sections for nodes under
the global_costmap and local costmap namespaces. This caused some issues
for our parameter rewriting code (see example below). So, to work around
this problem and to use what is probably a better organization anyways,
this PR puts the nodes under the same namespace section.
**To demonstate the current issue:**
Example input section:
```
local_costmap:
local_costmap:
ros__parameters:
use_sim_time: True
robot_radius: 0.17 …
```

Consolidate related parameter sections under a single namespace heading

---

nav2_map_server/include/nav2_map_server/occ_grid_loader.hpp
nav2_map_server/src/occ_grid_loader.cpp

---
When running with autostart = True, I don't see a map appear in RViz. I'm not sure why but I don't believe that the latching is working correctly for the /map topic. However, when I re-publish the map topic every 2 seconds, then the map appears in RViz. This is consistent with what we were doing before we moved to lifecycle nodes.
---
Debug why this is required. It may be that the QOS settings for the map need to be changed in RViz to 'transient local', 'reliable' which is what we're using for publishing the /map topic.
---

Re-add republishing of map every 2 sec

---

nav2_bt_navigator/CMakeLists.txt
nav2_bt_navigator/behavior_trees/navigate_w_replanning_and_recovery.xml
nav2_bt_navigator/include/nav2_bt_navigator/recovery_node.hpp
nav2_bt_navigator/src/navigate_to_pose_behavior_tree.cpp
nav2_bt_navigator/src/recovery_node.cpp

---
| Ticket(s) this addresses   | (fixes #832 ) |
| Robotic platform tested on | (Gazebo + TB3) |
---
- Added recovery node to nav2_bt_navigator (#832)
- Updated our existing `parallel_planning_w_recovery` tree to utilize the new recovery node
<a href="https://user-images.githubusercontent.com/39755151/59474267-fdbeef80-8dfa-11e9-8806-b114aca05982.png"><img src="https://user-images.githubusercontent.com/39755151/59474267-fdbeef80-8dfa-11e9-8806-b114aca05982.png" width="300"/></a>
<a href="https://user-images.githubusercontent.com/39755151/59530510-a53e2f80-8e98-11e9-9c7d-f91dce831876.jpg"><img src="https://user-images.githubusercontent.com/39755151/59530510-a53e2f80-8e98-11e9-9c7d-f91 …

Adding RecoveryNode to Behavior Tree

---

nav2_bringup/launch/nav2_bringup_launch.py
nav2_bringup/launch/nav2_simulation_launch.py

When launched with launch_ros, executables can withhold logging output at log level "INFO" until termination.
So RCLCPP_WARN will get output immediately, but you won't see RCLCPP_INFO until the program terminates.
Explicitly make stdout line-buffered so this doesn't happen.
Better solution than PR #852

Set environment variables so logging comes out in order

---

nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager.hpp
nav2_lifecycle_manager/src/lifecycle_manager.cpp

---
| Ticket(s) this addresses   | #817 |
---
- Added check for state of nodes after requesting transition
- if an error causes node to fail transition to intended state, should now be inferred
- some refactor and cleanup of code
Since we don't have access to the actual callback return code (i.e. CallbackReturn::Error) when an error is thrown during a transition, we can only infer an error by the resultant state request after a transition request. A future proposal could be to add additional information to the srv/ChangeState so that service clients can more precisely learn what happened during a transition request. 
Also, for now if a call to `on_cleanup` or `on_shutdown` is made and the error is thrown  during those …

Check in lifecycle_manager for successful state transitions and some refactors

---

nav2_util/CMakeLists.txt
nav2_util/src/CMakeLists.txt
nav2_util/src/map/CMakeLists.txt
nav2_util/src/map_loader/CMakeLists.txt
nav2_util/src/motion_model/CMakeLists.txt
nav2_util/src/pf/CMakeLists.txt
nav2_util/src/sensors/CMakeLists.txt

| Ticket(s) this addresses   | fixes #768, fixes #856  |
---
Moves `install` commands to the subdirectory where the library is defined to properly support CMake 3.10.2 on some systems.

Move install commands to subdirs where target is defined

---

nav2_util/include/nav2_util/lifecycle_node.hpp
nav2_util/src/lifecycle_node.cpp
nav2_util/test/CMakeLists.txt
nav2_util/test/test_lifecycle_node.cpp

This approach replaces #854 
| Ticket(s) this addresses   | #792 |
---
- Added executor to spin the rclcpp node in thread
- Cancel executor in destructor of nav2_util::LifecycleNode in order to stop spin in thread
---
- The only difference between this approach and a normal `rclcpp::spin(node)` is that we have created our own executor that we can use to cancel the spin(). Since the normal spin locally creates a `rclcpp::executors::SingleThreadedExecutor`, we could consider adding an interface such as:
```
void
rclcpp::spin(
rclcpp::Node::SharedPtr node_ptr, 
rclcpp::executors::SingleThreadedExecutor & exec = rclcpp::executors::SingleThreadedExecutor());
```

Spin rclcpp node on executor and cancel

---

nav2_dwb_controller/dwb_critics/src/map_grid.cpp

---
* There is a flaw in the Goal* critics that cause them to reject valid trajectories. This is most easily reproduced by "navigating to pose" and then dropping an obstacle onto the path some distance ahead of the robot. DWB will fail well before it reaches the obstacle saying no valid trajectories were found.
* The root cause is in the way the Goal* critics expand their cost function. They add a 0 cost goal cell and then expand out from their add 1 to the cost at each step. However there is an optimization in the expansion that skips cells that are invalid. When the goal itself is invalid, absolutely no cells …

Fix "no valid trajectories" when obstacle on path

---

nav2_amcl/src/amcl_node.cpp

---
* Addresses build errors when `-Werror=class-memaccess` is specified.
* Tested with: `gcc (GCC) 9.1.1 20190503 (Red Hat 9.1.1-1)`

Reset non-trivial objects using assignment

---

nav2_dwb_controller/dwb_critics/default_critics.xml
nav2_dwb_controller/dwb_plugins/plugins.xml

---
* Resolves the following runtime warnings:
```
[dwb_controller-8] [WARN] [pluginlib.ClassLoader]: given plugin name 'lib/libstandard_traj_generator' should be '/libstandard_traj_generator' for better portability
[dwb_controller-8] [WARN] [pluginlib.ClassLoader]: given plugin name 'lib/libsimple_goal_checker' should be '/libsimple_goal_checker' for better portability
[dwb_controller-8] [WARN] [pluginlib.ClassLoader]: given plugin name 'lib/libdwb_critics' should be '/libdwb_critics' for better portability
```
* This aligns the DWB plugins with costmap, where this is already correct: …

Use platform-independent library paths for DWB plugins

---

nav2_bringup/launch/nav2_default_view.rviz

---
* Laser scans are published using `SensorDataQoS`, which means 'Unreliable' should be checked in RViz
* `robot_state_publisher` pushes out the model over `/robot_description`.

Fix robot model and LiDAR display in RViz config

---

nav2_dwb_controller/dwb_core/src/dwb_local_planner.cpp

| Robotic platform tested on | hardware turtlebot3 waffle |
---
* This change makes critic initialization error messages display properly.
Without this change:
```
[dwb_controller-7] [ERROR] [dwb_controller]: Couldn't initialize critic plugin!
[dwb_controller-7] [ERROR] [dwb_controller]: Couldn't load critics! Caught exception: std::exception
```

Use proper exception rethrow for DWB critic init error

---

nav2_dwb_controller/dwb_controller/include/dwb_controller/dwb_controller.hpp
nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp
nav2_world_model/include/nav2_world_model/world_model.hpp
nav2_world_model/src/world_model.cpp

* Previously, the nodes that contain the costmap node (world_model and dwb_controller) relied upon the rclcpp::shutdown (checking rclcpp::ok) to exit the contained node's thread. This PR uses an executor and its cancel operation to cause the thread to exit. This eliminates a race condition that was present which occasionally caused crashes at shutdown. 
* Either make the costmap node a full-fledged node where it is accessed through normal ROS mechanisms (topics, services, etc.) or have it _not_ be a ROS node and accept a ROS node pointer to use to create its topics, etc. We currently have it as a hybrid where it is a ROS node, but the classes that use it (world_model and dwb) access its functionality directly using method calls.

Improve shutdown reliability

---

nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager.hpp
nav2_lifecycle_manager/src/lifecycle_manager.cpp

This PR aims to address _part_ of the issue concerning clean shutdown of nodes even while the robot is navigating
| Ticket(s) this addresses   | #883  |
| Robotic platform tested on | Gazebo simulation turtlebot3 |
- reversed order of shutting down nodes  (reverse of bringup)
- the `changeStateForAllNodes` function is only being used by the `shutdownAllNodes` call. I think we could refactor/clean up the code either by consolidating those functions or by using the former elsewhere during bringup. Instead of bringing up each node with configure and activate back to back, we could transition all nodes to configure first, and then transition them all to activate next.

Reverse order of shutdown nodes

---

nav2_amcl/include/nav2_amcl/amcl_node.hpp
nav2_amcl/src/amcl_node.cpp

---
| Ticket(s) this addresses   | (fixes #819 ) |
| Robotic platform tested on | (Gazebo + TB3) |
---
- This is a quick way to bring back map topic functionality to amcl (#819) for dashing release
- This requires re-initializing pf and memory allocation during active state which is not desirable
- This PR violates our initial lifecycle strategy to allocate memory during inactive state
- Let's have a team discussion to come up with a design to be more aligned with our lifecycle strategy

Amcl map update

---

nav2_msgs/CMakeLists.txt
nav2_msgs/srv/GetCostmap.srv
nav2_msgs/srv/GetRobotPose.srv
nav2_navfn_planner/CMakeLists.txt
nav2_navfn_planner/include/nav2_navfn_planner/navfn_planner.hpp
nav2_navfn_planner/package.xml
nav2_navfn_planner/src/navfn_planner.cpp
nav2_util/include/nav2_util/costmap_service_client.hpp
nav2_util/include/nav2_util/get_robot_pose_client.hpp
nav2_util/include/nav2_util/service_client.hpp
nav2_world_model/include/nav2_world_model/world_model.hpp
nav2_world_model/src/world_model.cpp

| Ticket(s) this addresses   | fixes #518  |
| Primary OS tested on | Ubuntu) |
---
* Get robot pose from transform in navfn.
* Fix navfn to get costmap in action instead of on init function
* We need to assess the impact of obtaining the robot pose via a service call instead of doing the transform locally.

Transform robot pose lifecycle

---

nav2_bt_navigator/include/nav2_bt_navigator/bt_navigator.hpp
nav2_bt_navigator/src/bt_navigator.cpp
nav2_dwb_controller/dwb_controller/include/dwb_controller/dwb_controller.hpp
nav2_dwb_controller/dwb_controller/include/dwb_controller/progress_checker.hpp
nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp
nav2_map_server/include/nav2_map_server/map_server.hpp
nav2_motion_primitives/include/nav2_motion_primitives/motion_primitive.hpp
nav2_motion_primitives/src/back_up.cpp
nav2_motion_primitives/src/spin.cpp
nav2_navfn_planner/include/nav2_navfn_planner/navfn_planner.hpp
nav2_navfn_planner/src/navfn_planner.cpp
nav2_tasks/include/nav2_tasks/behavior_tree_engine.hpp
nav2_tasks/src/behavior_tree_engine.cpp
nav2_util/include/nav2_util/simple_action_server.hpp
nav2_util/src/lifecycle_node.cpp
nav2_util/test/test_actions.cpp

Extended the `SimpleActionServer` interface and improved a few other things: 
* Added additional checks to make sure we only keep the latest preempt request in the queue.
* Action server users no longer interact directly with the goal handles. Provided additional functions for aborting, canceling, etc.
* Updated `bt_navigator`, `motion_primitives`, `dwb_controller`, `navfn_planner` to use the new interface.
Here's a diagram of the states and transitions:
Refactored the DWB controller main loop:
* Changed the order of the steps to: 1) check for cancel 2) check for preempting 3) compute control 4) check if reached goal
* Made a few other small refactors.
* Added checks for handling pending preemptions after the controller has succeeded or failed.
This partially addresses #811 and possibly …

Extended the SimpleActionServer interface

---

nav2_dwb_controller/dwb_core/src/publisher.cpp

Signed-off-by: vinnamkim <vinnam.kim@gmail.com>
I found some error when visualizing dwb_cost_grid. `totals.values` seems to be summation of scaled costs.

Fix error on visualizing the total cost

---

nav2_dwb_controller/dwb_core/include/dwb_core/trajectory_critic.hpp
nav2_dwb_controller/dwb_critics/src/twirling.cpp
nav2_dwb_controller/nav_2d_utils/include/nav_2d_utils/parameters.hpp

| Robotic platform tested on | hardware turtlebot3 waffle |
---
* Without these changes, I've been seeing 'foo has already been declared' errors.
* This doesn't appear to be covered by tests, but repro's when the `critics` parameter isn't set, triggering the following code path:
https://github.com/ros-planning/navigation2/blob/5fe3d4ecc2a5abd7abcdb622ec34f05721da3268/nav2_dwb_controller/dwb_core/src/dwb_local_planner.cpp#L190-L230
---
* When a backwards compatible parameter is set and moved, it is deleted. However, if neither the supported nor backwards compatible parameters are set, they're both left declared. I'm not sure what the desired behavior …

Fix backwards compabile parameters

---

nav2_util/include/nav2_util/simple_action_server.hpp

This PR addresses dwb_controller crash found when there is a failure of dwb. After the `followPath` goal handle is aborted from a dwb_controller failure, on the next loop of the `followPath` it will check for a preemption request on the next `updateGlobalPath`. Currently,  the pending goal is being aborted and reset but the `preempt_requested` flag is not set to false. This supposedly causes an exception and crash when the handle is now `nullptr`. 
Here was the log info:
```
[dwb_controller-8] [ERROR] [DWBLocalPlanner]: No valid trajectories out of 398! 
[dwb_controller-8] [ERROR] [DWBLocalPlanner]: 1.00: BaseObstacle/Trajectory Hits Obstacle.
[dwb_controller-8] [ERROR] [dwb_controller]: No valid trajectories out of 398! 
[dwb_controller-8] [WARN] [dwb_controller_rclcpp_node]: …
```

Set preempt request to false when resetting handle

---

nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp

---
| Ticket(s) this addresses   | #904 |
---
- Checks that a goal is either `action_msgs::msg::GoalStatus::STATUS_ACCEPTED ` or `action_msgs::msg::GoalStatus::STATUS_EXECUTING` before attempting to cancel when `halt()` is called for `BtActionNode`
- fixes crash seen in #904 due to race condition between aborting a goal on server side and sending a cancel on client 
- removes redundant cancel goal

Check goal handle status before canceling

---

nav2_bringup/launch/nav2_bringup_launch.py
nav2_bt_navigator/src/bt_navigator.cpp
nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp
nav2_motion_primitives/include/nav2_motion_primitives/motion_primitive.hpp
nav2_navfn_planner/src/navfn_planner.cpp
nav2_util/include/nav2_util/simple_action_server.hpp
nav2_util/test/test_actions.cpp

---
| Ticket(s) this addresses   | #911 |
| Robotic platform tested on | Turtlebot3 gazebo |
---
Made a few improvements to `SimpleActionServer`, mainly to address #911:
* Check if the goal is active before canceling or aborting.
* Cancel only if the client has requested so, otherwise abort.
* Remove separate `cancel` and `abort` methods, instead have one `terminate_goals` which calls the appropriate method depending on the state of the goal.
---

Fixing bugs with action cancellations

---

nav2_rviz_plugins/src/navigation_dialog.cpp

---
| Ticket(s) this addresses   | (#901 ) |
| Robotic platform tested on | (Gazebo simulation of TB3 Burger, RVIZ) |
---

nav2 rviz plugin action server timeout fix

---

nav2_bt_navigator/src/bt_navigator.cpp
nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp
nav2_navfn_planner/src/navfn_planner.cpp
nav2_util/include/nav2_util/simple_action_server.hpp

| Ticket(s) this addresses   | #883 |
---
- deactivate action server in DwbController and NavfnPlanner
- check and return if action server is unavailable or inactive
- stop robot when deactivating DwbController
- Enable and test pause, resume, and reset 
- `pause` can deactivate system
- `resume` can activate system
- `reset` can take system to unconfigured state (but not shutdown since it is terminal)

Shutdown nodes cleanly

---

nav2_bringup/launch/nav2_default_view.rviz

Since the current default doesn't support showing the local costmap in the odom frame, this PR enables the global costmap to be visualized in rviz.

Show global costmap in rviz as default

---

nav2_costmap_2d/CMakeLists.txt
nav2_dwb_controller/dwb_controller/CMakeLists.txt
nav2_dwb_controller/dwb_core/CMakeLists.txt
nav2_dwb_controller/dwb_critics/CMakeLists.txt
nav2_world_model/CMakeLists.txt

All our builds have boost installed due to other dependencies, so
we've never run into this. The build farm must build with all other
dependencies removed somehow.

Fix the dashing 0.2.1 build on OSRF build farm.

---

nav2_bt_navigator/include/nav2_bt_navigator/recovery_node.hpp
nav2_bt_navigator/src/recovery_node.cpp

---
| Ticket(s) this addresses   | (#939) |
| Robotic platform tested on | (Gazebo simulation) |
---
- This PR partially fixes #939.
- The halt() method needed to be overwritten in the recovery node to be able to reset the internal variable states of the recovery node.  Without this fix, if the tree is canceled, the reset method will invoke the halt but the states of the recovery node will not get reset. Thus, if the recovery node was ticking its second child during execution when cancel is called, the tree will remain in that state forever. 
---

Fixed a bug to be able to reset recovery node internal states

---

nav2_amcl/src/amcl_node.cpp
nav2_costmap_2d/src/costmap_2d_ros.cpp
nav2_system_tests/src/system/test_system_launch.py

| Ticket(s) this addresses   |  fixes #941 |
---
1. Makes use of the new CreateTimerInterface API in TF Buffer.
2. Reenables TF listener to create it's own node and thread. I don't know why this is necessary, but it seems like the right thing to do anyhow. Without this change we seem to end up with more transform errors.
3. Fixes a bug in the system test launch file introduced in #705

Add support for CreateTimerInterface - fix CI

---

nav2_bringup/launch/nav2_params.yaml

The navigation and obstacle avoidance perform less than ideal when the PathAlign and GoalAlign critics are being used. In the local planners from the ROS1 navigation stack, these align critics weren't used, so this PR sets the scale to 0 until we can further investigate why we were receiving poor obstacle avoidance using these critics. Removing their influence for now has led to better performance so far.
- Sets PathAlign and GoalAlign critcs scale to 0
- Tune and test critics scaling

Set GoalAlign & PathAlign critics scale to 0

---

nav2_rviz_plugins/include/nav2_rviz_plugins/navigation_dialog.hpp
nav2_rviz_plugins/src/goal_tool.cpp
nav2_rviz_plugins/src/navigation_dialog.cpp

---
| Ticket(s) this addresses   | (#901, #925) |
| Robotic platform tested on | (RVIZ, Gazebo, Nav2) |
---
- I added a timeout to spin_until_future_complete, so it won't keep spinning and rviz doesn't get frozen if something goes wrong in the navigation stack. 
- I did some changes in the start Navigation; 
- changed the function type to Boolean 
- added returns to the function, so it will return false if something goes wrong.
- I changed goal_tool added a if statement to check if start_navigation doesn't return false before calling any other functions in goal_tool
---
- These changes fix the current RVIZ crashing and getting frozen issues, but more testing is needed.
---
I'd like to …

Nav2-rviz-plugin changes.

---

doc/BUILD.md
tools/build_all.sh
tools/initial_ros_setup.sh

Build tool improvements
- Check if we're in the `navigation2_ws`, `ros2_ws`, or `ros_nav_dependencies_ws` and then cd out into root before running. Now you can run the build tool from any where that navigation2 touches
- rename `navstack_dependencies_ws` to `ros2_nav_dependencies_ws` so that auto complete for "nav" will bring you to the workspace you *actually* wanted to go to.

Build tools - Run build_all.sh from any nested repo workspace & rename dependencies workspace for "nav" autocomplete

---

nav2_rviz_plugins/CMakeLists.txt
nav2_system_tests/package.xml
nav2_system_tests/src/updown/CMakeLists.txt

---
* Fixes a typo introduced in #663. This typo now causes a build failure.

Fixing typo in dependencies

---

nav2_dwb_controller/dwb_controller/CMakeLists.txt

It is dependency of [this PR(port TEB to ROS2)](https://github.com/rst-tu-dortmund/teb_local_planner/pull/159).
Signed-off-by: vinnamkim <vinnam.kim@gmail.com>

Fix for TEB local planner buildable

---

nav2_dwb_controller/dwb_controller/include/dwb_controller/dwb_controller.hpp
nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp

| Ticket(s) this addresses   | #952  |
| Robotic platform tested on | TB3 in gazebo |
---
* Added the `controller_frequency` parameter to change the DWB rate loop. This is the parameter name used in ROS 1.
* Added printouts to report if we missed the loop
* We could push a change to the rclcpp::Rate object to allow us to retrieve how long the loop actually took so we could report it to the user. This would match ROS 1 behavior

Add support to change the local controller rate.

---

nav2_behavior_tree/include/nav2_behavior_tree/spin_action.hpp
nav2_msgs/action/Spin.action
nav2_recoveries/include/nav2_recoveries/spin.hpp
nav2_recoveries/src/spin.cpp

---
| Ticket(s) this addresses   | (fixes #423 ) |
| Primary OS tested on | (Ubuntu 18.02) |
| Robotic platform tested on | (Gazebo sim) |
---
A closed-loop controller similar to backup is added. 
Since for this task, we don't care how close we get to the setpoint, a simple on-off controller was implemented and overshoot is expected.  The faster the robot moves and the slower the loop rate gets, the higher the overshoot.
Parameterize the angle and speed.  Currently, the angle is set to `pi/2` in `spin_action.hpp`
We should be able to change the angle from BT.  For example:
```xml
<Spin theta="180"/>
```
Should make the robot to rotate 180 degrees CW
```xml
<Spin theta="-180"/>
```
Should make the robot to rotate 180 degrees …

enabling closed-loop control in spin

---

nav2_bringup/launch/nav2_default_view.rviz

Temporal fix for #1000, let's just disable displaying the RobotModel by default.

Disable displaying RobotModel in Rviz by default

---

nav2_costmap_2d/include/nav2_costmap_2d/footprint_subscriber.hpp
nav2_costmap_2d/src/footprint_subscriber.cpp

Signed-off-by: Shane Loretz <sloretz@osrfoundation.org>
---
| Primary OS tested on | Ubuntu Bionic |
---
The `FootprintSubscriber` constructor takes a non-const `std::string &`  for the topic name. This makes it impossible to give the topic name from a string literal. The topic name does not need to be mutable.
---
* I did not test this locally due to #965.
---

Make FootprintSubscriber topic parameter a const reference

---

nav2_costmap_2d/include/nav2_costmap_2d/costmap_subscriber.hpp
nav2_costmap_2d/src/costmap_subscriber.cpp

---
---
* Similar to #1011 
* Non-const reference to topic prevents passing string literals like `"costmap"`
* This PR makes the parameter a const reference
---
* I did not build locally due to #965

Costmap subscriber const topic

---

nav2_costmap_2d/CMakeLists.txt

---
| Primary OS tested on | (Ubuntu Bionic) |
| Robotic platform tested on | (NA) |
---
Removes CMake unused or duplicated variables
- `ament_INCLUDE_DIRS`: CMake complains that this variable is uninitialized. I believe this is a leftover from ROS 1 port (catkin_INCLUDE_DIRS was bundling all the found ROS packages include dirs but `ament_cmake` doesn't)
- `laser_geometry_INCLUDE_DIRS`: laser_geometry is in the list of dependencies passed to `ament_target_dependencies` so its presence in `include_directories` is redundant
Signed-off-by: Mikael Arguedas <mikael.arguedas@gmail.com>

[nav2_costmap_2d] remove unnecessary CMake code to remove warning

---

nav2_bringup/launch/nav2_default_view.rviz

The rviz config shows the set of tested DWB paths, which is nice for debug but a little TMI for typical development, just toggling it off.

disabling by default the debug markers for local planner

---

nav2_amcl/include/nav2_amcl/amcl_node.hpp
nav2_amcl/src/amcl_node.cpp
nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp
nav2_costmap_2d/src/costmap_2d_ros.cpp
nav2_dwb_controller/dwb_controller/include/dwb_controller/dwb_controller.hpp
nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp
nav2_util/include/nav2_util/lifecycle_node.hpp
nav2_util/src/lifecycle_node.cpp

---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/950 |
---
* first step in auditing pointers
* removing any pointers that don't fill a purpose, and not effecting lifecycle bringup
---
* convert more of the code to lifecycle so we can remove even more tiny configurable chunks of code from pointers
* understand better our style interest in lifecycle - some places we configure parameters or create pub/sub/clients in the constructor and in other places we do so in the configure state. Get an answer for what we want to do and I can homologate them.
Phase 2 of this …

removing unnecessary smart pointers that dont effect lifecycle

---

nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp
nav2_costmap_2d/src/costmap_2d_ros.cpp
nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp
nav2_util/include/nav2_util/node_utils.hpp
nav2_util/src/node_utils.cpp
nav2_world_model/src/world_model.cpp

| Ticket(s) this addresses   | #971  |
| Robotic platform tested on | Gazebo simulation of TB |
---
If the nodes hosting costmaps (i.e. world map & dwb) are placed on a namespace, this PR will also put the costmaps on that namespace:
| Namespace | World Model | Global Costmap  | DWB | Local Costmap |
| ---------------- | ----------------- | ---------------------- | ------- | -------------------- |
| /      | /world_model | /global_costmap/global_costmap | /dwb_controller | /local_costmap/local_costmap |
| /robot1 | /robot1/world_model | /robot1/global_costmap/global_costmap | /robot1/dwb_controller | /robot1/local_costmap/local_costmap |
The namespace could be provided on the hosting …

Add global namespace to costmap's local namespace

---

nav2_amcl/src/amcl_node.cpp
nav2_util/include/nav2_util/lifecycle_node.hpp
nav2_util/src/CMakeLists.txt
nav2_util/src/doit
nav2_util/src/dump_params.cpp

This is a utility that will dump all of the parameters for one or more running nodes. It can be used to document the default node parameters. The intention is to automatically generate markdown and/or yaml such that the output is derived from the code so that we don't have to manually keep the docs in sync with the code. 
```
Usage: dump_params
Options:
-h [ --help ]           Print help message
-n [ --node_names ] arg A list of comma-separated node names
-f [ --format ] arg     The format to dump ('yaml' or 'markdown')
-v [ --verbose ]        Verbose option
```
The following will dump parameters for all nodes currently running, defaulting to the concise yaml format (parameter name and value):
`dump_params`
The following will create yaml output with a verbose listing (including all of the …

Parameter dumping utility

---

nav2_bt_navigator/src/bt_navigator.cpp
nav2_costmap_2d/src/costmap_2d_ros.cpp
nav2_lifecycle_manager/src/lifecycle_manager.cpp
nav2_rviz_plugins/src/navigation_dialog.cpp
nav2_util/include/nav2_util/service_client.hpp
nav2_util/src/lifecycle_node.cpp
nav2_util/src/node_utils.cpp

Make sure service clients have a unique node name (this was a problem in recoveries nodes)
Delimit ros arguments with new `--ros-args`,`--` due to upstream changes in https://github.com/ros2/rcl/pull/477

Fix node name collisions

---

nav2_costmap_2d/include/nav2_costmap_2d/collision_checker.hpp
nav2_costmap_2d/src/collision_checker.cpp
nav2_costmap_2d/src/costmap_2d_ros.cpp
nav2_costmap_2d/test/integration/test_collision_checker.cpp
nav2_recoveries/include/nav2_recoveries/recovery.hpp
nav2_recoveries/src/back_up.cpp
nav2_recoveries/src/main.cpp
nav2_recoveries/src/spin.cpp
nav2_recoveries/test/test_recoveries.cpp

---
| Ticket(s) this addresses   | #994 https://github.com/ros-planning/navigation2/issues/1026  |
---
* using the odometric positioning so that the recoveries are **not** effected by global localizer updates for controller outputs
* pulling local costmap at potentially higher resolution so anything controlling motors is using the same sets of information 
* correcting the frame of reference
---
I need to test this before merging, but I'm having a hard time figuring out exactly how I plan to do that
---

Recovery using odometric poses and costmaps

---

tools/build_all.sh
tools/initial_ros_setup.sh

Also came up because the ros2_ws didn't have rosdep called over it so anything in a clean 18.04 container (or metal) didn't have alot of things installed that were necessary for a clean build on a new machine
Edit: I start out yesterday to work on recoveries... ended up battling dependency PIP vs APT nightmares for 15 hours... "Oh that's missing let me just pip install it..." *famous last words*

on download, rosdep all necessary items, calling on each build is redundant

---

nav2_bringup/launch/nav2_simulation_launch.py
nav2_recoveries/include/nav2_recoveries/recovery.hpp

Adding the `..._and_recovery` XML file for the simulation launch file so we can have the recovery behaviors running in the simulation. There were a few issues I resolved that likely would have been seen earlier if it were default.

adding recoveries XML to simulation launch file

---

codecov.yml

---
* adding a config file for codecov.io so that it can find our source files to include in the report.
* The actual code coverage data records the path relative to the top of the workspace eg src/navigation2/nav2_amcl/src/main.cpp. Codecov.io needs the file names relative to the root of the repo. So we just tell codecov.io to drop the src/navigation2 part of the path

Fixing up paths for codecov.io report

---

nav2_map_server/test/unit/test_occ_grid.cpp

No idea why this builds under GCC but these changes were needed to build under clang.

[Eloquent] Fix the build due to access specifiers

---

nav2_system_tests/package.xml

| Primary OS tested on | Ubuntu (docker container) |
---
Without these dependencies declared, if I build `--packages-up-to nav2_system_tests` on a clean ROS 2 source install, the tests fail.
---
I heard that `gzserver` may be crashing while running these tests at times, but I wasn't able to reproduce it in a clean environment. If anyone knows how to reproduce it, I'd be happy to take a look on whether the problem is coming from `gazebo_ros_pkgs`.

Add missing dependencies to system tests

---

nav2_util/src/map_loader/CMakeLists.txt

Fixes a failing compile bug for `nav2_util` which won't compile due to a recent commit that forgot to include a dependency on `tf2_geometry_msgs`

add tf2_geometry_msgs dependency

---

nav2_system_tests/src/updown/test_updown_launch.py
nav2_system_tests/src/updown/updownresults.py

| Robotic platform tested on |  NA |
---
* Fixes the updown test. The test launch file was written using the `ExecuteProcess` action, but hadn't been updated for the new commandline interface that requires the `--ros-arg` option.
* Adds a script to analyze the test log to report results.
---
* The launch file should be re-written to use the `Node` launch action instead of ExecuteProcess
* The test should be refactored to use the nav2_bringup params instead of providing its own.

Fix the updown test.

---

.dockerhub/debug/hooks/build
.dockerhub/devel/hooks/build
.dockerhub/release/hooks/build

Default build args for the dockerfile where not being overridden as the environment variables in the build hook where not exported. Thus the master.release tag was not being built with the intended rmw tag.
https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg

Export envs for arg in build hook

---

nav2_system_tests/package.xml
nav2_system_tests/src/system/test_system_node.py

Previously on Crystal, the system test had to set 'use_sim_time' dynamically for some composed nodes like /global_costmap/global_costmap. That's not necessary anymore. This removes that code. 
Let's see if it passes CI before reviewing.

Remove set sim time

---

nav2_system_tests/CMakeLists.txt
nav2_system_tests/package.xml
nav2_system_tests/src/planning/CMakeLists.txt
nav2_system_tests/src/planning/planner_tester.cpp
nav2_system_tests/src/planning/planner_tester.hpp
nav2_system_tests/src/planning/test_planner_launch.py
nav2_system_tests/src/planning/test_planner_node.cpp
tools/run_test_suite.bash

---
| Ticket(s) this addresses   | #586 |
| Primary OS tested on | Ubuntu 18.0 |
---
* Made a few upgrades, including using the ROS2 actions interface.
* Enabling the planner tests on CI. Ran the tests on my machine 100 times with two failures -- planning service was not available on both.

Enable global planner tester

---

nav2_costmap_2d/src/observation_buffer.cpp

#1073 changed to the improper `rclcpp::Duration` signature that uses `int32_t` for seconds though in the code we are passing in a double. This PR used the `rclcpp::Duration::from_seconds` which is more appropriate.

use rclcpp::Duration::from_seconds

---

nav2_system_tests/README.md
nav2_system_tests/scripts/ctest_loop.bash
nav2_system_tests/src/system/README.md
nav2_system_tests/src/system/test_system_launch.py

Adds a script to the system tests directory for looping the bt_navigator system test. Useful for reliability testing. 
Also updates the README files with instructions
---
N/A

Add ctest loop script

---

LICENSE
nav2_amcl/include/nav2_amcl/angleutils.hpp
nav2_amcl/package.xml
nav2_behavior_tree/package.xml
nav2_bringup/package.xml
nav2_bt_navigator/package.xml
nav2_common/package.xml
nav2_costmap_2d/package.xml
nav2_dwb_controller/costmap_queue/package.xml
nav2_dwb_controller/dwb_controller/package.xml
nav2_dwb_controller/dwb_core/package.xml
nav2_dwb_controller/dwb_critics/package.xml
nav2_dwb_controller/dwb_msgs/package.xml
nav2_dwb_controller/dwb_plugins/package.xml
nav2_dwb_controller/nav2_dwb_controller/package.xml
nav2_dwb_controller/nav_2d_msgs/package.xml
nav2_dwb_controller/nav_2d_utils/package.xml
nav2_dynamic_params/package.xml
nav2_lifecycle_manager/package.xml
nav2_map_server/package.xml
nav2_msgs/package.xml
nav2_navfn_planner/package.xml
nav2_recoveries/package.xml
nav2_rviz_plugins/package.xml
nav2_system_tests/package.xml
nav2_util/package.xml
nav2_voxel_grid/package.xml
nav2_world_model/package.xml
navigation2/package.xml

| Ticket(s) this addresses   | #1035 |
---
* Changed the license tag in all `package.xml` files to proper [SPDX ID](https://spdx.org/licenses/).
* For packages with mixed license, added a second license tag. This is the method specified in the [Package format specification](https://www.ros.org/reps/rep-0149.html#license-multiple-but-at-least-one)
* Added a LICENSE file
* Fixed a minor linter issue, even though the linter is currently disabled.
**NOTE** - I believe this resolves all license issues in the repo.

Clarify Licensing throughout the repo

---

nav2_common/nav2_common/launch/rewritten_yaml.py

Fixes the feature deprecated warning we get during runtime on `rewritten_yaml.py` -- more on this [here](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation)
```bash
rewritten_yaml.py:56: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details
```

Fix python yaml loader

---

nav2_map_server/src/occ_grid_loader.cpp

possibly responsible for heisenbug https://github.com/ros-planning/navigation2/issues/1079#issuecomment-526782592

Null-terminate string to dirname function

---

tools/ros2_dependencies.repos

| Robotic platform tested on | SystemTest |
---
* We were tracking the ros2 branch of the BT library, however, this branch seems out of date. Grabbing the latest tagged version instead.

Update to latest v2 BT Library

---

nav2_dynamic_params/test/test_dynamic_params_client.cpp
nav2_system_tests/src/planning/planner_tester.cpp
nav2_system_tests/src/planning/planner_tester.hpp
nav2_system_tests/src/planning/test_planner_launch.py
nav2_system_tests/src/planning/test_planner_node.cpp
nav2_util/include/nav2_util/lifecycle_utils.hpp
nav2_util/src/lifecycle_bringup_commandline.cpp
nav2_util/src/lifecycle_utils.cpp
nav2_util/test/test_lifecycle_utils.cpp

As is, the global planner tests still fail occasionally. The failure modes I'm observing are related to the robot pose transform not available to `navfn` at the time the plan request is sent and what appears to be a race condition where the tests are waiting for the planner to become available and planner is waiting for the costmap to become available.
Fixed this by:
* Replacing control of state transitions for `navfn` through `LifecycleManager` with transitions directly on the tests.
* Added periodic publishing of transforms.
* Added a `bringdownLifecycleNodes` method to `nav2_utils`
Ran tests 300 times with no failures on my machine.
---
* Bringing down the `navfn` node results on a fastrtps error.

Improvements to global planner tests

---

nav2_util/src/map_loader/CMakeLists.txt

---
| Primary OS tested on | NixOS (Linux) |
---
`nav2_util` fails to build on Nix (https://github.com/lopsided98/nix-ros-overlay) with the following error:
```
In file included from /build/navigation2-release-release-dashing-nav2_util-0.2.3-1/src/map_loader/map_loader.cpp:36:0:
/nix/store/snzbjcqvacn5i4y96i8wan4zvkaybdbn-SDL_image-1.2.12/include/SDL/SDL_image.h:27:10: fatal error: SDL.h: No such file or directory
#include "SDL.h"
^~~~~~~
compilation terminated.
```
Nix uses non-standard installation paths, which is probably why this bug did not show up on other platforms.
This PR adds the SDL include directories to the `map_loader` target.

map_loader: add SDL include directories

---

nav2_costmap_2d/plugins/obstacle_layer.cpp
nav2_costmap_2d/plugins/static_layer.cpp
nav2_costmap_2d/plugins/voxel_layer.cpp
nav2_costmap_2d/src/clear_costmap_service.cpp
nav2_costmap_2d/src/costmap_2d_ros.cpp
nav2_costmap_2d/src/layer.cpp
nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp
nav2_dwb_controller/dwb_core/src/dwb_local_planner.cpp
nav2_dwb_controller/dwb_core/src/publisher.cpp
nav2_dwb_controller/dwb_critics/src/base_obstacle.cpp
nav2_dwb_controller/dwb_critics/src/map_grid.cpp
nav2_dwb_controller/dwb_critics/src/oscillation.cpp
nav2_dwb_controller/dwb_critics/src/prefer_forward.cpp
nav2_dwb_controller/dwb_plugins/src/kinematic_parameters.cpp
nav2_dwb_controller/dwb_plugins/src/limited_accel_generator.cpp
nav2_dwb_controller/dwb_plugins/src/simple_goal_checker.cpp
nav2_dwb_controller/dwb_plugins/src/standard_traj_generator.cpp
nav2_dwb_controller/dwb_plugins/src/stopped_goal_checker.cpp
nav2_dwb_controller/dwb_plugins/src/xy_theta_iterator.cpp
nav2_dwb_controller/nav_2d_utils/include/nav_2d_utils/odom_subscriber.hpp
nav2_util/include/nav2_util/node_utils.hpp

Adds a `declare_if_not_declared` template function and integrates throughout the stack to allow nodes (and particularly plugins) to be reset (unconfigured and configured again) without causing run-time errors for a parameter that has already been declared. 
Related to #714

Declare if not declared parameters

---

nav2_bringup/launch/nav2_navigation_launch.py
nav2_bringup/launch/nav2_params.yaml
nav2_costmap_2d/include/nav2_costmap_2d/static_layer.hpp
nav2_costmap_2d/plugins/static_layer.cpp
nav2_costmap_2d/src/costmap_2d_ros.cpp
nav2_costmap_2d/src/costmap_layer.cpp

This PR includes changes for using Navigation 2 and Slam together. These changes are tested using Navigation 2 (Dashing-Devel), Cartographer and real robot (Turtlebot 3).
- set map_subscribe_transient_local parameter in the launch file to False when launching Navigation 2 without AMCL and Map Server. The default value for this parameter is True.  This parameter is used to set the QoS settings.
- Set QoS Keep_last to 1 or 10.
- added if costmap_ == nullptr. If for any reason costmap_ is nullptr, wrold model will stop working. this problem occurs when the QoS settings are not right.

Add support for running nav2 with cartographer

---

nav2_bringup/launch/nav2_simulation_launch.py
nav2_system_tests/src/updown/test_updown_launch.py

---
* there are two launch files that still use ExecuteProcess instead of the ros Node action to launch nav2 components. They are currently broken due to the new command line parameter format. This PR is a quick fix to get them working again. Replacing them with Node actions is being done as part of the multi-robot fixes.

Fix ExecuteProcess actions to use new parameter format.

---

.circleci/config.yml

| Ticket(s) this addresses   | This PR addresses the issue noted here https://github.com/ros-planning/navigation2/pull/1107#issuecomment-530652301 |
| Primary OS tested on |   |
---
* CircleCI is currently only running rosdep on the underlay(navstack dependencies) workspace, and not the nav2 workspace. This PR adds the current workspace to the rosdep command.
* When the CircleCI `install_dependencies` command is run on the underlay, the two paths will collapse to the same directory and should be harmless but redundant. When the `install_dependencies` command is run on the overlay (nav2) workspace, then underlay and overlay will be scanned for dependencies as desired.
* Once …

Add current workspace to the rosdep install command

---

nav2_rviz_plugins/src/nav2_panel.cpp

---
---
Fix for rviz complaining about deprecated params:
```'Found remap rule '__node:=navigation_dialog_action_client'. This syntax is deprecated. Use '--ros-args --remap __node:=navigation_dialog_action_client' instead.```
---

updated deprecated setting of ros-args 

---

nav2_planner/src/planner_server.cpp

Part of addressing fixes in #1121 . `costmap_ros_` is being created in the constructor of the planner, therefore we shouldn't be resetting it during the `on_cleanup` call, as this will crash the node when attempting to call `on_configure` again.

remove reset of costmap_ros shared ptr

---

nav2_system_tests/src/planning/planner_tester.cpp

There were recent changes in rclcpp for the deprecated publisher API, this PR fixes the current compilation error for the `nav2_system_tests`

Fix deprecated publisher api issues

---

Dockerfile

Use multistage build in Dockerfile to cache dependency install agents only the package.xml files themselves, rather than the entire build context passed to the docker daemon.  
Context: https://github.com/ros-planning/navigation2/pull/1106#issuecomment-530614144

Cache per packge.xml via multistage build

---

nav2_system_tests/src/system/test_system_launch.py

---
| Info | Set correct path for params file |
| Primary OS tested on | (Ubuntu 18.4) |
---
changed nav2_params.yaml file path from ```/nav2_bringup/launch/``` to ```/nav2_bringup/params/```
---

Fix params file path for nav2_params in the system tests

---

Dockerfile

Update Dockerfile now that colcon mixin comes pre-configured from base images.
Context: https://github.com/osrf/docker_images/pull/315

Colcon mixin now installed from base image

---

nav2_navfn_planner/src/navfn_planner.cpp

Since parameters are being declared in the `on_configure` call of `NavfnPlanner`, they should be `declare_if_not_declared` to allow for the node to be re-configured, otherwise we get an error.

declare_parameter_if_not_declared in NavfnPlanner

---

nav2_amcl/include/nav2_amcl/amcl_node.hpp
nav2_amcl/src/amcl_node.cpp

Fixes amcl lifecycle node transition bug in #1121, where the `LaserReceived` callback was being called even though the map had not yet been received, causing a crash because the map was null. There was a check the that `first_map_received_` was true lest it returned, so this PR sets that flag to false when the node calls `on_cleanup`. 
This is the last bug I've seen blocking the lifecycle nodes from being transitioned via the `LifecycleManager` with `reset` and back to `startup`.

set first_map_received in amcl to false when cleaning up

---

nav2_bt_navigator/src/bt_navigator.cpp
nav2_util/include/nav2_util/simple_action_server.hpp

Fixes (at least in my several local tests) `bt_navigator` bug in #1121 on re-configuring after reset. This PR creates the `SimpleActionServer` on the `BtNavigator` lifecycle node as opposed to the `rclcpp_node`. Added new constructor in `SimpleActionServer` to support node interfaces. In any case, not sure if there was a good reason not to have the goal subscription and action server on the `BtNavigator` node itself. 
Before, we were getting crashes in `bt_navigator` dealing with creation of action server on the `rclcpp_node`.  Current theory is that the `rclcpp_node` still had ownership to a shared pointer to the first action server even though the SimpleActionServer was destructed.
```
[bt_navigator-10] 2019-09-18 15:21:13.370 [PARTICIPANT Error] Type : …
```

create action server on BtNavigator node

---

nav2_lifecycle_manager/src/lifecycle_manager.cpp

The entire system may involve other nodes launched from a launch file, including non-lifecycle nodes, nodes not managed by Lifecycle Manager, etc.

Change "the system" to "managed nodes" in lifecycle manager logging

---

nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager.hpp
nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager_client.hpp
nav2_lifecycle_manager/src/lifecycle_manager.cpp
nav2_lifecycle_manager/src/lifecycle_manager_client.cpp
nav2_rviz_plugins/include/nav2_rviz_plugins/nav2_panel.hpp
nav2_rviz_plugins/src/nav2_panel.cpp

This PR enables the `Nav2Panel` to transition states properly whether the navstack has been autostart enabled or not
| Info |  |
| Ticket(s) this addresses   | #1067 |
| Primary OS tested on | Ubuntu 18.04) |
- adds `is_active_srv` and `is_active_client` to lifecycle manager and its client
- sets active flag  if lifecycle manager `startup` was successful
- adds `InitialThread` QThread which starts in the `Nav2Panel` constructor and requests active state, sends signal to button state, and terminates when finished
- Creates new `pre_initial` state that waits for the lifecycle manager to respond before transitioning to either `initial` or `completed` (should probably rename this state)

Rviz panel autostart fix

---

nav2_rviz_plugins/include/nav2_rviz_plugins/nav2_panel.hpp
nav2_rviz_plugins/src/nav2_panel.cpp

This PR is based off refactoring done in PR #1098 
| Ticket(s) this addresses   | #818  |
- Replaced `shutdown` with `reset`, allowing users to `startup` again
- Added second button for `pause` and `resume`, which will deactivate and activate the navstack lifecycle nodes
State diagram:
- Fix bugs to allow `startup` to work again properly after system has been `reset`
- This is an old problem, but perhaps the button states should fail transitioning if the lifecycle nodes were unsuccesfully transitioned? Right now the calls are asynchronous and the states will transition regardless of the outcome

Add Pause, Resume, and Reset rviz panel buttons

---

nav2_behavior_tree/include/nav2_behavior_tree/goal_reached_condition.hpp
nav2_bt_navigator/CMakeLists.txt
nav2_bt_navigator/include/nav2_bt_navigator/bt_navigator.hpp
nav2_bt_navigator/package.xml
nav2_bt_navigator/src/bt_navigator.cpp

---
---
Fix for #1105.
* Making a transform (buffer) available on the behavior tree blackboard for nodes to pull and use.
* Updating `GoalReachedCondition` to use the blackboard provided tf.
More details here: https://github.com/ros-planning/navigation2/issues/1105#issuecomment-534203963

Update design for providing transform to bt nodes

---

nav2_amcl/include/nav2_amcl/amcl_node.hpp
nav2_amcl/src/amcl_node.cpp

By default, we have the last known pose being initialized as the initial pose when AMCL is reset. However, when re-configuring and re-activating AMCL, the particle filter was being cleared and the covariances from the last known pose were not re-initialized even if the pose position itself was being re-initialized, causing poorer initialization after a reset. Also, if pose is set via parameter, the original initial pose parameters are being set even after AMCL is reset. Lastly, in the case that the robot does move (robot kidnapping) between resetting and starting up again, there should be an option to require that the user provide a new initial pose.
This PR addresses these issues via the following:
- forces update of particle filter when started after `on_cleanup` is called
- sets the …

reset AMCL initial pose with last known pose covariances

---

nav2_common/cmake/nav2_package.cmake

---
---
Enable deprecated warnings during build. -- we're currently getting no warnings :smiley:

Enable deprecated warnings

---

nav2_bringup/params/nav2_params.yaml

---
| Ticket(s) this addresses   | #1164 |
---
Params yaml file had wrong names for the planner nodes.
It was also missing a parameter on one bt node.

Set correct time in Planner

---

nav2_bringup/bringup/launch/nav2_bringup_launch.py
nav2_bringup/bringup/launch/nav2_localization_launch.py
nav2_bringup/bringup/launch/nav2_navigation_launch.py
nav2_bringup/bringup/launch/nav2_tb3_simulation_launch.py
nav2_bt_navigator/behavior_trees/navigate_w_replanning_and_recovery.xml
nav2_common/nav2_common/launch/__init__.py
nav2_common/nav2_common/launch/node.py
nav2_common/nav2_common/launch/rewritten_yaml.py
nav2_common/package.xml
nav2_controller/src/nav2_controller.cpp
nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp
nav2_costmap_2d/src/costmap_2d_ros.cpp
nav2_planner/src/planner_server.cpp

---
---
Extends #1146 adding capability of namespacing the stack (nodes and topics).
* Extending `rewritten_yaml` to also replace keys
* Adding a node launcher that puts a condition to applying the remappings.
* Add namespacing to launch files
* Update namespace of costmap. Planner and controller now pass the correct namespace to use.

[multirobot - Part2] Add namespacing to nav stack

---

nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp

this fixes rare cases where my dwb controller isn't picking up changes to the global path.

prevent dwb controller from missing changes to the global path (#1160)

---

nav2_bt_navigator/behavior_trees/navigate_w_replanning_and_recovery.xml

---
| Robotic platform tested on | TB3 simulation |
---
When running the system test 1000 times, I often saw this (12/1000):
```
12: [test_system_node-11] [INFO] [nav2_tester]: Distance from goal is: 1.6401835582713067
12: [navfn_planner-7] [WARN] [navfn_planner]: Planning algorithm failed to generate a valid path to (0.00, 2.00)
12: [dwb_controller-6] [INFO] [local_costmap.local_costmap]: Received request to clear entirely the local_costmap
12: [navfn_planner-7] [INFO] [global_costmap.navfn_planner]: Received request to clear entirely the global_costmap
12: [navfn_planner-7] [INFO] [global_costmap.navfn_planner]: Subscribing to the map topic (/map) with …
```

Update behavior tree with local and global planner recoveries

---

nav2_bringup/bringup/launch/nav2_multi_tb3_simulation_launch.py
nav2_bringup/bringup/rviz/nav2_namespaced_view.rviz
nav2_common/nav2_common/launch/__init__.py
nav2_common/nav2_common/launch/replace_string.py

---
---
*Last stacked PR*
Extends #1148. Adds functionality to launch one RVIZ instance per robot.
Each instance is set with the correct namespacing for controlling the corresponding robot.
---

[multirobot - Part4] Multiple robot control via RVIZ

---

nav2_costmap_2d/test/integration/CMakeLists.txt
nav2_costmap_2d/test/integration/test_collision_checker.cpp
tools/run_test_suite.bash

---
| Ticket(s) this addresses   | #1030  |
---
- Added sleep after broadcasting tf transform in  `test_collision_checker.cpp` to fix race condition when collision checker tries to get the pose off the tf transform immediately after it's been sent
- re-enable `test_collision_checker_exec` in CMakeLists
- for cleanup, removed nav2_dynamic_params from the `test_suite.bash` since that package has now been completely removed

Re-enable test_collision_checker

---

.circleci/config.yml
.dockerhub/debug/hooks/build

Use `/opt/underlay_ws` as the target underlay for overlay's `install_dependencies` command, otherwise the checksum.txt for the overlay is improperly copied from `/opt/ros_ws` instead of `/opt/underlay_ws`.

Fix underlay parameter for install_overlay_dependencies

---

nav2_bringup/bringup/launch/nav2_multi_tb3_simulation_launch.py
nav2_bringup/bringup/rviz/nav2_namespaced_view.rviz
nav2_common/nav2_common/launch/__init__.py
nav2_common/nav2_common/launch/replace_string.py

---
---
Incorrectly merged #1149 into a development branch -- I had the multi-robot PRs stacked and forgot to switch this last PR to `master` before merging.
Anyway, I'll just merge this since #1149 was already approved.

[multirobot - Part4] Multiple robot control via RVIZ - Fix merge

---

nav2_bt_navigator/behavior_trees/navigate_w_replanning_and_recovery.xml

---
Clear costmap services should be placed on relative namespaces.

Use relative namespace for clear costmap services

---

nav2_amcl/src/amcl_node.cpp

---
| Robotic platform tested on | (Gazebo + TB3 simulation) |
---
- Initial pose is not needed to save map messages. We need to be able to save map data even when the callback is called only once.
- When map messages are being published periodically and `first_map_only_` flag is set to false, we are resetting pf every time the map callback is called.  This can cause divergence. To fix this issue, every-time we get a map update, I only clear the map and laser data without re-initializing pf every time. 
---

Handle map messages even if there is no initial pose

---

nav2_bt_navigator/src/bt_navigator.cpp

---
---
Since we're passing a spinning node to the transform we should tell the tf buffer we're using a dedicated thread.
We currently get some warnings on the terminal:
```bash
[bt_navigator-10] Do not call canTransform or lookupTransform with a timeout unless you are using another thread for populating data. Without a dedicated thread it will always timeout.  If you have a seperate thread servicing tf messages, call setUsingDedicatedThread(true) on your Buffer instance.
```

Fix bug in BT Navigator transform

---

nav2_behavior_tree/src/recovery_node.cpp

---
| Ticket(s) this addresses   | (#1179) |
| Robotic platform tested on | (Gazebo + TB3) |
---
---
As a temporary quick fix I am calling the Halt method when recovery node returns success. We need to dive deeper to find out why the parent node is not calling the halt method.

Halt method in the recovery node is not being called after successfull navigation

---

nav2_system_tests/src/system/test_system_node.py

The bt_navigator and bt_navigator_dykstra system tests won't pass on dashing, since they are using the wrong topic "/goal_pose". This changes it back to using "/move_base_simple/goal"
NOTE: THIS IS A PR DIRECTLY TO THE DASHING BRANCH

Change system test back to using /move_base_simple/goal

---

nav2_recoveries/include/nav2_recoveries/recovery.hpp

The spin recovery cannot send velocity commands because the publisher is never activated. This PR activates/deactivates the publisher for the recovery plugins.

Activate recovery server velocity publisher

---

nav2_recoveries/plugins/back_up.cpp
nav2_recoveries/src/recovery_server.cpp

A reset and subsequent startup of the recovery server causes an error due to the re-declaration of parameters in the `on_configure` call. This PR moves parameter declarations in the `RecoveryServer` to the constructor and uses the `declare_if_not_declared` function in recovery plugins.

Declare parameters reset/startup fix for recovery server

---

nav2_amcl/src/amcl_node.cpp

The `init_pose` double array is intended to be for (x,y, yaw), not (x,y,z) as erroneously thought before, causing the yaw to be initialized incorrectly every time the stack was reset. This PR fixes this by setting the last known orientation.

Set init_pose yaw component in AMCL

---

nav2_recoveries/src/recovery_server.cpp

There is a bug when cleaning up the recovery plugins in the `recoveries_server` where the plugins are cleaned up but the plugin instances are never cleared from the vector. This causes an issue when the plugins are loaded again in the `on_configure` call, since duplicate plugins are added to the vector without removing the old ones.
This PR clears the recoveries vector `on_cleanup`. For consistency with the stack, I'm also resetting the tf buffer and tf listener.

Clear recovery plugins on cleanup

---

nav2_behavior_tree/include/nav2_behavior_tree/wait_action.hpp

The current WaitAction does not work properly because it does not accept parameter arguments from the behavior tree xml, making the duration 0 seconds. There was also a bug upon reset and startup of the recovery plugins such that the call to sleep for the duration hangs which this PR apparently fixes too. 
For reference, bt nodes which accept parameters must pass in the `BT::NodeParameters` in the constructor and implement the static method `requiredNodeParameters()`

Allow parameters in WaitAction

---

nav2_bringup/bringup/rviz/nav2_default_view.rviz
nav2_bringup/bringup/rviz/nav2_namespaced_view.rviz
nav2_map_server/src/occ_grid_loader.cpp

---
| Ticket(s) this addresses   | #867 , #331  |
| Robotic platform tested on | Turtlebot3 simulation |
---
* removes timer thread from map_server that republishes map every 2s
* updates the Rviz config file to add new QOS settings
* sets Rviz QOS settings for map topics (map, local & global costmaps) to use transient_local with depth of 1
* sets Rviz QOS settings for sensor topics (scan, pointcloud) to use default sensor settings (Best Effort reliability)
---
I grepped through the code to look for any other non-default QOS settings, couldn't find any others, but if anyone notices that something no longer shows up in Rviz, this PR could be the culprit
My testing looked good, I think it …

Dont republish map

---

nav2_bringup/bringup/params/nav2_params.yaml

The scan parameters were not being set from the yaml because the `declareParameter` was expecting the parameters to be under the 'obstacle_layer' namespace, e.g. `obstacle_layer.scan.topic'.  Therefore, the obstacle layer was never receiving scan callbacks, causing the robot to ram into obstacles since the costmap was not updated.
| Ticket(s) this addresses   | #1208 |
---
- moves parameters for the scan observations to the obstacle layer namespace in the `nav2_params.yaml`

Move scan parameters under obstacle layer namespace

---

nav2_costmap_2d/src/costmap_2d_ros.cpp

This PR is a fix for the global costmap node not receiving parameters from the `nav2_params.yaml`. The issue is that the launch file [mechanism to remap the node name](https://github.com/ros-planning/navigation2/blob/master/nav2_bringup/bringup/launch/nav2_navigation_launch.py#L115)  in the planner server node in the `nav2_navigation_launch.py` has a bug that also overwrites the name of the `Costmap2DROS` node that is created in its constructor. The name of the costmap node becomes 'global_costmap/planner_server', which doesn't align with the node specified in the yaml as 'global_costmap/global_costmap', thus the yaml parameters are not being set. 
This PR resolves this by adding the `__node` remapping to the node options in the costmap in order to enforce that the costmap node keeps its …

Enforce costmap to retain its node name

---

nav2_bringup/bringup/launch/nav2_bringup_launch.py
nav2_bringup/bringup/launch/nav2_multi_tb3_simulation_launch.py
nav2_bringup/bringup/launch/nav2_navigation_launch.py
nav2_bringup/bringup/launch/nav2_tb3_simulation_launch.py
nav2_bt_navigator/CMakeLists.txt
nav2_system_tests/src/system/test_system_launch.py

---
| Ticket(s) this addresses   | fixes #1090 |
| Robotic platform tested on | TB 3 in Gazebo |
---
* Install behavior trees in `/opt/ros/dashing/share/nav2_bt_navigator/behavior_trees` instead of `/opt/ros/dashing/behavior_trees`

Install Behavior Trees in correct location

---

nav2_controller/include/nav2_controller/nav2_controller.hpp
nav2_controller/src/nav2_controller.cpp
nav2_recoveries/include/nav2_recoveries/recovery.hpp

| Ticket(s) this addresses   | #1114  |
| Robotic platform tested on | CI* |
* since just ptr type changes
---
* changed any shared ptr that could be unique to unique. 
* Now only shared ptrs are needed as such or TF
* frankly, we were in better shape than I suspected 
---

convert candidate shared ptrs to unique ptrs

---

nav2_behavior_tree/include/nav2_behavior_tree/back_up_action.hpp
nav2_behavior_tree/include/nav2_behavior_tree/spin_action.hpp
nav2_bt_navigator/behavior_trees/navigate_w_replanning_and_recovery.xml
nav2_costmap_2d/src/costmap_2d_publisher.cpp
nav2_msgs/action/BackUp.action
nav2_recoveries/include/nav2_recoveries/recovery.hpp
nav2_recoveries/plugins/back_up.cpp
nav2_recoveries/plugins/back_up.hpp
nav2_recoveries/plugins/spin.cpp
nav2_recoveries/plugins/spin.hpp
nav2_recoveries/src/recovery_server.cpp
nav2_util/src/costmap.cpp

---
| Ticket(s) this addresses   | #775 https://github.com/ros-planning/navigation2/issues/727 |
| Primary OS tested on | CI tests |
| Robotic platform tested on | CI  |
* tested on CI since BT would simply crash if any of the behavior tree stuff was broken. Will test Monday for recovery server side but don't expect issues since primarily is just declaring params or taking new params from action message
---
* got rid of all magic numbers in stack (except timeouts)
---
* parameterize timeout

Remove hard-coded numbers from recovery actions

---

nav2_lifecycle_manager/src/lifecycle_manager_client.cpp
nav2_rviz_plugins/include/nav2_rviz_plugins/nav2_panel.hpp
nav2_rviz_plugins/src/nav2_panel.cpp

---
| Ticket(s) this addresses   | #1200  |
---
This fixes the bug (#1200) where the nav2 rviz panel wasn't working with cyclonedds.
There was a race condition during initialization between:
1. the start of the state machine in the panel which tracks the state of the system and updates the buttons
2. the thread which retrieves the system status via the lifecycle_manager/is_active service. 
If the thread received a response too fast and it emitted the signal back to the state machine before the state machine had asynchronously started, the state machine didn't receive the signal at all. 
This fixes that by using the state …

Fix rviz panel initialization race

---

nav2_bringup/launch/nav2_navigation_launch.py
nav2_costmap_2d/plugins/static_layer.cpp

---
The upstream ros2/cartographer changed to use transient_local, so now we can use transient local in the nav2_navigation_launch.py 
Also, during back-port of the previous change, another change was needed to set the "map_received" flag to true in the static layer after it is received. This change was already existing in the master branch, but not backported.
IF it's not too late, we should release these changes with the newest release (0.2.5 -> 0.2.6)

Dashing Slam fix

---

nav2_controller/include/nav2_controller/nav2_controller.hpp
nav2_controller/src/nav2_controller.cpp
nav2_planner/include/nav2_planner/planner_server.hpp
nav2_planner/src/planner_server.cpp
nav2_system_tests/src/planning/planner_tester.cpp
nav2_system_tests/src/planning/planner_tester.hpp
nav2_util/include/nav2_util/lifecycle_node.hpp
nav2_util/include/nav2_util/node_thread.hpp
nav2_util/src/CMakeLists.txt
nav2_util/src/lifecycle_node.cpp
nav2_util/src/node_thread.cpp

This PR consolidates the thread and executor pattern that is being used to spin nested nodes in an executor inside a thread. A `NodeThread` object can now be initialized to create the thread and the lambda which spins a passed in node on an executor. Also, the object will take care of canceling the spin and joining the thread so the user doesn't have to manage the thread when the user class is destroyed.

Add node thread object to nav2_util and replace nested node threads

---

nav2_system_tests/src/system/CMakeLists.txt
nav2_system_tests/worlds/turtlebot3_ros2_demo.world
nav2_system_tests/worlds/turtlebot3_ros2_demo_obstacle.world
tools/run_test_suite.bash

---
| Ticket(s) this addresses   | #1253 |
---
Addressing #1253. Here's a [video](https://youtu.be/FcJejE2xqd0) showing the robot successfully navigating on an alternate path.
---
Even when the scenario is straight-forward, the test still fails occasionally. We need to improve the default recovery behavior.

Add arbitrary obstacle in CI map that isn't in static map

---

nav2_bringup/bringup/README.md

---
---
Adding instructions (for advanced users) for launching the simulation stack on a single terminal, including the multi-robot example.

Adding single-terminal launch instructions

---

nav2_behavior_tree/CMakeLists.txt
nav2_behavior_tree/include/nav2_behavior_tree/back_up_action.hpp
nav2_behavior_tree/include/nav2_behavior_tree/behavior_tree_engine.hpp
nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
nav2_behavior_tree/include/nav2_behavior_tree/bt_conversions.hpp
nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp
nav2_behavior_tree/include/nav2_behavior_tree/clear_costmap_service.hpp
nav2_behavior_tree/include/nav2_behavior_tree/compute_path_to_pose_action.hpp
nav2_behavior_tree/include/nav2_behavior_tree/follow_path_action.hpp
nav2_behavior_tree/include/nav2_behavior_tree/goal_reached_condition.hpp
nav2_behavior_tree/include/nav2_behavior_tree/is_stuck_condition.hpp
nav2_behavior_tree/include/nav2_behavior_tree/navigate_to_pose_action.hpp
nav2_behavior_tree/include/nav2_behavior_tree/rate_controller_node.hpp
nav2_behavior_tree/include/nav2_behavior_tree/recovery_node.hpp
nav2_behavior_tree/include/nav2_behavior_tree/reinitialize_global_localization_service.hpp
nav2_behavior_tree/include/nav2_behavior_tree/spin_action.hpp
nav2_behavior_tree/include/nav2_behavior_tree/wait_action.hpp
nav2_behavior_tree/package.xml
nav2_behavior_tree/src/behavior_tree_engine.cpp
nav2_behavior_tree/src/recovery_node.cpp
nav2_bt_navigator/CMakeLists.txt
nav2_bt_navigator/behavior_trees/navigate_w_replanning.xml
nav2_bt_navigator/behavior_trees/navigate_w_replanning_and_recovery.xml
nav2_bt_navigator/include/nav2_bt_navigator/bt_navigator.hpp
nav2_bt_navigator/package.xml
nav2_bt_navigator/src/bt_navigator.cpp
tools/ros2_dependencies.repos

---
| Ticket(s) this addresses   | #958 |
| Robotic platform tested on |  System Test |
---
* Switched to version 3 of the behavior tree library.
* Major changes include:
* Parameters in the XML are now ports. The classes now use the new port interface for that data.
* Tree nodes are provided a configuration that includes the ports instead of being passed parameters.
* TreeNodes no longer have an onInit method. Initialization happens in the constructor instead.
* The blackboard is accessed through the config method instead of the blackboard method

Migrate to Behavior Tree V3.

---

nav2_system_tests/src/system/test_multi_robot_launch.py
nav2_system_tests/src/system/test_system_launch.py

---
| Ticket(s) this addresses   | #1283 |
---
Path to the BT xml description file was not provided correctly to the tests. Fixes #1283.

Fix BT xml paths on tests

---

tools/ros2_dependencies.repos

---
* Switch the build to use the latest version of the behavior tree library instead of the 3.0.9 tag.

Switch behavior tree to dev branch instead of 3.0.9 tag.

---

Dockerfile

| Ticket(s) this addresses   | #1281 |
---
* Testing to see if passing console output through prevents travis timeout failure

Cause build output to be sent to screen to prevent Travis timeouts.

---

nav2_system_tests/src/localization/test_localization_node.cpp

| Robotic platform tested on | gazebo simulation of turtlebot |
---
This changes the localization system test to use transient_local + reliable QOS settings for subscribing to the amcl_pose topic. It also slows down the re-try rate from 100ms to 1s.
With this change the test passes 300/300 times. Previously it has been passing at about 85%

Change localization test QOS settings to transient local + reliable

---

nav2_costmap_2d/include/nav2_costmap_2d/costmap_layer.hpp
nav2_costmap_2d/src/costmap_layer.cpp

#1290 
This PR gives control to costmap_2d plugins to clear sections of its own area. This also helps by letting a plugin override this method if it also needs to clear out sections of its own internal data structure separate of the costmap_2d projected costmap.
Nothing uses this right now but it is necessary as more things are ported to ROS2

add clear area method for plugins

---

nav2_behavior_tree/include/nav2_behavior_tree/back_up_action.hpp
nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
nav2_behavior_tree/include/nav2_behavior_tree/bt_conversions.hpp
nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp
nav2_behavior_tree/include/nav2_behavior_tree/compute_path_to_pose_action.hpp
nav2_behavior_tree/include/nav2_behavior_tree/follow_path_action.hpp
nav2_behavior_tree/include/nav2_behavior_tree/navigate_to_pose_action.hpp
nav2_behavior_tree/include/nav2_behavior_tree/spin_action.hpp
nav2_behavior_tree/include/nav2_behavior_tree/wait_action.hpp
nav2_bt_navigator/src/bt_navigator.cpp

---
| Ticket(s) this addresses   | (#1248 ) |
| Robotic platform tested on | (Yunji Robot) |
---
* Add a parameter to control the timeout of every specific action/service
``` <ClearEntireCostmap service_name="/local_costmap/clear_entirely_local_costmap" server_timeout="200"/> ```
* Add  a warning  stating that the service timed out 
---
* There might be another elegant way to fix this problem, cz' clear a 10000x10000pix costmap  may take a while.

Service timeout

---

nav2_bringup/bringup/launch/nav2_tb3_simulation_launch.py

---
| Ticket(s) this addresses   | #1272 |
---
Updating simulation launch files to launch RVIZ as a node instead of using `ExecuteProcess`.

Launch RVIZ using launch_ros::Actions::Node

---

tools/ros2_dependencies.repos

There is no "stable" branch the behavior tree repo. We just need to track the latest tag instead.
The branch we were tracking was deleted, so this fix is needed to get CI working again.
We need to update to 3.1.0 before making our Eloquent release, however, 3.1.0 doesn't build successfully yet, so I'm tracking 3.0.9 instead.

Track Behavior Tree 3.0.9 release tag instead of ros2-dev branch.

---

nav2_behavior_tree/include/nav2_behavior_tree/behavior_tree_engine.hpp
nav2_behavior_tree/src/behavior_tree_engine.cpp

| Primary OS tested on | Ubuntu 18 |
| Robotic platform tested on | TB3 in simulation |
---
* removing an unused variant of the `run` method from the behavior tree engine class

Remove dead code from behavior tree engine

---

nav2_dwb_controller/dwb_core/src/dwb_local_planner.cpp
nav2_dwb_controller/dwb_critics/src/goal_align.cpp
nav2_dwb_controller/dwb_critics/src/oscillation.cpp
nav2_dwb_controller/dwb_critics/src/path_align.cpp
nav2_dwb_controller/dwb_critics/src/rotate_to_goal.cpp
nav2_dwb_controller/nav_2d_utils/include/nav_2d_utils/parameters.hpp

Fixes issue with some dwb critic parameters not being declared.
| Ticket(s) this addresses   | #1154 |
---
- updates `searchAndGetParam` utility function to declare parameters if not declared
- adds parameter namespace where relevant for critics
- the `searchAndGetParam` has largely lost its original meaning, so we should consider to remove function entirely or rename

declare parameters inside searchAndGetParam

---

nav2_bt_navigator/src/bt_navigator.cpp
nav2_lifecycle_manager/src/lifecycle_manager.cpp
nav2_system_tests/src/system/tester_node.py

---
| Ticket(s) this addresses   | #1168 and #1274 |
---
Cleanining system tests shutdown (#1168 and #1274):
* Request navigation through the action interface (instead of topic).
* Shutdown nav-stack once test has been completed.
* Have lifecycle manager reset managed noded in the correct order.
* Add comment about race condition on action server during shutdown
* Listener should be reset before the buffer.
---
* Need to re-enable topic-based nav request.

Clean shutdown of system tests

---

nav2_behavior_tree/include/nav2_behavior_tree/behavior_tree_engine.hpp
nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
nav2_behavior_tree/include/nav2_behavior_tree/bt_conversions.hpp
nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp
nav2_behavior_tree/include/nav2_behavior_tree/goal_reached_condition.hpp
nav2_behavior_tree/include/nav2_behavior_tree/initial_pose_received_condition.hpp
nav2_behavior_tree/include/nav2_behavior_tree/is_stuck_condition.hpp
nav2_behavior_tree/include/nav2_behavior_tree/rate_controller.hpp
nav2_behavior_tree/include/nav2_behavior_tree/recovery_node.hpp
nav2_behavior_tree/plugins/back_up_action.cpp
nav2_behavior_tree/plugins/clear_costmap_service.cpp
nav2_behavior_tree/plugins/compute_path_to_pose_action.cpp
nav2_behavior_tree/plugins/follow_path_action.cpp
nav2_behavior_tree/plugins/goal_reached_condition.cpp
nav2_behavior_tree/plugins/initial_pose_received_condition.cpp
nav2_behavior_tree/plugins/is_stuck_condition.cpp
nav2_behavior_tree/plugins/rate_controller.cpp
nav2_behavior_tree/plugins/recovery_node.cpp
nav2_behavior_tree/plugins/reinitialize_global_localization_service.cpp
nav2_behavior_tree/plugins/spin_action.cpp
nav2_behavior_tree/plugins/wait_action.cpp
nav2_behavior_tree/src/behavior_tree_engine.cpp
tools/ros2_dependencies.repos

Behavior Trees Library in C++ has now updated their include directory files from behaviortree_cpp to behaviortree_cpp_v3 in their latest commit in [ros2_devel branch](https://github.com/BehaviorTree/BehaviorTree.CPP/tree/ros2-devel). I went ahead and updated the includes in navigation2 header files to reflect this change.

updated header files with v3

---

nav2_bringup/bringup/launch/nav2_tb3_simulation_launch.py

This PR is for #827 
- Execute gzclient and gzserver independently in nav2_tb3_simulation_launch.py
- Check an argument named `headless` when executing `gzclient`.
- The default value for `headless` is False.
- `ros2 launch nav2_bringup nav2_tb3_simulation_launch.py headless:=True` brings up `RViz` and execute `gzserver` only.

Execute gzclient and gzserver independently and use the argument 'headless'

---

nav2_dwb_controller/dwb_plugins/test/CMakeLists.txt
nav2_dwb_controller/dwb_plugins/test/goal_checker.cpp
nav2_dwb_controller/dwb_plugins/test/twist_gen.cpp

Fixes and re-enables `twist_gen_test` and `goal_checker` test in dwb_plugins package.
| Ticket(s) this addresses   | #789  |

Re-enable dwb_plugin tests

---

nav2_navfn_planner/src/navfn.cpp
nav2_navfn_planner/src/navfn_planner.cpp

---
| Ticket(s) this addresses   | #573 |
---
* Fixed the bug where navfn planner was backtracking the path twice.
* Before the fix the whole operation was like
1. set `goal` and `start` pose.
2. call `calcNavFnAstar()`/`calcNavFnDijkstra`
a. call `propNavFnAstar`/`propNavFnDijkstra`
b. call `calcPath()`
3. Find new `goal` point around the old `goal` which has low potential and is not far from old `goal` point.
4. call `calcPath()` with new `goal` point.
* After the fix, its like
1. set `goal` and `start` pose.
2. call `calcNavFnAstar()`/`calcNavFnDijkstra`
a. call `propNavFnAstar`/`propNavFnDijkstra`
3. Find new `goal` point around the old `goal` …

Fix twice backtracking of path by navfn planner.

---

nav2_behavior_tree/plugins/decorator/rate_controller.cpp

Once the child node begins to run, it should continue to run until completion.

Fix rate controller issue

---

nav2_amcl/include/nav2_amcl/amcl_node.hpp
nav2_amcl/src/amcl_node.cpp

This is primarily a direct port of the callback (though refactored) for the ROS1 navigation `reconfiugreCB`. 
| Ticket(s) this addresses   | #956 |
| Robotic platform tested on | tb3 waffle simulation |

Bringing back dynamic parameters: Amcl

---

nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp
nav2_behavior_tree/plugins/action/follow_path_action.cpp

Reverts ros-planning/navigation2#1384
This seems to be causing the tests to fail as seen here.
https://circleci.com/gh/ros-planning/navigation2/6500?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
Backing this out till we can figure out what's going on.

Revert "Fix BT action client implementation"

---

nav2_bringup/bringup/launch/nav2_multi_tb3_simulation_launch.py
nav2_bringup/bringup/launch/nav2_tb3_simulation_launch.py

---
| Ticket(s) this addresses   | #1410 |
---
Fixes #1410, the problem is here:
https://github.com/ros-planning/navigation2/blob/c2d93596084968376ccb3d6213621f1cf59fe7b5/nav2_bringup/bringup/launch/nav2_tb3_simulation_launch.py#L138-L141
Where the `and` operation over two conditions is not well defined.

Fix launching multiple gzclient instances

---

sphinx_doc/Makefile

* This fixes the doc_publish step in CI. It is currently failing if there are no updates to publish. The failure is harmless, but gives us another red X in CI.
* This PR makes the docs_publish step check whether there are actual changes before making the commit. if none, then it just returns.

Fix docs_publish error if nothing to commit.

---

nav2_util/include/nav2_util/parameter_events_subscriber.hpp

* Linter failure was introduced on the eloquent branch. This PR fixes it.

Fixing linter failure in nav2_util on eloquent branch

---

full_ros_build.Dockerfile
nav2_system_tests/package.xml
release_branch.Dockerfile

* We need to update the docker builds that are used to test the release branch. They don't have up-to-date rosdep information in them, resulting in a failure to install the behavior tree package. I added a call to rosdep update into the build sequence, and that fixes the problem.
* The test found a missing dependency in the nav2_system_tests package. I've added that dependency as well.
This will need to be merged to eloquent in order to release.

Dependency test related fixes needed for eloquent release.

---

nav2_bt_navigator/src/bt_navigator.cpp
nav2_controller/src/nav2_controller.cpp
nav2_planner/src/planner_server.cpp
nav2_recoveries/include/nav2_recoveries/recovery.hpp
nav2_util/include/nav2_util/simple_action_server.hpp
nav2_util/test/test_actions.cpp

---
| Ticket(s) this addresses   | #861 |
---
Addressing #861 and partially #1344.
Improvements:
- Simplify usage by removing the need to terminate goals if the action was not successfully completed.
- Handle action server deactivation while the action is still running.
- Handle race condition between completing an action and receiving a preemption.
Improvements were mainly implemented by wrapping the action execution callback around a method that will terminate the goals if needed and re-run the callback if there are any pending handles. This addresses #861, i.e. if there is a pending preemption in DWB after returning from the …

Improvements to (Simple) Action Server

---

nav2_costmap_2d/include/nav2_costmap_2d/inflation_layer.hpp
nav2_costmap_2d/plugins/obstacle_layer.cpp
nav2_costmap_2d/plugins/static_layer.cpp
nav2_costmap_2d/plugins/voxel_layer.cpp
nav2_costmap_2d/src/costmap_2d_ros.cpp
nav2_costmap_2d/test/integration/obstacle_tests.cpp

The `nav2_system_tests` were failing in large part due to the parameter callbacks being called erroneously during the `on_cleanup` of the `Costmap2DROS` object. It is a pattern that the `reset` of costmap plugins will reset/deactivate and also re-initialize. In this PR I'm maintaining that behavior since I believe that is intended for use when clearing the costmap during run-time, but here I'm  removing the `resetLayers` inside of `on_cleanup`, especially since deleting the `layered_costmap` will destroy the plugins anyway. Also, since the parameters are being `declare_if_not_declared`, there's no real need to undeclare the parameters when resetting. 
- cleanup plugin activate/deactivate/reset logic in alignment with lifecycle transitions

Fix costmap on_cleanup issues [eloquent-devel] 

---

nav2_util/include/nav2_util/simple_action_server.hpp

If the action server is deactivated before it has accepted its first action goal request, then the future does not have a state associated with it since it was never initialized with the async thread. In this PR, I'm checking that the future is valid in the `deactivate` call with the assumption that there has yet to be a goal request accepted. 
| Ticket(s) this addresses   | #1429  |

Check if future is valid in action server deactivate

---

nav2_controller/src/nav2_controller.cpp
nav2_planner/src/planner_server.cpp

This PR fixes bugs in the `controller_server` and `planner_server` where upon a reset/startup of the stack, the plugins are not being reassigned into the map since the keys still exist on the map. I think it makes better sense to clear all the plugins in the map when cleaning up. After this PR and #1430, the stack should be able to successfully reset and startup.

Clear controller and planner map on_cleanup

---

sphinx_doc/howtos/tunning/params/tunable-params.rst

---
---
Minor typo fix in `/sphinx_doc/howtos/tunning/params/tunable-params.rst`.

Fix minor typo in tunable-params.rst

---

nav2_common/nav2_common/launch/rewritten_yaml.py

A default value of None is not given to __root_key in the RewrittenYaml class and will cause it to throw an exception if root_key is None. This PR initializes __root_key with None to avoid this exception.

initialized member variable root_key with default value

---

sphinx_doc/howtos/tutorials/docs/navigation2_on_real_turtlebot3.rst
sphinx_doc/howtos/tutorials/docs/navigation2_with_stvl.rst
sphinx_doc/howtos/tutorials/index.rst

Adding documentation about how to switch out costmap 2d plugins, with the example being the newly ported STVL https://github.com/SteveMacenski/spatio_temporal_voxel_layer available in Dashing and Eloquent.
The goal of this is to A) give some explanation in general about how to use plugins, B) highlight STVL as an option in Navigation2 and ROS2, C) learn rst.
I followed rst examples in the repo and I found online, so let me know if you find issues. The youtube link is wrong (its the real-robot video you have) but will be updated soon as I can get youtube to upload..

adding STVL documentation

---

nav2_controller/CMakeLists.txt
nav2_dwb_controller/dwb_plugins/CMakeLists.txt
nav2_navfn_planner/CMakeLists.txt
nav2_planner/CMakeLists.txt
nav2_recoveries/CMakeLists.txt

They aren't needed in ROS2 and cause the official build to break.
See http://build.ros2.org/job/Ebin_uB64__nav2_recoveries__ubuntu_bionic_amd64__binary/1/console for an example of the failure.

Disable boost includes in packages that use pluginlib

---

nav2_rviz_plugins/include/nav2_rviz_plugins/nav2_panel.hpp
nav2_rviz_plugins/src/nav2_panel.cpp

Using arrows instead of circles to shows the user robot's target pose (location and orientation)
This PR is a result of the conversation that I had with @yathartha3 a few weeks ago about how to use way point markers in a more efficient way.
PS: I guess I should have opened an issue about this first :)

Use arrow markers for waypoints instead of circles

---

nav2_bringup/bringup/worlds/waffle.model
nav2_system_tests/models/turtlebot3_waffle/model-1_4.sdf
nav2_system_tests/models/turtlebot3_waffle/model.sdf
nav2_system_tests/models/turtlebot3_waffle_depth_camera/model.sdf
nav2_system_tests/worlds/turtlebot3_ros2_demo.world
nav2_system_tests/worlds/turtlebot3_ros2_demo_obstacle.world

Signed-off-by: Mikael Arguedas <mikael.arguedas@gmail.com>
---
| Ticket(s) this addresses   | None? |
| Robotic platform tested on | None, used simulated tb3 to test the implementation of the tag itself https://github.com/ros-simulation/gazebo_ros_pkgs/issues/991#issuecomment-544895833 |
---
- This change is not valid for dashing and older.
- This is the result of a simple search/replace for all argument tags with the new `remapping` tag in SDF.
- Apologies for unrelated whitespace changes
I sanity checked the diff but haven't use this on actual hardware, assuming that the CI here will run all the tests on this change. 
Ran tests locally but had failures, they didn't seem related to this …

[eloquent] use remapping tag in urdf/sdf

---

sphinx_doc/howtos/tutorials/docs/navigation2_with_stvl.rst

---
| Ticket(s) this addresses   | fixes #1452  |
---
* Fixes displaying the STVL video in the docs.
*Change stvl video link to embed type instead of watch.
*You can get the youtube embed html by clicking the `share` button under the video and choosing the embed option.

Change stvl video link to embed type instead of watch.

---

nav2_common/nav2_common/launch/rewritten_yaml.py

This backports #1444 to the `eloquent-devel` branch. I skipped the PR template since it's a trivial change.

[eloquent backport] initialized member variable root_key with default value (#1444)

---

sphinx_doc/getting_started/index.rst

The documentation was incorrect - the launch file to use is `nav2_simulation_launch.py` for the dashing release
We still need to update for Eloquent

Fix getting started instructions

---

nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager.hpp
nav2_lifecycle_manager/src/lifecycle_manager.cpp

Signed-off-by: Francisco Martin Rico <fmrico@gmail.com>
---
| Ticket(s) this addresses   | #1345 |
---
* I removed the need to pass a flag for performing the transition of nodes in reverse or normal order. As @orduno said in #1345, this was prone to errors.
* My PR removes the flag. The transition itself defines the order.
* I tested on gazebo with tb3. Nodes are activated in order and deactivated in reverse order when pausing.
---

Order of activate/deactivate nodes in lifecycle manager

---

nav2_bringup/bringup/launch/nav2_bringup_launch.py

Fixes #1470 
Simply set the default value to an empty string as discussed in #1470.
Tested on simulation. Map loads and the robot is able to navigate.

fix map loading

---

README.md

Updated readme file.
@ruffsl I noticed on DockerHub the docker file it says its using is (https://hub.docker.com/r/rosplanning/navigation2/dockerfile) the dummy file, though I see from the `.dockerhub` I believe it shows it using the `Dockerfile` which is the "real" one. Can you confirm for me what its actually using and can we get rid of the dummy file?

made table for badges and added doxy info

---

README.md

Per https://github.com/ros-planning/navigation2/issues/1499, DockerHub is incorrectly reporting a failing status when it is building fine.
I've seen this problem in 5 projects and there's tickets filed with DockerHub that are being ignored widely. As a result, I'm going to replace the badge with something that's actually accurate, the pull pointer

Changing dockerhub from status to pull counter

---

sphinx_doc/how_it_works/index.rst
sphinx_doc/index.rst

its empty and not likely to be filled in anytime in the medium term future

[website sprint] remove the "how it works" tab from documentation

---

.circleci/config.yml

As support for OpenSplice has been discontinued from ROS Foxy onwards.
https://github.com/ros2/rmw_implementation/pull/79

Remove OpenSplice test jobs

---

nav2_behavior_tree/include/nav2_behavior_tree/behavior_tree_engine.hpp
nav2_behavior_tree/src/behavior_tree_engine.cpp
nav2_bt_navigator/include/nav2_bt_navigator/bt_navigator.hpp
nav2_bt_navigator/src/bt_navigator.cpp

This is https://github.com/ros-planning/navigation2/pull/1322 targeting head of master. 
Like that ticket says, 
> Rather than trying to re-use the behavior tree, create the behavior tree each time NavigateToPose is called. This avoids some problems in the BT library when using CoroActionNodes (coroutines).
should fix 
https://github.com/ros-planning/navigation2/issues/1285
and
https://github.com/ros-planning/navigation2/issues/1439
Recreation of the tree is taking 200-300ms in my test environment. This delay directly adds to the time it takes the nav stack to receive to a NavigateToPose request.
Future work can be done to reduce this time.
Tested with rviz start/stop commands in simulation and a script with some start/stop commands.

cherry-picking mjeronimo:fix_bt_crash_after_reset

---

nav2_bringup/bringup/params/nav2_multirobot_params_1.yaml
nav2_bringup/bringup/params/nav2_multirobot_params_2.yaml
nav2_bringup/bringup/params/nav2_params.yaml
nav2_core/include/nav2_core/goal_checker.hpp
nav2_dwb_controller/dwb_core/CMakeLists.txt
nav2_dwb_controller/dwb_core/include/dwb_core/dwb_local_planner.hpp
nav2_dwb_controller/dwb_core/include/dwb_core/publisher.hpp
nav2_dwb_controller/dwb_core/include/dwb_core/trajectory_generator.hpp
nav2_dwb_controller/dwb_core/include/dwb_core/trajectory_utils.hpp
nav2_dwb_controller/dwb_core/src/dwb_local_planner.cpp
nav2_dwb_controller/dwb_core/src/publisher.cpp
nav2_dwb_controller/dwb_core/src/trajectory_utils.cpp
nav2_dwb_controller/dwb_critics/include/dwb_critics/rotate_to_goal.hpp
nav2_dwb_controller/dwb_critics/src/rotate_to_goal.cpp
nav2_dwb_controller/dwb_msgs/msg/Trajectory2D.msg
nav2_dwb_controller/dwb_plugins/include/dwb_plugins/one_d_velocity_iterator.hpp
nav2_dwb_controller/dwb_plugins/include/dwb_plugins/simple_goal_checker.hpp
nav2_dwb_controller/dwb_plugins/include/dwb_plugins/standard_traj_generator.hpp
nav2_dwb_controller/dwb_plugins/src/kinematic_parameters.cpp
nav2_dwb_controller/dwb_plugins/src/limited_accel_generator.cpp
nav2_dwb_controller/dwb_plugins/src/simple_goal_checker.cpp
nav2_dwb_controller/dwb_plugins/src/standard_traj_generator.cpp
nav2_dwb_controller/dwb_plugins/test/goal_checker.cpp
nav2_dwb_controller/dwb_plugins/test/twist_gen.cpp
sphinx_doc/configuration/configuring-the-controller.rst
sphinx_doc/configuration/dwb-plugins/trajectory-critics.rst
sphinx_doc/configuration/params/tunable-params.rst

---
| Ticket(s) this addresses   | #229 |
| Robotic platform tested on | Turtlebot3 |
---
* Ported most of the changes from the robot_navigation repo.
---
* I haven't ported some changes which includes [input_params](https://github.com/locusrobotics/robot_navigation/pull/15/files#diff-a7386ed917198fe34cc4d7dd79b44d1a) and some minor changes.
* I am planning to complete this work shortly.
* Need to know if anyone wants me to port [input_params](https://github.com/locusrobotics/robot_navigation/pull/15/files#diff-a7386ed917198fe34cc4d7dd79b44d1a) which I think is redundant. But it is just my thoughts.

Update dwb_controller as per robot_navigation stack.

---

nav2_bt_navigator/src/bt_navigator.cpp
nav2_lifecycle_manager/src/lifecycle_manager_client.cpp
nav2_rviz_plugins/src/nav2_panel.cpp
nav2_system_tests/src/system/tester_node.py
nav2_waypoint_follower/src/waypoint_follower.cpp

---
| Ticket(s) this addresses   | follow-up after https://github.com/ros-planning/navigation2/pull/1467 |
| Primary OS tested on | - |
**Note**: it took me a while to get this one up due to lack of time and because I repeatedly attempted and failed to run `nav2_system_tests` locally. I presume I'm not configuring my environment properly, but I didn't want to further delay this.
---
* Normalize action names to be snake cased.
---
* I think the `navigate_to_pose` action isn't the only one that may require snake casing (e.g. see the [`FollowWaypoints` action](https://github.com/ros-planning/navigation2/blob/3c736f87dfcbba029e92f2f40de332073aba742a/nav2_waypoint_follower/src/waypoint_follower.cp …

Normalize navigate_to_pose action names to be snake cased.

---

nav2_map_server/src/map_server.cpp
nav2_util/include/nav2_util/lifecycle_node.hpp
nav2_util/src/lifecycle_node.cpp

| Ticket(s) this addresses   | fixes #1240 |
---
* Adds a warning to end of each lifecycle node constructor informing the user that they've launched a lifecycle need and need to take addtional action
* This is mainly meant as a warning to users who directly run a node using `ros2 run` and aren't aware that additional steps are needed to get the node fully active.
Thoughts on this approach? If that seems reasonable, I'll go ahead and change the other nodes as well.

Add warning to lifecycle node constructor, so people know they've launched a lifecyle node

---

nav2_bringup/bringup/worlds/waffle.model

---
| Ticket(s) this addresses   | #1521  |
| Robotic platform tested on | TB3 waffle simulation |
---
* Shifted collision of RGBD model to prevent collisions with the laser scan.

Collision fix for 'flickering' laser scan.

---

nav2_controller/include/nav2_controller/progress_checker.hpp
nav2_controller/src/nav2_controller.cpp
nav2_controller/src/progress_checker.cpp

| Ticket(s) this addresses   | fixes https://answers.ros.org/question/344004/configuring-the-progress-checker-in-navigation2/ |
| Robotic platform tested on | TB3 on Gazebo |
---
* Progress checker parameters were not declared.
* Progress checker parameters were on the wrong node (the controller_server_rclcpp_node)
* This PR fixes that.
* Make the parameters dynamic. Right now they are only read once during the configure lifecycle transition

Declare progress checker parameters

---

nav2_dwb_controller/nav_2d_utils/include/nav_2d_utils/odom_subscriber.hpp
nav2_util/include/nav2_util/lifecycle_node.hpp

---
| Ticket(s) this addresses   | #1409 |
---
* Adding proposed lifecycle shared from this implementation.
---
* Perhaps rethink the use of a lifecycle node wrapper **once** we are able to remove effectively the client nodes. For now its required, and as @bpwilcox brings up, it may be beneficial for some users.

adding lifecycle shared from this to lifecycle utils

---

nav2_system_tests/src/waypoint_follower/tester.py

On the path to fixing nightly woes
This stops the crashing for all nightly builds, but doesn't yet solve the issue of them not exiting after destruction, which is interesting. 
See here (https://8834-135363400-gh.circle-artifacts.com/0/opt/overlay_ws/log/test/nav2_system_tests/stdout.log) and search for `***Timeout` . You'll see they all pass and appear to shutdown cleanly, yet fail to actually return to exit the test

wrap spins for waypoint follower in try / except

---

sphinx_doc/conf.py

---
| Ticket(s) this addresses   | #1421  |
---
* Its a little involved to update the timestamp, and its not that important. I'm removing it so that we don't burn maintainers time on a superficial accessory. 
---
@crdelsey can you give your thoughts on this one? I won't just charge it in since I know its something that people may disagree with. Its definitely the "easy way out" but hour-for-hour with limited bandwidth, it seems silly to spend any time on this.

removing last time updated from readthedocs

---

nav2_costmap_2d/src/footprint_subscriber.cpp

---
| Primary OS tested on | (Ubuntu Bionic) |
| Robotic platform tested on | (gazebo simulation of turtlebot waffle) |
---
* uses `Duration::from_seconds()` to avoid the footprint timeout (given as a `double`) being truncated to an integer
---
* This change could be safely backported to `eloquent`

FootprintSubscriber use from_seconds() to avoid integer truncation

---

nav2_costmap_2d/src/footprint_subscriber.cpp

Backports #1560 to the `eloquent-devel` branch. This PR is a cherry-pick of 547f7bc.

[eloquent] Backport #1560 Use from_seconds() to avoid integer truncation

---

.github/PULL_REQUEST_TEMPLATE.md

I've spent a bunch of time (and will continue to) on improving the documentation and compiling resources.
I do not want this work to go in vein because documentation isn't kept up with changes. This acts as a reminder in case folks forget when they make changes to add them to documentation

Updating PR template to force people to reference necessary documentation changes

---

nav2_bringup/bringup/params/nav2_multirobot_params_1.yaml
nav2_bringup/bringup/params/nav2_multirobot_params_2.yaml
nav2_bringup/bringup/params/nav2_params.yaml
nav2_dwb_controller/dwb_critics/src/rotate_to_goal.cpp

this fixes issue: https://github.com/ros-planning/navigation2/issues/1567
I changed these two params because they are shared with other parts of the system
`xy_goal_tolerance` is used by the `rotate_to_goal` critic and the `simple_goal_checker`
`trans_stopped_velocity` is used by the `rotate_to_goal` critic and the  `stopped_goal_checker` (I do not use this and did now know what it was before this PR). 
The other two params, `slowing_factor` and `lookahead_time`, are exclusive to the `rotate_to_goal` critic, so I kept their names in that critics namespace (I don't use them and don't know what they do).  I updated the default param file in this repo to the correct names for these params.
I reordered some params in the yaml file so that only critic params are declared after the critics are …

RotateToGoal param name fixes

---

nav2_util/include/nav2_util/simple_action_server.hpp

[eloquent-backport] only let a new goal in after the currently running goal's thread has finished (#1520)

---

nav2_system_tests/src/system/tester_node.py
nav2_system_tests/src/waypoint_follower/tester.py

I suspect this is causing the issues:
```
[453.043s] 10: [tester_node-13] [ERROR] [1583454435.358193353] [nav2_tester]: [1;37;41mService call failed RuntimeError('Failed to take status with an action client: error not set',)[0m
[344.359s] 13: [tester_node-13] [ERROR] [1583454326.674545839] [nav2_waypoint_tester]: [1;37;41mService call failed RuntimeError('Failed to take feedback with an action client: error not set',)[0m
```
which may be leaving a server up causing the lack of exiting. This is not seen in Fast-RTPS, which is the only RMW which regularly passes the nightly builds.

Adding destroy call to rclpy action client in system tests 

---

nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp
nav2_behavior_tree/plugins/action/follow_path_action.cpp

---
| Ticket(s) this addresses   | #1289 |
| Robotic platform tested on | gazebo simulation of TB3 |
---
* Clears up unnecessary networking traffic in constantly timing out a request
* Handle the preemption of the controller server abort rather than throwing away results
@crdelsey I'd appreciate a review on this one since its a big behavioral change. I found the issue in the last time I tried to do this.
Turns out the controller server will return a preempt (which translates to failure in the BT action node) which the `goto` actually completely throws out and is missed. My synchronous callback method didn't throw it out because it triggers on a result. So I added a check if it was preempted, …

fixing BT node action processors

---

nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp

The removed code has no effect at all: the status of a node will be its returned value!
In general, you never set your status to IDLE, unless halted.

setStatus(BT::NodeStatus::IDLE) removed

---

sphinx_doc/build_instructions/index.rst
sphinx_doc/getting_started/index.rst
sphinx_doc/substitutions.txt
sphinx_doc/tutorials/docs/navigation2_on_real_turtlebot3.rst
sphinx_doc/tutorials/docs/navigation2_with_slam.rst
sphinx_doc/tutorials/docs/navigation2_with_stvl.rst

Updating docs to reference only the abstract `<ros2-distro>` in install and setup guides to reduce burden on maintainers to keep updating. At this point, we don't expect any major changes to happen in the future to require too much additional versioning

making documentation distro agnostic

---

nav2_navfn_planner/src/navfn_planner.cpp

---
| Ticket(s) this addresses   | #1608 |
| Robotic platform tested on | ( gazebo simulation of Turtlebot) |

Issue 1608 segmentation fault planner server node master

---

nav2_behavior_tree/include/nav2_behavior_tree/behavior_tree_engine.hpp
nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp
nav2_behavior_tree/plugins/action/compute_path_to_pose_action.cpp
nav2_bt_navigator/include/nav2_bt_navigator/bt_navigator.hpp
nav2_bt_navigator/src/bt_navigator.cpp

I haven't been able to test these changes yet, even if I am 90% confident that they should work and fix issues #1600 and #1439
I compiled on Eloquent, Ubuntu 18.04. 
I wanted to test it using [these instructions](https://ros-planning.github.io/navigation2/getting_started/index.html), but the turtlebot3 packages haven't been released in Eloquent.
I am really sorry to ask, normally I wouldn't, but... is there anyone that can try these changes?
@SteveMacenski and @Jconn ? Sorry for asking, I really wanted to do this myself, but I am hitting a wall.

BehaviorTree refactoring

---

nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp

| Ticket(s) this addresses   | #1614 |
---
- `BtServiceNode::check_future()` was created, to encapsulate the logic
where a the output of the BtServiceNode is computed.
- Inherited classes can overload this function according to the requirement
of the user

Decide the output of BtServiceNode based on the service-response

---

nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
nav2_behavior_tree/plugins/action/compute_path_to_pose_action.cpp
nav2_behavior_tree/plugins/action/follow_path_action.cpp

| Ticket(s) this addresses   | #1613  |
---
- A `BT::InputPort` `server_name` is introduced in case the user wants to change the default action_name
of `BtActionNode`.
- A similar implementation (which was dysfunctional) was removed from `ComputePathToPose` and `FollowPath` BT actions

Add server_name parameter to BtActionNode

---

nav2_dwb_controller/dwb_plugins/include/dwb_plugins/kinematic_parameters.hpp
nav2_dwb_controller/dwb_plugins/include/dwb_plugins/standard_traj_generator.hpp
nav2_dwb_controller/dwb_plugins/include/dwb_plugins/velocity_iterator.hpp
nav2_dwb_controller/dwb_plugins/include/dwb_plugins/xy_theta_iterator.hpp
nav2_dwb_controller/dwb_plugins/src/kinematic_parameters.cpp
nav2_dwb_controller/dwb_plugins/src/standard_traj_generator.cpp
nav2_dwb_controller/dwb_plugins/src/xy_theta_iterator.cpp

Signed-off-by: Aitor Miguel Blanco <aitormibl@gmail.com>
---
| Ticket(s) this addresses   | #1459  |
| Robotic platform tested on | gazebo simulation of Turtlebot3) |
---
* Refactored KinematicParameters class.
* Added KinematicsHandler class managing the kinematic parameters (initialization, parameter update).
* Parameters are now managed dinamically with an atomic pointer, making their access thread safe.
* Deleted unused function declaration ```reconfigureCB```.
* Fixed bug: values of ```min_speed_xy_sq_``` and ```max_speed_xy_sq_``` are now updated when updating the parameters ```min_speed_xy_``` and ```max_speed_xy_``` (before they were only set on initialization).
---

Added thread synchronization to KinematicParameters (#1459)

---

nav2_recoveries/plugins/wait.cpp
nav2_recoveries/plugins/wait.hpp

---
| Ticket(s) this addresses   | #1622 |
---
* Updated onCycleUpdate to check if wait time has passed instead of using a sleep function. This allows stopping the wait action if needed.
---
* Currently only the cancellation is working due to issues with the preemption handling.
This will most likely require bigger changes and will be taken care of in a different pull request.

Allow reaction to cancellation and preemption on wait recovery plugin

---

sphinx_doc/tutorials/docs/writing_new_costmap2d_plugin.rst

---
---
* Add best practice line for pluginlib export macro's location in costmap plugin docs
---

Minor improvement on best practice for pluginlib export

---

sphinx_doc/tutorials/docs/writing_new_costmap2d_plugin.rst
sphinx_doc/tutorials/docs/writing_new_nav2planner_plugin.rst

---
---
* Add caps to headers
* Fix some grammar!
---

Add caps to headers

---

nav2_system_tests/src/planning/planner_tester.hpp

Fix for the `test_planner_random_node` and `test_planner_costmaps_node` flaky tests.
---
| Ticket(s) this addresses   | #1585 |
| Primary OS tested on | Ubuntu 18.04 with ROS2 eloquent onboard |
| Platform tested on | colcon test |
---

Fix segfault in test_planner_random_node/test_planner_costmaps_node

---

nav2_dwb_controller/dwb_plugins/src/stopped_goal_checker.cpp

Signed-off-by: Shrijit Singh <shrijitsingh99@gmail.com>
---
| Ticket(s) this addresses   | (add tickets here #1645) |
| Robotic platform tested on | (gazebo simulation of turtlebot) |
---
Updated trans_stopped_velocity threshold to compare with hypot() of x & y velocity.

Fix trans_stopped_velocity comparison with x & y velocity

---

nav2_controller/src/progress_checker.cpp
nav2_dwb_controller/dwb_core/src/publisher.cpp
nav2_dwb_controller/nav_2d_utils/include/nav_2d_utils/parameters.hpp

Signed-off-by: Pablo Vega <epvega@gmail.com>
---
| Ticket(s) this addresses   |  #1648 |
| Primary OS tested on | (Ubuntu 20.04 |
| Robotic platform tested on |   |
---
* I initialized some uninitialized variables which were causing build errors on master branch for Ubuntu 20.04. As in #758, the values are set by get_parameter and get_parameter_or but the compiler issues warnings , which are treated as errors

Initialize variabes to avoid errors during build

---

nav2_system_tests/CMakeLists.txt

These are by far the most flakey tests. Removing them from running to return CI to some stability.

Temporarily remove planner tests

---

codecov.yml
nav2_util/test/test_string_utils.cpp

Ignoring the codecov results for the test directories. We should be measuring code coverage of production code, not redundant coverage of the tests themselves.

Ignore codecov paths in tests

---

nav2_recoveries/plugins/spin.cpp
nav2_recoveries/plugins/spin.hpp
nav2_system_tests/CMakeLists.txt
nav2_system_tests/src/recoveries/CMakeLists.txt
nav2_system_tests/src/recoveries/README.md
nav2_system_tests/src/recoveries/spin_recovery_tester.cpp
nav2_system_tests/src/recoveries/spin_recovery_tester.hpp
nav2_system_tests/src/recoveries/test_spin_recovery_launch.py
nav2_system_tests/src/recoveries/test_spin_recovery_node.cpp

---
| Ticket(s) this addresses   |  #1655 |
| Robotic platform tested on | gazebo simulation of TurtleBot3 |
---
* Fixes the logic to keep track of relative yaw which allows Spin target yaw to be greater than M_PI/-M_PI
* Calculates velocity commands based on the remaining angle to cover
* Adds tests for Spin Recovery

Fix infinite rotation in Spin recovery when angle > PI

---

nav2_navfn_planner/src/navfn_planner.cpp

Removing dead code from Navfn that is unused.

Remove dead code from navfn planner

---

README.md
codecov.yml

To deal with code cov still picking up:
- https://codecov.io/gh/ros-planning/navigation2/tree/master/nav2_map_server
- https://codecov.io/gh/ros-planning/navigation2/tree/master/nav2_recoveries
- https://codecov.io/gh/ros-planning/navigation2/tree/master/nav2_util/test

Add ignoring code cov any files named test_

---

nav2_costmap_2d/test/integration/inflation_tests.cpp

| Ticket(s) this addresses   | (#1689 ) |
---
* Fixed mentioned issue by replacing object reference with copy.
* Added distance calculation before enqueuing cell since map key should be distance of the cell being enqueued from it source.

Inflation test fix

---

nav2_system_tests/src/planning/planner_tester.cpp
nav2_system_tests/src/planning/planner_tester.hpp

deactivate needs to be called before cleanup to stop the mapUpdateLoop()
Signed-off-by: Siddarth Gore <siddarth.gore@gmail.com>
---
| Ticket(s) this addresses   | #1585  |
| Primary OS tested on | Ubuntu 18.04 (WSL2) |
| Robotic platform tested on | colcon test |
---

Fix segfault in test_planner_random_node

---

nav2_util/include/nav2_util/simple_action_server.hpp
nav2_util/test/CMakeLists.txt
nav2_util/test/test_actions.cpp
nav2_util/test/test_lifecycle_cli_node.cpp
nav2_util/test/test_node_utils.cpp

Filling out no particular ticket.

Adding more simple action server, nav2_utils, and lifecycle bringup CLI tests

---

nav2_amcl/src/amcl_node.cpp
nav2_bt_navigator/src/ros_topic_logger.cpp
nav2_controller/src/nav2_controller.cpp
nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_publisher.hpp
nav2_costmap_2d/include/nav2_costmap_2d/voxel_layer.hpp
nav2_costmap_2d/plugins/voxel_layer.cpp
nav2_costmap_2d/src/costmap_2d_cloud.cpp
nav2_costmap_2d/src/costmap_2d_markers.cpp
nav2_costmap_2d/src/costmap_2d_publisher.cpp
nav2_costmap_2d/src/costmap_2d_ros.cpp
nav2_dwb_controller/dwb_core/src/publisher.cpp
nav2_lifecycle_manager/src/lifecycle_manager_client.cpp
nav2_map_server/include/nav2_map_server/map_server.hpp
nav2_map_server/src/map_server/map_server.cpp
nav2_planner/src/planner_server.cpp
nav2_recoveries/include/nav2_recoveries/recovery.hpp
nav2_recoveries/plugins/back_up.cpp
nav2_recoveries/plugins/back_up.hpp
nav2_recoveries/plugins/spin.cpp
nav2_recoveries/plugins/spin.hpp
nav2_rviz_plugins/src/nav2_panel.cpp
nav2_system_tests/src/dummy_controller/dummy_controller.cpp
nav2_system_tests/src/localization/test_localization_node.cpp

---
| Ticket(s) this addresses   | #1672 |
| Robotic platform tested on | gazebo simulation of TurtleBot3 (Waffle) |
---
- Change all the publishers to publish unique pointers.
- Publishers in navigation2 should publish unique pointers rather than raw messages.
---
- I have tried to cover all ROS publishers in navigation2. I'll make the necessary changes if any required.

Change publishers to publish unique ptrs

---

nav2_rviz_plugins/CMakeLists.txt

with ament_export_targets
See foxy notice here:
https://index.ros.org/doc/ros2/Releases/Release-Foxy-Fitzroy/

Replace deprecated ament_export_interfaces

---

nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp
tools/ros2_dependencies.repos

---
* Remove deprecated rclcpp::executor::FutureReturnCode to rclcpp::FutureReturnCode

Refactor rclcpp::executor::FutureReturnCode deprecation

---

codecov.yml
tools/code_coverage_report.bash

---
| Ticket(s) this addresses   |  #1709 |
---
I am changing some options here to see if it makes any difference to current branch coverage.

[WIP] Checking line coverage in codecov

---

nav2_system_tests/CMakeLists.txt
nav2_system_tests/src/planning/planner_tester.hpp
nav2_system_tests/src/system/test_multi_robot_launch.py

Testing PR for reproduce Issue No.1 from ticket #1585

Fix system_tests flaky issue

---

nav2_bringup/bringup/params/nav2_multirobot_params_1.yaml
nav2_bringup/bringup/params/nav2_multirobot_params_2.yaml
nav2_bringup/bringup/params/nav2_params.yaml
nav2_costmap_2d/plugins/static_layer.cpp
nav2_navfn_planner/src/navfn_planner.cpp

1. Fix minor build error for uninitialized temp_tf_tol in static_layer.cpp.
2. Follow [this ticket](https://github.com/ros-planning/navigation2/issues/1683). Change default GridBased.tolerance from 2.0 to 0.5 meters. People (like me) are used to 0 meter tolerance without knowing there is a new parameter set to 2.0 meters. If we keep using default 2.0 meters, users may wonder why navigation is always successful even the robot is stuck inside a 2x2 meter square area.

Fix uninitialized variable warnings and change default value

---

nav2_costmap_2d/include/nav2_costmap_2d/cost_values.hpp
nav2_costmap_2d/include/nav2_costmap_2d/inflation_layer.hpp
nav2_costmap_2d/include/nav2_costmap_2d/testing_helper.hpp
nav2_costmap_2d/plugins/inflation_layer.cpp
nav2_costmap_2d/src/layered_costmap.cpp
nav2_costmap_2d/test/integration/inflation_tests.cpp

Signed-off-by: Shrijit Singh <shrijitsingh99@gmail.com>
---
| Ticket(s) this addresses   | #1628 |
| Robotic platform tested on | turtlebot simulation |
---
* Added option to inflate unknown space
* Made some small optimizations and changes to make code cleaner
* Added new parameter `inflate_around_unknown`, so need to add that to default configs and documentation page

Add option to inflate unknown space

---

.dockerhub/release/hooks/build

Not sure why connext related cmake from the upstream nightly archive is blocking our builds.
This switches away from the `nightly-rmw-nofree` tag, given connext rmw tests where disabled.
Related:
* https://github.com/ros-planning/navigation2/pull/1742#issuecomment-629703245
* https://github.com/osrf/docker_images/issues/403
I manually pushed a local build to Dockerhub to check, and the release CI seems fine with this:
Example: https://circleci.com/workflow-run/11963602-4cc1-44c3-a3f2-e66b176e4547

Switch to nightly tag for release image

---

.circleci/config.yml
Dockerfile
tools/ros2_dependencies.repos

Fixes: https://github.com/ros-planning/navigation2/issues/1687

Revert libgazebo11 workaround for CI

---

nav2_util/src/robot_utils.cpp
nav2_util/test/CMakeLists.txt
nav2_util/test/test_robot_utils.cpp

More tests to increase coverage - starting to handle all the different tf2 exceptions that our robot_utils can throw.

make basic failing test for tf2 wrapper (start of robot utils tests)

---

.circleci/config.yml
Dockerfile

So we don't have to wait for the nightly parent image to update rosdep.
Related: https://github.com/ros-planning/navigation2/pull/1750#issuecomment-630482940

Run rosdep update in builder

---

.circleci/config.yml
Dockerfile

Context: https://github.com/osrf/docker_images/pull/399

Don't pass rosdistro when using empty index

---

nav2_bringup/nav2_gazebo_spawner/setup.cfg

Explicitly set `junit_family` parameter which fixes pytest warning message appearing in stderr.
---
| Info |  |
| Ticket(s) this addresses   | #1749  |
| Primary OS tested on | Ubuntu 20.04 Focal |
| ROS tested on | Foxy |

Explicitly set junit_family parameter for nav2_gazebo_spawner tests

---

nav2_navfn_planner/src/navfn_planner.cpp

Reproduction & fix PR for #1733

Add the goal to NavFN tolerance region traversing algorithm

---

.circleci/config.yml

Looks like codecov analytics from merged PRs alone do not update codecov status for the master branch. Re-enabling nightly debug builds to keep codecov status on master up-to-date.
https://codecov.io/gh/ros-planning/navigation2

Re-enable nightly debug builds for codecov

---

nav2_navfn_planner/src/navfn_planner.cpp

* corrected wrong indexing in NavfnPlanner::smoothApproachToGoal function
* resolved uncrustify errors
* corrected the condition inside NavfnPlanner::smoothApproachToGoal to replace last pose of computed path
Co-authored-by: chikmagalore.thilak <chikmagalore.thilak@bshg.com>
---
---
---

Issue 1608 segmentation fault planner server node master (#1612)

---

nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp

The following is an example of the error.
[ERROR] [1590171638.335693813] [bt_navigator]: Action server failed while executing action callback: "failed to send request: ros_request argument is null, at /opt/ros/src/ros2/rcl/rcl/src/rcl/client.c:278"a bugfix of clear costmap service action
`BtServiceNode` creates `request_` in `on_tick` but it was overrided without it.  
https://github.com/ros-planning/navigation2/blob/master/nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp#L94
Signed-off-by: Daisuke Sato <daisukes@cmu.edu>

a bugfix of clear costmap service action

---

nav2_bt_navigator/src/bt_navigator.cpp
nav2_waypoint_follower/src/waypoint_follower.cpp

Signed-off-by: Daisuke Sato <daisukes@cmu.edu>
---
| Ticket(s) this addresses   | #1773  |
---
To deal with #1773 issue
- set `use_rclcpp_node` option to true to prevent from creating a node not used
- change the name of the node `client_node_` as `xxx_rclcpp_node` to keep configuration file consistency 
N/A

a patch for #1773 BT navigator nodes with use_sim_time

---

nav2_bringup/bringup/params/nav2_params.yaml
nav2_system_tests/CMakeLists.txt
nav2_system_tests/src/recoveries/backup/CMakeLists.txt
nav2_system_tests/src/recoveries/backup/backup_recovery_tester.cpp
nav2_system_tests/src/recoveries/backup/backup_recovery_tester.hpp
nav2_system_tests/src/recoveries/backup/test_backup_recovery_launch.py
nav2_system_tests/src/recoveries/backup/test_backup_recovery_node.cpp
nav2_util/include/nav2_util/geometry_utils.hpp

Adding test coverage for the backup recovery behavior. I have it back up in 2 phases: 10cm and then 20cm, both should succeed. Then a failure case of -2m to hit a wall.

adding backup tests

---

nav2_dwb_controller/dwb_core/src/dwb_local_planner.cpp

Declared `<dwb plugin>.default_critic_namespaces` parameter as discussed in #1783

declaring default_critic_namespaces param in dwb_local_planner

---

nav2_behavior_tree/plugins/condition/goal_reached_condition.cpp
nav2_bt_navigator/include/nav2_bt_navigator/bt_navigator.hpp
nav2_bt_navigator/src/bt_navigator.cpp

---
| Ticket(s) this addresses   | None (related to #1742) |
| Robotic platform tested on | [Stage](https://github.com/rtv/Stage) and [stage_ros2](https://github.com/ymd-stella/stage_ros2) |
---
* Fix some parameters (global_frame, robot_frame, transform_tolerance) not being passed to getCurrentPose

Fix some parameters not being passed to getCurrentPose

---

nav2_bringup/bringup/launch/bringup_launch.py
nav2_bringup/bringup/launch/slam_launch.py
nav2_bringup/bringup/launch/tb3_simulation_launch.py
nav2_bringup/bringup/params/nav2_params.yaml
nav2_bringup/bringup/worlds/waffle.model

Adding new `nav2_bringup/bringup/launch/slam_launch.py` file running SLAM Toolbox, map_saver_server and requesting once a map through `/map_saver/save_map'` service call. This can be enabled via `slam` parameter, as follows:
```
ros2 launch nav2_bringup tb3_simulation_launch.py slam:=True
```
Default behavior when `slam` parameter is not specified did not changed.
| Ticket(s) this addresses   | #1630 |
| Robotic platform tested on | Gazebo simulation of TB3 waffle |

Add SLAM Toolbox and map_saver_server into launch-files

---

nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp
nav2_behavior_tree/plugins/action/navigate_to_pose_action.cpp

Signed-off-by: Daisuke Sato <daisukes@cmu.edu>
| Primary OS tested on | Ubuntu20.04 |
| Robotic platform tested on | Turtlebot, nav2_system_tests |
---
bt_action_node and bt_service_node could not get server_timeout input properly due to lack of `convertFromString` definition.
* include `bt_conversions.hpp` 
* remove redundant include statement
N/A

BT navigator conversion fix

---

nav2_bringup/bringup/launch/bringup_launch.py
nav2_bringup/bringup/launch/multi_tb3_simulation_launch.py
nav2_bringup/bringup/launch/navigation_launch.py
nav2_bringup/bringup/launch/tb3_simulation_launch.py
nav2_bringup/bringup/params/nav2_multirobot_params_1.yaml
nav2_bringup/bringup/params/nav2_multirobot_params_2.yaml
nav2_bringup/bringup/params/nav2_params.yaml
nav2_bt_navigator/include/nav2_bt_navigator/bt_navigator.hpp
nav2_bt_navigator/src/bt_navigator.cpp
nav2_msgs/action/NavigateToPose.action

Basic Info
| Ticket(s) this addresses   | #1780  |
---
*  Changes in  NavigateToPose.action to include a field `string behavior_tree` with the ID of the BT to use. If it is void (""), the use the first BT in params. This change solves backward compatibility.
* Use a list of BTs, in the similar way as plugins (the first could is the BT by default):
```
bt_xml_filenames: ["navigate_w_replanning_and_recovery.xml", "navigate_w_replanning_time.xml"]
bt_xml_ids:  ["default", "time"]
```
- In `bt_navigator`  tree_ is changed to `std::shared_ptr<BT::Tree>` to ensure a clean BT when it is changed. Measured BT recreating time. It is …

Select behavior Tree in NavigateToPoseAction

---

nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp

Signed-off-by: Daisuke Sato <daisukes@cmu.edu>
---
| Ticket(s) this addresses   | #1652  |
| Robotic platform tested on | turtlebot |
---
* fix the issue BT action node does not abort #1652 for temporary until rcl interface is updated 
N/A
---
* #1652 still needs to be tracked

a workaround patch for #1652

---

nav2_behavior_tree/include/nav2_behavior_tree/plugins/control/round_robin_node.hpp
nav2_behavior_tree/plugins/control/recovery_node.cpp
nav2_behavior_tree/plugins/control/round_robin_node.cpp
nav2_behavior_tree/test/plugins/control/CMakeLists.txt
nav2_behavior_tree/test/plugins/control/test_recovery_node.cpp
nav2_behavior_tree/test/plugins/control/test_round_robin_node.cpp

---
| Ticket(s) this addresses   | #1819 #1810 |
| Robotic platform tested on | Turtlebot3 gazebo simulation |
---
* Fixes `RoundRobin` logic (if current child return failure tick next child until all fail or one succeeds)
* Fixes `RecoveryNode` error where actual number of retries performed = required number of retries - 1
* Adds unit tests for `RoundRobin`

Fix logic in RoundRobinNode and RecoveryNode and add unit tests

---

tools/bt2img.py

This PR enables the behavior tree print script to also draw subtrees.   
The way of calling the script didn't change.  
But there is a change of how the root node is detected.  
I now read the `main_tree_to_execute` tag to know which one is the root tree.
Also maybe consider using the _explicit_ form of writing BT xml's, that way one doesn't need to update the `node_names` array every time a new node comes into play.
So writing `<Action ID="FinishTaskNode" />` instead of `<FinishTaskNode />` leads to automatic detection of the node type.
```
<root main_tree_to_execute="Demo">
<BehaviorTree ID="Demo">
<SequenceStar>
<Condition ID="HasNavigationTask"/>
<SubTree ID="Navigation" />
</SequenceStar>
<SequenceStar>
<Condition ID="HasTransferTask"/>
<SubTree ID="Transfer" />
</SequenceStar> …
```

Updated bt2img.py to handle subtrees

---

nav2_bringup/nav2_gazebo_spawner/nav2_gazebo_spawner/nav2_gazebo_spawner.py

A small change, if you use 'argument' instead of 'remapping' you get the following warning:
`[gzserver-1] [WARN] [rcl]: Found remap rule '/tf:=/robot1/tf'. This syntax is deprecated. Use '--ros-args --remap /tf:=/robot1/tf' instead.`
Using 'argument' still works, but as it states it's deprecated. This one word change removes the error.

changed argument to remapping

---

.circleci/config.yml

Removing the release / debug elements from the mixins list for CircleCI

attempt to resolve issues with mixins in CI

---

.circleci/config.yml
Dockerfile
nav2_bringup/bringup/package.xml
tools/ros2_dependencies.repos

---
| Ticket(s) this addresses   | (add tickets here #1827) |
| Primary OS tested on | Ubuntu 20.04 (docker) |
---
Added exec depend to the package.xml for nav2 bringup to address issue #1827
---
Handle ceres solver dependency to the docker container

Add slam toolbox as exec dep for nav2_bringup

---

.github/ISSUE_TEMPLATE.md

I want people to be required to specify this

Adding ROS2 versions to issue template

---

nav2_bt_navigator/src/bt_navigator.cpp

| Robotic platform tested on | Tturtlebot |
---
Bugfix of BT navigator
- symptoms: nullptr error or no `/behavior_tree_log` topic
- problem: `tree_` is replaced after making a topic logger
How to reproduce
```
Terminal 1 $ ros2 launch nav2_bringup tb3_simulation_launch.py
Terminal 2 $ ros2 action send_goal /navigate_to_pose nav2_msgs/action/NavigateToPose '{"pose":{"header":{"stamp":{"sec":0,"nanosec":0},"frame_id":"map"},"pose":{"position":{"x":1,"y":1,"z":0},"orientation":{"x":0,"y":0,"z":0,"w":1}}},"behavior_tree":"/opt/overlay_ws/src/navigation2/nav2_bt_navigator/behavior_trees/navigate_w_replanning_speed.xml"}'
Terminal 3 $ ros2 topic echo /behavior_tree_log
```

A patch to fix BT navigator nullptr error or no /behavior_tree_log problem

---

nav2_costmap_2d/src/observation_buffer.cpp

---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/545 |
| Robotic platform tested on | prototype |
Points remain in obstacle layer after we stopped publishing a point cloud on regular basis. Settings to reproduce:
```
obstacle_layer:
enabled: true
observation_sources: pointcloud
pointcloud:
topic: "blabla"
max_obstacle_height: 2.0
data_type: "PointCloud2"
expected_update_rate: 0.0
observation_persistence: 1.0
clearing: true
marking: true
```
According to `observation_persistence: 1.0` the point clouds used by the obstacle layers should time-out after 1 second. 
* `last_updated_` is updated on every new cloud that needs to be added to the buffer. 
* …

Use current time to check if observation is out of date

---

doc/parameters/param_list.md
nav2_amcl/include/nav2_amcl/amcl_node.hpp
nav2_amcl/src/amcl_node.cpp
nav2_bringup/bringup/params/nav2_multirobot_params_1.yaml
nav2_bringup/bringup/params/nav2_multirobot_params_2.yaml
nav2_bringup/bringup/params/nav2_params.yaml

| Robotic platform tested on | TB3 simulation |
---
Adds the ability to configure the amcl scan topic in the parameters yaml file like the topics of the rest of the ROS2 nav nodes.  
Added in PR to the configuration docs of navigation.ros.org (https://github.com/ros-planning/navigation.ros.org/pull/45)

Added parameters to configure amcl laser scan topic

---

nav2_bringup/bringup/launch/tb3_simulation_launch.py
nav2_bringup/bringup/params/nav2_params.yaml
nav2_map_server/include/nav2_map_server/map_saver.hpp
nav2_map_server/src/map_saver/map_saver.cpp

| Ticket(s) this addresses   | #1864 |
| Robotic platform tested on | TB3 simulation |
---
Added parameter to map saver that configures it to subscribe to the /map topic as transient local.

Added transient local subscription qos profile parameter to map saver

---

nav2_lifecycle_manager/src/lifecycle_manager_client.cpp
nav2_recoveries/test/test_recoveries.cpp
nav2_rviz_plugins/src/nav2_panel.cpp
nav2_system_tests/src/recoveries/backup/backup_recovery_tester.cpp
nav2_system_tests/src/recoveries/spin/spin_recovery_tester.cpp
nav2_system_tests/src/recoveries/wait/wait_recovery_tester.cpp
nav2_util/include/nav2_util/service_client.hpp
nav2_util/test/test_actions.cpp

Remove deprecated rclcpp::executor::FutureReturnCode::SUCCESS in favor of rclcpp::FutureReturnCode::SUCCESS
Signed-off-by: Hunter L. Allen <hunter.allen@ghostrobotics.io>
---
Trivial Change.
---
* Fixed the [deprecated declarations warning](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations) that was being treated as an error.
* N/A
---
No future work should be required (unless it changes again, obviously).

Remove Deprecated Declaration

---

nav2_dwb_controller/nav_2d_utils/CMakeLists.txt
nav2_dwb_controller/nav_2d_utils/include/nav_2d_utils/tf_help.hpp
nav2_dwb_controller/nav_2d_utils/src/tf_help.cpp

---
| Ticket(s) this addresses   | #1879 |
| Robotic platform tested on | gazebo simulation of turtlebot3 on eloquent |
---
* Moved definitions of nav_2d_util::transformPose into separate cpp file to avoid multiple definition compilation error
* Added library to CMakeLists
Noticed a few other methods in nav_2d_util were also defined in header files. These too could cause an issue if included in multiple src files.

Move definitions in tf_help to separate src cpp file

---

nav2_bt_navigator/src/bt_navigator.cpp

---
| Ticket(s) this addresses   |  #1893 |
| Robotic platform tested on | TurtleBot3 Gazebo |
---
* Tiny fix in `nav2_bt_navigator` cleanup to clear `current_bt_xml_filename_` which prevented `BtNavigator::loadBehaviorTree` to load a BT with the latest blackboard

Fix nav2_bt_navigator cleanup

---

nav2_planner/src/planner_server.cpp
nav2_system_tests/src/planning/planner_tester.cpp
nav2_system_tests/src/system/CMakeLists.txt
nav2_system_tests/src/system/test_system_launch.py
nav2_system_tests/src/system/tester_node.py
nav2_system_tests/src/waypoint_follower/tester.py
nav2_waypoint_follower/include/nav2_waypoint_follower/waypoint_follower.hpp
nav2_waypoint_follower/src/waypoint_follower.cpp

#1810 
Looks like from test coverage docs that we're not actually testing A* at all even though set in the parameter remapping. I think we're missing the full namespacing from it to count. Seeing if this will fix things. If not, we'll have to reassess how to get A* coverage. 
cleaner destruction of planner server, add preemption and cancel coverage for waypoint follower and cancel for bt navigator coverage, A* coverage via planner tests, topic-based navigation

Bunches of random new tests

---

nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/back_up_action.hpp
nav2_behavior_tree/plugins/action/back_up_action.cpp
nav2_behavior_tree/test/plugins/action/test_back_up_action.cpp
nav2_recoveries/plugins/back_up.cpp

---
| Ticket(s) this addresses   |  #1896 |
---
* Fixes that backup_action_node cannot enter a negative speed and therefore the action cannot backed up.
* Changed to invert speed when distance is negative (robot should go forward) similar to backup recovery node.
---

Speed is inverted when dist is negative

---

nav2_dwb_controller/dwb_core/src/dwb_local_planner.cpp
nav2_navfn_planner/src/navfn_planner.cpp

| Ticket(s) this addresses   | #1911 |
---
* This avoids making a plan while the costmap layer is updating
---
* This may happen with a custom planner plugin
* The following version could prevent such problem but may lock up costmap update longer time
https://github.com/CMU-cabot/navigation2/commit/ba6b87e60899e7f0ce960d74bef11ee21a2a01d0

Costmap lock while copying data in navfn planner

---

nav2_controller/include/nav2_controller/nav2_controller.hpp
nav2_controller/src/nav2_controller.cpp
nav2_planner/src/planner_server.cpp
nav2_voxel_grid/test/voxel_grid_tests.cpp

Adding near-complete voxel grid test coverage and more to controller server

---

nav2_controller/src/nav2_controller.cpp
nav2_planner/src/planner_server.cpp
nav2_system_tests/src/waypoint_follower/tester.py

#1810 
Collapsing lines that can be on 1 line where they make sense. Also removing a controller server warning that is covered by exceptions. Adding sleep to waypoint follower integration test to give some time for networking to die down

[Testing sprint] minor changes to lower redundent warnings 

---

nav2_costmap_2d/src/costmap_2d_ros.cpp

---
| Ticket(s) this addresses   | #1917 |
| Robotic platform tested on | gazebo simulation  |
---
* Declare if not declared the plugin parameter when getting plugins for costmap_2d
* N/A
---

Costmap plugins declare if not declared for reset capabilities

---

nav2_map_server/test/CMakeLists.txt
nav2_map_server/test/map_saver_cli/CMakeLists.txt
nav2_map_server/test/map_saver_cli/test_map_saver_cli.cpp

adding map saving CLI tests

---

doc/parameters/param_list.md
nav2_behavior_tree/include/nav2_behavior_tree/bt_conversions.hpp
nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/navigate_to_pose_action.hpp
nav2_behavior_tree/nav2_tree_nodes.xml
nav2_behavior_tree/plugins/action/navigate_to_pose_action.cpp
nav2_behavior_tree/test/plugins/action/test_navigate_to_pose_action.cpp
nav2_behavior_tree/test/test_bt_conversions.cpp

---
| Ticket(s) this addresses   | (related to #1796) |
---
* NavigateToPose input has been changed from (Position, Orientation) to Goal to make the goal easier to handle.
---

Improve interface of NavigateToPose

---

.circleci/config.yml

Avoid duplicate colcon tests, and update/optimize CI config.
Context: https://github.com/ros-planning/navigation2/pull/1284#issuecomment-671636246

Cleanup CircleCI config

---

nav2_costmap_2d/include/nav2_costmap_2d/inflation_layer.hpp
nav2_costmap_2d/plugins/inflation_layer.cpp

| Ticket(s) this addresses   | #1931  |
| Robotic platform tested on | tb3 |
---
* fix resource locking problem of InflationLayer
N/A

Fix InflationLayer resource locking problem (#1931)

---

nav2_waypoint_follower/src/waypoint_follower.cpp

---
| Ticket(s) this addresses   | #1937|
| Robotic platform tested on | Sim |
---
* Changed the way we define the name of the node, which as memory serves for client / secondary nodes has to be done a little bit of a funky way. I think there's some hacky solution in rclcpp for remapping the node names in the C++ code to launch that effects the entire process' nodes not just the object of that name. 
* N/A 
---
* N/A

Fixing multiple waypoint follower nodes on network, resolves #1937

---

nav2_costmap_2d/package.xml

---
---
* Added 'angles' as dependency in `nav2_costmap_2d` package.xml to fix failing foxy debian builds

Add 'angles' dependency to nav2_costmap_2d package.xml

---

nav2_controller/src/nav2_controller.cpp

| Robotic platform tested on | UBR-1 |
* fix regression from #1857 - the goal has to be transformed to the costmap frame or you never finish a navigation goal (I presume in simulation you don't notice this because odom is pretty close to map frame?)

transform goal to costmap frame

---

tools/code_coverage_report.bash

#1810 
We exclude navigation system tests because they're not run-time tools use on someone's robot during an actual use. The rviz plugins are a similar analog, only used for entry level testing, not used when actually on someone's robot for use. We should consider if it makes sense to exclude this as well.
CC @naiveHobo - thoughts?

[WIP] removing rviz plugins from test coverage since its not a production run-time component

---

nav2_bt_navigator/src/ros_topic_logger.cpp
nav2_costmap_2d/package.xml
nav2_dwb_controller/nav_2d_utils/CMakeLists.txt
nav2_map_server/src/map_io.cpp

---
| Robotic platform tested on | Turtlebot3 Simulation |
---
* Those build breaks are found by building against [release-foxy-20200807](https://github.com/ros2/ros2/blob/release-foxy-20200807/ros2.repos).
* `tf_help` has a linkage dependency on `conversions` for the usage of `poseStampedToPose2D`.
* Fixed a time\duration conversion build break in `ros_topic_logger.cpp`.
* Added the missing dependency `angles` for `nav2_costmap_2d`.
N/A
---
N/A

[Foxy] More Windows build fix.

---

nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/compute_path_to_pose_action.hpp
nav2_behavior_tree/plugins/action/compute_path_to_pose_action.cpp
nav2_behavior_tree/plugins/action/follow_path_action.cpp
nav2_behavior_tree/test/plugins/action/test_back_up_action.cpp
nav2_behavior_tree/test/plugins/action/test_clear_costmap_service.cpp
nav2_behavior_tree/test/plugins/action/test_compute_path_to_pose_action.cpp
nav2_behavior_tree/test/plugins/action/test_follow_path_action.cpp
nav2_behavior_tree/test/plugins/action/test_navigate_to_pose_action.cpp
nav2_behavior_tree/test/plugins/action/test_reinitialize_global_localization_service.cpp
nav2_behavior_tree/test/plugins/action/test_spin_action.cpp
nav2_behavior_tree/test/plugins/action/test_wait_action.cpp
nav2_behavior_tree/test/plugins/condition/test_transform_available.cpp
nav2_behavior_tree/test/test_behavior_tree_fixture.hpp
nav2_bt_navigator/src/bt_navigator.cpp

| Ticket(s) this addresses   | #1938 |
| Robotic platform tested on | turtlebot |
---
* Remove `path_updated` blackboard variable and use `path.header.stamp` to check if the path is updated or not
* This change fixes both #809 and #1938
* I think nothing
---
* if this change is okay, tests should be fixed. There are many tests that set/gets `path_udpated` to/from the blackboard

Fix FollowPath path_updated issue (#1938)

---

nav2_costmap_2d/test/integration/inflation_tests.cpp

this fix was applied as part of the noetic release of costmap_2d
https://github.com/ros-planning/navigation/commit/05d42ac1f8d164359f2f0da1d63d52e1d4b6ec05

fix invalid memory access

---

nav2_costmap_2d/plugins/inflation_layer.cpp

another fix from noetic release
https://github.com/ros-planning/navigation/commit/71b95c26c9b713705ea584e93ea494c3d02b919d

initialize variables in inflation layer

---

nav2_waypoint_follower/src/waypoint_follower.cpp

---
| Ticket(s) this addresses   | #1977 |
| Robotic platform tested on | Gazebo simulation of turtlebot 3 |
---
Check for the number of waypoints. If there are no waypoints, then terminate the action and return.
No updates to documentation required.

Fix zero waypoints crash

---

nav2_costmap_2d/plugins/range_sensor_layer.cpp
nav2_costmap_2d/test/integration/test_costmap_topic_collision_checker.cpp

| Ticket(s) this addresses   | #1987  |
| Primary OS tested on | Ubuntu 20.04 in VirtualBox on Windows 10 |
| Robotic platform tested on | n.a. |
---
Valgrind reported uninitialized variables in range_test. After this initialization valgrind does not report errors anymore.
No documentation changes required.
---
The unit and integration tests are unstable. We still have to find what the problem is.

Initialize inflate_cone_ variable.

---

nav2_behavior_tree/test/plugins/action/test_back_up_action.cpp
nav2_behavior_tree/test/plugins/action/test_compute_path_to_pose_action.cpp
nav2_behavior_tree/test/plugins/action/test_follow_path_action.cpp
nav2_behavior_tree/test/plugins/action/test_navigate_to_pose_action.cpp
nav2_behavior_tree/test/plugins/action/test_spin_action.cpp
nav2_behavior_tree/test/plugins/action/test_wait_action.cpp

Noticed some flaky tests in `nav2_behavior_tree` which failed sometimes especially during the nightly builds ([example](https://app.circleci.com/pipelines/github/ros-planning/navigation2/3834/workflows/50051751-1124-4fac-810d-f875d3c0e96e/jobs/14847)). This PR should fix all the issues.

Fix flaky nav2_behavior_tree tests

---

nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
nav2_bringup/nav2_gazebo_spawner/nav2_gazebo_spawner/nav2_gazebo_spawner.py
nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager_client.hpp
nav2_lifecycle_manager/src/lifecycle_manager_client.cpp
nav2_rviz_plugins/include/nav2_rviz_plugins/nav2_panel.hpp
nav2_rviz_plugins/src/nav2_panel.cpp

---
| Ticket(s) this addresses   | #985 |
| Robotic platform tested on | TurtleBot3 Gazebo Simulation |
---

Add timeouts to all spin_until_future_complete calls

---

nav2_dwb_controller/dwb_core/src/publisher.cpp

| Robotic platform tested on | simulation |
---
dwb_controller has a parameter `publish_trajectories` to publish the scored trajectories on the `marker` topic. This publisher is enabled by default, but does not actually publish anything unless something also subscribes to another topic called `evaluation`. This is due to the `publishTrajectories` method being called from the `publishEvaluation` method, while `publishEvaluation` returns early when there are no subscribers.
As far as I could find, there's no documentation referring to the trajectory topic. IMO the topic name could also be improved from `marker` to something like `trajectories`, but that could …

Fix trajectory publisher not publishing unless subscribed to evaluation

---

nav2_controller/src/nav2_controller.cpp
nav2_costmap_2d/src/costmap_2d_ros.cpp
nav2_recoveries/include/nav2_recoveries/recovery.hpp
nav2_waypoint_follower/src/waypoint_follower.cpp

| Robotic platform tested on | simulation |
---
- `rclcpp::Rate` is used for controlling the frequency in a few parts of the code.
- `rclcpp::Rate` uses [`std::chrono::system_clock`](https://en.cppreference.com/w/cpp/chrono/system_clock) which is meant to represent wall time. Due to unevitable clock drift on the local system in combination with time synchronisation mechnism's like NTP this clock can tick at a slower or faster rate to stay synchronized with the actual wall time or even jump both forwards and backwards in time in case of bigger offsets.
- `rclcpp::Rate` does not have a mechanism to deal with time jumps, so for example if the time jumps …

Controllers should not be influenced by time jumps or slew

---

nav2_navfn_planner/src/navfn_planner.cpp

---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/2016 |
| Primary OS tested on | (Raspbian Buster) |
| Robotic platform tested on | (Raspberry Pi 4 + RPLIDAR A1 + Roomba) |
---
My test environment is much larger in length than width, I was frequently getting failed path plans when issuing commands that traversed the length of the environment.  I noticed the max cycles to run NavFn::calcPath is derived from the X dimension alone, I changed it to be depending on whether the X or Y dimension is larger.

Fix max path cycles for case where map has larger Y dimension than X dimension

---

.circleci/config.yml

As OMPL isn't yet registering properly with the ament index for ros2
and searching all of << parameters.underlay >>/install will stall rosdep
when searching entire $ROS_WS/install folder
Related: https://github.com/ros-planning/navigation2/pull/2021#issuecomment-704604732

Include underlay source folder in rosdep path

---

doc/parameters/param_list.md
nav2_bringup/bringup/params/nav2_params.yaml
nav2_core/include/nav2_core/waypoint_task_executor.hpp
nav2_system_tests/src/waypoint_follower/tester.py
nav2_waypoint_follower/CMakeLists.txt
nav2_waypoint_follower/include/nav2_waypoint_follower/plugins/wait_at_waypoint.hpp
nav2_waypoint_follower/include/nav2_waypoint_follower/waypoint_follower.hpp
nav2_waypoint_follower/package.xml
nav2_waypoint_follower/plugins.xml
nav2_waypoint_follower/plugins/wait_at_waypoint.cpp
nav2_waypoint_follower/src/waypoint_follower.cpp

Signed-off-by: jediofgever <fetulahatas1@gmail.com>
Successor PR for https://github.com/ros-planning/navigation2/pull/1993, 
https://github.com/ros-planning/navigation2/pull/1993 was mistakenly targeted to distro(`foxy-devel`) branch and it became difficult to track the changes and merge the new code into `main`, This PR includes reviewed and modified changes through discussions in https://github.com/ros-planning/navigation2/pull/1993
---
| Ticket(s) this addresses   | (https://github.com/ros-planning/navigation2/issues/1992) |
| Robotic platform tested on | (Gazebo simulation of Turtlebot3) |
---
* Added a plugin interface to `nav2_waypoint_follower`, with aim of executing a task on …

Successor PR for #1993, Introduces A plugin interface to define behaviours at waypoint arrivals when using nav2_waypoint_follower

---

nav2_dwb_controller/dwb_plugins/test/CMakeLists.txt
nav2_dwb_controller/dwb_plugins/test/kinematic_parameters_test.cpp

---
* I added a test for settting the kinematic parameters in nav2_dwb_controller / dwb_plugins.

Add kinematic parameters test

---

nav2_bt_navigator/include/nav2_bt_navigator/bt_navigator.hpp
nav2_dwb_controller/dwb_plugins/test/CMakeLists.txt
nav2_dwb_controller/dwb_plugins/test/kinematic_parameters_test.cpp
nav2_dwb_controller/dwb_plugins/test/twist_gen.cpp
smac_planner/include/smac_planner/a_star.hpp
smac_planner/include/smac_planner/costmap_downsampler.hpp
smac_planner/include/smac_planner/node_basic.hpp
smac_planner/test/test_a_star.cpp
smac_planner/test/test_costmap_downsampler.cpp
smac_planner/test/test_node2d.cpp
smac_planner/test/test_nodebasic.cpp
smac_planner/test/test_smac_2d.cpp
smac_planner/test/test_smac_se2.cpp
smac_planner/test/test_smoother.cpp
tools/underlay.repos

---
* I added a test with an (invalid) value of the controller_frequency parameter of 0.0
The expected behavior is that the LimitedAccelGenerator prints an error message and the frequency should be set to the default frequency of 20Hz. This should set the test coverage to 100% for the limited_accel_generator.cpp file.

Added test for nav2_dwb_controller / dwb_plugins / LimitedAccelGenerator

---

doc/parameters/param_list.md
nav2_waypoint_follower/CMakeLists.txt
nav2_waypoint_follower/include/nav2_waypoint_follower/plugins/input_at_waypoint.cpp
nav2_waypoint_follower/include/nav2_waypoint_follower/plugins/input_at_waypoint.hpp
nav2_waypoint_follower/plugins.xml
nav2_waypoint_follower/plugins/input_at_waypoint.cpp

Adding input at waypoint task executor. This can be used when you need to wait for external stimulus to move to the next waypoint (e.x. human hit a button when they picked a package and its on the robot)
@jediofgever please take a look

Input at waypoint task executor plugin

---

nav2_controller/src/nav2_controller.cpp
nav2_costmap_2d/src/costmap_2d_ros.cpp
nav2_costmap_2d/src/observation_buffer.cpp
nav2_costmap_2d/test/integration/test_costmap_topic_collision_checker.cpp
nav2_dwb_controller/dwb_critics/include/dwb_critics/oscillation.hpp
nav2_lifecycle_manager/src/lifecycle_manager.cpp
nav2_recoveries/plugins/wait.cpp
nav2_rviz_plugins/src/nav2_panel.cpp
nav2_system_tests/src/planning/planner_tester.cpp
nav2_system_tests/src/recoveries/backup/test_backup_recovery_launch.py
nav2_system_tests/src/recoveries/backup/test_backup_recovery_node.cpp
nav2_system_tests/src/recoveries/spin/test_spin_recovery_node.cpp
nav2_system_tests/src/recoveries/wait/test_wait_recovery_node.cpp
nav2_waypoint_follower/plugins/input_at_waypoint.cpp
smac_planner/test/test_a_star.cpp
tools/underlay.repos

Fixing deprecation warning on bondcore / gazebo ros pkgs

[WIP] Fix CI build issues

---

smac_planner/include/smac_planner/costmap_downsampler.hpp
smac_planner/include/smac_planner/smac_planner.hpp
smac_planner/include/smac_planner/smac_planner_2d.hpp
smac_planner/src/costmap_downsampler.cpp
smac_planner/src/smac_planner.cpp
smac_planner/src/smac_planner_2d.cpp
smac_planner/test/test_costmap_downsampler.cpp

---
| Robotic platform tested on | TurtleBot3 Gazebo Simulation |
---
* Fix `shared_ptr` cyclic dependencies in `SmacPlanner` and `CostmapDownsampler` as per #1900
* Refactor `CostmapDownsampler` to have `on_` type functions to configure, activate, deactivate, and cleanup costmap publisher stuff
* Fix `CostmapDownsampler` test which has been failing on Cyclone DDS (#2043)

Fix SmacPlanner memory leaks and costmap downsampler test

---

nav2_map_server/src/map_saver/map_saver.cpp
nav2_map_server/test/component/test_map_saver_publisher.cpp
nav2_map_server/test/map_saver_params.yaml

Fix for #2077:
1. Protect Map Saver's resource by mutex
2. Remove unnecessary map republisher for `transient local` messages in `test_map_saver_node`
3. Increase map saving timeout from 1sec -> to 5sec. Sometimes it also causes rare test fails
**plus**
4. This is not related to current issue, but added forgotten reset of save_map_service_ in `MapSaver::on_cleanup()` routine.

Fix Map Saver and testing

---

nav2_amcl/src/amcl_node.cpp
nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp
nav2_bt_navigator/src/ros_topic_logger.cpp
nav2_costmap_2d/include/nav2_costmap_2d/observation.hpp
nav2_costmap_2d/include/nav2_costmap_2d/observation_buffer.hpp
nav2_costmap_2d/plugins/obstacle_layer.cpp
nav2_costmap_2d/src/observation_buffer.cpp
nav2_dwb_controller/nav_2d_utils/CMakeLists.txt
nav2_recoveries/include/nav2_recoveries/recovery.hpp
nav2_util/src/dump_params.cpp
nav2_waypoint_follower/include/nav2_waypoint_follower/plugins/photo_at_waypoint.hpp
nav2_waypoint_follower/package.xml
smac_planner/src/a_star.cpp

---
macOS : 11.0.1 (20B5022a)
Build tools : Apple Clang 12.0.x
ROS2 : Foxy (Patch release 3)
---
Building navigation2 on latest macOS 11 (Big Sur) is now possible with a ros2 foxy environment. Previous macOS versions should also work but remains untested. This PR adresses the following fatal build errors (with tests set to OFF) :
```
--- stderr: nav2_util
/Users/ewen/ros_ws/navigation2/nav2_util/src/dump_params.cpp:351:33: error: use of undeclared identifier 'basename'
std::cout << "Usage: " << basename(argv[0]) << "\n";
```
```
--- stderr: nav2_amcl
/Users/ewen/ros_ws/navigation2/nav2_amcl/src/amcl_node.cpp:404:64: error: cannot pass object of non-trivial type 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char> >') through variadic function; call will abort at …
```

Fix build on macOS (10.x / 11.x)

---

nav2_dwb_controller/dwb_core/include/dwb_core/trajectory_critic.hpp
nav2_dwb_controller/dwb_critics/test/CMakeLists.txt
nav2_dwb_controller/dwb_critics/test/obstacle_footprint_test.cpp

---
* I added unit tests for the obstacle footprint critic in the dwb_critics.

Add obstacle footprint dwb critic test

---

nav2_costmap_2d/plugins/costmap_filters/keepout_filter.cpp
nav2_costmap_2d/test/unit/keepout_filter_test.cpp
nav2_system_tests/maps/keepout_mask.yaml

Clean-up of Keepout Filter developed together with PR #2074.
This includes:
* Make logging messages to be more clear: explicitly point on `KeepoutFilter`, like made in `StaticLayer`
* Use `logger_` and `clock_` new paradigm, mentioned in https://github.com/ros-planning/navigation2/pull/2074/files#r528936661
* Various clean-ups and improvements (PR #2074 stuff which is related to Keepout Filter)

Keepout Filter cleanup

---

nav2_controller/src/nav2_controller.cpp
nav2_planner/src/planner_server.cpp
nav2_recoveries/include/nav2_recoveries/recovery_server.hpp
nav2_recoveries/src/recovery_server.cpp

To be honest, I'm a little embarrassed that it never occurred to me until now to utilize the return codes of the lifecycle state transition to cleanly fault bringup on a fatal issue like not being able to find a plugin.

return failure on plugin failure in on_configure

---

nav2_navfn_planner/include/nav2_navfn_planner/navfn_planner.hpp
nav2_navfn_planner/src/navfn_planner.cpp

set "allow_unknown" parameter in navfn_planner to be configurable
---
| Ticket(s) this addresses   |(#2134  |
| Robotic platform tested on | (My own robot) |
---
I add some code to allow the parameter "allow_unknown" to be configured

allow "allow_unknown" parameter to be configurable

---

nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp

Use rclcpp::FutureReturnCode::SUCCESS replace rclcpp::executor::FutureReturnCode::SUCCESS
---
| Primary OS tested on | Arch Linux |
---
Use rclcpp::FutureReturnCode::SUCCESS replace rclcpp::executor::FutureReturnCode::SUCCESS to fix the deprecated error in building navigation2 foxy-devel. I found that it's fixed in main branch, but not in this branch.
none
none

Fix deprecated usage of FutureReturnCode::SUCCESS

---

nav2_behavior_tree/plugins/condition/is_stuck_condition.cpp
nav2_behavior_tree/plugins/decorator/speed_controller.cpp
nav2_costmap_2d/plugins/costmap_filters/speed_filter.cpp
nav2_costmap_2d/src/clear_costmap_service.cpp
nav2_map_server/test/component/test_map_saver_publisher.cpp
nav2_planner/src/planner_server.cpp
nav2_system_tests/src/planning/planner_tester.cpp
nav2_util/src/costmap.cpp
nav2_waypoint_follower/src/waypoint_follower.cpp

---
| Primary OS tested on | (Ubuntu 20.04) |
| Robotic platform tested on | (none) |
---
* Fixed incorrect format (printf) options in multiple locations. I found these formatting mistakes by building against the latest main branch of the core ros2 libraries.
none
---
none

Fix format strings in calls to RCLCPP macros

---

release_branch.Dockerfile
tools/build_all.sh
tools/initial_ros_setup.sh

Build scripts for Eloquent branch has 'dashing' as ROS2_DISTRO, instead of 'eloquent'.

Replace dashing tags to eloquent for building scripts

---

nav2_costmap_2d/src/costmap_2d.cpp

equivalent of [this ros-navigation pull request](https://github.com/ros-planning/navigation/pull/1095):
> A bug in the function that returns all the cells contained in a (convex) polygon:
> 
> - sorts all the points along the polygon outline by x coordinate
> - for all points with same x coordinate, find min and max y coordinate
> - for that x coordinate, considers all points between min and max y coordinate to be within the polygon
> 
> The bug is that the maximum y coordinate also needs to be included.

fix boundary point exclusion in convexFillCells

---

nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp

| Ticket(s) this addresses   | #2152  |
| Primary OS tested on | Ubuntu 18.04
| Robotic platform tested on | Turtlebot simulation
---
The green trajectory is the old behavior and the yellow trajectory is the new behavior in which angular velocity is updated.
The new behavior ensures the robot moves towards the lookahead point more closely. In the case of the old behavior, as seen in the GIF, it generates a trajectory that makes the robot take a cut (i.e. move with a higher angular speed) while turning which leads it much closer to the obstacle and could potentially lead to a collision.
Signed-off-by: Shrijit Singh <shrijitsingh99@gmail.com>

Update angular velocity after constraining linear velocity

---

nav2_bringup/bringup/worlds/waffle.model
nav2_system_tests/models/turtlebot3_waffle/model-1_4.sdf
nav2_system_tests/models/turtlebot3_waffle/model.sdf
nav2_system_tests/models/turtlebot3_waffle_depth_camera/model.sdf
nav2_system_tests/src/costmap_filters/keepout_params.yaml
nav2_system_tests/src/costmap_filters/speed_global_params.yaml
nav2_system_tests/src/costmap_filters/speed_local_params.yaml
nav2_system_tests/src/costmap_filters/test_keepout_launch.py
nav2_system_tests/src/costmap_filters/test_speed_launch.py
nav2_system_tests/src/costmap_filters/tester_node.py
nav2_system_tests/src/system/CMakeLists.txt
nav2_system_tests/src/system/tester_node.py
nav2_system_tests/src/system_failure/test_system_failure_launch.py
nav2_system_tests/src/system_failure/tester_node.py
nav2_system_tests/src/waypoint_follower/test_case_py.launch
nav2_system_tests/src/waypoint_follower/tester.py
nav2_system_tests/worlds/turtlebot3_ros2_demo.world
nav2_system_tests/worlds/turtlebot3_ros2_demo_obstacle.world

Performing context updates on parameters  probably (?) causing `Original error: parameter 'GridBased.use_astar' has invalid type: expected [bool] got [string]`. 
Updating warning that occasionally crashes test on rclpy QoS updates
Adding some context in service publisher timeouts
Future:
- Switch to cyclone in CI?
- debug gazebo crashes
- rcl lifecycle / rcl rmw crash debugging with eprosima
- gazebo gzserver rather than the .so file call

attempt at bringing up CI (2158)

---

nav2_regulated_pure_pursuit_controller/README.md
nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/regulated_pure_pursuit_controller.hpp
nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
nav2_regulated_pure_pursuit_controller/test/test_regulated_pp.cpp

| Ticket(s) this addresses   | #2152  |
| Primary OS tested on | Ubuntu 18.04
| Robotic platform tested on | Turtlebot simulation
---
The new cost scaling heuristic will scale the speed linearly based on distance from a lethal obstacle.
Updated heuristic: 
Earlier velocity decreased exponentially since it was based on inflation cost which is computed using an exponential function. This called the velocity to drop significantly in highly inflated areas even though the robot could safely traverse at a higher speed.
This updated heuristic will allow the robot to move at a higher speed in inflated areas will ensuring it slows down if it comes near an obstacle.
**TODO:**
Signed-off-by: Shrijit Singh <shrijitsingh99@gmail.com>

Update cost scaling heuristic to vary speed linearly with distance

---

.circleci/config.yml

#2158 
Trying to see if changing the default RMW will fix the issue. I'm seeing failures in the action server now with goals failing which makes me think now this is just a performance regression that is overloading our CI container limits

CI resolution Part 3

---

nav2_system_tests/src/updown/CMakeLists.txt

---
| Ticket(s) this addresses   |https://github.com/ros-planning/navigation2/issues/2200|
| Robotic platform tested on | Default test launch |
---
* Fixed installation to `\lib`

Install test_updown to lib/

---

nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp

If the carrot is 10 meters away at 1m/s travel, then checking this is bogus. Stopping should be based on the max time to collision parameter. While the carrot _should_ be always open in a path, the stoppages might be really preemptive before a replan if we do this.

[RPP] Remove optimization check on carrot, incorrect optimization

---

doc/parameters/param_list.md
nav2_controller/src/nav2_controller.cpp
nav2_core/include/nav2_core/controller.hpp
nav2_costmap_2d/include/nav2_costmap_2d/costmap_filters/speed_filter.hpp
nav2_costmap_2d/plugins/costmap_filters/speed_filter.cpp
nav2_costmap_2d/test/unit/speed_filter_test.cpp
nav2_dwb_controller/dwb_core/include/dwb_core/dwb_local_planner.hpp
nav2_dwb_controller/dwb_core/include/dwb_core/trajectory_generator.hpp
nav2_dwb_controller/dwb_plugins/include/dwb_plugins/kinematic_parameters.hpp
nav2_dwb_controller/dwb_plugins/include/dwb_plugins/standard_traj_generator.hpp
nav2_dwb_controller/dwb_plugins/src/kinematic_parameters.cpp
nav2_dwb_controller/dwb_plugins/test/speed_limit_test.cpp
nav2_msgs/msg/CostmapFilterInfo.msg
nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/regulated_pure_pursuit_controller.hpp
nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
nav2_regulated_pure_pursuit_controller/test/test_regulated_pp.cpp

According to public [discussions](https://discourse.ros.org/t/nav2-speed-restriction-support-now-available/18068/2), we are choosing the following solution to support speed limits expressed in absolute values:
> _Solution #1:_
> 
> Encode maximum linear velocity in a filter mask. Then restrict maximum angular velocity in the same proportion as it was changed for maximum linear velocity.
> 
> For example, a robot has 100 m/s max linear velocity and 20 rad/s max angular velocity allowed by its construction. Robot enters in a speed restriction area having 15 m/s speed restriction. This means, that maximum linear velocity will be restricted by this value, and maximum angular velocity by ( 15m/s / 100m/s ) * 20rad/s = 3rad/s. This will be a restriction of maximum angular velocity for this …

Add support of absolute limits to Speed Filter

---

nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/regulated_pure_pursuit_controller.hpp
nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp

CC @fmrico something to test on Monday
https://github.com/ros-planning/navigation2/issues/2210

[RPP] Remove dependency on collision checking to carrot location

---

nav2_bt_navigator/CMakeLists.txt

---
* Export the nav2_bt_navigator library to allow inheritance from it
---

Export nav2_bt_navigator library and dependencies

---

nav2_bringup/bringup/params/nav2_params.yaml
nav2_map_server/include/nav2_map_server/map_saver.hpp
nav2_map_server/src/map_saver/map_saver.cpp

| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/pull/1871|
---
* Same changes as https://github.com/ros-planning/navigation2/pull/1871 but keeping default foxy behavior unless `map_subscribe_transient_local` is set to `true`
* To save the map you have to set the parameter to True via `ros2 run nav2_map_server map_saver_cli -f ~/map --ros-args -p map_subscribe_transient_local:=True`

Optional transient map saver

---

nav2_bringup/bringup/launch/slam_launch.py
nav2_common/nav2_common/launch/__init__.py
nav2_common/nav2_common/launch/has_node_params.py

| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/2196|
| Robotic platform tested on | simulated turtlebot |
---
* After https://github.com/SteveMacenski/slam_toolbox/pull/347 params-file is automatically passed to slam_toolbox, these changes make sure that only happens if the params_file has `slam_toolbox` parameters.

If provided param file has no slam_toolbox params, don't forward it

---

nav2_rviz_plugins/src/nav2_panel.cpp

#2225 
Enables cancellation in waypoint following mode and removes lifecycle state transition options in the other active navigation state (shouldn't have been there)

Rviz state machine waypoint follower updates

---

nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server.hpp

As discussed here: https://github.com/ros-planning/navigation2/issues/1971#issuecomment-795862059

Add getTree() and  haltTree() to bt_action_server

---

nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
nav2_costmap_2d/include/nav2_costmap_2d/layer.hpp
nav2_costmap_2d/plugins/costmap_filters/costmap_filter.cpp
nav2_costmap_2d/src/layer.cpp
nav2_costmap_2d/test/unit/declare_parameter_test.cpp
nav2_dwb_controller/dwb_core/src/dwb_local_planner.cpp
nav2_dwb_controller/dwb_plugins/src/limited_accel_generator.cpp
nav2_lifecycle_manager/src/lifecycle_manager.cpp
nav2_map_server/src/map_server/map_server.cpp
nav2_util/include/nav2_util/node_utils.hpp
nav2_util/test/test_dump_params/dump_params_md.txt
nav2_util/test/test_dump_params/dump_params_md_verbose.txt
nav2_util/test/test_dump_params/dump_params_multiple.txt
nav2_util/test/test_dump_params/dump_params_yaml.txt
nav2_util/test/test_dump_params/dump_params_yaml_verbose.txt
nav2_util/test/test_dump_params/test_dump_params_node.py

This commit fixes build failures with latest ROS2 releases appeared due to changed and deprecated RCLCPP API.
In RCLCPP API [update](https://discourse.ros.org/t/feedback-required-should-parameters-be-able-to-change-of-type/18319/2) all ROS2 parameters are treated to be a static by-default. This leaded an impossibility of using the `declare_parameters("with_one_argument")` method without knowing a type of parameter. Additionally, these changes forced all static parameters by their design intentionally to be initialized with some value.
This commit adopts Nav2 stack parameters for the changes from above and fixes related tests.
---
| Ticket(s) this addresses   | #2220 |
| Robotic platform …

Forse ROS2 parameters to be static to meet RCLCPP API changes

---

nav2_controller/include/nav2_controller/plugins/simple_goal_checker.hpp
nav2_controller/plugins/simple_goal_checker.cpp

I need to change the **SimpleGoalChecker** params at runtime, so here is a PR activating this feature in a similar fashion as https://github.com/ros-planning/navigation2/pull/2181
Working and tested on my simulation.
If there is an interest I can add to this PR changeable parameters for the 2 others `nav2_controller` plugins: **SimpleProgressChecker** and **StoppedGoalChecker**

[SimpleGoalChecker] Make parameters changeable at runtime

---

nav2_common/nav2_common/launch/__init__.py
nav2_common/nav2_common/launch/has_node_params.py

| Ticket(s) this addresses   | Addressing comment on https://github.com/SteveMacenski/slam_toolbox/pull/368|
| Robotic platform tested on | simulated turtlebot, simulated TIAGo Base |
---
Add has_node_params launch utility

Add has_node_params launch utility

---

nav2_costmap_2d/plugins/inflation_layer.cpp
nav2_costmap_2d/test/integration/inflation_tests.cpp

This appearing when some layer is going after `inflation_layer`. More details are in #2051 ticket.

Fix for inflation artifacts behind update bounds

---

nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp

For my console sanity, switched RCLCPP_INFO to RCLCPP_DEBUG

[nav2_behavior_tree] Reduce bt_action_node verbose

---

nav2_util/include/nav2_util/service_client.hpp
nav2_util/test/test_service_client.cpp

| Ticket(s) this addresses   | [comment](https://github.com/ros-planning/navigation2/pull/2267#issuecomment-809671090) |
| Robotic platform tested on | Wyca (simulation)|
---
* I changed the behavior of wait_for_service to be not blocked forever if the service doesn't exist
* The method returns the result of `client.wait_for_service()`
* I added a unit test to check this behavior

ServiceClient wait_for_service not infinite

---

nav2_smac_planner/include/nav2_smac_planner/collision_checker.hpp
nav2_smac_planner/include/nav2_smac_planner/constants.hpp
nav2_smac_planner/test/test_collision_checker.cpp

CC @maxlein you should test this out, it should speed you up quite a bit
With change:
```
[planner_server-8] It took 141.18 milliseconds with 15296 iterations.
[planner_server-8] It took 518.114 milliseconds with 111194 iterations.
```
Without change:
```
[planner_server-8] It took 554.892 milliseconds with 76187 iterations.
[planner_server-8] It took 745.096 milliseconds with 112351 iterations.
```
~15% speed up
Baseline radius footprint:
```
[planner_server-8] It took 230.307 milliseconds with 43561 iterations.
[planner_server-8] It took 389.351 milliseconds with 83213 iterations.
```
Only ~25% slower than just a radius footprint check -- an improvement from ~45%

smac checking collision footprint only when in possibly inscribed situation

---

nav2_bringup/bringup/params/nav2_params.yaml
nav2_controller/include/nav2_controller/nav2_controller.hpp
nav2_controller/src/nav2_controller.cpp

| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/2262 |
| Robotic platform tested on | Wyca Elodie Sim |
---
This is a draft PR to support the discussion from here https://github.com/ros-planning/navigation2/issues/2262
Adds a `controller_patience` which makes the controller retry when for `computeVelocityCommands` throws an exception for the desired amount of second before failing. When equals to 0.0 the functionality is disabled. When equals to -1.0 the patience is infinite (the nav2_controller "FollowPath" action will likely fails thanks to the ProgressChecker though).
Edit: I meant ProgressChecker instead of GoalChecker

[Draft] [nav2_controller] Add controller_patience param

---

nav2_bringup/bringup/params/nav2_multirobot_params_1.yaml
nav2_bringup/bringup/params/nav2_multirobot_params_2.yaml

Same as ros-planning/navigation2#2287, but for foxy branch. 
Fairly trivial change - the multi-robot param files included in nav2_bringup used an invalid plugin name for nav2_recoveries/BackUp. 
The .yaml file used "back_up" where "backup" should have been used. This resulted in a Fatal Error when a multi-robot simulation is run with the recoveries_server. Removing the underscore fixes the issue.

corrected backup plugin name for multirobot params

---

nav2_costmap_2d/include/nav2_costmap_2d/clear_costmap_service.hpp
nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d.hpp
nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_publisher.hpp
nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp
nav2_costmap_2d/include/nav2_costmap_2d/costmap_filters/costmap_filter.hpp
nav2_costmap_2d/include/nav2_costmap_2d/costmap_filters/keepout_filter.hpp
nav2_costmap_2d/include/nav2_costmap_2d/costmap_filters/speed_filter.hpp
nav2_costmap_2d/include/nav2_costmap_2d/costmap_layer.hpp
nav2_costmap_2d/include/nav2_costmap_2d/costmap_math.hpp
nav2_costmap_2d/include/nav2_costmap_2d/costmap_subscriber.hpp
nav2_costmap_2d/include/nav2_costmap_2d/costmap_topic_collision_checker.hpp
nav2_costmap_2d/include/nav2_costmap_2d/exceptions.hpp
nav2_costmap_2d/include/nav2_costmap_2d/footprint_collision_checker.hpp
nav2_costmap_2d/include/nav2_costmap_2d/footprint_subscriber.hpp
nav2_costmap_2d/include/nav2_costmap_2d/inflation_layer.hpp
nav2_costmap_2d/include/nav2_costmap_2d/layer.hpp
nav2_costmap_2d/include/nav2_costmap_2d/layered_costmap.hpp
nav2_costmap_2d/include/nav2_costmap_2d/observation.hpp
nav2_costmap_2d/include/nav2_costmap_2d/obstacle_layer.hpp
nav2_costmap_2d/include/nav2_costmap_2d/range_sensor_layer.hpp
nav2_costmap_2d/include/nav2_costmap_2d/static_layer.hpp
nav2_costmap_2d/include/nav2_costmap_2d/voxel_layer.hpp

https://github.com/ros-planning/navigation2/issues/2155

adding doxygen to costmap_2d

---

nav2_bringup/bringup/worlds/waffle.model

Changed to the latest tire mesh file names for waffle as per the latest `turtlebot3_gazebo` package.
This results in faster loading and resolves the errors that come in `gazebo --verbose`

[nav2_bringup] Update waffle.model

---

nav2_bringup/bringup/worlds/waffle.model

See https://github.com/ros-planning/navigation2/pull/2296 for details
TB3 model has changed the file paths for the tires, requiring people to pull in the new changes `turtlebot3_simulation` repository if building locally. 
@ruffsl for CI, I don't see where it pulls `turtlebot3_simulation` to get these files, can you clarify for me? The underlay workspace doesn't include it and nor does `ros2 master`. We don't base on foxy so it can't be getting those binaries. 
Foxy users we tell to get the binaries in the build instructions. ROS2 main developers have a local copy. Its not clear to me where its coming from for CI. **Should we be including turtlebot3_simulation in the underlay?**

adjusting new files for tb3 model (ros2 of 2296)

---

nav2_bringup/bringup/launch/bringup_launch.py
nav2_bringup/bringup/launch/multi_tb3_simulation_launch.py
nav2_bringup/bringup/launch/navigation_launch.py
nav2_bringup/bringup/launch/tb3_simulation_launch.py
nav2_bringup/bringup/params/nav2_multirobot_params_1.yaml
nav2_bringup/bringup/params/nav2_multirobot_params_2.yaml
nav2_bringup/bringup/params/nav2_params.yaml

https://github.com/ros-planning/navigation2/issues/2270

audited and removed unnecessarily complex launch configurations

---

nav2_util/include/nav2_util/geometry_utils.hpp

---
| Robotic platform tested on | Wyca Elodie Sim |
---
This fix a SEG fault arising in `calculate_path_length` in case the path length is 0. It is due to negative unsigned integer comparison: https://stackoverflow.com/questions/7221409/is-unsigned-integer-subtraction-defined-behavior
---

[nav2_utils] Fix calculate_path_length SEG fault if size is 0

---

nav2_lifecycle_manager/src/lifecycle_manager_client.cpp

---
---
Switched RCLCPP_INFO to RCLCPP_DEBUG in `lifecycle_manager_client`. They are only messages about waiting and sending services to the lifecycle manager.
---

[nav2_lifecycle_manager] Reduce lifecycle manager client verbose

---

nav2_behavior_tree/nav2_tree_nodes.xml

| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/2312 |
---
expected behavior:

[nav2_behavior_tree] fix RemovePassedGoals Tree Node

---

nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d.hpp
nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp
nav2_costmap_2d/include/nav2_costmap_2d/layered_costmap.hpp
nav2_costmap_2d/src/clear_costmap_service.cpp
nav2_costmap_2d/src/costmap_2d.cpp
nav2_costmap_2d/src/costmap_2d_ros.cpp
nav2_costmap_2d/src/layered_costmap.cpp
nav2_costmap_2d/test/unit/CMakeLists.txt
nav2_costmap_2d/test/unit/copy_window_test.cpp
nav2_system_tests/src/costmap_filters/keepout_params.yaml
nav2_system_tests/src/costmap_filters/speed_global_params.yaml
nav2_system_tests/src/costmap_filters/speed_local_params.yaml

This fixes remaining "wings" artifacts from #2051 issue.
Wings artifacts appeared on the boundary window edges when costmap filters (e.g. `keepout_filter`) are being applied _after_ `inflation_layer`. The result of filter work at the `LayeredCostmap::updateMap()` stage is being merged into resulting costmap and on next `updateMap()` iterations treated as normal obstacles and finally being inflated inside boundary window which is causing "wings".
This can lead to such effects as shown in the picture below:
The proposed fix separates plugins and filters, applying plugins on `plugins_costmap_` and filters over the plugins, to usual `costmap_`. After fix applied, the resulting costmap looks like expected:
---
| Ticket(s) this …

[WIP] Fix for wings artifacts: adding new filters entity to separately update costmaps

---

nav2_bringup/bringup/launch/rviz_launch.py

---
This should be a pretty trivial change to avoid warnings when launching `rviz_launch.py` included in the bringup directory (discussed a bit over in ros2/rviz#671). Setting the Node name parameter remaps the name of all 4 nodes launched by `rviz_launch.py` to be the same name. This results in warnings on launch and when listing ros2 nodes. As far as I can tell, removing the name parameter does not affect behavior of the launch script and avoids the node name clash. 
| Robotic platform tested on | () |
---
- removed `name='rviz2'` from rviz_launch.py to eliminate duplicate node name warning
---
- This could be extended to other branches that include …

removed name parameter from rviz_launch.py

---

nav2_util/include/nav2_util/simple_action_server.hpp

---
| Ticket(s) this addresses   |#2273 |
| Robotic platform tested on |Turtlebot3 Simulation |
---
I added `is_publishing_succeeded_state_` and `is_handling_cancel_request_` to mark down current handling state. Make sure that `succeeded_current` and` cancel_handle` can not be handled simultaneously. And I also added `handle_state_mutex_` to protect the two variables.
1. I think all invailed state transformations should be avoided, such as `SUCCEEDED` to `CANCELING`, `ABORTED` to `CANCELING`, and so on. But It seems to be a little complicated to SimpleActionServer. 
2. I'm not sure if action server only run in one thread could be better. It seems that these problems are all caused by …

checking if handle is active in handle_cancel

---

nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager_client.hpp
nav2_lifecycle_manager/src/lifecycle_manager_client.cpp

In the process of removing all service nodes (#816).
After removing the service_node from lifecycle Manager (#2267), I propose an option to remove it from lifecycle Manager Clients.
---
| Ticket(s) this addresses   | #816 |
| Robotic platform tested on | Wyca robotics simulation and robot|
---
* I added the option to give a parent_node in the `LifecycleMangerClient` constructor to be used instead of creating a "_service_client" node.
* I used the `nav2_util::ServiceClient` for the implementation.

Open option to use parent node in lifecycle Manger Client

---

.circleci/config.yml
tools/code_coverage_report.bash

After the recent Codecov security incident[1] I've been reviewing
codecov usage across ROS repositories.
This repository is fetching the codecov bash uploader without performing
the recommended validation step.
The validation step does not appear to have been widely explained or
publicised and even the official codecov GitHub action was not
validating the script until the recent security incident.
I have made an attempt to validate the bash uploader here.
[1]: https://about.codecov.io/security-update/

Validate codecov script against checksums.

---

.circleci/config.yml
tools/code_coverage_report.bash

`local` in bash can only be used within a function context.
Fixes the regression reported in https://github.com/ros-planning/navigation2/pull/2330#issuecomment-837032101

Fix script error in codecov validation.

---

.gitignore
nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server.hpp
nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp
nav2_behavior_tree/test/plugins/action/CMakeLists.txt
nav2_behavior_tree/test/plugins/action/test_back_up_action.cpp
nav2_behavior_tree/test/plugins/action/test_bt_action_node.cpp
nav2_behavior_tree/test/plugins/action/test_clear_costmap_service.cpp
nav2_behavior_tree/test/plugins/action/test_compute_path_through_poses_action.cpp
nav2_behavior_tree/test/plugins/action/test_compute_path_to_pose_action.cpp
nav2_behavior_tree/test/plugins/action/test_follow_path_action.cpp
nav2_behavior_tree/test/plugins/action/test_navigate_through_poses_action.cpp
nav2_behavior_tree/test/plugins/action/test_navigate_to_pose_action.cpp
nav2_behavior_tree/test/plugins/action/test_reinitialize_global_localization_service.cpp
nav2_behavior_tree/test/plugins/action/test_spin_action.cpp
nav2_behavior_tree/test/plugins/action/test_wait_action.cpp
nav2_behavior_tree/test/plugins/condition/test_transform_available.cpp
nav2_behavior_tree/test/test_behavior_tree_fixture.hpp
nav2_bringup/bringup/params/nav2_multirobot_params_1.yaml
nav2_bringup/bringup/params/nav2_multirobot_params_2.yaml
nav2_bringup/bringup/params/nav2_params.yaml
nav2_rviz_plugins/src/nav2_panel.cpp
nav2_system_tests/src/behavior_tree/test_behavior_tree_node.cpp

---
| Ticket(s) this addresses   | #2280 |
| Robotic platform tested on | TurtleBot3 Gazebo simulation |
---
* `BtServiceNode` and `BtActionNode` use incremental timeout values in all `rclcpp::spin_until_future_complete` calls while waiting for the server to response to a request when the specified server timeout exceeds the BT execution loop rate. This ensures that `rclcpp::spin_until_future_complete` don't slow down BT execution if the server timeout has to be increased for whatever reason.
* Expose `bt_loop_timeout` and `default_server_timeout` as node parameters.
* Add `bt_loop_timeout` and `default_server_timeout` to …

Use incremental timeouts in spin_until_future_calls during BT execution to handle large server timeouts

---

nav2_rviz_plugins/include/nav2_rviz_plugins/nav2_panel.hpp
nav2_rviz_plugins/src/nav2_panel.cpp

---
| Ticket(s) this addresses   | #2255 |
| Robotic platform tested on | Turtlebot3 gazebo simulation |
---
* Added labels to display feedback information for `NavigateToPose` an `NavigateThroughPoses` actions to Nav2 Rviz panel.

Add action feedback information to nav2 rviz panel

---

.circleci/config.yml
Dockerfile

Change daily job for CI so it only triggers Docker Hub to rebuild CI image tags when there are dependencies to upgrade, specifically apt upgrades for installed ros2 packages. This helps preserve CI caches for longer, while ensuring the CI image remains up-to-date.
This is because an image timestamp is used in computing the cache key
https://github.com/ros-planning/navigation2/blob/1ab08ce555bea9304e291682ce6b6d141dc2fb14/.circleci/config.yml#L204-L206
The timestamp of this file is modified when building the image here:
https://github.com/ros-planning/navigation2/blob/1ab08ce555bea9304e291682ce6b6d141dc2fb14/Dockerfile#L101-L103
The above is done so CI caches are invalidated when CI images are updated, as new images could include API/ABI breaks from updated dependencies.

Rebuild CI images when there are dependency updates

---

.circleci/config.yml
.dockerhub/debug/hooks/build
.dockerhub/release/hooks/build
Dockerfile

This updates the CI to make use of colcon cache, a colcon extension that enables the caching of an entire workspace by tracking the state of package source files. This essentially allows the CI to focus on building and testing only packages that have been modified. For more info on colcon cache: https://github.com/ruffsl/colcon-cache/pull/12 . 
Changes in this PR to incorporate colcon cache include:
* Add cache key from main branch as a fallback cache to restore from
* now that invalid packages can be detected and rebuilt on demand with colcon cache 
* Cache only the build, install, log folders, not the entire workspace directory
* as not to include or restore the deterministic checksum files
* Hash underlay repos into checksum, rather than active workspace
* so that source file changes …

Update CI to use colcon cache

---

nav2_costmap_2d/test/unit/declare_parameter_test.cpp
nav2_util/include/nav2_util/node_utils.hpp

Since https://github.com/ros2/rclcpp/pull/1673, uninitialized parameters are allowed (ie. an exception is not thrown). Instead, if the parameter is not set by the time it is accessed, then an exception is thrown.
Note, this is a decision upstream to change this particular API for the upcoming Galactic release. Ultimately, we're hoping to avoid a deprecation cycle by landing this prior to the release date.

Update invalid parameter exception handling

---

nav2_amcl/src/amcl_node.cpp
nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_publisher.hpp
nav2_costmap_2d/include/nav2_costmap_2d/observation_buffer.hpp
nav2_costmap_2d/include/nav2_costmap_2d/range_sensor_layer.hpp
nav2_costmap_2d/plugins/costmap_filters/keepout_filter.cpp
nav2_costmap_2d/plugins/costmap_filters/speed_filter.cpp
nav2_costmap_2d/plugins/static_layer.cpp
nav2_costmap_2d/src/costmap_2d_ros.cpp
nav2_costmap_2d/test/integration/footprint_tests.cpp
nav2_dwb_controller/nav_2d_utils/include/nav_2d_utils/tf_help.hpp
nav2_lifecycle_manager/src/lifecycle_manager_client.cpp
nav2_recoveries/plugins/spin.cpp
nav2_rviz_plugins/include/nav2_rviz_plugins/nav2_panel.hpp
nav2_system_tests/src/recoveries/spin/spin_recovery_tester.hpp
nav2_util/include/nav2_util/geometry_utils.hpp
nav2_util/include/nav2_util/robot_utils.hpp

tf2_geometry_msgs.h was replaced by tf2_geometry_msgs.hpp in https://github.com/ros2/geometry2/pull/418.
tf2_sensor_msgs.h was replaced by tf2_sensor_msgs.hpp in https://github.com/ros2/geometry2/pull/416.
This PR overlaps with #2346, which replaces only `tf2_sensor_msgs.h`.

Replace deprecated headers

---

nav2_controller/src/nav2_controller.cpp

---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/2351 |
| Primary OS tested on | CI |
---
* Cleanup state resets map of goal checkers, not just resetting the current one
---

reset all goal checkers on cleanup state

---

nav2_bringup/nav2_gazebo_spawner/nav2_gazebo_spawner/nav2_gazebo_spawner.py

---
---
If namespace is empty, `ros_tf_remap.text` would be `/tf:=//tf`.

Fix nav2_gazebo_spawner not working while namespace is empty

---

.circleci/config.yml
.github/workflows/trigger_dockerhub.yaml

So for a recent PR https://github.com/ros-planning/navigation2/pull/2349 after merging https://github.com/ros-planning/navigation2/pull/2343 , I noticed that it's cache restore step was not finding the matching cache key provide by the main branch:
```
Creating cache archive...
Uploading cache archive...
Stored Cache to overlay_ws-v1-arch1-linux-amd64-6_85-main-<no value>-C8DP7DcUx71NZcYchPyQBH0ElDOZYfM4Uez8CyHmtNE=-1621429706
* /opt/overlay_ws/build
* /opt/overlay_ws/install
* /opt/overlay_ws/log
https://app.circleci.com/pipelines/github/ros-planning/navigation2/5359/workflows/9c999dde-f6c0-4007-b8a3-87d6e091638f/jobs/19741/parallel-runs/0/steps/0-118
```
```
No cache is found for key: overlay_ws-v1-arch1-linux-amd64-6_85-pull/2349-2349-C8DP7DcUx71NZcYchPyQBH0ElDOZYfM4Uez8CyHmtNE=
No …
```

Adjust CI to enable cache sharing with forked PRs

---

nav2_map_server/src/map_saver/main_cli.cpp

Fixes #2358
---
| Ticket(s) this addresses   | #2358  |
---
* Fixes `map_saver_cli` when parsing `--free` and `--occ` arguments.

Fix map_saver_cli arguments not parsed well

---

.github/workflows/trigger_dockerhub.yaml

To avoid notification noise from failed CI status when apt and ros packages change.

Trigger via env rather than on failure

---

.github/workflows/trigger_dockerhub.yaml

To avoid this:
https://github.com/ros-planning/navigation2/runs/2682686099

Initialize environment for when no trigger is tripped

---

nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp

---
| Ticket(s) this addresses   | #2303, #2305 |
| Robotic platform tested on | gazebo simulation|
---
- Checking `goal_handle_` if it is `nullptr`.
- If the `future_goal_handle_` is not `nullptr`, try to get `goal_handle_` in `result_callback`.

Fix SEGV caused by goal_handle_ which is nullptr while result_callback called

---

.circleci/config.yml
Dockerfile
tools/code_coverage_report.bash

Make use of `fastcov` to speed up CI:
https://github.com/RPGillespie6/fastcov

Use fastcov to speed up coverage for CI

---

nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp

---
| Ticket(s) this addresses   | Requested change from PR #2375  |
| Primary OS tested on | macOS |
---
Moves changes from PR #2375 that haven't been fixed in the past into galactic.

Move unmerged changes from #2375 into galactic

---

nav2_amcl/src/amcl_node.cpp
nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp
nav2_bt_navigator/src/ros_topic_logger.cpp
nav2_costmap_2d/include/nav2_costmap_2d/observation.hpp
nav2_costmap_2d/plugins/obstacle_layer.cpp
nav2_recoveries/include/nav2_recoveries/recovery.hpp
nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
nav2_util/src/dump_params.cpp
nav2_waypoint_follower/package.xml
smac_planner/src/a_star.cpp

| Ticket(s) this addresses   | Closes #2368 |
| Primary OS tested on | macOS |
---
- Foxy branch now builds on macOS, based on fixes from PR #2083! Proof of build on CI: https://github.com/nkalupahana/ros2-foxy-macos/runs/2698988683?check_suite_focus=true
---

Moves changes from PR #2083 to foxy

---

.circleci/config.yml
.dockerhub/builder/hooks/build
Dockerfile
tools/underlay.repos

Reverts parts of: https://github.com/ros-planning/navigation2/pull/2348
Depends on: https://github.com/osrf/docker_images/pull/542

Revert CI image to build from osrf/ros2:testing

---

.circleci/config.yml
.circleci/defaults.yaml
Dockerfile

Use the colcon clean extension to clean out stale build artifacts or test results for packages that are to be rebuilt or retested, preventing them from persisting in the cache cycle and accounting for when source files or tests are deleted or renamed.

Clean install and test result bases for stale packages

---

.circleci/config.yml
Dockerfile

Fixes issue with restoring ccache, introduced in https://github.com/ros-planning/navigation2/pull/2343 . This does so by setting the `CCACHE_DIR` to be inside the workspace (i.e. current working directory). This also has the benefit that each workspace now caches it's own ccache directory, and simplifies the number of specific steps.

Cache ccache folder in CI workspace

---

.circleci/config.yml

Update lockfile format to cleanly list versioned package dependencies for each workspace in a readable table format, and fix up environment so that rosdep correctly resolves apt installed dependencies.

Update lockfile formating

---

.circleci/config.yml

as ccache doesn't seem to work otherwise with relative paths.
Related: https://github.com/ros-planning/navigation2/pull/2401

Set ccache envs to use absolute paths

---

nav2_dwb_controller/nav_2d_utils/src/conversions.cpp
nav2_waypoint_follower/plugins/photo_at_waypoint.cpp
nav2_waypoint_follower/test/test_task_executors.cpp

---
| Ticket(s) this addresses   | None|
| Robotic platform tested on | None|
---
- Added filled image message data to _PhotoAtWaypoint_ test in order to test uncovered lines of **photo_at_waypoint.cpp** plugin
- Other tests might be necessary to get 100% coverage

Improve coverage for waypoint_follower package

---

nav2_rviz_plugins/src/nav2_panel.cpp

Resolves https://github.com/ros-planning/navigation2/issues/2383 to increase the base timeout for nav2 panel. If it reoccurs as an issue, we can add a parameterization. Ideally the nav2 panel is just a demo panel for people getting started or during basic testing. If we find that people want to use in a more real use-case, many more things should be parameterized.

Increase timeout for nav2 rviz panel clients to 100ms

---

nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp

---
| Ticket(s) this addresses   | #2408  |
| Primary OS tested on | Ubuntu 20.04 (docker) |
---
* New ability to override the default name of action node name
* Fixes #2408 
---

Allow separate naming of client action server nodes in bt navigator

---

codecov.yml
tools/code_coverage_report.bash

This mainly fixes the include filter to only look for the package name in the paths reported, as using package source paths can exclude coverage for files from other packages, such as header files reported using under workspace's install path.

Fix code coverage

---

nav2_costmap_2d/include/nav2_costmap_2d/observation.hpp

Also move constructor. Default copy assignment is not just a shortcut to copy constructor, sadly
---
| Ticket this addresses   | #2412) |
| Primary OS tested on | Ubuntu under WSL1 |
---
* Fixed bug with copy assignment being just a copy of all class fields, without proper `new` call for `sensor_msgs::msg::PointCloud2 * cloud_`
* Added move assignment and move constructor, because it's they are called inside `std::vector` with less (de)allocations
Teeeny changes:
* Changed description for copy assignment
* Added description for move assignment and move constructor
---
* I guess similar pulls for `crystal` and `main` braches should be done
* Maybe check if any other default defined …

Explicit assignment operators for Observation, default assignment is a bug here

---

nav2_controller/CMakeLists.txt
nav2_costmap_2d/CMakeLists.txt
nav2_dwb_controller/dwb_core/CMakeLists.txt
nav2_dwb_controller/dwb_critics/CMakeLists.txt
nav2_dwb_controller/dwb_plugins/CMakeLists.txt
nav2_navfn_planner/CMakeLists.txt
nav2_planner/CMakeLists.txt
nav2_recoveries/CMakeLists.txt
nav2_regulated_pure_pursuit_controller/CMakeLists.txt
nav2_rviz_plugins/CMakeLists.txt
nav2_smac_planner/CMakeLists.txt
nav2_waypoint_follower/CMakeLists.txt

Boost features have been deprecated and removed
in pluginlib for rolling
---
| Ticket(s) this addresses   |#2429|
---
* Removed compile definition `PLUGINLIB__DISABLE_BOOST_FUNCTIONS` as it has been deprecated for rolling (and galactic)
None required. Should be transparent to users.
---
None required.

Remove deprecated pluginlib boost feature disable

---

nav2_system_tests/src/system/CMakeLists.txt
nav2_system_tests/src/system/nav_to_pose_tester_node.py
nav2_system_tests/src/system/test_system_launch.py
nav2_system_tests/src/system/test_wrong_init_pose_launch.py

---
---
* Added invalid start position test to check NavFn planner behaviour

Improve coverage for NavFn package

---

nav2_waypoint_follower/include/nav2_waypoint_follower/waypoint_follower.hpp
nav2_waypoint_follower/src/waypoint_follower.cpp

---
| Ticket(s) this addresses   | (add tickets here #816) |
| Primary OS tested on |  (Ubuntu20.04, ROS 2 Galactic from binaries) |
| Robotic platform tested on | (gazebo simulation of  turtlebot3) |
---
This work is under project `Reduce ROS2 Nodes and Determinism` of OSPP2021.
As described in #816,  `client_node_` in `class WaypointFollower` need be removed, you can find more details(other nodes which need be removed) in https://github.com/ros-planning/navigation2/issues/816#issuecomment-876061677 
refer to https://github.com/ros-planning/navigation2/pull/2334, i remove `client_node_` by using callback groups / executors
* create new callback groups and executor 
* …

Reduce nodes for nav2_waypoint_follower 

---

nav2_bt_navigator/src/bt_navigator.cpp

Missing comma after bt node plugin name https://github.com/ros-planning/navigation2/blob/54911a701933f4613aef3f8f9cb62ac18975d907/nav2_bt_navigator/src/bt_navigator.cpp#L64

Add missing comma in bt_navigator plugin list

---

nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/regulated_pure_pursuit_controller.hpp
nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
nav2_regulated_pure_pursuit_controller/test/test_regulated_pp.cpp

---
| Ticket(s) this addresses   | #2327 #2427 |
| Robotic platform tested on | gazebo simulation of [Neobotix mp-400](https://github.com/neobotix/neo_simulation2.git) |
---
* I added this neat new feature for driving the robot using the RRP planner backwards. This enables car-like robots to efficiently perform the maneuvers using the SMAC planner. 
* Added new parameter "allow_reversing", so need to add that to default configs and documentation page
---
* I tested on a differential drive robot, but it will be great if someone can test it on an Ackermann drive!

 Feature addition: capability for the RRP to drive the robot backwards 

---

nav2_util/package.xml

https://github.com/ros-planning/navigation2/issues/2433

Adding launch_testing_ros dep on nav2 utils to install to fix dump tests

---

nav2_costmap_2d/src/footprint_collision_checker.cpp
nav2_smac_planner/include/nav2_smac_planner/collision_checker.hpp

| Ticket(s) this addresses   | #2457 |
| Robotic platform tested on | Physical & Simulated DiffDrive Robot |
---
* The collision checker of the Smac planner does not count INSCRIBED as a collision (infeasible path) anymore, allowing the robot footprint edges to touch inscribed grid cells. 
* Some early stopping on the `nav2_costmap_2d::FootprintCollisionChecker::footprintCost` and `::lineCost` were reduced to OCCUPIED cells.
* I would say none, as this is the expected behavior of the collision checker
---
None.

SMAC Planner: Treating "inscribed" costs not as collision anymore

---

nav2_map_server/src/map_saver/map_saver.cpp

---
-------
As described in [#816](https://github.com/ros-planning/navigation2/issues/816), `rclcpp_node_` in `class MapSaver` need be removed, you can find more details(other nodes which need be removed) in [#816 (comment)](https://github.com/ros-planning/navigation2/issues/816#issuecomment-876061677)
refer to …

Reduce map saver nodes

---

nav2_controller/src/nav2_controller.cpp

---
Add `costmap_thread_.reset()` on the destructor of ControllerServer class
I referred [this line](https://github.com/ros-planning/navigation2/blob/21a44bcb559682f67289ac72571206597c00855b/nav2_planner/src/planner_server.cpp#L70) of `nav2_planner` package.

Add costmap_thread_.reset() on the destructor of ControllerServer class

---

nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager.hpp
nav2_lifecycle_manager/src/lifecycle_manager.cpp
nav2_lifecycle_manager/src/main.cpp
nav2_util/include/nav2_util/node_thread.hpp
nav2_util/src/node_thread.cpp

---
| Primary OS tested on       | (Ubuntu20.04, ROS 2 Galactic)                  |
-------
As described in [#816](https://github.com/ros-planning/navigation2/issues/816), `bond_client_node_` in `class LifecycleManager` need be removed, you can find more details(other nodes which need be removed) in [#816 (comment)](https://github.com/ros-planning/navigation2/issues/816#issuecomment-876061677)
I use …

Reduce lifecycle manager nodes

---

nav2_bringup/nav2_gazebo_spawner/nav2_gazebo_spawner/nav2_gazebo_spawner.py

---
| Ticket(s) this addresses   | no ticket |
| Primary OS tested on | (Ubuntu 20.04) |
| Robotic platform tested on | Gazebo simulation,  turtlebot multi-robot simulation |
---
Use gazebo diff_drive plugin filename instead of the customized plugin name to allow correct spawn of any type of robot.
I used the comparison with filename "libgazebo_ros_diff_drive.so" because AFAIK there is no other gazebo diff_drive plugin than this one.
Can be merged with both foxy and galactic
---

allow spawn non turtlebot urdf

---

nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager_client.hpp
nav2_lifecycle_manager/src/lifecycle_manager_client.cpp
nav2_lifecycle_manager/test/test_bond.cpp
nav2_lifecycle_manager/test/test_lifecycle_manager.cpp
nav2_rviz_plugins/include/nav2_rviz_plugins/nav2_panel.hpp
nav2_rviz_plugins/src/nav2_panel.cpp
nav2_system_tests/src/updown/test_updown.cpp

---
-------
As described in [#816](https://github.com/ros-planning/navigation2/issues/816), `node_ ` in `class LifecycleManagerClient` need be removed, you can find more details(other nodes which need be removed) in [#816 …

Reduce lifecycle service client nodes

---

nav2_bringup/bringup/launch/multi_tb3_simulation_launch.py
nav2_bringup/nav2_gazebo_spawner/nav2_gazebo_spawner/nav2_gazebo_spawner.py
nav2_map_server/test/test_launch_files/map_saver_node.launch.py
nav2_simple_commander/nav2_simple_commander/demo_picking.py
nav2_simple_commander/nav2_simple_commander/robot_navigator.py
nav2_simple_commander/test/test_flake8.py
nav2_system_tests/src/costmap_filters/tester_node.py
nav2_system_tests/src/system/nav_through_poses_tester_node.py
nav2_system_tests/src/system/nav_to_pose_tester_node.py
nav2_system_tests/src/system/test_multi_robot_launch.py
nav2_system_tests/src/system_failure/tester_node.py
nav2_system_tests/src/waypoint_follower/tester.py
tools/bt2img.py

---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/pull/2411#issuecomment-863561181 |
---
As per @SteveMacenski's request: https://github.com/ros-planning/navigation2/pull/2411#issuecomment-863561181
---

Python string format

---

nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp

| Ticket(s) this addresses   | Related to PR #2410, addresses the issue explained in [this comment](https://github.com/ros-planning/navigation2/pull/2410#issuecomment-884317758) |
| Primary OS tested on | Ubuntu 20.04 ROS2 Galactic |
| Robotic platform tested on | Wyca Elodie robot (simulation) |
---
The PR #2410 aimed at getting an unique name for each BT client nodes, by adding the action name into the BT client node name.
Action names often come with namespaces, and so with "/" characters.
Let's say my action is named "/my_api/navigation/go_to_pose". With the PR #2410, the BT client node's name will be remapped to "bt_navigator/my_api/navigation/go_to_pose_rclcpp_node". 
Nodes can be namespaced, but a node has a name and a …

Naming BT client node after action name

---

nav2_recoveries/include/nav2_recoveries/recovery.hpp
nav2_util/include/nav2_util/simple_action_server.hpp

---
-------
improve `SimpleActionServer` 
* support two args  `options` and `group`  for action server ([rclcpp_action/create_server.hpp](https://github.com/ros2/rclcpp/blob/master/rclcpp_action/include/rclcpp_action/create_server.hpp#L57-L68))
* remove template `<typename nodeT = rclcpp::Node>` for `class SimpleActionServer`, and …

improve SimpleActionServer

---

nav2_bringup/bringup/launch/multi_tb3_simulation_launch.py
nav2_bringup/bringup/launch/tb3_simulation_launch.py
nav2_bringup/bringup/params/nav2_multirobot_params_1.yaml
nav2_bringup/bringup/params/nav2_multirobot_params_2.yaml
nav2_bringup/nav2_gazebo_spawner/nav2_gazebo_spawner/nav2_gazebo_spawner.py

---
| Ticket(s) this addresses   | #2446 |
| Primary OS tested on | (Ubuntu 20.04) |
| Robotic platform tested on | Foxy Gazebo multi-robot simulation) |
---
add libgazebo_ros_init.so in launch file and change groot ports in nav2_params so the costmaps are published and navigation starts for both robots.
---

fix nav2 params and launch file to publish Local and global costmaps in multi robots example

---

nav2_planner/src/planner_server.cpp

---
-------
As described in [#816](https://github.com/ros-planning/navigation2/issues/816), `rclcpp_node_` in `class PlannerServer` need be removed, you can find more details(other nodes which need be removed) in [#816 …

Reduce planner server nodes

---

nav2_controller/src/nav2_controller.cpp

---
-------
As described in [#816](https://github.com/ros-planning/navigation2/issues/816), `rclcpp_node_` in `class ControllerServer ` need be removed, you can find more details(other nodes which need be removed) in [#816 …

Reduce controller server nodes

---

nav2_smac_planner/include/nav2_smac_planner/smac_planner_2d.hpp
nav2_smac_planner/src/smac_planner_2d.cpp

---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/956|
| Robotic platform tested on | Wyca sim) |
---
I am starting to experiment with **SmacPlanner2D** and in order to work in our workflow, I need the tolerance parameter to be dynamic, which is what this PR is about.
---
Should we make other paremeters dynamic in **SmacPlanner2D** ? Though most of them would require re-initialization of several objects

[SmacPlanner2D] make tolerance parameter dynamic

---

nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp

---
| Ticket(s) this addresses   | #2467 |
| Robotic platform tested on | custom differential drive robot |
---
* Modified the `bt_service_node` to include an `on_success()` function, to process the service answer. 
* The additional `on_success()` function can be used to process the results send from the service server, to, for example, set the BT::NodeStatus of the behavior tree leave node
* The `on_success()` function was added. However, I am not sure if this needs to be documented somewhere. 
---
* So far I can't think of an additional on-function, which could be useful and which is not yet implemented.

Modify the BtServiceNode to include an on_success call.

---

nav2_map_server/test/component/test_map_saver_publisher.cpp

A trivial fix. It is a bug passing a string object to sprintf like variadic function.
I found it by building from source code with the tag (-Wnon-pod-varargs).

fix: bug of passing string to printf

---

nav2_smac_planner/src/a_star.cpp

---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/2494 |
| Robotic platform tested on | Wyca Elodie |
---
Solves https://github.com/ros-planning/navigation2/issues/2494 . 
Fully tested with smac2d planner. However as a_star is used for the hybrid version, it may have implications that I don't foresee (I did a basic sanity check with the hybrid though)
---

[Smac2d] Accept path of length 1

---

nav2_bringup/bringup/worlds/waffle.model

It looks like `camera_rgb_link` is now `camera_link` e3ee2da2d5a274b52d32fcdf7e270567ca1093d0
| Ticket(s) this addresses   | #2493 |
| Robotic platform tested on | none, Gazebo 11.5 |
Fix the `waffle.model` file
None
None

Fix #2493 by removing the unused joint to camera_rgb_frame

---

nav2_costmap_2d/include/nav2_costmap_2d/layered_costmap.hpp
nav2_costmap_2d/src/layered_costmap.cpp

---
| Ticket(s) this addresses   | #2508|
---
addPlugin() and resizeMap() can be executed concurrently.
std::vector is unsafe in multithreading.
---

fix data race: addPlugin() and resizeMap() can be executed concurrently

---

nav2_costmap_2d/plugins/voxel_layer.cpp

---
| Ticket(s) this addresses   | #2508 |
---
VoxelLayer::matchSize may be executed concurrently.
One path is from VoxelLayer::onInitialize();
the other path is from layered_costmap_->resizeMap() in static_layer.cpp.
---

fix data race: VoxelLayer::matchSize may be executed concurrently

---

nav2_costmap_2d/plugins/obstacle_layer.cpp

---
| Ticket(s) this addresses   | #2506 |
| Robotic platform tested on |  gazebo simulation turtlebot3) |
---
catch runtime_error from rclcpp if the message from laser is malformed.
---

catch runtime_error if the message from laser is malformed

---

nav2_smac_planner/src/a_star.cpp
nav2_smac_planner/test/test_a_star.cpp

---
| Ticket(s) this addresses   | #2515 |
---
Fixed bug that allowed a `std::bad_alloc` to be thrown by providing a `-1`, cast to `INT_MAX`, to `std::vector::reserve`
None
---
Single pose paths and zero length paths are still nonfunctional, but that is for another ticket.

Smac planner bad alloc

---

nav2_amcl/src/amcl_node.cpp
nav2_costmap_2d/plugins/obstacle_layer.cpp

---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/2333 |
| Robotic platform tested on | Elodie Wyca|
---
Use a timeout on the obstacle_layer message_filter. And use `transform_tolerance` to set its value since buffered message from the message_filter older than `transform_tolerance` would have been discarded later.
This effectively solves the controller_server being stuck with a very high CPU usage after few tf extrapolation errors
---

[ObstacleLayer] Use message_filter timeout

---

nav2_bringup/bringup/worlds/waffle.model

---
Remove the second `collision` node from `camera_link` in the `waffle.model`.
Fixes this Error:
```
[gzserver-1] [Msg] Loading world file [/opt/ros/foxy/share/nav2_bringup/worlds/waffle.model]
[gzserver-1] Error: Non-unique names detected in type collision in
[gzserver-1] <link name='camera_link'>
[gzserver-1]   <inertial>
[gzserver-1]     <pose>0.069 -0.047 0.107 0 -0 0</pose>
[gzserver-1]     <inertia>
[gzserver-1]       <ixx>0.001</ixx>
[gzserver-1]       <ixy>0</ixy>
[gzserver-1]       <ixz>0</ixz>
[gzserver-1]       <iyy>0.001</iyy>
[gzserver-1]       <iyz>0</iyz>
[gzserver-1] …
```

Remove second collision node from camera_link

---

nav2_controller/CMakeLists.txt
nav2_map_server/CMakeLists.txt
nav2_recoveries/CMakeLists.txt
nav2_waypoint_follower/CMakeLists.txt

---
| Ticket(s) this addresses   | #2147 |
| Primary OS tested on | - |
---
fix export dependency and library so that we can use nav2 packages correctly (for exmaple, used in `nav2_composition`).
---

Fix export dependency and library

---

nav2_amcl/include/nav2_amcl/amcl_node.hpp
nav2_amcl/src/amcl_node.cpp
nav2_bt_navigator/include/nav2_bt_navigator/bt_navigator.hpp
nav2_bt_navigator/src/bt_navigator.cpp
nav2_controller/include/nav2_controller/nav2_controller.hpp
nav2_controller/src/nav2_controller.cpp
nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager.hpp
nav2_lifecycle_manager/src/lifecycle_manager.cpp
nav2_map_server/include/nav2_map_server/map_saver.hpp
nav2_map_server/include/nav2_map_server/map_server.hpp
nav2_map_server/src/map_saver/map_saver.cpp
nav2_map_server/src/map_server/map_server.cpp
nav2_planner/include/nav2_planner/planner_server.hpp
nav2_planner/src/planner_server.cpp
nav2_recoveries/include/nav2_recoveries/recovery_server.hpp
nav2_recoveries/src/recovery_server.cpp
nav2_waypoint_follower/include/nav2_waypoint_follower/waypoint_follower.hpp
nav2_waypoint_follower/src/waypoint_follower.cpp

---
| Ticket(s) this addresses   | #2147 |
| Primary OS tested on | - |
---
add argument `rclcpp::NodeOptions` for Nav2 Nodes, so that we can configure Node in `main()`.
* for example, use `rclcpp::NodeOptions().use_intra_process_comms(true)` for intra-process communication in `nav2_composition`
---

Add argument node options

---

nav2_costmap_2d/src/costmap_subscriber.cpp

---
| Ticket(s) this addresses   | #2529 , #2510   |
---
fix potential use-after-free bug. The cause is much the same as #2510.
std::atomic_load() and std::atomic_store() require C++11.
---

fix possible use-after-free: unsafe shared_ptr in multithread

---

nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/regulated_pure_pursuit_controller.hpp
nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp

---
| Ticket(s) this addresses   | #2332  |
| Robotic platform tested on | mp-400 from Neobotix |
---
* Fixed the segfault issue that occurred when the robot was set to drive at high speed using RPP. 
NA
---
NA

Hot fix rrp slow

---

nav2_voxel_grid/include/nav2_voxel_grid/voxel_grid.hpp
nav2_voxel_grid/test/CMakeLists.txt
nav2_voxel_grid/test/voxel_grid_bresenham_3d.cpp

| Ticket(s) this addresses   | #2373 |
| Robotic platform tested on | TB3 simulation at shared in ticket pre-recorded dataset |
---
* Fix for floating point precision loss due to double->int->double conversions which are leading to incorrectly calculated data array ranges leading to out-of-array addressing causing segfaults on some configurations.
* (Additionally) Correct shift length reduction by min range components instead of absolute min range value.

Fix for voxel grid out-of-range issues due to loss of precision during floating-point calculations

---

nav2_costmap_2d/src/clear_costmap_service.cpp

Use `worldToMapEnforceBounds` in `clear_costmap_service` to avoid buffer overflow
Signed-off-by: zouyonghao <yonghaoz1994@gmail.com>
---
| Robotic platform tested on | gazebo simulation turtlebot |
---
I got buffer overflow when I call the clear_except_* service
```
=================================================================
==27609==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x620000005e90 at pc 0x0000005aaa2f bp 0x7f4eed79d2b0 sp 0x7f4eed79ca78
WRITE of size 60 at 0x620000005e90 thread T13
#0 0x5aaa2e in __asan_memset (/home/r1/ros2_clang_navigation/build/nav2_controller/controller_server+0x5aaa2e)
#1 0x7f4ef996d176 in …
```

Use worldToMapEnforceBounds in clear_costmap_service

---

nav2_smac_planner/include/nav2_smac_planner/smac_planner_2d.hpp
nav2_smac_planner/include/nav2_smac_planner/smac_planner_hybrid.hpp
nav2_smac_planner/src/smac_planner_hybrid.cpp
nav2_smac_planner/test/test_smac_hybrid.cpp

---
| Ticket(s) this addresses   | #956  |
| Primary OS tested on | Ubuntu 20.04|
| Robotic platform tested on | Personal Laptop |
---
* Added runtime configuration for Hybrid A* planner parameters
---

Enabled runtime configuration of parameters for Hybrid A*

---

nav2_amcl/src/amcl_node.cpp

---
| Ticket(s) this addresses   | (-) |
| Robotic platform tested on | (gazebo simulation of turtlebot3) |
---
```cpp
nav2_util::CallbackReturn
AmclNode::on_configure(const rclcpp_lifecycle::State & /*state*/)
{
// initMessageFilters is before initParticleFilter
initMessageFilters();
...
initParticleFilter();
return nav2_util::CallbackReturn::SUCCESS;
}
```
```cpp
void
AmclNode::initParticleFilter()
{
// pf_ is initialzed here, otherwise it is nullptr
pf_ = pf_alloc(
min_particles_, max_particles_, alpha_slow_, alpha_fast_,
(pf_init_model_fn_t)AmclNode::uniformPoseGenerator,
reinterpret_cast<void *>(map_));
}
```
```cpp
void
AmclNode::initMessageFilters()
{
...
laser_scan_connection_ = …
```

fix pf_ use-before-initialized in laserReceived() callback

---

nav2_amcl/src/amcl_node.cpp

---
| Ticket(s) this addresses   | (-) |
| Robotic platform tested on | (gazebo simulation of turtlebot3) |
---
A trivial fix. If resample_interval_ is set to zero,  `Floating point exception (core dumped)` would occur in the below code.
```cpp
void
AmclNode::laserReceived(sensor_msgs::msg::LaserScan::ConstSharedPtr laser_scan)
{
...
if (!(++resample_count_ % resample_interval_))
...
}
```

add semantic checks

---

nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp

---
| Info | Please fill out this column
| ----------- | ----------- |
| Ticket(s) this addresses   | #2538 |
---
Fix build failure (#2538) by replacing implicit deprecated type conversion from `rclcpp::Client::FutureAndRequestId` to `std::shared_future` with call to convenience method `FutureAndRequestId::share()`

Fix deprecated type conversion (#2538)

---

nav2_amcl/CMakeLists.txt
nav2_amcl/src/amcl_node.cpp
nav2_bt_navigator/CMakeLists.txt
nav2_bt_navigator/src/bt_navigator.cpp
nav2_controller/CMakeLists.txt
nav2_controller/src/nav2_controller.cpp
nav2_lifecycle_manager/CMakeLists.txt
nav2_lifecycle_manager/src/lifecycle_manager.cpp
nav2_map_server/CMakeLists.txt
nav2_map_server/src/map_saver/map_saver.cpp
nav2_map_server/src/map_server/map_server.cpp
nav2_planner/CMakeLists.txt
nav2_planner/src/planner_server.cpp
nav2_recoveries/CMakeLists.txt
nav2_recoveries/src/recovery_server.cpp
nav2_waypoint_follower/CMakeLists.txt
nav2_waypoint_follower/src/waypoint_follower.cpp

---
| Ticket(s) this addresses   |(tickets:  [#1013](https://github.com/ros-planning/navigation2/issues/1013)) |
| Primary OS tested on | -  |
| Robotic platform tested on |  -  |
---
Register Nav2 nodes as rclcpp components so that they could be launched in a same container (i.e. a single process).
---
add launch files to use component container （blocked by some problems）

Register nodes as components

---

nav2_theta_star_planner/README.md
nav2_theta_star_planner/include/nav2_theta_star_planner/theta_star_planner.hpp
nav2_theta_star_planner/src/theta_star_planner.cpp

---
---
This PR basically does the following:
- removing 'w_heuristic_cost_' from Nav2 Theta Star Planner as a user configurable parameter
- updates to nav2_theta_star_planner/README.md to remove its reference wherever applicable
- updates to nav2_theta_star_planner/src/theta_star_planner.cpp to set w_heuristic_cost as std::min(1.0, w_euc_cost_)
- fixed an incorrect check of whether the start and goal pose are the same in nav2_theta_star_planner/src/theta_star_planner.cpp, this was leading to runtime errors
removing the mention of w_heuristic_cost from Nav2 Theta Star Planner's docs, as it no longer user configurable
--- …

Updates to Nav2 Theta Star Planner docs

---

nav2_smac_planner/src/a_star.cpp
nav2_smac_planner/src/node_hybrid.cpp
nav2_smac_planner/src/smac_planner_hybrid.cpp

- Related issue: https://github.com/ros-planning/navigation2/issues/2547

Fixed vector::reserve exception in smac planner due to precision error

---

nav2_smac_planner/README.md

Tiny documentation change in the smac planner README. Looks like those two parameters were overlooked when adding the Lattice Node example. The [docu example](https://navigation.ros.org/configuration/packages/configuring-smac-planner.html) does not hold the redundant params.

removed redundant params in smac example

---

nav2_bringup/urdf/turtlebot3_waffle.urdf
nav2_bringup/worlds/waffle.model

1. Update uri(model://) of dae files for waffle model in waffle.model(Gazebo uses)
2. Update uri(package://) of dae files for turtlebot3_waffle.urdf(Rviz2
uses)
---
| Ticket(s) this addresses   | (add tickets here #2571 ) |
---
---

Fixed model loading issue with Gazebo and Rviz2

---

nav2_smac_planner/include/nav2_smac_planner/smac_planner_2d.hpp
nav2_smac_planner/src/smac_planner_2d.cpp

---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/956 |
| Robotic platform tested on | Wyca's Elodie|
---
As discussed here https://github.com/ros-planning/navigation2/issues/956

[Draft] Set parameters result example

---

nav2_bt_navigator/src/navigators/navigate_through_poses.cpp
nav2_bt_navigator/src/navigators/navigate_to_pose.cpp

---
| Ticket(s) this addresses   | #2663 |
| Robotic platform tested on | gazebo simulation of MPO-700 |
---
* Fixed the issue for setting the `default_nav_to_pose_bt_xml` in the yaml
NA
---
NA

Bug fix: set the BT Navigator "default_nav_to_pose_bt_xml" and "default_nav_through_pose_bt_xml" from the yaml file

---

nav2_amcl/src/amcl_node.cpp
nav2_costmap_2d/plugins/obstacle_layer.cpp

Backport #2518
