ros-navigation/navigation2

- nav2_smac_planner/include/nav2_smac_planner/node_hybrid.hpp
- nav2_smac_planner/src/node_hybrid.cpp
Issue: https://github.com/ros-planning/navigation2/issues/2676
> Corrected reinitialization in nav2_smac_planner::HybridMotionTable

- nav2_behavior_tree/include/nav2_behavior_tree/behavior_tree_engine.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
- nav2_behavior_tree/src/behavior_tree_engine.cpp
- nav2_bringup/params/nav2_multirobot_params_1.yaml
- nav2_bringup/params/nav2_multirobot_params_2.yaml
- nav2_bringup/params/nav2_params.yaml
- nav2_bt_navigator/src/bt_navigator.cpp
- nav2_system_tests/src/system/CMakeLists.txt
- nav2_system_tests/src/system/nav_to_pose_tester_node.py
- nav2_system_tests/src/system/test_system_launch.py
- nav2_system_tests/src/system/test_wrong_init_pose_launch.py
There have been near-endless tickets of issues regarding live groot monitoring, so we'll be removing it from Nav2 since it really hasn't worked out well since we introduced it. 
It was a great feature idea but never quite panned out, especially after we introduced multiple navigator types in the BT Navigator server. The issue we run into primarily is that Zero-MQ prevents users from producing multiple logger types in the same process. Since BT nav has multiple servers, the swapping between them for viewing has never had a clean hand off causing folks to file tickets or have nasty logs appear or ZMQ crashes in the background. The BT.CPP client for this doesn't allow us to have a clean shutdown process so we're left with hoping that ZMQ properly handles the situation, which it rarely does. …
> removing live groot monitoring from Nav2

- nav2_amcl/CMakeLists.txt
`ament_cmake_ros` dependency is added in #2642. This breaks build in our repository where navigation2 is dependency.
Looking at the changed in #2642 I am not sure why this dependency is added, or it is at least added wrongly because there should equivalent in the package.xml file and there is none.
Based on my experience working on 10+ CPP repositories with ROS2 I think the dependency is not necessary, therefore propose to remove it.
> Remove "wrong"/unnecessary dependency

- nav2_theta_star_planner/src/theta_star_planner.cpp
- nav2_theta_star_planner/test/test_theta_star.cpp
| Ticket(s) this addresses   | #2698 |
| Primary OS tested on |  Ubuntu |
| Robotic platform tested on | test code |
---
* fix the bug #2698, check if a plan is generated to avoid crash
* add test case if the goal is unsafe
> Theta star planner fix

- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/regulated_pure_pursuit_controller.hpp
- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
- nav2_regulated_pure_pursuit_controller/test/test_regulated_pp.cpp
https://github.com/ros-planning/navigation2/issues/2670
> [RPP] remove velocity scaling option (now required) and enable orientation sp projection times

- Dockerfile
Update to use latest fixes, including: https://github.com/ruffsl/colcon-cache/pull/26
> Version bump up colcon extensions

- nav2_costmap_2d/plugins/voxel_layer.cpp
---
| Ticket(s) this addresses   | #2692 |
| Primary OS tested on | (Ubuntu, Archlinux) |
| Robotic platform tested on | (turtlebot3 in gazebo) |
---
* With this fix we avoid calling `std::vector::front()` on an empty vector, which is undefined behavior and causes glibc asserts to fail in runtime. See the ticket for more info.
[none]
---
* Can be backported to galactic. Older releases are not affected.
> Always initialize clearing endpoints in voxel layer

- nav2_amcl/include/nav2_amcl/amcl_node.hpp
- nav2_amcl/src/amcl_node.cpp
Prohibit simultaneous usage of `pf_` shared object by possible callbacks. This will eliminate inconsistent data within `pf_`, (such as `pf_->sets[]->samples[]`) causing crashes of AMCL during "initialpose" and "laserscan" messages receiving at the same time (described in #2711)
---
| Ticket(s) this addresses   | #2711 |
| Primary OS tested on | Ubuntu 20.04 focal |
| Robotic platform tested on | Nav2 integrated tests |
> Prohibit of simultaneous usage of callbacks accessing to pf_ object

- nav2_smac_planner/src/node_lattice.cpp
https://github.com/ros-planning/navigation2/issues/2710
> One more observation (not tested): Shouldn't these three lines (521, 522, 523) be replaced by just neighbor->backwards(backwards); so that also an originally backward neighbor can be reset to a forward one?
> adding backwards state update

- .circleci/config.yml
"Each time you run the program, the execution counts are summed into any existing .gcda files, so be sure to remove any old files if you do not want their contents to be included."
https://llvm.org/docs/CommandGuide/llvm-cov.html
Example:
<details>
```
libgcov profiling error:/opt/overlay_ws/build/nav2_util/test/CMakeFiles/test_node_utils.dir/test_node_utils.cpp.gcda:overwriting an existing profile data with a different timestamp
libgcov profiling error:/opt/overlay_ws/build/nav2_util/src/CMakeFiles/nav2_util_core.dir/odometry_utils.cpp.gcda:overwriting an existing profile data with a different timestamp
libgcov profiling error:/opt/overlay_ws/build/nav2_util/src/CMakeFiles/nav2_util_core.dir/node_thread.cpp.gcda:overwriting an existing profile data with a different timestamp
libgcov …
```
> Clean .gcda files for invalidated package tests

- nav2_rotation_shim_controller/CMakeLists.txt
- nav2_rotation_shim_controller/README.md
- nav2_rotation_shim_controller/include/nav2_rotation_shim_controller/nav2_rotation_shim_controller.hpp
- nav2_rotation_shim_controller/nav2_rotation_shim_controller.xml
- nav2_rotation_shim_controller/package.xml
- nav2_rotation_shim_controller/src/nav2_rotation_shim_controller.cpp
- nav2_rotation_shim_controller/test/CMakeLists.txt
- nav2_rotation_shim_controller/test/test_shim_controller.cpp
- navigation2/package.xml
---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/2064 |
---
* Adds the rotation shim controller plugin, with near 100% test coverage, and readme documentation
* Also adds a tutorial
Needs
---
> adding shim rotation controller plugin

- nav2_smac_planner/README.md
- nav2_smac_planner/include/nav2_smac_planner/smoother.hpp
- nav2_smac_planner/include/nav2_smac_planner/types.hpp
- nav2_smac_planner/src/smac_planner_2d.cpp
- nav2_smac_planner/src/smac_planner_hybrid.cpp
- nav2_smac_planner/src/smac_planner_lattice.cpp
- nav2_smac_planner/src/smoother.cpp
- nav2_smac_planner/test/CMakeLists.txt
- nav2_smac_planner/test/test_nodelattice.cpp
- nav2_smac_planner/test/test_smoother.cpp
Addresses
- https://github.com/ros-planning/navigation2/issues/2690 -- smoother issues
Docs PR
- https://github.com/ros-planning/navigation.ros.org/pull/249
TODO
> Smoother feasbility

- .github/workflows/update_ci_image.yaml
- Dockerfile
using --with-new-pkgs flag.
This ensures all packages in CI image are updated, preventing the Update CI Image workflow from needlessly retriggering and rebuilding the images due packages otherwise having been kept back.
https://unix.stackexchange.com/a/241062/213124
> Apt upgrade with new pkgs

- nav2_regulated_pure_pursuit_controller/README.md
- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/regulated_pure_pursuit_controller.hpp
- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
- nav2_regulated_pure_pursuit_controller/test/test_regulated_pp.cpp
Handles https://github.com/ros-planning/navigation2/issues/2670
Dos PR: https://github.com/ros-planning/navigation.ros.org/pull/253
>  RPP max lookahead collision detection time limited by lookahead point itself

- nav2_bringup/rviz/nav2_default_view.rviz
Fixes the visualization issues in https://github.com/ros-planning/navigation2/issues/2720, however warnings still appear in Rolling binaries
> allowing rviz to visualize laser scans again with rolling binaries

- nav2_smac_planner/README.md
---
| Ticket(s) this addresses   | (add tickets here #2775 ) |
| Robotic platform tested on | (have nothing to do with them) |
---
* I fixed tiny misspelled word in [smac_planner's readme](https://github.com/ros-planning/navigation2/tree/main/nav2_smac_planner#parameters)
---
> Fix : misspelling in smac_planner's readme

- nav2_controller/include/nav2_controller/controller_server.hpp
- nav2_controller/src/controller_server.cpp
Signed-off-by: Erik Örjehag <erik@orjehag.se>
| Robotic platform tested on | (gazebo simulation of other diff drive robot) |
* Move tf lookup of goal pose in nav2_controller from `setPlannerPath` to `isGoalReached`. This is needed because the local planner will otherwise have a much more recently transformed goal compared to the goal checker causing the local planner to stop when it has reached its goal but the goal checker will not trigger (we use pure pursuit). If setPlannerPath is called with 1Hz this is barely noticeable but we have a different behavior tree that only plans when we have a new goal (and in the future we'll try to check if the plan in …
> Bugfix tf lookup of goal pose in nav2_controller

- nav2_simple_commander/nav2_simple_commander/robot_navigator.py
> added planner_id

- nav2_bringup/bringup/params/nav2_multirobot_params_1.yaml
- nav2_bringup/bringup/params/nav2_multirobot_params_2.yaml
Fix to https://github.com/ros-planning/navigation2/issues/2719 and answer to
https://answers.ros.org/question/394711/nav2-multi_tb3_simulation_launchpy-cannot-get-plugin-param-value-for-wait_at_waypoint/
---
| Ticket(s) this addresses   | #2719 |
| Robotic platform tested on | Gazebo simulation of TB3 in `turtlebot3_world` |
---
* Fixed missing parameters name in `nav2_bringup` for `galactic`
* Instructions for multi-robot simulation with independent Nav2 stacks could be added to the "Getting Started" page (https://navigation.ros.org/getting_started/index.html)
---
* I think robots ignore each other and possibly collide even if they can sense each other - dynamic obstacles avoidance is …
> Correct params for multi_tb3_simulation_launch.py (galactic)

- nav2_simple_commander/package.xml
The enum module was added in PEP 435 and is present in Python versions 3.4 and newer, which includes all currently supported Python versions.
Additionally, this `rosdep` [is a Python 2 package](https://github.com/ros/rosdistro/blob/685c61ca135f9c80f25be50e93db683837bc7546/rosdep/python.yaml#L1589-L1598), where ROS 2 targets Python 3.
---
* Drop unneeded dependency on python-enum34
N/A
---
N/A
> Drop unneeded dependency on python-enum34

- nav2_costmap_2d/include/nav2_costmap_2d/inflation_layer.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/static_layer.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/voxel_layer.hpp
- nav2_costmap_2d/plugins/inflation_layer.cpp
- nav2_costmap_2d/plugins/obstacle_layer.cpp
- nav2_costmap_2d/plugins/static_layer.cpp
- nav2_costmap_2d/plugins/voxel_layer.cpp
- nav2_costmap_2d/test/integration/inflation_tests.cpp
- nav2_costmap_2d/test/integration/obstacle_tests.cpp
---
| Ticket(s) this addresses   | ros-planning#956 |
| Robotic platform tested on | Turtlebot3 simulation |
---
* Dynamic parameter setting callbacks are added in the layers using suitable mutexes to prevent segfaults
* Decision on whether parameters are settable/non-settable dynamically are taken after referring to these layers in the ROS1 nav stack and warning messages are added wherever parameter setting is rejected
* Appropriate functions are called after dynamic parameter changes (also referring to the ROS1 nav stack)
* Changes are tested on the turtlebot3 simulation
* Suitable test cases are added to test parameter setting
---
> Dynamic parameter setting of costmap layers (inflation/static/voxel)

- nav2_bt_navigator/include/nav2_bt_navigator/bt_navigator.hpp
- nav2_bt_navigator/include/nav2_bt_navigator/navigator.hpp
- nav2_bt_navigator/include/nav2_bt_navigator/navigators/navigate_through_poses.hpp
- nav2_bt_navigator/include/nav2_bt_navigator/navigators/navigate_to_pose.hpp
- nav2_bt_navigator/src/bt_navigator.cpp
- nav2_bt_navigator/src/navigators/navigate_through_poses.cpp
- nav2_bt_navigator/src/navigators/navigate_to_pose.cpp
Signed-off-by: Alberto Soragna <alberto.soragna@gmail.com>
There's an unused `OdomSmoother` object in the BT Navigator code.
Removing it to avoid creation of unnecessary subscription.
> remove unused odometry smoother in bt navigator

- nav2_bt_navigator/include/nav2_bt_navigator/bt_navigator.hpp
- nav2_bt_navigator/include/nav2_bt_navigator/navigator.hpp
- nav2_bt_navigator/src/bt_navigator.cpp
Signed-off-by: wep21 <border_goldenmarket@yahoo.co.jp>
---
---
* modify build failure of nav2 bt navigator
---
> fix: modify build failure of nav2 bt navigator

- nav2_simple_commander/README.md
- nav2_simple_commander/nav2_simple_commander/robot_navigator.py
---
| Ticket(s) this addresses   | #2415 |
---
* Added optional arguments for action requests
* PR includes docs changes in this package
* Docs in navigation.ros.org also need updating
---
> Add all action options

- .circleci/config.yml
- Dockerfile
- tools/distro.Dockerfile
- tools/source.Dockerfile
---
| Ticket(s) this addresses   | #2813  |
| Primary OS tested on | NA |
---
This is a hotfix to run CI on `ros:rolling-ros-base-focal` while `ros:rolling` is unstable during the transition to Ubuntu 22.04. This circumvents the rosdep keys being updated by avoiding calls to `rosdep update`.
None
---
Revert this change when everything is ready to build on Ubuntu 22.04.
> Ci focal rolling

- nav2_costmap_2d/src/footprint_collision_checker.cpp
---
| Robotic platform tested on | ClearPath Dingo |
---
* LETHAL_OBSTACLE must be captured and returned before UNKNOWN
NA
---
NA
> fix- Hybrid smac planner plans in collision in case of unknown cost

- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d.hpp
- nav2_costmap_2d/test/CMakeLists.txt
- nav2_costmap_2d/test/regression/CMakeLists.txt
- nav2_costmap_2d/test/regression/costmap_bresenham_2d.cpp
Partial back-port of #2460 and #2784 fixes from 3D version of `raytraceLine()`/`bresenham3D()` (from `voxel_grid.hpp`) to its 2D version of algorithms (in `costmap_2d.hpp`).
---
| Ticket(s) this addresses   | #2835 |
| Primary OS tested on | Ubuntu focal |
| Robotic platform tested on | TB3 standard simulation |
---
* Correct shift length reduction by min range components instead of absolute min range value
* Fix for issues if start point equals to end point in `raytraceLine()`
---
> Apply raytraceLine 3D fixes to its 2D version

- nav2_dwb_controller/dwb_core/src/trajectory_utils.cpp
- nav2_dwb_controller/nav_2d_utils/src/conversions.cpp
- nav2_map_server/test/component/test_map_saver_node.cpp
- nav2_map_server/test/component/test_map_server_node.cpp
- nav2_smac_planner/include/nav2_smac_planner/node_lattice.hpp
- nav2_waypoint_follower/plugins/input_at_waypoint.cpp
- nav2_waypoint_follower/plugins/photo_at_waypoint.cpp
- nav2_waypoint_follower/plugins/wait_at_waypoint.cpp
---
---
Update include order to pass cpplint on rolling. Cpplint on rolling is smarter now, so we can actually follow the [Google Style Guide for include order](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes).
None
---
None
> Fix cpplint include order errors

- nav2_costmap_2d/test/regression/costmap_bresenham_2d.cpp
Minor test optimizations/fixups for 2D `raytraceLine()` costmap_bresenham_2d test
---
| Ticket(s) this addresses   | #2835 |
| Robotic platform tested on | `colcon test` for nav2_cosmap_2d |
---
* Corrected `(sz_x, y)` array edge index check
* Test code optimized
---
> Additional revision for costmap_bresenham_2d test

- nav2_amcl/src/amcl_node.cpp
- nav2_bringup/params/nav2_params.yaml
Signed-off-by: Harshal Deshpande <hardesh1deshpande@gmail.com>
---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation.ros.org/pull/284 |
| Primary OS tested on | Ubuntu) |
| Robotic platform tested on | gazebo simulation of Turtlebot) |
---
- Fixed first_map_only parameter issue in AMCL
- Updated its documentation in the docs repo. PR is mentioned in the above table
---
> Fixed first_map_only parameter issue

- nav2_costmap_2d/plugins/obstacle_layer.cpp
- nav2_costmap_2d/plugins/voxel_layer.cpp
| Robotic platform tested on | Unity simulated Jackal |
---
* Improve the error messages in the costmap layers to say WHY the origin was out of bounds
* None
> Better Costmap Error Message

- nav2_controller/src/controller_server.cpp
---
| Ticket(s) this addresses   | #2833 |
| Primary OS tested on | Debian |
| Robotic platform tested on | gazebo simulation|
---
* Don't cause a deadlock when we try to dynamically change controller
parameters while the controller is running.
* Also provide a appropriate
error message on failure to change parameters.
Shouldn't be necessary
* Maybe add correct handling of dynamic parameter changes to the plugins
> nav2_controller: stop mutex from deadlocking on parameter change

- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp
---
| Robotic platform tested on | Wyca Elodie |
---
Added `getRobotRadius()` to `costmap_2d_ros` in a similar fashion to `getUseRadius()` (and to complete it).
This was missing if one needed to accurately get the footprint when it is defined as a circle (for instance to be able to manipulate it, think inflation). When it is defined as a circle, a polygonial footprint is interpolated, hence the loss of precision (but the information that it was generated from a circle was already there).
---
> add getRobotRadius() in costmap_2d_ros

- nav2_msgs/action/BackUp.action
- nav2_msgs/action/ComputePathThroughPoses.action
- nav2_msgs/action/ComputePathToPose.action
- nav2_msgs/action/DummyBehavior.action
- nav2_msgs/action/FollowPath.action
- nav2_msgs/action/FollowWaypoints.action
- nav2_msgs/action/NavigateThroughPoses.action
- nav2_msgs/action/NavigateToPose.action
- nav2_msgs/action/SmoothPath.action
- nav2_msgs/action/Spin.action
- nav2_msgs/action/Wait.action
Just a very small change in the `nav_msgs`, that would allow a very new user for ROS-2 to easily find out the details of the interfaces that we provide.
> Adding the missing "feedback definition" for the action interface 

- nav2_dwb_controller/nav_2d_utils/include/nav_2d_utils/parameters.hpp
Fixes #2916.
Moreover, I double-checked the snipped that was included in the TODO right above, and realized that was referring to old ROS API. For me, it had no more meaning in this context, but maybe @crdelsey can tell if it's right to do this clean up or not.
> Allow usage of std::string in searchAndGetParam()

- nav2_regulated_pure_pursuit_controller/CMakeLists.txt
- nav2_regulated_pure_pursuit_controller/package.xml
- nav2_regulated_pure_pursuit_controller/test/CMakeLists.txt
- nav2_regulated_pure_pursuit_controller/test/test_regulated_pp.cpp
- nav2_rviz_plugins/CMakeLists.txt
- nav2_smac_planner/src/a_star.cpp
---
---
Fix a bunch of small issues found while compiling against Rolling on Ubuntu 22.04.
None needed.
---
N/A
> Fix various issues found while compiling against Rolling on Ubuntu 22.04

- nav2_simple_commander/README.md
- nav2_simple_commander/nav2_simple_commander/robot_navigator.py
---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/2923 |
---
- Removes an unwanted warning
- Enables controlled release of resources
---
> Clean up action clients in nav2_simple_commander

- nav2_regulated_pure_pursuit_controller/README.md
Minor fix of RPP README that was accidentally forgot in https://github.com/ros-planning/navigation2/pull/2631 and left me with confusion.
> removed linear kinematic params from RPP Readme

- nav2_amcl/include/nav2_amcl/amcl_node.hpp
- nav2_amcl/src/amcl_node.cpp
---
| Ticket(s) this addresses   | (#2931 ) |
| Primary OS tested on | Ubuntu 20.04.3 LTS |
---
Fixed Segmentation Fault happening in map_calc_range() if new laserscans were processed during a map change event.
This was done by adding ```configuration_mutex_``` lock on laserscan callback. Mutex lock has been added also to other methods accordingly to ROS Noetic implementation
none
---
> Added mutex to prevent SEGFAULT on map change in AMCL

- nav2_bt_navigator/include/nav2_bt_navigator/navigator.hpp
| Ticket(s) this addresses   | [#2946](https://github.com/ros-planning/navigation2/issues/2946) |
---
When an initial goal is received, the plugin muxer only calls startNavigating() if goalReceived() returns true. This will allow the client to try sending another goal if the initial goal is not accepted by the server rather than being stuck 
None
---
> Added goal accepted check before flagging navigator as running

- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/navigate_through_poses_action.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/navigate_to_pose_action.hpp
- nav2_behavior_tree/nav2_tree_nodes.xml
- nav2_behavior_tree/plugins/action/navigate_through_poses_action.cpp
- nav2_behavior_tree/plugins/action/navigate_to_pose_action.cpp
---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/pull/1784#issuecomment-1086153629 |
| Robotic platform tested on | Own gazebo simulation |
---
The NavigateToPose Action server [accepts a behavior tree as input](https://github.com/ros-planning/navigation2/blob/609342fa27016a1677768f93fb3c44dec98b1f55/nav2_bt_navigator/src/navigators/navigate_to_pose.cpp#L89) but its corresponding [BT action node ](https://navigation.ros.org/configuration/packages/bt-plugins/actions/NavigateToPose.html)does not have a behavior_tree option. I added the behavior_tree option
* Added new parameter, so need to add that to default configs and documentation page
---
> Added behaviour_tree as input to action nodes

- nav2_behavior_tree/include/nav2_behavior_tree/plugins/decorator/path_longer_on_approach.hpp
The current version (Tue May 10 12:16:24 2022 -0700) breaks when building using `colcon` on `rolling`. 
There are missing dependencies on `include/nav2_behavior_tree/plugins/decorator/path_longer_on_approach.hpp`
---
| Robotic platform tested on | NA|
---
> Building breaks using colcon on rolling.

- nav2_lifecycle_manager/src/lifecycle_manager.cpp
---
| Ticket(s) this addresses   | #2917 |
| Robotic platform tested on | Tested by @AlexeyMerzlyakov |
---
* Fixed lifecycle manager startup failure with FastRTPS which was caused by an [rclcpp bug](https://github.com/ros2/rclcpp/issues/1611) whose fix hasn't been merged yet
* No updates needed
---
* Can be reverted after ros2/rclcpp#1640 has been merged
> Fixed lifecycle manager startup (#2917)

- .circleci/config.yml
- Dockerfile
- tools/distro.Dockerfile
- tools/source.Dockerfile
- tools/underlay.repos
---
| Ticket(s) this addresses   | #2813  |
| Primary OS tested on | NA |
---
This is a hotfix to run CI on `ros:rolling` during the transition to Ubuntu 22.04. This circumvents the missing gazebo package by installing gazebo11 from upstream and compiling gazebo_ros from source in the underlay. It also installs python3.9-dev as a work-around for jammy migration to python3.10.
Alternatives: 
- https://github.com/ros-planning/navigation2/pull/2851
None
---
Revert this change when everything is ready to build on Ubuntu 22.04.
> Ci jammy rolling

- nav2_amcl/include/nav2_amcl/amcl_node.hpp
- nav2_amcl/src/amcl_node.cpp
---
| Primary OS tested on       | (Ubuntu20.04, ROS 2 Galactic)                  |
-------
As described in [#816](https://github.com/ros-planning/navigation2/issues/816), `rclcpp_node_` in `class AmclNode` need be removed, you can find more details(other nodes which need be removed) in [#816 (comment)](https://github.com/ros-planning/navigation2/issues/816#is …
> Reduce amcl_node nodes

- nav2_amcl/src/amcl_node.cpp
this was a stupid mistake from https://github.com/ros-planning/navigation2/pull/2483. i don't know why it can be compiled without error.
> fix tf_broadcaster in amcl_node

- nav2_bringup/launch/bringup_launch.py
- nav2_bringup/launch/localization_launch.py
- nav2_bringup/launch/navigation_launch.py
- nav2_simple_commander/nav2_simple_commander/robot_navigator.py
- nav2_smac_planner/test/test_a_star.cpp
- nav2_system_tests/src/costmap_filters/CMakeLists.txt
- nav2_system_tests/src/costmap_filters/keepout_params.yaml
- nav2_system_tests/src/costmap_filters/speed_global_params.yaml
- nav2_system_tests/src/costmap_filters/speed_local_params.yaml
- nav2_system_tests/src/costmap_filters/test_keepout_launch.py
- nav2_system_tests/src/costmap_filters/test_speed_launch.py
- nav2_system_tests/src/system/nav_to_pose_tester_node.py
> fix some tests

- nav2_controller/include/nav2_controller/plugins/simple_goal_checker.hpp
- nav2_controller/include/nav2_controller/plugins/stopped_goal_checker.hpp
- nav2_controller/plugins/simple_goal_checker.cpp
- nav2_controller/plugins/stopped_goal_checker.cpp
- nav2_controller/plugins/test/goal_checker.cpp
- nav2_controller/src/controller_server.cpp
- nav2_core/include/nav2_core/goal_checker.hpp
- nav2_rotation_shim_controller/test/test_shim_controller.cpp
Addresses https://github.com/ros-planning/navigation2/issues/2939 
Tested the build with ROS2 Humble
> Added costmap in goal_checker plugins

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/follow_path_action.hpp
- nav2_behavior_tree/plugins/action/follow_path_action.cpp
---
| Ticket(s) this addresses   | #2958 |
| Robotic platform tested on | Gazebo simulation of turtlebot3 |
---
* `nav2_behavior_tree::BtActionNode::on_wait_for_result(feedback)` allows access to a shared_ptr to the latest feedback message
---
> Allow access to action feedback in nav2_behavior_tree::BtActionNode::on_wait_for_result

- nav2_constrained_smoother/include/nav2_constrained_smoother/constrained_smoother.hpp
- nav2_constrained_smoother/src/constrained_smoother.cpp
- nav2_core/include/nav2_core/controller.hpp
- nav2_core/include/nav2_core/smoother.hpp
- nav2_dwb_controller/dwb_core/include/dwb_core/dwb_local_planner.hpp
- nav2_dwb_controller/dwb_core/src/dwb_local_planner.cpp
- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/regulated_pure_pursuit_controller.hpp
- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
- nav2_rotation_shim_controller/include/nav2_rotation_shim_controller/nav2_rotation_shim_controller.hpp
- nav2_rotation_shim_controller/src/nav2_rotation_shim_controller.cpp
- nav2_smoother/include/nav2_smoother/simple_smoother.hpp
- nav2_smoother/src/simple_smoother.cpp
- nav2_smoother/test/test_smoother_server.cpp
---
| Ticket(s) this addresses   | #2966 |
| Robotic platform tested on | Gazebo simulation of turtlebot3 |
---
* Changed all `const shared_ptr &` references to `shared_ptr`s so counter increment takes place properly
---
> Change all shared_ptr references to shared_ptr

- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp
- nav2_costmap_2d/src/costmap_2d_ros.cpp
replace raw pointer with unique_ptr.
> use unique_ptr for map_update_thread

- nav2_lifecycle_manager/CMakeLists.txt
- nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager.hpp
- nav2_lifecycle_manager/package.xml
- nav2_lifecycle_manager/src/lifecycle_manager.cpp
---
| Ticket(s) this addresses   | #2984 |
| Robotic platform tested on |Turtlebot gazebo simulation |
---
* I added diagnostics publishing for the lifecycle state of the nodes
* Not sure, let me know if I should add docs
---
* Maybe more elaborate diagnostics
> Add diagnostics

- nav2_amcl/src/amcl_node.cpp
- nav2_behaviors/src/behavior_server.cpp
- nav2_bt_navigator/src/bt_navigator.cpp
- nav2_controller/src/controller_server.cpp
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp
- nav2_costmap_2d/src/costmap_2d_ros.cpp
- nav2_costmap_2d/test/integration/inflation_tests.cpp
- nav2_costmap_2d/test/integration/test_costmap_topic_collision_checker.cpp
- nav2_costmap_2d/test/testing_helper.hpp
- nav2_map_server/src/map_saver/map_saver.cpp
- nav2_map_server/src/map_server/map_server.cpp
- nav2_planner/src/planner_server.cpp
- nav2_smoother/src/nav2_smoother.cpp
- nav2_util/include/nav2_util/lifecycle_node.hpp
- nav2_util/src/lifecycle_node.cpp
- nav2_util/test/test_lifecycle_node.cpp
- nav2_waypoint_follower/src/waypoint_follower.cpp
---
| Robotic platform tested on | (gazebo simulation of turtlebot3) |
---
this is a final PR to solve https://github.com/ros-planning/navigation2/issues/816
* remove LifecycleNode's argument `use_rclcpp_node` and member `rclcpp_node_` which is unused currently.
* update the construction function of some nodes which derived from LifecycleNode.
* update `test_costmap_topic_collision_checker.cpp` which use  `rclcpp_node_` (like https://github.com/ros-planning/navigation2/pull/2489).
update migration documentation : …
> remove LifecycleNode's argument use_rclcpp_node

- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
* fix: correct curvature signal
Signed-off-by: Afonso da Fonseca Braga <afonso.braga@engenharia.ufjf.br>
* cleanup: move sign's position
Signed-off-by: Afonso da Fonseca Braga <afonso.braga@engenharia.ufjf.br>
---
| Ticket(s) this addresses   | Backport PR https://github.com/ros-planning/navigation2/pull/2979|
| Robotic platform tested on | Gazebo Tricycle |
---
Hi! Thanks for approving the other PR! I would like to backport it to the galactic branch too. :smile: 
Backporting from https://github.com/ros-planning/navigation2/pull/2979
---
> Backport_galactic: correct curvature signal on RPP (#2979)

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
- nav2_bt_navigator/include/nav2_bt_navigator/navigator.hpp
- nav2_bt_navigator/include/nav2_bt_navigator/navigators/navigate_through_poses.hpp
- nav2_bt_navigator/include/nav2_bt_navigator/navigators/navigate_to_pose.hpp
- nav2_bt_navigator/src/navigators/navigate_through_poses.cpp
- nav2_bt_navigator/src/navigators/navigate_to_pose.cpp
---
| Ticket(s) this addresses   | [2991](https://github.com/ros-planning/navigation2/issues/2991) |
---
Added input parameter 'final_bt_status' of type nav2_behavior_tree::BtStatus to the goalCompleted() function of navigator.hpp that makes the final status of the behavior tree run available to the navigator. This could provide the navigator with important context while populating the result and doing anything else it might do during that function.
None of the navigators that are included in nav2 currently do anything with this goalCompleted() function, but this could be a nice feature for developers who are creating their own custom navigators, and …
> Provide bt result

- nav2_bt_navigator/src/navigators/navigate_through_poses.cpp
- nav2_costmap_2d/plugins/inflation_layer.cpp
- nav2_planner/src/planner_server.cpp
- nav2_waypoint_follower/src/waypoint_follower.cpp
---
| Ticket(s) this addresses   | #3002 |
| Primary OS tested on | Ubuntu on arm32 (qemu) |
---
- This patch uses a portable string format specifier for size_t (%zu) to replace non-generic specifiers (%lu, %li)
- This patch is necessary (and sufficient) for building navigation2 on arm32 machines
---
> Fix size_t format specifier

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
- nav2_bringup/params/nav2_multirobot_params_1.yaml
- nav2_bringup/params/nav2_multirobot_params_2.yaml
- nav2_bringup/params/nav2_params.yaml
- nav2_system_tests/src/costmap_filters/keepout_params.yaml
- nav2_system_tests/src/costmap_filters/speed_global_params.yaml
- nav2_system_tests/src/costmap_filters/speed_local_params.yaml
---
after some internal `rclcpp_node_`, `client_node_` are removed (https://github.com/ros-planning/navigation2/issues/816), params files should be cleared up.
* remove unused `_rclcpp_node` and `_client` in params file.
* correct name of `rclcpp_node` for `BtActionServer`: add '_', and add `bt_navigator_navigate_through_poses_rclcpp_node` and  `bt_navigator_navigate_to_pose_rclcpp_node` in params file.
> clear up params file

- nav2_behavior_tree/test/plugins/action/test_back_up_cancel_node.cpp
- nav2_behavior_tree/test/plugins/action/test_controller_cancel_node.cpp
- nav2_behavior_tree/test/plugins/action/test_drive_on_heading_cancel_node.cpp
- nav2_behavior_tree/test/plugins/action/test_spin_cancel_node.cpp
- nav2_behavior_tree/test/plugins/action/test_wait_cancel_node.cpp
- nav2_behavior_tree/test/plugins/condition/test_is_path_valid.cpp
- nav2_behavior_tree/test/plugins/condition/test_path_expiring_timer.cpp
---
The main branch had issues successfully running the behavior_tree tests. 
The following error was recorded previously here https://github.com/ros2/rclcpp/issues/1766. 
| Primary OS tested on | Ubuntu 22.04 LTS |
---
Added resets to static vars that were not being reset which caused the test to fail. 
None
---
> Bt test fix

- nav2_map_server/include/nav2_map_server/map_saver.hpp
- nav2_map_server/src/map_saver/main_cli.cpp
- nav2_map_server/src/map_saver/map_saver.cpp
Signed-off-by: MartiBolet <mboletboixeda@gmail.com>
Map saver has getting only the parameters in the constructor of the class.
---
| Ticket(s) this addresses   | #2985|
---
Added the `get_parameter` in `on_configure` transition for `map_saver`.
None
---
> Get parameters on configure transition addressing #2985

- nav2_bringup/launch/navigation_launch.py
- nav2_bringup/params/nav2_params.yaml
- nav2_velocity_smoother/CMakeLists.txt
- nav2_velocity_smoother/README.md
- nav2_velocity_smoother/include/nav2_velocity_smoother/velocity_smoother.hpp
- nav2_velocity_smoother/package.xml
- nav2_velocity_smoother/src/main.cpp
- nav2_velocity_smoother/src/velocity_smoother.cpp
- nav2_velocity_smoother/test/CMakeLists.txt
- nav2_velocity_smoother/test/test_velocity_smoother.cpp
#2633 
Docs PR: https://github.com/ros-planning/navigation.ros.org/pull/314
TODO 
- testing on hardware
Had one tester
> I actually tried the smoother on the real robot. Seems that it works fine.
> Nav2 Velocity Smoother

- nav2_behaviors/include/nav2_behaviors/timed_behavior.hpp
- nav2_bringup/params/nav2_params.yaml
Small cleanup tasks while investigating https://github.com/ros-planning/navigation2/issues/3014
> adding plugin type for static in local + removing unused print

- nav2_costmap_2d/include/nav2_costmap_2d/footprint_subscriber.hpp
- nav2_costmap_2d/src/footprint_subscriber.cpp
---
Removed member variable that is not being used. 
---
---
> remove extra sub

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
- nav2_bt_navigator/src/navigators/navigate_through_poses.cpp
Signed-off-by: Vinny Ruia <vinny.ruia@fireflyautomatix.com>
---
| Ticket(s) this addresses   | #3027  |
| Primary OS tested on | N/A* |
| Robotic platform tested on | N/A* |
* I am currently having trouble compiling from `main` on my system. I started this PR so that I can see if CI can do it.
---
Adding timeout to the action server initialization
N/A
---
N/A
> adding timeout for action client initialization

- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
---
| Ticket(s) this addresses   | #3065 |
| Robotic platform tested on | Proprietary |
---
Zero out transformed global plan z values so it is consistent with lookahead point visualization.
None, I think.
---
Maybe think about other implications of 3D issues.
> zero z values in rpp transformed plan

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
- nav2_bt_navigator/behavior_trees/navigate_w_replanning_only_if_goal_is_updated.xml
- nav2_map_server/test/component/test_map_server_node.cpp
- nav2_system_tests/src/behavior_tree/test_behavior_tree_node.cpp
- nav2_util/include/nav2_util/service_client.hpp
- nav2_util/src/lifecycle_service_client.cpp
---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/pull/3033 |
| Robotic platform tested on |Steve's Robot |
---
> adding looping timeout for lifecycle service clients + adding string name of action for BT action nodes

- nav2_map_server/src/map_io.cpp
| Ticket(s) this addresses   | #3078  |
| Robotic platform tested on | Own robot |
---
* Extraced only the image file name instead of the whole path when saving the meta data YAML file. 
N/A
---
I wanted to avoid having to add another dependency, but it could also be done using std::filesystem, like here: https://en.cppreference.com/w/cpp/filesystem/path/filename
> Fix for #3078, fix image path in YAML

- nav2_regulated_pure_pursuit_controller/README.md
- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/regulated_pure_pursuit_controller.hpp
- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
- nav2_regulated_pure_pursuit_controller/test/test_regulated_pp.cpp
---
| Ticket(s) this addresses   | #3045  |
| Robotic platform tested on | Not yet |
---
Depend only on the path length left on whether to scale velocity on approach, since depending on lookahead distance results in a cyclic dependency
Added a new parameter.
---
Need to test this and build it still.
> do not depend on velocity for approach scaling

- nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp
---
| Robotic platform tested on | Custom simulation setup |
---
* I noticed that service calls from the tree using bt_servcie_node blocks in the tick() instead of returning RUNNING
* The reason appears to be a typo, and my understanding is that the unused `timeout` variable was supposed to be used instead of `server_timeout_`.
> Use correct timeout when checking future in bt_servcie_node

- nav2_bt_navigator/src/bt_navigator.cpp
Signed-off-by: Aaron Chong <aaronchongth@gmail.com>
---
| Ticket(s) this addresses   | [(add tickets here #1)](https://github.com/ros-planning/navigation2/issues/3092) |
---
Added missing commas to ensure default plugin lib names are accurate.
> Adds missing commas so default plugin names are not stuck together

- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp
- nav2_costmap_2d/src/costmap_2d_ros.cpp
| Ticket(s) this addresses   | N/A? |
| Robotic platform tested on | Simulated Jackal |
---
* `costmap_2d_ros` creates a node but there was nothing spinning it, so getting its parameters (and other operations) were blocked. 
* I added a `nav2_util::NodeThread`
?
---
* Not needed in `main` because client node has been removed.
> Add Client Thread for costmap_client_node

- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
---
| Ticket(s) this addresses   | #3086 |
| Primary OS tested on | Docker 20.04 Ubuntu |
| Robotic platform tested on | Ignition differential sim |
---
Removed the additional sign* bug from this [PR](https://github.com/ros-planning/navigation2/pull/2979).
None
---
> fix: Removed additional sign multiplication in RPP angular velocity (in backward motion)

- nav2_util/include/nav2_util/simple_action_server.hpp
- nav2_waypoint_follower/src/waypoint_follower.cpp
> adding checks on goal IDs in results for waypoint follower

- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/compute_path_through_poses_action.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/compute_path_to_pose_action.hpp
- nav2_behavior_tree/plugins/action/compute_path_through_poses_action.cpp
- nav2_behavior_tree/plugins/action/compute_path_to_pose_action.cpp
---
| Ticket(s) this addresses   | #3090 |
---
This pr sets the path to be empty on the blackboard if compute pose to path fails. It addresses the issue with the behavior tree navigating along a old path using https://github.com/ros-planning/navigation2/blob/main/nav2_bt_navigator/behavior_trees/navigate_w_recovery_and_replanning_only_if_path_becomes_invalid.xml. 
The new behavior will be
Tries to compute path, fails clears costmap
Recovery node ticks again, compute path does get ticked again because isPathValid == FAILURE due to the path being empty.
---
> ComputePathToPose Sets empty path on blackboard if action is aborted or cancelled

- nav2_waypoint_follower/src/waypoint_follower.cpp
---
| Ticket(s) this addresses   | #3129 |
| Robotic platform tested on | Custom skid steer robot on gazebo |
---
* Added a missing return in #3130 to ignore feedback coming from outdated goals on the waypoint follower action server
* None to my knowledge
---
* None to my knowledge
> Ignore feedback from old goals in waypoint follower

- nav2_common/nav2_common/launch/rewritten_yaml.py
---
| Primary OS tested on | Ubuntu 22.04 , humble |
| Robotic platform tested on | turtlebot3, gazebo |
---
nav2_common.RewrittenYaml's function pathify not applied joinchar argument
None
---
> apply joinchar in RewrittenYaml's pathify function

- nav2_behavior_tree/plugins/action/compute_path_through_poses_action.cpp
- nav2_collision_monitor/include/nav2_collision_monitor/circle.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/collision_monitor_node.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/pointcloud.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/scan.hpp
- nav2_costmap_2d/plugins/voxel_layer.cpp
- nav2_waypoint_follower/src/waypoint_follower.cpp
> linting and uncrusitfy fixes for CI

- nav2_smac_planner/src/node_2d.cpp
- nav2_smac_planner/src/node_hybrid.cpp
- nav2_smac_planner/src/node_lattice.cpp
---
| Ticket(s) this addresses   | #3085 |
---
Start point is now added to the path
---
> start is now added to the path

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
- nav2_bringup/launch/bringup_launch.py
- nav2_bringup/launch/localization_launch.py
- nav2_bringup/launch/multi_tb3_simulation_launch.py
- nav2_bringup/launch/navigation_launch.py
- nav2_bringup/launch/rviz_launch.py
- nav2_bringup/launch/slam_launch.py
- nav2_bringup/launch/tb3_simulation_launch.py
- nav2_bringup/params/nav2_multirobot_params_1.yaml
- nav2_bringup/params/nav2_multirobot_params_2.yaml
- nav2_bringup/params/nav2_params.yaml
- nav2_collision_monitor/params/collision_monitor_params.yaml
- nav2_constrained_smoother/README.md
- nav2_controller/src/controller_server.cpp
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp
- nav2_costmap_2d/src/costmap_2d_ros.cpp
- nav2_planner/src/planner_server.cpp
- nav2_regulated_pure_pursuit_controller/README.md
- nav2_rotation_shim_controller/README.md
- nav2_smac_planner/README.md
- nav2_system_tests/src/costmap_filters/keepout_params.yaml
- nav2_system_tests/src/costmap_filters/speed_global_params.yaml
- nav2_system_tests/src/costmap_filters/speed_local_params.yaml
- nav2_theta_star_planner/README.md
---
| Ticket(s) this addresses   | #3119) |
---
* I used SetParameter to set the use_sim_time parameter and removed the parameter from launch files
---
> use_sim_time refactoring

- nav2_behavior_tree/nav2_tree_nodes.xml
Missing BT nodes are added to nav2_tree_nodes.xml
---
Missing BT nodes are added to nav2_tree_nodes.xml 
The nodes are:
- ClearCostmapAroundRobot
- ClearCostmapExceptRegion
The contribution is made to solve issue #3105 
---
Possible reviewer: @SteveMacenski 
Tested on Groot
> missing nodes added to nav2_tree_nodes.xml

- nav2_constrained_smoother/include/nav2_constrained_smoother/smoother_cost_function.hpp
- nav2_constrained_smoother/include/nav2_constrained_smoother/utils.hpp
error: 'bool ceres::IsInfinite(double)' is deprecated: ceres::IsInfinite will be removed in a future Ceres Solver release. Please use ceres::isinf.
> Change deprecated ceres function

- nav2_bringup/worlds/waffle.model
---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/3135 |
| Primary OS tested on | Ubuntu 22.04, Humble |
| Robotic platform tested on | Multi robot sim |
---
Removed a joint in the waffle sim model that referred to the `camera_rgb_frame` link which does not exist in the model.
None
---
None
> remove camera_rgb_joint since child frame does not exist

- nav2_simple_commander/nav2_simple_commander/costmap_2d.py
Signed-off-by: Stevedan Ogochukwu Omodolor <stevedan.o.omodolor@gmail.com>
---
| Robotic platform tested on | (gazebo ) |
---
* Add a costmap API for OccupancyGrid messages coming into the Simple Commander API
* Constructor for OccupancyGrid which stores the relevant information
* Implementation of the  following first few functions
* getSizeInCellsX / getSizeInCellsY
* getSizeInMetersX / getSizeInMetersY
*  getOriginX / getOriginY
* getResolution
* getGlobalFrameID
* getCostmapTimestamp
* Added new api, documentation on this api might be required in the simple commander page documentation. 
---
* Implementation of the following …
> simple command costmap api - first few functions

- navigation2/package.xml
---
| Ticket(s) this addresses   | #2982 |
| Primary OS tested on | Ubuntu 22.04.1 LTS |
| Robotic platform tested on | ----- |
---
* I  added missing dependency on nav2_collision_monitor module
> Fix missing dependency on nav2_collision_monitor

- nav2_smac_planner/include/nav2_smac_planner/node_lattice.hpp
- nav2_smac_planner/src/node_2d.cpp
- nav2_smac_planner/src/node_hybrid.cpp
- nav2_smac_planner/src/node_lattice.cpp
- nav2_smac_planner/test/test_a_star.cpp
---
| Ticket(s) this addresses   | #3085 |
---
---
> fixed start

- nav2_collision_monitor/include/nav2_collision_monitor/types.hpp
- nav2_collision_monitor/test/collision_monitor_node_test.cpp
Fixes incorrect velocities comparison appeared when robot is rotating on the place. This was leading to failure of `safe_vel < robot_action.req_vel` checks for APPROACH and SLOWDOWN behavioral models, that causes robot to ignoring its intended behavior.
---
| Ticket(s) this addresses   | #3171 |
| Primary OS tested on | Ubuntu 20.04 with ROS2 Rolling built from sources |
| Robotic platform tested on | TB3 simulation, colcon testing & coverage verification |
---
> Fix velocities comparison for rotation at place case

- nav2_simple_commander/nav2_simple_commander/costmap_2d.py
Updated-by: Jaehun Kim <k9632441@gmail.com>
* finish task B and tested on gazebo
* Update nav2_simple_commander/nav2_simple_commander/costmap_2d.py
---
| Ticket(s) this addresses   | #3151  |
---
* Update costmap API for OccupancyGrid messages coming into the Simple Commander API
* Implementation of the following few functions
* getCostIdx
* getCostXY
* setCost
* mapToWorld
* worldToMap
* getIndex
* Added new api, documentation on this api might be required in the simple commander page documentation.
---
* Implement and test a line iterator to march through the costmap given 2 points ancd check for collision
* Use that line iterator + costmap object + …
> simple command costmap api - update few functions

- nav2_regulated_pure_pursuit_controller/README.md
- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/regulated_pure_pursuit_controller.hpp
- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
---
| Ticket(s) this addresses   | #3200 |
| Primary OS tested on | Ubuntu 22.04.1 LTS|
| Robotic platform tested on | ----- |
---
* I added a new parameter to enable/disable collision detection in RPP
I already described this parameter in README in nav2_regulated_pure_pursuit_controller directory. (Part of this PR).
The documentation page that must be updated is here: https://navigation.ros.org/configuration/packages/configuring-regulated-pp.html (I will do that)
I will create another PR in repo: https://github.com/ros-planning/navigation.ros.org to do that. 
---
> [RPP] Add parameter to enable/disable collision detection

- nav2_costmap_2d/include/nav2_costmap_2d/obstacle_layer.hpp
- nav2_costmap_2d/plugins/obstacle_layer.cpp
| Ticket(s) this addresses   | / |
---
When using a PointCloud2 source, nav2_costmap_2d's ObstacleLayer plugin won't clear obstacles detected on the ground when they move away, as the `<source>.min_obstacle_height` parameter either will filter out the ground for the raytracing (if set to > 0.0) or detect it as an obstacle (if set to 0.0).
This problem is similar to [#662](https://github.com/ros-planning/navigation/issues/662).
This PR adds a new global `min_obstacle_height` parameter, allowing the per-source one to be extended to include the range to be taken into account for the retracing, while still filtering obstacles down to that …
> Add a min_obstacle_height param to the nav2_costmap_2d's ObstacleLayer plugin

- nav2_smac_planner/src/node_2d.cpp
- nav2_smac_planner/src/node_hybrid.cpp
- tools/planner_benchmarking/metrics.py
The impact is small, less than 2% or so, but it definitely doesn't hurt performance and I still see deterministically the same path metrics from experiments of 100 randomly generated paths.
> removing hypotf from smac planner heuristic computation

- nav2_smac_planner/README.md
- nav2_smac_planner/include/nav2_smac_planner/smac_planner_hybrid.hpp
- nav2_smac_planner/include/nav2_smac_planner/smac_planner_lattice.hpp
- nav2_smac_planner/src/a_star.cpp
- nav2_smac_planner/src/smac_planner_hybrid.cpp
- nav2_smac_planner/src/smac_planner_lattice.cpp
- nav2_smac_planner/test/test_smac_hybrid.cpp
- nav2_smac_planner/test/test_smac_lattice.cpp
> Adding Smac Planner Tolerances for Feasible Planners 

- .circleci/config.yml
- Dockerfile
in an attempt to fix CI Build timed outs.
- https://github.com/ros-planning/navigation2/issues/3189
> Improve Colcon Output 

- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp
- nav2_costmap_2d/src/costmap_2d_node.cpp
- nav2_costmap_2d/src/costmap_2d_ros.cpp
---
| Ticket(s) this addresses   | [(3213)](https://github.com/ros-planning/navigation2/issues/3213) |
---
* Added a new constructor in cosmtap2DROS to allow setting namespace and other options from launch file
---
> Add new constructor to cosmtap2DROS

- nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp
- nav2_lifecycle_manager/src/lifecycle_manager.cpp
- nav2_util/include/nav2_util/service_client.hpp
- nav2_waypoint_follower/include/nav2_waypoint_follower/plugins/photo_at_waypoint.hpp
I encountered this when building from source on Rolling.
```
/home/andy/ws_mobile_pick_place/src/navigation2/nav2_util/include/nav2_util/service_client.hpp:47:45: error: 'typename rclcpp::Client<ServiceT>::SharedPtr rclcpp::Node::create_client(const string&, const rmw_qos_profile_t&, rclcpp::CallbackGroup::SharedPtr) [with ServiceT = lifecycle_msgs::srv::GetState; typename rclcpp::Client<ServiceT>::SharedPtr = std::shared_ptr<rclcpp::Client<lifecycle_msgs::srv::GetState> >; std::string = std::__cxx11::basic_string<char>; rmw_qos_profile_t = rmw_qos_profile_s; rclcpp::CallbackGroup::SharedPtr = std::shared_ptr<rclcpp::CallbackGroup>]' is deprecated: use rclcpp::QoS instead of rmw_qos_profile_t [-Werror=deprecated-declarations]
47 |     client_ = node_->create_client<ServiceT>(
| …
```
> Fix RMW deprecation warnings

- nav2_costmap_2d/CMakeLists.txt
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_filters/costmap_filter.hpp
- nav2_costmap_2d/package.xml
- nav2_costmap_2d/plugins/costmap_filters/costmap_filter.cpp
- nav2_costmap_2d/test/unit/CMakeLists.txt
- nav2_costmap_2d/test/unit/costmap_filter_service_test.cpp
Adding costmap filters enabling/disabling service.
For the basis it was taken already existing "ros2/common_interfaces/std_srvs/srv/SetBool.srv":
```
bool data # e.g. for hardware enabling / disabling
---
bool success   # indicate successful run of triggered service
string message # informational, e.g. for error messages
```
---
| Ticket(s) this addresses   | #3194 |
| Primary OS tested on | Ubuntu 20.04 with ROS2 Rolling built from sources onboard |
| Robotic platform tested on | TB3 simulation, unit testing, code coverage |
---
> Costmap Filter enabling service

- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/compute_path_to_pose_action.hpp
- nav2_behavior_tree/nav2_tree_nodes.xml
- nav2_behavior_tree/plugins/action/compute_path_to_pose_action.cpp
- nav2_core/include/nav2_core/exceptions.hpp
- nav2_msgs/action/ComputePathToPose.action
- nav2_navfn_planner/include/nav2_navfn_planner/navfn_planner.hpp
- nav2_navfn_planner/src/navfn_planner.cpp
- nav2_planner/include/nav2_planner/planner_server.hpp
- nav2_planner/src/planner_server.cpp
- nav2_smac_planner/include/nav2_smac_planner/a_star.hpp
- nav2_smac_planner/src/a_star.cpp
- nav2_smac_planner/src/smac_planner_2d.cpp
- nav2_smac_planner/src/smac_planner_hybrid.cpp
- nav2_smac_planner/src/smac_planner_lattice.cpp
- nav2_theta_star_planner/include/nav2_theta_star_planner/theta_star_planner.hpp
- nav2_theta_star_planner/src/theta_star_planner.cpp
- nav2_theta_star_planner/test/test_theta_star.cpp
Reverts ros-planning/navigation2#3146
Having issues where its randomly saying that the start is occupied when clearly isn't. Example:
Makes navigation highly unreliable
> Revert "added result codes for global planner"

- nav2_amcl/src/amcl_node.cpp
---
| Robotic platform tested on | gazebo simulation of turtlebot |
---
When any of the alphas get a negative value, it was tested that the navigation may be crashed with overflow visiting sample->pose when running pf_update_resample().
It's possibly because the odometryUpdate() went wrong with some sqrt functions in it obtaining a negative input(which is a sum of alpha*positive value)
Add a check when getting the parameters in amcl_node.cpp, if any of them is negative, change it to zero and publish a warning.
---
* Maybe more checks during the update of odometry.
> odom alpha restriction to avoid overflow caused by user-misconfiguration

- nav2_smoother/CMakeLists.txt
- nav2_smoother/README.md
- nav2_smoother/include/nav2_smoother/savitzky_golay_smoother.hpp
- nav2_smoother/include/nav2_smoother/smoother_utils.hpp
- nav2_smoother/plugins.xml
- nav2_smoother/src/nav2_smoother.cpp
- nav2_smoother/src/savitzky_golay_smoother.cpp
- nav2_smoother/src/simple_smoother.cpp
- nav2_smoother/test/CMakeLists.txt
- nav2_smoother/test/test_savitzky_golay_smoother.cpp
- nav2_smoother/test/test_simple_smoother.cpp
> Adding new Nav2 Smoother: Savitzky-Golay Smoother

- nav2_regulated_pure_pursuit_controller/CMakeLists.txt
- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/collision_checker.hpp
- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/parameter_handler.hpp
- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/path_handler.hpp
- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/regulated_pure_pursuit_controller.hpp
- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/regulation_functions.hpp
- nav2_regulated_pure_pursuit_controller/src/collision_checker.cpp
- nav2_regulated_pure_pursuit_controller/src/parameter_handler.cpp
- nav2_regulated_pure_pursuit_controller/src/path_handler.cpp
- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
- nav2_regulated_pure_pursuit_controller/test/test_regulated_pp.cpp
> refactoring RPP a bit for cleanliness on way to ROSCon

- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/compute_path_through_poses_action.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/compute_path_to_pose_action.hpp
- nav2_behavior_tree/nav2_tree_nodes.xml
- nav2_behavior_tree/plugins/action/compute_path_through_poses_action.cpp
- nav2_behavior_tree/plugins/action/compute_path_to_pose_action.cpp
- nav2_core/include/nav2_core/planner_exceptions.hpp
- nav2_msgs/action/ComputePathThroughPoses.action
- nav2_planner/include/nav2_planner/planner_server.hpp
- nav2_planner/src/planner_server.cpp
---
| ------ | -----  |
| Ticket(s) this addresses   | #3043  |
---
Added error codes for compute path through poses. 
---
> exceptions for compute path through poses

- nav2_bringup/launch/bringup_launch.py
- nav2_bringup/launch/localization_launch.py
- nav2_bringup/params/nav2_params.yaml
---
| Ticket(s) this addresses   | (add tickets here #3149 ) |
| Robotic platform tested on | (gazebo)|
---
* Use SetParameter Launch API to set the yaml filename for map_server 
* Remove the note added to the navigation.ros.org configuration for map server explaining that yaml_filename is strictly required.
---
> Use SetParameter Launch API to set the yaml filename for map_server

- nav2_amcl/src/amcl_node.cpp
---
| Primary OS tested on | Ubuntu20.04 |
| Robotic platform tested on | (gazebo simulation of turtlebot3 |
---
There is a possibility that the laser scan can be malformed or forged to be negative or zero, or, with a malfunction, the sensor may output a message with all the content zeros.
with a new laserscan received, the function UpdateFilter may be called:
```
AmclNode::laserReceived(sensor_msgs::msg::LaserScan::ConstSharedPtr laser_scan)
{
......
bool resampled = false;
// If the robot has moved, update the filter
if (lasers_update_[laser_index]) {
updateFilter(laser_index, laser_scan, pose);
// Resample the particles
if (!(++resample_count_ % resample_interval_)) { …
```
> Check for range_max of laserscan in updateFilter to avoid a implicit overflow crash.

- nav2_behavior_tree/package.xml
- nav2_bt_navigator/package.xml
---
| Robotic platform tested on | N/A ||
---
Remove `<exec_depend>` on `behaviortree_cpp_v3` since only headers are used from it (no binaries or libraries), but the packages in question already have `<build_depend>` for it. This avoids adding `behaviortree_cpp_v3` as a dependency to the bloomed package, but for development you will still get it if you install with rosdep or use debian tooling to install build dependencies.
None
---
None
> remove exec_depend on behaviortree_cpp_v3

- nav2_smac_planner/include/nav2_smac_planner/smoother.hpp
- nav2_smac_planner/include/nav2_smac_planner/types.hpp
- nav2_smac_planner/src/smoother.cpp
- nav2_smoother/include/nav2_smoother/simple_smoother.hpp
- nav2_smoother/src/simple_smoother.cpp
- nav2_smoother/test/test_simple_smoother.cpp
Helps allows a user a tune smoother behavior further in case you're in confined spaces and refining the smoother values 4x results in paths that regularly skirt obstacles. Also reduces smoother refinement count to 2 cycles rather than 4 to reduce out-of-the-box over-smoothing
> add parameterized refinement recursion numbers in Smac Planner Smoother and Simple Smoother

- nav2_theta_star_planner/include/nav2_theta_star_planner/theta_star.hpp
- nav2_theta_star_planner/src/theta_star.cpp
- nav2_theta_star_planner/src/theta_star_planner.cpp
- nav2_theta_star_planner/test/test_theta_star.cpp
---
| Ticket(s) this addresses   | #3285 |
| Primary OS tested on | Ubuntu 22 |
| Robotic platform tested on | Custom gazebo robot |
---
Added the allow_unknown parameter to the theta star planner to make it possible to plan through unknown space
I need to add the new parameter to the configuration guide in navigation.ros.org
---
> Add allow_unknown parameter to theta star planner

- nav2_system_tests/src/waypoint_follower/tester.py
---
| Ticket(s) this addresses   | (add tickets here) |
| Primary OS tested on | (Ubuntu jammy, docker) |
| Robotic platform tested on | (Turtlebot simulatino) |
---
Include the following test cases to waypoint follower tests 
* Param stop_on_failure set to true and create a situation of waypoint following (such as a bogus impossible goal off the map) and check that it terminates as failed + the result message contains the correct missed_waypoints field.
* A test where we send 0 goal poses in the request, make sure it returns successfully
* During a waypoint navigation run, cancel it
---
> Include test cases waypoint follwer

- nav2_collision_monitor/README.md
- nav2_collision_monitor/include/nav2_collision_monitor/circle.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/polygon.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/source.hpp
- nav2_collision_monitor/src/circle.cpp
- nav2_collision_monitor/src/collision_monitor_node.cpp
- nav2_collision_monitor/src/pointcloud.cpp
- nav2_collision_monitor/src/polygon.cpp
- nav2_collision_monitor/src/range.cpp
- nav2_collision_monitor/src/scan.cpp
- nav2_collision_monitor/src/source.cpp
- nav2_collision_monitor/test/polygons_test.cpp
- nav2_util/include/nav2_util/robot_utils.hpp
- nav2_util/src/robot_utils.cpp
Adding an ability to dynamically read polygon vertices from input topic for "STOP" and "SLOWDOWN" behavior models.
---
| Ticket(s) this addresses   | #3196 |
| Primary OS tested on | Ubuntu 20.04 with ROS2 Rolling onboard |
| Robotic platform tested on | TB3 simulation, unit & codecov testing |
---
* New ROS-parameter `polygon_sub_topic`. If it is set, subscribe to the polygon from input `PolygonStamped` messages. If not - use classical static user-defined polygon vertices.
* Allowing to use polygon shape published in a different from `robot_base` frame by reading `PolygonStamped->header.frame_id`.
* The change applied to "STOP" and "SLOWDOWN" behavior models, since for "APPROACH" one we have already utilized footprint …
> Dynamically changing polygons support

- nav2_costmap_2d/include/nav2_costmap_2d/inflation_layer.hpp
- nav2_costmap_2d/plugins/inflation_layer.cpp
Makes its easier for other places already dynamically casting layers to get inflation layer metadata to get the cost scaling factor rather than duplicating parameters, e.g. #3289
> adding getCostScalingFactor

- nav2_map_server/include/nav2_map_server/costmap_filter_info_server.hpp
- nav2_map_server/src/costmap_filter_info/costmap_filter_info_server.cpp
- nav2_map_server/test/unit/test_costmap_filter_info_server.cpp
Signed-off-by: MartiBolet <mboletboixeda@gmail.com>
Adressing the Issue #3291 when CostmapFilterInfo server is deactivated and then reactivated fails the transition.
---
| Ticket(s) this addresses   | Issue #3291 |
---
* Changed the typo of the `msg_` of `CostmapFiterInfoServer` from `unique_ptr` to prevent deleting when publishing using `std::move`
* I added a new test for the class `CostmapFilterInfoServer` that reproduces what was happening in the issue to check it doesn't happen again.
---
> Solve bug when CostmapInfoServer is reactivated

- tools/smoother_benchmarking/README.md
- tools/smoother_benchmarking/metrics.py
- tools/smoother_benchmarking/process_data.py
Update path smoothers benchmarking scripts with new smoothness metrics and Savitzky-Golay smoother support
---
| Robotic platform tested on | Nav2 simple commander-based benchmarks |
---
Updates in `tools/smoother_benchmarking` scripts:
* Update metrics for path smoothness from quad `( dx(i+1) - dx(i) )^2` to module value `| dx(i+1) - dx(i) |`
* Added a support of Savitzky-Golay smoother
`README.md` in the scripts was already adjusted. No further actions needed.
---
> Smoothness metrics update

- nav2_system_tests/src/behaviors/spin/spin_behavior_tester.cpp
- nav2_system_tests/src/behaviors/spin/spin_behavior_tester.hpp
- nav2_system_tests/src/behaviors/spin/test_spin_behavior_node.cpp
---
| Ticket(s) this addresses   | (add tickets here ) |
| Robotic platform tested on | (Simulation) |
---
* include preempt/cancel test for time behavior, in the spin plugin
---
> preempt/cancel test for time behavior, spin pluguin

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
Signed-off-by: Owen Hooper <17ofh@queensu.ca>
---
| Ticket(s) this addresses   | #3150  |
---
* I added a parameter to allow an implementing developer to prevent the BtActionNode from sending a goal
* Parameter gets reset before `on_tick` is called
* Parameter is checked before both calls to `send_new_goal`
* Needs to get added to the migration guide
* Needs to be added to the table in writing_new_bt_plugin 
---
> Added a flag to not send goal in BtActionNode

- nav2_costmap_2d/CMakeLists.txt
- nav2_costmap_2d/src/costmap_2d_ros.cpp
- nav2_costmap_2d/test/regression/CMakeLists.txt
- nav2_costmap_2d/test/regression/order_layer.cpp
- nav2_costmap_2d/test/regression/order_layer.hpp
- nav2_costmap_2d/test/regression/order_layer.xml
- nav2_costmap_2d/test/regression/plugin_api_order.cpp
Fixes the situations when Costmap2D plugin is being processed before initialization
---
| Ticket(s) this addresses   | #3299 |
| Primary OS tested on | Ubuntu 20.04 with ROS2 Rolling (built from sources) onboard |
| Robotic platform tested on | colcon test of `nav2_costmap_2d` and `nav2_system_tests`: no regressions |
---
* Ensure that plugin->updateCosts()/updateBounds() won't be called unless all plugins to be initialized: the `Costmap2DROS::updateMap()` is being processed in the main update loop only if `stopped_` is `false`.
* Added the regression test for this case. There is a new `OrderLayer` costmap plugin that sleeps in the `activate()` stage checking that parallel thread won't call `updateCosts()`/`updateBound()` …
> Ensure that plugin initialization to be called before updating routines

- nav2_amcl/include/nav2_amcl/pf/pf.hpp
- nav2_amcl/src/amcl_node.cpp
- nav2_amcl/src/pf/pf.c
---
| Ticket(s) this addresses   | #3311 |
| Robotic platform tested on | Gazebo Simulation of TurtleBot3, Our Own Robot) |
---
Not assigning fixed map pointer to particle filter, using latest when resample.
---
> Fix Wrong Map Pointer (#3311)

- tools/planner_benchmarking/metrics.py
- tools/planner_benchmarking/planning_benchmark_bringup.py
- tools/smoother_benchmarking/metrics.py
Support new result codes of Path Planner in Nav2 benchmarking suite, added since 1c106173dbc5b2321e9d3f1bf111e40293d36a4f
---
| Ticket(s) this addresses   | #3043 |
| Robotic platform tested on | TB3 simulation |
---
* Added the support of non-NULL return states from `computePlan()` (passed as `action_server->terminate_current(result)` with non-empty argument).
* Fixed the bug in `planning_benchmark_bringup.py` when the Map Server can not start with non-existing map.
Not required
---
> Support result codes for path planner in benchmarking

- nav2_controller/src/controller_server.cpp
- nav2_core/include/nav2_core/controller.hpp
Add method to reset the state of a controller plugin when the server is terminating a task so that we can start a new request fresh. 
In response to MPPI development to be released here in ~January
> add a controller reset due to predictive controllers retaining state

- nav2_costmap_2d/include/nav2_costmap_2d/inflation_layer.hpp
Analogous to the function added last month for the inflation scale
> get inflation radius in inflation layer

- nav2_bt_navigator/src/bt_navigator.cpp
---
The duplicate led to a failure during configuration stage of bt_navigator, when the parameter fallbacks to its default.   
(A ticket was not created in order to avoid unnecessary noise.)
---
- Removed the duplicate of nav2_back_up_cancel_bt_node
Nice to have:
- One could remove duplicates in the list programmatically, i.e. turn the list into a set and back to a list to avoid this kind of problems forever, and for custom configurations, too.
> [bt_navigator] plugin_lib_names default: Remove duplicate of nav2_back_up_cancel_bt_node

- nav2_behavior_tree/package.xml
- nav2_bt_navigator/package.xml
Reverts ros-planning/navigation2#3279 @Aposhian
Causes build failure in build farm https://build.ros2.org/job/Hbin_uJ64__nav2_behaviors__ubuntu_jammy_amd64__binary/22/consoleFull
```
16:41:26 -- Found nav2_behavior_tree: 1.1.4 (/opt/ros/humble/share/nav2_behavior_tree/cmake)
16:41:27 CMake Error at /opt/ros/humble/share/nav2_behavior_tree/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package):
16:41:27   By not providing "Findbehaviortree_cpp_v3.cmake" in CMAKE_MODULE_PATH this
16:41:27   project has asked CMake to find a package configuration file provided by
16:41:27   "behaviortree_cpp_v3", but CMake did not find one.
16:41:27 
16:41:27   Could not find a package configuration file provided by
16:41:27   "behaviortree_cpp_v3" with any of the following names:
16:41:27 …
```
> Revert "remove exec_depend on behaviortree_cpp_v3"

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/bt_cancel_action_node.hpp
---
| Info | Correct exception message when action server is not up within a specified interval |
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/3331 |
| Robotic platform tested on | custom |
---
* fixed using non-existent std::string constructor
* None
---
> Std::string doesn't have such constructor, therefore wrong exception happens when waiting for action server is over

- nav2_bringup/params/nav2_multirobot_params_1.yaml
- nav2_bringup/params/nav2_multirobot_params_2.yaml
- nav2_bringup/params/nav2_params.yaml
- nav2_bt_navigator/CMakeLists.txt
- nav2_bt_navigator/include/nav2_bt_navigator/bt_navigator.hpp
- nav2_bt_navigator/include/nav2_bt_navigator/navigators/navigate_through_poses.hpp
- nav2_bt_navigator/include/nav2_bt_navigator/navigators/navigate_to_pose.hpp
- nav2_bt_navigator/navigator_plugins.xml
- nav2_bt_navigator/package.xml
- nav2_bt_navigator/src/bt_navigator.cpp
- nav2_bt_navigator/src/navigators/navigate_through_poses.cpp
- nav2_bt_navigator/src/navigators/navigate_to_pose.cpp
- nav2_core/CMakeLists.txt
- nav2_core/README.md
- nav2_core/include/nav2_core/behavior_tree_navigator.hpp
- nav2_core/package.xml
Closing https://github.com/ros-planning/navigation2/issues/3335
Creates a new NavigatorBase class for which is used ONLY to create navigator templated plugin vectors for the BT Navigator server. Its methods are implemented as `final` in the `BehaviorTreeNavigator` plugin class, which is the user-facing class to implement their BT Action Navigator types. The virtual methods within that class are the core to creating new navigator behaviors.
APIs to implement for plugins:
- getName
- getDefaultBTFilepath
- goalReceived
- onLoop
- onPreempt
- goalCompleted
- configure
- cleanup
- activate
- deactivate
> Pluginizing BT Navigators

- nav2_costmap_2d/include/nav2_costmap_2d/layer.hpp
- nav2_costmap_2d/src/layered_costmap.cpp
When clearing entirely a costmap (see the `clear_entirely_*` service), its layers are reset. This sets their `current_` attribute to False, until they are updated (`updateCosts()`). However, for disabled plugins/filters, the `updateCosts()` is bypassed so that the `current_` attribute is never reset to True, and the costmap never becomes "current" again; because of that the controller_server used to get stuck in an endless loop (see `while (!costmap_ros_->isCurrent())` in `ControllerServer::computeControl()`).
This patch fixes that by adding a condition for not considering disabled plugins/filters in the `LayeredCostmap::isCurrent()`.
---
| Ticket(s) this addresses   | #3353  |
| Robotic platform …
> Do only consider enabled costmap plugins/filters in the isCurrent() method of a LayeredCostmap

- nav2_smac_planner/CMakeLists.txt
| Ticket(s) this addresses   |https://github.com/ros-planning/navigation2/issues/3357 |
---
* Export necessary ompl include directories from nav2_smac_planner to fix build issue.
> Export ompl include directories from nav2_smac_planner.

- nav2_constrained_smoother/README.md
- nav2_constrained_smoother/include/nav2_constrained_smoother/options.hpp
- nav2_constrained_smoother/test/test_constrained_smoother.cpp
During the benchmarking of Path Smoothers, it was discovered abnormal behavior of Constrained Smoother. This behavior appeared on some experiments with SmacHybridA* planner and Constrained Smoother, where the path smoothed by Constrained Smoother could have some “wobblings” or “oscillations” like depicted below:
The analysis is being performed and attached to current PR in a [CS_path_oscillation_analysis_v7.pdf](https://github.com/ros-planning/navigation2/files/10309245/CS_path_oscillation_analysis_v7.pdf) file.
As the results of analysis and during the numerous tests and benchmarks under different environments (on small and large maps, narrow- and wide-spaced) it was found and proved the optimal set of the residual coefficients causing Constrained Smoother to produce the rational path …
> Constrained Smoother tuning

- nav2_velocity_smoother/src/velocity_smoother.cpp
---
| Info | Fix nav2_velocity_smoother for sim time |
---
If sim time is used: `now()` might be close to 0 on startup and `last_command_time_` is defined 0 making the condition `now() - last_command_time_ > velocity_timeout_` False, which assumes that velocity command was received recently and then leads to an error when trying to access command_'s properties ( `command_->linear.x` )
So i added check for command_ being null before proceeding with smoothing
---
> Fix nav2_velocity_smoother for sim time

- nav2_simple_commander/nav2_simple_commander/footprint_collision_checker.py
---
| Ticket(s) this addresses   | #3151 |
| Primary OS tested on | Ubuntu 22.04.01 |
---
* This PR is to change step_size to 0.5 instead of 0.1 in the footprint collision checker as discussed in https://github.com/ros-planning/navigation.ros.org/pull/382#discussion_r1064964995
---
> Changed step_size to 0.5 in collision checker

- nav2_theta_star_planner/test/test_theta_star.cpp
Request was out of bounds of the set size. Not sure why this didn't fail before.
> Fixing Theta* test failures

- nav2_behavior_tree/include/nav2_behavior_tree/plugins/decorator/speed_controller.hpp
- nav2_behavior_tree/nav2_tree_nodes.xml
- nav2_behavior_tree/plugins/decorator/speed_controller.cpp
- nav2_behavior_tree/test/plugins/decorator/test_speed_controller.cpp
- nav2_bt_navigator/behavior_trees/navigate_w_replanning_speed.xml
- nav2_core/include/nav2_core/behavior_tree_navigator.hpp
- nav2_system_tests/src/behavior_tree/test_behavior_tree_node.cpp
* Using blackboard get() method that does not throw error
* Share odom_smoother on the blackboard
Signed-off-by: Borong Yuan <yuanborong@hotmail.com>
---
---
The SpeedController is broken since (#2271).
There are two get() methods in blackboard. One of them throws an error if `val` doesn't exist. Obviously `goal` and `goals` cannot exist on blackboard at the same time. So we need to use another get() method like in GoalUpdatedController.
Now the BT Navigator already has an instance of OdomSmoother, we can't create another one in SpeedController, otherwise we won't get the correct data. A simple fix is to share …
> Fix SpeedController

- nav2_bringup/launch/localization_launch.py
- nav2_bringup/launch/navigation_launch.py
- nav2_bringup/params/nav2_multirobot_params_1.yaml
- nav2_bringup/params/nav2_multirobot_params_2.yaml
* Use full name of composable nodes container
* Correct and update BT plugins and error codes list
* Fix and update local and global costmap used plugins parameters
---
| Ticket(s) this addresses   | #3182 |
| Primary OS tested on | Ubuntu 20.04, 22.04 |
| Robotic platform tested on | Single-bot and multi-robot TB3 standard simulation |
---
This fixes Issues No.1, No.3 and No.4 reported in #3182:
**Issue1**
Nav2 stack is not starting for multi-robot simulation in composable nodes mode.
Root cause:
If we have the push namespace, container for composable nodes won't work in the same `PushNamespace`.
Workaround fix:
Use full container name in all configurations.
**Issue3**
BT node loading failed due to unrecognized …
> Fix multi-robot launch issues

- nav2_bringup/launch/localization_launch.py
- nav2_bringup/launch/navigation_launch.py
- nav2_bringup/launch/slam_launch.py
- nav2_controller/src/controller_server.cpp
- nav2_costmap_2d/src/costmap_2d_cloud.cpp
- nav2_costmap_2d/src/costmap_2d_ros.cpp
- nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager.hpp
- nav2_lifecycle_manager/src/lifecycle_manager.cpp
- nav2_planner/src/planner_server.cpp
- nav2_simple_commander/nav2_simple_commander/footprint_collision_checker.py
- nav2_simple_commander/nav2_simple_commander/line_iterator.py
- nav2_simple_commander/test/test_footprint_collision_checker.py
- nav2_simple_commander/test/test_line_iterator.py
- nav2_system_tests/src/error_codes/test_error_codes.py
- nav2_system_tests/src/error_codes/test_error_codes_launch.py
- nav2_system_tests/src/waypoint_follower/tester.py
- nav2_util/include/nav2_util/lifecycle_node.hpp
- nav2_util/src/lifecycle_node.cpp
- nav2_util/test/test_lifecycle_node.cpp
---
| Ticket(s) this addresses   | 3271 |
| Robotic platform tested on | nav2_system_tests (i.e. turtlebot3_waffle?) |
---
In brief: unclean shutdown of several processes resulted in code coverage data being dropped on the floor, rather than flushed to the .gcda files. So to get the code coverage data, we fix the unclean shutdowns. There are a few instances fixed in this PR, but likely not all (see Future work below).
The gist of all these fixes is that rclcpp::shutdown() invalidates a bunch of state, and if something attempts to touch that state again after the shutdown(), exceptions and seg faults can occur, resulting in unclean shutdown. rclcpp provides a preshutdown callback …
> Address code cov loss due to unclean shutdown (issue #3271)

- nav2_collision_monitor/include/nav2_collision_monitor/collision_monitor_node.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/pointcloud.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/range.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/scan.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/source.hpp
- nav2_collision_monitor/params/collision_monitor_params.yaml
- nav2_collision_monitor/src/collision_monitor_node.cpp
- nav2_collision_monitor/src/pointcloud.cpp
- nav2_collision_monitor/src/range.cpp
- nav2_collision_monitor/src/scan.cpp
- nav2_collision_monitor/src/source.cpp
- nav2_collision_monitor/test/sources_test.cpp
ignoring time shifts between source and base frame during the movement
---
| Ticket(s) this addresses   | #3402 |
| Primary OS tested on | Ubuntu 20.04 with ROS2 Rolling built from sources |
| Robotic platform tested on | TB3 Gazebo simulation, `colcon test --packages-select nav2_collision_monitor`, code coverage |
---
* Added an new option allowing to control which `lookupTransform()` API to use: [simple](https://docs.ros2.org/latest/api/tf2/classtf2_1_1BufferCore.html#a5d578ecbea2ec0fdb92de1616251e175) or [advanced](https://docs.ros2.org/latest/api/tf2/classtf2_1_1BufferCore.html#a779c28b06b41f9ebc63e8c0d0da77e9b), considering considering the difference between current time and latest source time and allowing to correct …
> Option allowing to use simple lookupTransform API

- nav2_dwb_controller/dwb_core/include/dwb_core/dwb_local_planner.hpp
- nav2_dwb_controller/dwb_core/src/dwb_local_planner.cpp
Until now, the prune_distance was used as distance threshold to shorten the upcoming path when shorten_transformed_plan was enabled. However, the prune and shortening mechanisms are de-correlated mechanisms. One could wish to use a different shortening distance for upcoming points, than the prune distance used for passed points. For this reason, a new parameter "forward_prune_distance" was added.
---
---
---
> nav2_dwb_controller: add forward_prune_distance parameter

- nav2_costmap_2d/plugins/costmap_filters/costmap_filter.cpp
- nav2_costmap_2d/test/unit/CMakeLists.txt
- nav2_costmap_2d/test/unit/costmap_filter_test.cpp
This fixes the cases where `CostmapFilter::worldToMask()` incorrectly calculates mask coordinates leading to incorrect function return on world points belonging to mask (more information in #3417).
---
| Ticket(s) this addresses   | #3417 |
| Robotic platform tested on | `colcon test --packages-select nav2_cosmap_2d` + new testcase covering the `CostmapFilter::worldToMask()` functionality |
---
* Fixed `mx`, `my` calculation to cover whole filter mask area
* Optimized temporary used variables with `const` identifier
* Added new `costmap_filter_test` covering `CostmapFilter::worldToMask()` functionality (including reported corner-case)
> Fix mask coordinates calculation in worldToMask

- nav2_costmap_2d/include/nav2_costmap_2d/costmap_filters/binary_filter.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_filters/costmap_filter.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_filters/keepout_filter.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_filters/speed_filter.hpp
- nav2_costmap_2d/plugins/costmap_filters/binary_filter.cpp
- nav2_costmap_2d/plugins/costmap_filters/costmap_filter.cpp
- nav2_costmap_2d/plugins/costmap_filters/keepout_filter.cpp
- nav2_costmap_2d/plugins/costmap_filters/speed_filter.cpp
- nav2_costmap_2d/test/unit/costmap_filter_test.cpp
Do not copy `OccupancyGrid` mask -> to `Costmap2D` in mask receiving callback. Directly store and use `OccupancyGrid` mask instead.
---
| Ticket(s) this addresses   | #3419 |
| Robotic platform tested on | TB3 simulation, colcon test, local code coverage |
---
* Do not copy OccupancyGrid mask -> to Costmap2D. Directly store and use OccupancyGrid mask instead:
```
-  std::unique_ptr<Costmap2D> mask_costmap_;
+  nav_msgs::msg::OccupancyGrid::SharedPtr filter_mask_;
```
* Add new unsigned char `CostmapFilter::getMaskCost(OccupancyGrid::SharedPtr filter_mask, & mx, & my)` routine to CostmapFilter, which will convert OccupancyGrid values to Costmap2D ones; and will be called each time, when …
> Improve KeepoutFilter mask receiving performance

- nav2_costmap_2d/include/nav2_costmap_2d/costmap_filters/costmap_filter.hpp
- nav2_costmap_2d/plugins/costmap_filters/costmap_filter.cpp
Keep original Costmap2D copyrights in CostmapFilters, as it uses some common with it routines.
---
| Ticket(s) this addresses   | #3420 |
| Robotic platform tested on | N/A (text fixup)|
---
Keep with respect to original authors Costmap2D copyrights, as CostmapFilters code have common with Costmap2D methods:
* `CostmapFilters::getMaskCost()` [[1](https://github.com/ros-planning/navigation2/blob/99f7ff63129a2eff08011557f0d239dcbaa34956/nav2_costmap_2d/plugins/costmap_filters/costmap_filter.cpp#L218-L227 )], [[2](https://github.com/ros-planning/navigation2/blob/63b690a27a4ba1bde24ebd8e6c592c9894eec169/nav2_costmap_2d/src/costmap_2d.cpp#L80-L89)]
* `CostmapFilters::worldToMask()` …
> Correct CostmapFilters copyrights

- nav2_costmap_2d/test/unit/costmap_filter_test.cpp
- nav2_dwb_controller/dwb_core/src/dwb_local_planner.cpp
- nav2_regulated_pure_pursuit_controller/src/parameter_handler.cpp
See https://github.com/ros-planning/navigation2/issues/3367 and https://github.com/ros-planning/navigation2/issues/3375
> set negative prune values as use full path in RPP and DWB

- nav2_mppi_controller/include/nav2_mppi_controller/tools/path_handler.hpp
- nav2_mppi_controller/src/path_handler.cpp
- nav2_mppi_controller/test/path_handler_test.cpp
It is currently impossible to use a different global frame for the global and local costmap.
The use of `worldToMap` to check if the pose is inside the costmap works only if the pose to check is referenced relative to the costmap frame: https://github.com/ros-planning/navigation2/blob/9dca1cfa60af9cdc4f6111db960bae72fd85b17c/nav2_mppi_controller/src/path_handler.cpp#L66
Proposed fix is to replace `transformPlanPosesToCostmapFrame` and `getGlobalPlanConsideringBounds` by `getGlobalPlanConsideringBoundsInCostmapFrame` in order not to have to transform the pose from the global plan/global costmap frame to the controller/local costmap frame twice.
> Fix using different frame for global and local costmap

- nav2_regulated_pure_pursuit_controller/README.md
- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/parameter_handler.hpp
- nav2_regulated_pure_pursuit_controller/src/parameter_handler.cpp
- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
---
| Robotic platform tested on | Custom: Sim and Real |
---
Introduce option to set lookahead for curvature detection to a fixed distance. This breaks a reference cycle that becomes especially problematic with long lookaheads.
Added two new parameters.
---
Determine if there is a way to derive this metric so that it can be enabled by default for all users
> Rpp curve regulation reference cycle

- nav2_mppi_controller/include/nav2_mppi_controller/optimizer.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp
- nav2_mppi_controller/src/optimizer.cpp
- nav2_mppi_controller/test/utils_test.cpp
https://github.com/ros-planning/navigation2/issues/3351 + FYI @doisyg
> changing MPPI's SG filter to 9-point formulation (prev. 5)

- nav2_bt_navigator/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml
---
| Robotic platform tested on | Real hardware |
---
* There seems to be a back quote character in the default pose navigation file. I'm not sure how it's considered valid XML, but in the case that XML parsers are switched, this should be a little more resilient.
---
> Remove back quote

- nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp
---
| Info | Add default service name to BTServiceNode |
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/3442 |
---
* Added service_name to BtServiceNode constructor, so that it could be passed from nodes that inherit BtServiceNode
If the service_name is not specified in xml -> `getInput("service_name", service_name_)` would just [return false](https://github.com/BehaviorTree/BehaviorTree.CPP/blob/bbfd51c68c352aaaa537cc9f722ddae178f89237/include/behaviortree_cpp/tree_node.h#L379) and service node would try to subscribe to the default service name. 
If default service name wasn't specified either the …
> Add default service name to BTServiceNode

- nav2_mppi_controller/src/path_handler.cpp
- nav2_mppi_controller/test/path_handler_test.cpp
---
---
This PR fixes one of the issue with looping paths in MPPI. See example of oscillation below:
https://user-images.githubusercontent.com/15727892/222525415-181b87a8-7732-4eb4-9605-eb8c04e7622e.mp4
(global path in green, transformed path in purple arrows)
- For searching the upper bound , we search up to the pruning distance along the path, instead of searching up the euclidean distance.
- For the the lower bound, the closest pose from the robot on the path is still used. But the closest pose search is modified: we look up to the min between `max_robot_pose_search_dist` and `prune_distance`
To discuss: is …
> [MPPI] Fix transformed path oscillations

- .devcontainer/devcontainer.json
- .dockerignore
- .github/workflows/update_ci_image.yaml
- doc/development/codespaces.md
Work in progress for adding support for Dev Container and Codespaces:
- https://code.visualstudio.com/docs/devcontainers/containers
- https://containers.dev
- https://docs.github.com/en/codespaces
> Support for Dev Containers and Codespaces

- .github/workflows/update_ci_image.yaml
- Dockerfile
- tools/distro.Dockerfile
- tools/source.Dockerfile
To avoid errors and warnings when updating CI images, such as issues when passing empty strings to `--build-arg`.
E.g: `FAIL_ON_TEST_FAILURE=''`
```
> [tester 4/4] RUN if [ -n "True" ]; then         . install/setup.sh &&         colcon test &&         colcon test-result           || ([ -z "''" ] || exit 1)     fi:
```
> https://github.com/ros-planning/navigation2/actions/runs/4386514560/jobs/7680671404#step:7:702
or deprications warnings for github action commands.
> Patch CI actions and Dockerfiles

- nav2_constrained_smoother/CMakeLists.txt
- nav2_constrained_smoother/include/nav2_constrained_smoother/smoother_cost_function.hpp
- nav2_constrained_smoother/include/nav2_constrained_smoother/utils.hpp
Fix for different `ceres::IsInfinite()`/`ceres::isinf()` API on different Ceres Solver versions (`2.0.0-`/`2.1.0+` respectively), causing build regression on Ubuntu 20.04 where Ceres is being distributed under older version.
---
| Ticket(s) this addresses   | #3158 |
| Robotic platform tested on | `colcon test --packages-select nav2_constrained_smoother`, TB3 simulation |
---
* The regression appeared since on Ubuntu 20.04 since #3158 commit. This commit is adjusting for newer `ceres::isinf()` API used in Ubuntu 22.04, but Ubuntu 20.04 begins out of support
* Since Ubuntu 20.04 is in the [officially supported](https://docs.ros.org/en/rolling/Installation/Alternatives/Ubuntu-Development-S …
> Fix for different ceres isinf() API

- nav2_mppi_controller/src/critics/path_follow_critic.cpp
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/3480 |
| Robotic platform tested on | Dexory's robot |
---
Fix https://github.com/ros-planning/navigation2/issues/3480
> [MPPI] Fix segfault in path_follow_critic when path is empty

- nav2_common/nav2_common/launch/rewritten_yaml.py
| ------------------------------------|-----------------------------------------------------------------------|
| Ticket(s) this addresses      | RewrittenYaml does not parse integers keys #3483 |
| Primary OS tested on         | Ubuntu                                                                        |
| Robotic platform tested on | gazebo simulation                                                       |
---
Added string casting inside RewrittenYaml to yaml keys in order to correctly parse integers keys such as:
```
nodes_number: 3
0:
node_name: name1
1:
node_name: name2
2:
node_name: name3
```
> Added str cast to parse int

- nav2_route/graphs/scripts/README.md
- nav2_route/graphs/scripts/export_shapefiles.py
- nav2_route/graphs/scripts/generate_start_and_end_id.sql
- nav2_route/graphs/scripts/increment_edge_id.json
- nav2_route/graphs/scripts/increment_node_id.json
---
| Ticket(s) this addresses   | NONE|
---
Added scripts to help automate the route graph generation. 
---
> scripts for route

- .circleci/config.yml
- .circleci/defaults.yaml
To try and help CircleCI to parse the output file. 
- https://stackoverflow.com/a/70774733/2577586
- https://colcon.readthedocs.io/en/released/reference/verb/test.html#cmake-specific-arguments
Fixes: #3437
> Prepare test results to only use junit/xunit schema

- .github/workflows/update_ci_image.yaml
Tag by version instead of by timestamp, to keep archive sustainable and more semantically useful. Timesamps of images can still be inferred from metadata. This also tries to avoid pushing untagged manifests.
Replaces: https://github.com/ros-planning/navigation2/pull/3474
> Container retention via version tagging

- .github/workflows/update_ci_image.yaml
Otherwise there is no source code to use to set the version output.
Fixes: https://github.com/ros-planning/navigation2/pull/3491
> Use checkout action to set version output

- .github/workflows/update_ci_image.yaml
or relative path under $GITHUB_WORKSPACE
that actions/checkout places the repository
Fixes: https://github.com/ros-planning/navigation2/pull/3492
Grr... I wish I could easily test these patches to action locally.
> Change directory to inside checked out repo

- .github/workflows/update_ci_image.yaml
even when github.event_name != 'push', by moving run step to same job as build-push action.
Also set context path provided by checkout action to avoid future nonintuitive behavoir using default Git context, even when the checkout action appears to be being used.
- https://github.com/docker/build-push-action#git-context
- https://github.com/docker/build-push-action#path-context
Fixes:
- https://github.com/ros-planning/navigation2/pull/3494
> Ensure version output is always set

- nav2_collision_monitor/CMakeLists.txt
- nav2_collision_monitor/include/nav2_collision_monitor/collision_monitor_node.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/types.hpp
- nav2_collision_monitor/package.xml
- nav2_collision_monitor/params/collision_monitor_params.yaml
- nav2_collision_monitor/src/collision_monitor_node.cpp
- nav2_collision_monitor/test/collision_monitor_node_test.cpp
- nav2_msgs/CMakeLists.txt
- nav2_msgs/msg/CollisionMonitorState.msg
---
| Ticket(s) this addresses   | #3496  |
| Robotic platform tested on | Dexory Simulation |
---
* Added a new msg in `nav2_msgs` - `CollisionMonitorState.msg`
* Publish CollisionMonitor action state
* Also fixed that the first action will not be printed if it is `DO_NOTHING`
* Also updated the state change logic to check with `polygon_name` instead of `action_type` (To handle multiple `slowdown` polygons correctly)
* Added new topic + param, so need to add that to default configs and documentation page
---
* This PR report the CM's action state change based on the input `cmd_vel`, but I think it will be very useful to publish the polygon state even when the robot is not moving too. …
> Publish collision monitor state

- nav2_collision_monitor/include/nav2_collision_monitor/polygon.hpp
- nav2_collision_monitor/params/collision_monitor_params.yaml
- nav2_collision_monitor/src/collision_monitor_node.cpp
- nav2_collision_monitor/src/polygon.cpp
- nav2_collision_monitor/test/collision_monitor_node_test.cpp
- nav2_collision_monitor/test/polygons_test.cpp
| Ticket(s) this addresses   | #3499 |
| Primary OS tested on | Ubuntu 22.04 w/ ROS2 Rolling built from source (from 20230110) |
| Robotic platform tested on | `colcon test --packages-select nav2_collision_monitor` |
---
* `<polygon_name>.max_points` parameter was renamed to `<polygon_name>.min_points` to track its meaning
* Default value for this parameter was adjusted accordingly to not change default CM's behavior
* Old `<polygon_name>.max_points` is still used  (to be removed in the future releases), but now with deprecation warning, if parameter was set by developer
* New `testPolygonMaxPoints` testcase for `max_points` deprecated parameter
* Update parameter description on CM parameters page
* Switch parameters on …
> Rename max_points to min_points polygon parameter

- nav2_costmap_2d/include/nav2_costmap_2d/layered_costmap.hpp
- nav2_costmap_2d/src/layered_costmap.cpp
---
| Ticket(s) this addresses   | #2508 |
| Primary OS tested on | Ubuntu 22.04 & 20.04  |
| Robotic platform tested on | my hardware robot |
---
addFilter() and resizeMap() can be executed concurrently.
std::vector is unsafe in multithreading.
PR #2512 has already addressed a part of the problem, but did not fix consider filters.
---
> fix data race: addFilter() and resizeMap() can be executed concurrently

- nav2_costmap_2d/src/costmap_2d_ros.cpp
---
| Ticket(s) this addresses   | #2508 |
| Primary OS tested on | Ubuntu 22.04 & 20.04 |
| Robotic platform tested on | my hardware robot |
---
- all filters and plugins have a `layered_costmap_` variable. 
- it's set when `initialize()` is called
- so it's not yet set when the filter/plugin is added to the costmap
- when `resizeMap()` is called after a filter/plugin was added but before it was initialized a segmentation fault could happen.
---
> fix data race: prohibit resizeMap() during plugin/filter initialization

- .devcontainer/devcontainer.json
- .devcontainer/on-create-command.sh
- .devcontainer/update-content-command.sh
This mounts the overlay workspace into a Dev Container via a volume, instead of relying on the write layers of the container.
This is an ergonomic improvement over previously storing workspace artifacts directly in the container file-system, as they are then inherently tied to the life-cycle of that particular container, and subsequently not persistent across Dev Container rebuilds. This can be a hassle when wanting to modify the Dev Container locally, a modification that would then necessitate rebuilding the entire Nav2 overlay workspace. While the existing use of ccache and it's own persistent volume help to lessen the compilation time, such re-compilation is often needless when modifying and testing dev container changes, such as those related to VS Code or development tools.
This is …
> Mount overlay workspace into Dev Container via volume

- nav2_simple_commander/launch/assisted_teleop_example_launch.py
- nav2_simple_commander/launch/follow_path_example_launch.py
- nav2_simple_commander/launch/inspection_demo_launch.py
- nav2_simple_commander/launch/nav_through_poses_example_launch.py
- nav2_simple_commander/launch/nav_to_pose_example_launch.py
- nav2_simple_commander/launch/picking_demo_launch.py
- nav2_simple_commander/launch/recoveries_example_launch.py
- nav2_simple_commander/launch/security_demo_launch.py
- nav2_simple_commander/launch/waypoint_follower_example_launch.py
| Ticket(s) this addresses   | #3523 |
---
Add headless and use_rviz LaunchConfigurations in nav2_simple_commander demo launch files, for whether to start rviz or gzclient, to simplify their use in headless environments:
- https://github.com/ros-planning/navigation2/pull/3523
None, as the defaults maintain the existing launch file behavior.
---
> Add headless and use_rviz LaunchConfigurations to demo launch files

- nav2_smac_planner/src/node_lattice.cpp
- nav2_smac_planner/test/test_nodelattice.cpp
This fixes State-Lattice planner out-of-bounds array crashes due to floating-point precision loss. This appears in some cases, e.g. when robot has custom footprint and `allow_reverse_expansion` option is enabled.
---
| Ticket(s) this addresses   | #3528 |
| Primary OS tested on | Ubuntu 22.04 w/ ROS2 Rolling built from sources |
| Robotic platform tested on | `colcon test --packages-select nav2_smac_planner` |
---
* Fixed State-Lattice planner crashes appeared due to floating-point precision loss for some cases
* Added a regression testcase, repeating the situation reported in origin #3528 ticket, which crashes on vanilla branch and working on fixed one.
N/A
---
No future work is expected
> Fix State-Lattice planner crashes due to FP precision loss

- nav2_velocity_smoother/src/velocity_smoother.cpp
- nav2_velocity_smoother/test/test_velocity_smoother.cpp
---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/3526 |
| Robotic platform tested on | Dexory Sim |
---
Fix https://github.com/ros-planning/navigation2/issues/3526
Tested only in sim, can test on real hardware next week. I would not mind a second pair of eyes / independent test on this one before merging as it is quite critical (in our system it is the last layer before the hardware commands). @richardw347 
With :
```
velocity_smoother = Node(
package='nav2_velocity_smoother',
name='root_velocity_smoother',
executable='velocity_smoother',
parameters=[
{'smoothing_frequency': 20.0},
{'scale_velocities': False},
{'feedback': 'OPEN_LOOP'},
{'max_velocity': …
```
> [velocity_smoother] Fix accel and deccel inverted for negative speeds

- .circleci/config.yml
- .circleci/defaults.yaml
- nav2_msgs/CMakeLists.txt
---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/3533 |
---
Disabled deprecation error on nav2_msgs package to bypass idl issue. https://github.com/ros2/rosidl_typesupport_fastrtps/issues/28
---
> ignore warning

- nav2_bt_navigator/src/bt_navigator.cpp
| Ticket(s) this addresses   | #3545 |
| Robotic platform tested on | gazebo simulation  |
---
* move `declare_parameter("navigators")` in the constructor
* remove useless `default_navigator_types`
> Fix bt_navigator crashes when restarted

- nav2_bringup/launch/tb3_simulation_launch.py
- nav2_bringup/package.xml
| Robotic platform tested on | TB3 Simulation |
---
* I added support at launch time to verify the necessary turtlebot3_gazebo package is installed, preventing a cryptic runtime failure if you forget to install the dependnecy
* I added a dependency in the package.xml on the tb3 model, which is smaller than the suggested method: `sudo apt install ros-<ros2-distro>-turtlebot3*`
before, the launch continues despite errors. Errors are in white and hard to notice. Gazebo launches but is empty. 
```
[spawn_entity.py-3] [ERROR] [1682316083.368866917] [spawn_entity]: Service %s/spawn_entity unavailable. Was Gazebo started with GazeboRosFactory?
[spawn_entity.py-3] [ERROR] [1682316083.369139584] …
```
> Verify tb3 exists at launch time

- tools/underlay.repos
Add ros2/geometry2 to underlay in interim until next rolling sync.
Related:
- https://github.com/ros2/geometry2/pull/601
> Add ros2/geometry2 to underlay

- .circleci/config.yml
to avoid CI timeout issues with CircleCI.
Related:
- https://github.com/ros-planning/navigation2/pull/3543
> Split nav2_system_tests into separate CI jobs

- nav2_simple_commander/nav2_simple_commander/robot_navigator.py
---
| Ticket(s) this addresses   | #3558 |
---
Fixed #3558 for Humble branch as well
> Fix wrong usage of default params in python3 commander API

- .circleci/config.yml
from: https://github.com/ros-planning/navigation2/pull/3554
> Fix typo in config.yml

- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/follow_path_action.hpp
- nav2_behavior_tree/nav2_tree_nodes.xml
- nav2_behavior_tree/plugins/action/follow_path_action.cpp
- nav2_bringup/params/nav2_multirobot_params_1.yaml
- nav2_bringup/params/nav2_multirobot_params_2.yaml
- nav2_bringup/params/nav2_params.yaml
- nav2_controller/include/nav2_controller/controller_server.hpp
- nav2_controller/src/controller_server.cpp
- nav2_msgs/action/FollowPath.action
- nav2_regulated_pure_pursuit_controller/README.md
- nav2_rotation_shim_controller/README.md
- nav2_system_tests/src/costmap_filters/keepout_params.yaml
- nav2_system_tests/src/costmap_filters/speed_global_params.yaml
- nav2_system_tests/src/costmap_filters/speed_local_params.yaml
---
| Robotic platform tested on | Dexory sim |
---
The parameters `goal_checker_plugins` and `controller_plugins` are list of strings, allowing multiple plugin configuration, whereas `progress_checker_plugin` is a single string allowing the declaration of only one goal checker.
This PR initializes the progress checker plugin(s) in the same way as for the goal checker and controller plugins: it is now a list of string and was renamed from `progress_checker_plugin` to `progress_checker_plugins`. This allows the initialization of multiple goal checker that can be chosen from the added `progress_checker_id` field of the `FollowPath` action
This is a breaking …
> [controller_server] [FollowPath] Allow multiple progress checkers

- nav2_mppi_controller/include/nav2_mppi_controller/motion_models.hpp
- nav2_mppi_controller/test/motion_model_tests.cpp
| Ticket(s) this addresses   | [#3579](https://github.com/ros-planning/navigation2/issues/3579) |
| Robotic platform tested on | custom sim |
---
* I fixed a wrong condition in ackerman motion model constraints
> Fix the condition in ackerman motion model constraints

- nav2_smac_planner/README.md
- nav2_smac_planner/include/nav2_smac_planner/a_star.hpp
- nav2_smac_planner/include/nav2_smac_planner/smac_planner_hybrid.hpp
- nav2_smac_planner/src/a_star.cpp
- nav2_smac_planner/src/smac_planner_hybrid.cpp
---
| Robotic platform tested on | Dexory sim |
---
This is a draft adding a `viz_expansions` parameter which when set to true publishes on the topic `/expansions` the path search for the SmacHybrid planner.
This is what I use for debugging planner issues, similarly (and up to date) to what is described in **https://github.com/ros-planning/navigation2/tree/main/nav2_smac_planner** readme.
If there is an interest, I can extend to other Smac planners and make it a proper PR.
WDYT ?
---
> Add viz_expansions parameter for debug

- Dockerfile
Typo from https://github.com/ros-planning/navigation2/pull/3576
> Fix broken symlink for gzweb

- nav2_collision_monitor/include/nav2_collision_monitor/polygon.hpp
- nav2_collision_monitor/src/collision_monitor_node.cpp
- nav2_collision_monitor/src/polygon.cpp
- nav2_collision_monitor/test/polygons_test.cpp
This is the fix for #3590 issue: Collision Monitor to correct polygon vertices to the actual TF state, for the case when this polygon was obtained from another than `base_link` frame. 
---
| Ticket(s) this addresses   | #3590|
| Robotic platform tested on | TB3 simulation, `colcon test --packages-select nav2_collision_monitor`, code coverage |
---
Fix dynamic polygons vertices not updated for different frame
* In `updatePolygon()`, correct `poly_` vertice coordinates to the latest frame state, when polygon is published in another (than `base_frame_id_`) frame
* Re-use `geometry_msgs::msg::PolygonStamped polygon_` to preserve latest dynamic polygon message for this correction
* Call …
> Fix dynamic polygons vertices not updated for different frame

- nav2_map_server/CMakeLists.txt
- nav2_map_server/include/nav2_map_server/costmap_filter_info_server.hpp
- nav2_map_server/src/costmap_filter_info/costmap_filter_info_server.cpp
---
| Ticket(s) this addresses   | [Link to issue](https://github.com/ros-planning/navigation2/issues/3589) |
| Robotic platform tested on | (Turtlebot3 simulation) |
---
---
> Add CostmapFilterInfoServer as a component

- nav2_mppi_controller/src/critics/path_follow_critic.cpp
---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/3480 |
| Robotic platform tested on | Dexory robot |
---
Complementary as https://github.com/ros-planning/navigation2/pull/3484, as discussed a while ago, to be sure to protect against path of length 0 (though this should never happen)
Tests across all critics for path of length 0 and 1
> [MPPI] empty path_follow_critic proper fix

- nav2_collision_monitor/launch/collision_monitor_node.launch.py
- nav2_collision_monitor/params/collision_monitor_params.yaml
This PR fixes Collision Monitor launch-script with:
* Apply to the CM the refactor of `sim_time` usage, introduced in 7703c816a11368fb1a48663dc92e4e93affb637e
* Adding the ability to launch CM as composable node in the container. Enabling this option by-default.
* Adding the support of non-empty root namespace
---
| Ticket(s) this addresses   | #3131, #2750|
| Robotic platform tested on | standard Gazebo TB3 simulation |
---
* No documentation updates required for sim time refactoring.
* Collision Monitor launch-file by-default also launch CM and CM's lifecycle manager in composable container, so all previously described in tutorial commands will remain correct and untouched. Please, …
> Refactor sim_time and composable node usage in Collision Monitor

- nav2_common/cmake/nav2_package.cmake
- nav2_core/include/nav2_core/behavior_tree_navigator.hpp
- nav2_dwb_controller/costmap_queue/include/costmap_queue/map_based_queue.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/critic_manager.hpp
- nav2_mppi_controller/test/critic_manager_test.cpp
- nav2_system_tests/src/behavior_tree/dummy_action_server.hpp
- nav2_system_tests/src/behavior_tree/dummy_service.hpp
---
| Ticket(s) this addresses   | NONE |
| Robotic platform tested on | NONE |
---
Added the flag non-virtual destructor to the compile flags. This flag warns the user if a class with virtual functions has a non-virtual destructor. This helps catch hard to track down memory errors.
---
Future compile flags could be added from https://github.com/cpp-best-practices/cppbestpractices/blob/master/02-Use_the_Tools_Available.md. 
Adding flags from this list might be a good first issue.
> Compile flags non-virtual-destructor

- nav2_common/cmake/nav2_package.cmake
---
| Ticket(s) this addresses   | [(discovered here)](https://github.com/ros-planning/navigation2/pull/3609#issuecomment-1585120435) |
---
The recently added flag `Wnon-virtual-dtor` only applies to C++. It was applied to the whole build, rather than only the targets that are compiled with C++. Since `nav2_amcl` has C sources, this was failing on my computer.
Reference: https://stackoverflow.com/questions/25525047/cmake-generator-expression-differentiate-c-c-code
To test the generator is still applying the flag, I undid some of the changes earlier, such as adding the `virtual` keyword to destructor for `NavigatorBase`, and it failed to compile, as desired.
> Only apply Wnon-virtual-dtor if the compile language is CXX

- nav2_amcl/src/pf/eig3.c
- nav2_common/cmake/nav2_package.cmake
- nav2_constrained_smoother/include/nav2_constrained_smoother/smoother.hpp
- nav2_costmap_2d/plugins/denoise_layer.cpp
- nav2_costmap_2d/test/integration/test_costmap_topic_collision_checker.cpp
- nav2_dwb_controller/dwb_core/src/dwb_local_planner.cpp
- nav2_dwb_controller/dwb_critics/test/obstacle_footprint_test.cpp
- nav2_navfn_planner/src/navfn.cpp
- nav2_regulated_pure_pursuit_controller/src/path_handler.cpp
- nav2_smoother/test/test_smoother_server.cpp
- nav2_system_tests/CMakeLists.txt
---
| Ticket(s) this addresses   | None, Adding compiler warning protection and fixing the internal issues |
---
* Add in Wshadow: https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wshadow
* Fix shadowing warnings in the build
* Add a patch in nav2_system_tests for missing dependency on pluginlib
* Treat pluglinlib headers as SYSTEM so we don't get shadow warnings on them in nav2
* Remove the workaround for pluginlib once pluginlib removes the Wshadow problems. https://github.com/ros/pluginlib/issues/248
> Fix Wshadow errors and enforce it

- nav2_common/cmake/nav2_package.cmake
- nav2_costmap_2d/include/nav2_costmap_2d/denoise/image_processing.hpp
- nav2_mppi_controller/test/critic_manager_test.cpp
---
| Ticket(s) this addresses   | (None) |
---
Add Wnull-derefence warning  to compiler and fix it
> add -Wnull-dereference and fix warnings

- nav2_mppi_controller/README.md
- nav2_mppi_controller/include/nav2_mppi_controller/critics/path_angle_critic.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp
- nav2_mppi_controller/src/critics/constraint_critic.cpp
- nav2_mppi_controller/src/critics/path_angle_critic.cpp
- nav2_mppi_controller/test/utils_test.cpp
@doisyg please review
This adapts https://github.com/ros-planning/navigation2/pull/3454 for optionality and not using the path angles -- which might not be populated if not using the smac planners and/or including one of the optional Path Smoothers.
First step in path inversion work this week.
This method includes a check on if reversing is possible at all at the controller level. If not, uses only the forward values. It also has a new parameter (docs PR to match to be linked) if forward is preferred. That way, we consider using the inverted angle schema **only** when reversing is possible and that there genuinely is no preference one way or another. Otherwise, if there is a preference, we do penalize to encourage rotating to go forward.   
I also removed the use of the path point's …
> updating mppi's path angle critic for optional bidirectionality

- nav2_controller/src/controller_server.cpp
- nav2_planner/src/planner_server.cpp
https://github.com/ros-planning/navigation2/issues/3629
> Fixing 3629

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/3626 |
---
Used suggested solution to only print warning message if parameter was given a default value. 
---
> correct error message

- nav2_costmap_2d/include/nav2_costmap_2d/cost_values.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_layer.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/obstacle_layer.hpp
- nav2_costmap_2d/plugins/obstacle_layer.cpp
- nav2_costmap_2d/plugins/voxel_layer.cpp
- nav2_costmap_2d/src/costmap_layer.cpp
- nav2_costmap_2d/test/integration/obstacle_tests.cpp
---
| Ticket(s) this addresses   | [#3603](https://github.com/ros-planning/navigation2/issues/3603) |
---
* I added an updateWithMaxWithoutUnknownOverride method to the CostmapLayer
* I added an value option to the ObstacleLayer's  combination_method parameter that uses the previous method.
* Added new parameter value, so need to add that to the documentation page
* 
---
> Option for ObstacleLayer to not override StaticLayer's unknown parts

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
---
| Ticket(s) this addresses   | [#3633](https://github.com/ros-planning/navigation2/issues/3633) |
---
* Change "Failed to get error code: %s from blackboard" log from ERROR to DEBUG
* Add INFO log on initialization about which errors codes are being used to help debug
* 
---
> Let Navigators have different error codes

- nav2_mppi_controller/README.md
- nav2_mppi_controller/include/nav2_mppi_controller/critics/goal_critic.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/critics/path_follow_critic.hpp
- nav2_mppi_controller/src/critics/goal_angle_critic.cpp
- nav2_mppi_controller/src/critics/goal_critic.cpp
- nav2_mppi_controller/src/critics/path_align_critic.cpp
- nav2_mppi_controller/src/critics/path_angle_critic.cpp
- nav2_mppi_controller/src/critics/path_follow_critic.cpp
- nav2_mppi_controller/src/critics/prefer_forward_critic.cpp
- nav2_mppi_controller/test/critics_tests.cpp
CC @doisyg for testing
If this works
> adapting goal critic for speed to goal

- nav2_costmap_2d/plugins/costmap_filters/costmap_filter.cpp
| Primary OS tested on | Ubuntu 23 with gcc12 |
---
In NAV2, this warning is treated as an error. Uninitialized doubles are bad, and the compiler can't guarantee anything before it's passed in to `get_parameter`.
> Fix uninitialized value

- nav2_rviz_plugins/src/nav2_panel.cpp
---
Fixes this warning
```
[rviz2-1] [WARN 1687712615.161990346 rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
```
Node arguments are not parsed correctly when given as a single string.
---
> Fix rviz panel node arguments

- nav2_constrained_smoother/CMakeLists.txt
| Primary OS tested on | Ubuntu 23 with GCC12 |
---
* Ceres has compiler warnings that fail nav2 build with werr
* This treats them as SYSTEM includes so we can ignore them
> Fix CERES failing build from compilation warnings

- nav2_behavior_tree/test/plugins/decorator/test_single_trigger_node.cpp
- nav2_smoother/test/test_smoother_server.cpp
Requires https://github.com/BehaviorTree/BehaviorTree.CPP/pull/579 to be merged + released to build but resolves https://github.com/ros-planning/navigation2/issues/3310
Fixes 
- CI failures related to BT.CPP unit tests
- CI failures related to the smoother server
> CI test fixing for BT.CPP (paired with BehaviorTree.CPP/579)

- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/navigate_through_poses_action.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/condition/are_error_codes_present_condition.hpp
- nav2_behavior_tree/test/plugins/condition/test_are_error_codes_present.cpp
- nav2_behavior_tree/test/plugins/condition/test_would_a_controller_recovery_help.cpp
- nav2_behavior_tree/test/plugins/condition/test_would_a_planner_recovery_help.cpp
- nav2_behavior_tree/test/plugins/condition/test_would_a_smoother_recovery_help.cpp
- nav2_mppi_controller/test/utils_test.cpp
> fix some new build warnings from sync

- nav2_costmap_2d/test/integration/test_costmap_2d_publisher.cpp
---
---
Sometimes the costmap data will be empty. Since the checks are assuming it be populated an index is accessed that is out of range. To resolve this, a check has been put in place to verify that costmap data has been correctly populated.
---
> Fix costmap publisher test

- nav2_behavior_tree/CMakeLists.txt
- nav2_behavior_tree/test/CMakeLists.txt
---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/3683 |
| Robotic platform tested on | Built with `--cmake-args "-DBUILD_TESTING=OFF"` and verified that `install/nav2_behavior_tree/include` contains the utils folder |
---
- Moved nav2_behavior_tree/test/utils/ installs to be outside of BUILD_TESTING
---
> Install nav2_behavior_tree utils outside of BUILD_TESTING

- nav2_collision_monitor/include/nav2_collision_monitor/collision_monitor_node.hpp
- nav2_collision_monitor/params/collision_monitor_params.yaml
- nav2_collision_monitor/src/collision_monitor_node.cpp
- nav2_util/include/nav2_util/robot_utils.hpp
Here are various fixes for CM, that have been detected recently during CM PR's review
* Fix `max_points` -> `min_points` in parameters
* Move `robot_utils.hpp` include to the source where it is actually using
* Remove double-description of `getTransform()` in header
---
| Robotic platform tested on | `colcon test --packages-select nav2_collision_monitor` (no regressions) |
---
> Collision Monitor fixups

- nav2_bringup/launch/bringup_launch.py
- nav2_bringup/launch/localization_launch.py
- nav2_bringup/launch/navigation_launch.py
- nav2_bringup/launch/slam_launch.py
- nav2_collision_monitor/launch/collision_monitor_node.launch.py
| Robotic platform tested on | gazebo simulation of turtlebot |
---
- Enable substitution in parameter file. For example, you can write the following
```yaml
default_nav_to_pose_bt_xml: $(find-pkg-share my_package)/behavior_tree/my_nav_to_pose_bt.xml
```
---
> Use ParameterFile (allow_substs)

- nav2_velocity_smoother/src/velocity_smoother.cpp
| Ticket(s) this addresses   | Fix latest issue after #3512 |
| Robotic platform tested on | our simulation |
---
* Moved last_cmd update before deadband is applied. 
This will fix the velocity smoother being stuck when the deadband is too high.
> Fix the velocity smoother being stuck when the deadband is too high

- nav2_mppi_controller/src/critics/obstacles_critic.cpp
- nav2_smac_planner/include/nav2_smac_planner/collision_checker.hpp
- nav2_smac_planner/src/collision_checker.cpp
- nav2_smac_planner/src/smac_planner_2d.cpp
- nav2_smac_planner/src/smac_planner_hybrid.cpp
- nav2_smac_planner/src/smac_planner_lattice.cpp
- nav2_smac_planner/test/test_a_star.cpp
- nav2_smac_planner/test/test_collision_checker.cpp
- nav2_smac_planner/test/test_node2d.cpp
- nav2_smac_planner/test/test_nodehybrid.cpp
- nav2_smac_planner/test/test_nodelattice.cpp
- nav2_smac_planner/test/test_smoother.cpp
Resolves https://github.com/ros-planning/navigation2/issues/3580 via
- Warnings printed clearly about the error and point to how to fix it
- Handles the case so that when it happens, we do fully SE2 collision check every time due to issue
> adding error warnings around incorrect inflation layer setups in MPPI and Smac which impact performance substantially

- nav2_velocity_smoother/src/velocity_smoother.cpp
- nav2_velocity_smoother/test/test_velocity_smoother.cpp
Per https://github.com/ros-planning/navigation2/issues/3520
> adding checks on config and dynamic parameters for proper velocity and acceleration limits

- nav2_bringup/rviz/nav2_default_view.rviz
- nav2_bringup/rviz/nav2_namespaced_view.rviz
- nav2_bringup/worlds/world_only.model
---
---
* The coordinate frames in rviz and gazebo are oriented such that the positive x-axis points right
* This could simplify things for beginner users.
Is there maybe some tutorial that references this?
---
None
> Same orientation of coordinate frames in rviz ang gazebo

- nav2_system_tests/src/costmap_filters/keepout_params.yaml
- nav2_system_tests/src/costmap_filters/test_keepout_launch.py
- nav2_system_tests/src/costmap_filters/test_speed_launch.py
1. Set forward_prune_distance to `1.0` to robot not getting lost during keepout zone avoidance
2. Correct map name for costmap filter tests
---
| Robotic platform tested on | local and `navigation2:main` docker colcon tests |
---
Fixes for Costmap Filter keepout and speed flaky system tests. The following issues were resolved:
Incorrect map, passed through ROS-parameters gave lack of sensor points for AMCL to synchronize on:
This caused loosing of localization accuracy and robot "twitching" on the map, that sometimes gave incorrect number of speed area entries in speed filter system tests, that could be confirmed by the following logs:
``` …
```
> Fix flaky costmap filters tests

- nav2_planner/src/planner_server.cpp
---
---
- Before the change, IsPathValid sometimes missed obstacles.
---
> Fix missing mutex in PlannerServer::isPathValid

- nav2_behaviors/include/nav2_behaviors/plugins/wait.hpp
- nav2_behaviors/plugins/wait.cpp
---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/3780 |
| Robotic platform tested on | Dexory Simulation |
---
Use ros time that automatically uses simulation time if `use_sim_time = true` so waiting time is coherent with simulation time
Migration guide ?
---
Solve all cases listed here: https://github.com/ros-planning/navigation2/issues/3303
> use ros clock for wait

- nav2_controller/src/controller_server.cpp
- nav2_costmap_2d/src/costmap_2d_ros.cpp
- nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager.hpp
- nav2_lifecycle_manager/src/lifecycle_manager.cpp
- nav2_planner/src/planner_server.cpp
- nav2_util/include/nav2_util/lifecycle_node.hpp
- nav2_util/src/lifecycle_node.cpp
- nav2_util/test/test_lifecycle_node.cpp
Backporting important elements of https://github.com/ros-planning/navigation2/commit/4aaefad1162d5edcba26878cdb4a2f11322ada99 by @mmattb
> [Humble] Fixing 3768: planner server lifecycle transition down

- nav2_smac_planner/include/nav2_smac_planner/a_star.hpp
- nav2_smac_planner/include/nav2_smac_planner/node_basic.hpp
- nav2_smac_planner/include/nav2_smac_planner/node_hybrid.hpp
- nav2_smac_planner/include/nav2_smac_planner/types.hpp
- nav2_smac_planner/src/a_star.cpp
- nav2_smac_planner/src/node_basic.cpp
- nav2_smac_planner/src/node_hybrid.cpp
- nav2_smac_planner/src/node_lattice.cpp
- nav2_smac_planner/src/smac_planner_hybrid.cpp
- nav2_smac_planner/test/test_a_star.cpp
- nav2_smac_planner/test/test_nodehybrid.cpp
- nav2_smac_planner/test/test_smoother.cpp
- tools/planner_benchmarking/README.md
Per https://github.com/ros-planning/navigation2/issues/3172, we sometimes see zig-zagging behavior due to the discrete increments of angular quanitizations not fully utilizing the requested angular resolution. This issue is written out in detail in this comment: https://github.com/ros-planning/navigation2/issues/3172#issuecomment-1672249118
This solves that by creating additional motion primitives to fill in the angular space for each expansion to hit every angular bin possible. As a result, keeping angular bin densities of 64/72 as previously utilized will create **many** more new primitives for certain configurations than previously. It may be wise to reduce your resolution to not create additional primitives that your application does not require.
TODO
> Fix zig-zaggin in smac planner due to discrete angular bin quantizations

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
- nav2_common/nav2_common/launch/rewritten_yaml.py
- nav2_system_tests/src/waypoint_follower/test_case_py.launch
- nav2_system_tests/src/waypoint_follower/tester.py
- nav2_waypoint_follower/src/waypoint_follower.cpp
* New RewrittenYaml ability to add non-existing parameters
* Prune distance fix for WPF test
* Treat UNKNOWN status as error in WPF
* Clear error codes after BT run
* Remove unnecessary setInitialPose() from WPF test
---
| Ticket(s) this addresses   | #3765 |
| Robotic platform tested on | colcon test |
---
The following problems described in #3765, were fixed:
| Problem | Solution description |
| ------------- | ------------- |
| Problem1: No action | Return back BT action server timeout to 15 minutes: #3787 |
| Problem1: No action  | New RewrittenYaml ability to add non-existing parameters & prune distance fix for lower probability of recovery situations |
| Problem1: No action | …
> Fixes for flaky WPF test

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
- nav2_behaviors/include/nav2_behaviors/timed_behavior.hpp
- nav2_bringup/params/nav2_multirobot_params_1.yaml
- nav2_bringup/params/nav2_multirobot_params_2.yaml
- nav2_bringup/params/nav2_multirobot_params_all.yaml
- nav2_bringup/params/nav2_params.yaml
- nav2_controller/src/controller_server.cpp
- nav2_planner/src/planner_server.cpp
- nav2_smoother/src/nav2_smoother.cpp
- nav2_waypoint_follower/src/waypoint_follower.cpp
---
| Ticket(s) this addresses   | #3765  |
| Primary OS tested on | Ubuntu 22.04 (docker) |
| Robotic platform tested on | gazebo turtlebot |
---
* As described in #3765, the waypoint follower is getting `UNKNOWN` results if the call to `/navigate_to_pose` takes more than 10 seconds to complete. @AlexeyMerzlyakov traced this back the problem to https://github.com/ros2/rcl/pull/1012. I'm exposing the result timeout of the action server as a parameter in the `bt_navigator` node following @AlexeyMerzlyakov suggestion in #3765
* Added the new parameter `action_server_result_timeout`, so need to add that to default configs and documentation page
---
> Expose action server result timeout as a parameter in bt navigator servers

- nav2_simple_commander/README.md
- nav2_simple_commander/nav2_simple_commander/robot_navigator.py
>  Using Simple Commander API for multi robot systems

- nav2_mppi_controller/include/nav2_mppi_controller/critic_manager.hpp
Added the missing empty virtual destructor which prevented package building of nav2_mppi_controller. 
| Primary OS tested on | Ubuntu 22.04 
| Robotic platform tested on | ROS2 Humble + simulation setup used -> NeoBotix sim mp400 robot
---
Added the missing empty virtual destructor which prevented package building of nav2_mppi_controller. 
A simple enough one-liner fix which allowed for the package to build
No documentation update required
---
> Added missing destructor to MPPI critic manager

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
- nav2_bt_navigator/include/nav2_bt_navigator/bt_navigator.hpp
- nav2_bt_navigator/src/bt_navigator.cpp
- nav2_util/CMakeLists.txt
- nav2_util/include/nav2_util/node_utils.hpp
- nav2_util/package.xml
- nav2_util/test/test_node_utils.cpp
Per https://github.com/ros-planning/navigation2/issues/3800
> adding copy all params primitive for BT navigator (to ingest into rclcpp)

- nav2_controller/src/controller_server.cpp
Per https://github.com/ros-planning/navigation2/issues/3802
> removing deprecated progress single checker param

- nav2_mppi_controller/src/critics/obstacles_critic.cpp
otherwise the controller crashes at ObstaclesCritic::costAtPose because x_i and y_i isn't initialized.
> mppi: return NO_INFORMATION when the checked point is outside the costmap

- nav2_behavior_tree/README.md
The documentation link was broken  ¯\\_(ツ)_/¯ not much to say about
> Fix broken behaviortree doc link

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
- missing letter in comment
- `virtual BT::NodeStatus on_cancelled()` has a similar comment which is correct
> Fix typo in Doxygen comment

- nav2_behavior_tree/README.md
I fixed the broken link a few days ago in #3822 but just realized that the new one points to the BT.CPPv4.3 docs and nav2 is currently using v3.8
This might result in some confusion if:
- using this link to continue browsing the BT docs since there are some differences between v3 vs. v4
- the latest doc version is bumped to an incompatible version and not comparable to v3
Not sure if it's worth the update :) your choice regardless
> adjust link to point to v3.8 of behavior tree docs instead of v4.3

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
- nav2_behavior_tree/test/plugins/action/test_bt_action_node.cpp
---
| Ticket(s) this addresses   | #3848 |
| Primary OS tested on | Ubuntu 22.04.3 LTS (Jammy Jellyfish) |
---
* Fixed the bug in halt function inside
nav2_behavior_tree/plugin/action/bt_action_node.hpp
* Added new case to nav2_behavior_tree/plugin/action/bt_action_node.hpp
for testing the scenario to cancel
* Refactored existing cases in
nav2_behavior_tree/plugin/action/bt_action_node.hpp
---
Test this on simulation platform.
---
> Fix bug in nav2_behavior_tree/bt_action_node

- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/wait_action.hpp
- nav2_behavior_tree/plugins/action/wait_action.cpp
- nav2_behavior_tree/test/plugins/action/test_wait_action.cpp
- nav2_bt_navigator/behavior_trees/nav_to_pose_with_consistent_replanning_and_if_path_becomes_invalid.xml
- nav2_bt_navigator/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml
- nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml
- nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_goal_patience_and_recovery.xml
- nav2_bt_navigator/behavior_trees/navigate_w_recovery_and_replanning_only_if_path_becomes_invalid.xml
---
---
wait_duration port for Wait node is an integer, so if we pass something like 1.3 or 2.42 than it will automatically cast to nearest integer value, so i changed type of this port from int to double.
---
> In wait_action node change duration type from int to double

- nav2_controller/src/controller_server.cpp
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp
- nav2_costmap_2d/src/costmap_2d_ros.cpp
- nav2_costmap_2d/test/unit/CMakeLists.txt
- nav2_costmap_2d/test/unit/lifecycle_test.cpp
- nav2_planner/src/planner_server.cpp
| Ticket(s) this addresses   | #3749 |
| Robotic platform tested on | only tested without robot by optionally manually providing the transform |
---
* Previously the `on_activate` method of the costmap was blocking indefinitely if the transform from the robot base frame to the global frame is not available
* This adds a timeout so that the transition from `configured` to `active` fails if the transform is not available
* The timeout can be configured by a costmap parameter
* The controller server transition from `configured` to `active` fails if the corresponding costmap transitions fails
* There is a new costmap parameter: `wait_for_transforms_timeout`
---
> Add a timeout to the wait for transforms step of the costmap activation.

- nav2_costmap_2d/src/costmap_2d.cpp
- nav2_mppi_controller/src/controller.cpp
- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
- nav2_rotation_shim_controller/src/nav2_rotation_shim_controller.cpp
---
| Ticket(s) this addresses   | No tickets known |
| Robotic platform tested on | Peanut's robot (sim) |
---
* Protect costmap reads with the existing mutex.
* Otherwise costmap can be read during a map update and return 0.
* No documentation changes needed.
---
* None expected.
> Use mutex to protect costmap reads.

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
- nav2_collision_monitor/src/collision_monitor_node.cpp
- nav2_costmap_2d/test/module_tests.cpp
- nav2_costmap_2d/test/unit/binary_filter_test.cpp
- nav2_costmap_2d/test/unit/keepout_filter_test.cpp
- nav2_costmap_2d/test/unit/speed_filter_test.cpp
- nav2_mppi_controller/test/utils_test.cpp
- nav2_smac_planner/include/nav2_smac_planner/thirdparty/robin_hood.h
- nav2_system_tests/src/behaviors/spin/spin_behavior_tester.cpp
- nav2_voxel_grid/include/nav2_voxel_grid/voxel_grid.hpp
- nav2_waypoint_follower/include/nav2_waypoint_follower/plugins/photo_at_waypoint.hpp
- fixing some minor typos in the comments
- no grammatical changes
---
> fix code comment typos

- nav2_costmap_2d/include/nav2_costmap_2d/denoise/image.hpp
So Sorry, I misunderstood something and compared `humble` fork with `main` fork by mistake.
It should be right this time.   #3891
> Adjust the Variable types in Nav2_costmap_2d pkg in [nav2_humble]  #3891

- nav2_bringup/launch/bringup_launch.py
- nav2_bringup/launch/cloned_multi_tb3_simulation_launch.py
Hello, I'm opening a PR instead of a ticket so the pipeline is also triggered and we can discuss further
This sounds pretty strange, but the reason is quite simple:
The CI is using [`ghcr.io/ros-planning/navigation2:main`](https://github.com/ros-planning/navigation2/blob/a1c9fd5ad29bb00e40ce6e696d899a2bcd50cde5/.circleci/config.yml#L485C23-L485C23
) as the base image, which is based on `rolling`.
By doing a simple docker run in such a container one can immediately see all the plugins that are installed there:
```
python3-flake8/now 4.0.1-2 all [installed,local]
python3-flake8-builtins/now 1.5.3-3 all [installed,local]
python3-flake8-comprehensions/now 3.8.0-1 all [installed,local]
python3-flake8-docstrings/now 1.6.0-1 all [installed,local]
python3-flake8-import-order/now 0.18.1-2 all …
```
> Fix nav2_bringup flake8 tests proposal

- nav2_mppi_controller/CMakeLists.txt
- nav2_mppi_controller/test/noise_generator_test.cpp
---
| Ticket(s) this addresses   | #3926 |
| Primary OS tested on | ubuntu 22.04 |
| Robotic platform tested on | `None` |
---
fix build fail when source build with apt pkg overriding.
I fix some CMakeLists of mppi controller, and add missing include in mppi test
---
> fix build mppi

- nav2_regulated_pure_pursuit_controller/README.md
- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/parameter_handler.hpp
- nav2_regulated_pure_pursuit_controller/src/parameter_handler.cpp
- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
- nav2_regulated_pure_pursuit_controller/test/test_regulated_pp.cpp
Docs PR: https://github.com/ros-planning/navigation.ros.org/pull/486
CC @doisyg @vinnnyr 
Thanks @Aposhian for this feature and happy to now make it an always-on part of the code :-)
> removing RPP's use_interpolation param: always on

- nav2_amcl/src/sensors/laser/beam_model.cpp
| Robotic platform tested on | Data-driven benchmark |
---
Pretty much what the title says. I accidentally came across this bug while running AMCL against a dataset with LaserScan messages that happened to bear NaNs every now and then.
Here I apply the same NaN check that the other sensor models use, for consistency.
None.
---
None.
> Handle NaNs in AMCL beam sensor model

- nav2_mppi_controller/include/nav2_mppi_controller/critics/obstacles_critic.hpp
- nav2_mppi_controller/src/critics/obstacles_critic.cpp
---
| Ticket(s) this addresses   | No known tickets |
| Robotic platform tested on |Peanut's in-house robot (sim) |
---
* Inscribed/Circumscribed costs must be updated to take into account the current shape of the robot.
* `ObstaclesCritic::findCircumscribedCost()` was only being called once, in initialize()
* in `initialize()`, `findCircumscribedCost()` uses placeholder inner/outer radius values which come from` robot_radius`.
* `findCircumscribedCost()` was never called again, and the circumscribed cost was never updated based on the footprint.
* depending on the value of `robot_radius`, this could cause too much or too little footprint checking in `costAtPose()`
* No documentation changes. …
> Fix for  robot footprint collision in obstacles critic

- nav2_behavior_tree/include/nav2_behavior_tree/behavior_tree_engine.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
- nav2_behavior_tree/src/behavior_tree_engine.cpp
---
---
As discussed, draft to open the discussion.
Update to use the the native cpp library `haltTree()`  method in `BehaviorTreeEngine::haltAllActions`.
https://github.com/BehaviorTree/BehaviorTree.CPP/blob/61c55ed720e0630f211686b3830942ae27e90501/include/behaviortree_cpp_v3/bt_factory.h#L162-L179
Before this change, only the active BT node was halted when finishing the action. After this change, all BT nodes `halt()` methods are called. This is very convenient to handle cleaning operation (switch off your lights when leaving) in halt().
Also updated …
> Use native library haltTree()

- nav2_velocity_smoother/src/velocity_smoother.cpp
---
| Robotic platform tested on | Dexory's Robot |
---
On dynamic change of `max_accel` or `max_decel` parameters, invalid values (wrong sign) were triggering an error message and returning `false`, but the invalid values were still set internally.
This PR fixes it. `break` was not used as we are in a nested for loop there.
---
> [velocity smoother] Protect properly againt invalid max_accel and max_decel values

- README.md
---
| Info |  |
| Primary OS tested on | Github |
---
* Currently the `README.md` is linking to an invalid page in the docs (404 error) for build and install instructions. 
* Changed links from `https://navigation.ros.org/build_instructions/index.html` to the Build and Install page in `https://navigation.ros.org/development_guides/build_docs/index.html`.
N/A 
---
> Fixed links for Install and build in README

- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
- nav2_util/include/nav2_util/geometry_utils.hpp
@Aposhian  @vinnnyr  @doisyg  I could use a sanity check here as I'm proposing a solution to https://github.com/ros-planning/navigation2/issues/3089.
Previously, cusps that involve in-place rotations from the state lattice planner are ignored. This is an attempted solution which I don't think has any negative side effects, but its subtle and worth expanding upon for visibility and understandability.
Previously, we check the dot project is negative, meaning that we have a discontinuity in the path that is a direction change. Since in place rotations have the same position, the dot product is `0` which isn't triggered.  That's a problem.
So, I adjusted a new check if we're `0` and that the orientations of the poses are different -- that way if we simply have 2 overlapping exactly same …
> [RPP] Adding support for rotate in place cusps

- nav2_util/include/nav2_util/base_footprint_publisher.hpp
- nav2_util/src/CMakeLists.txt
- nav2_util/src/base_footprint_publisher.cpp
- nav2_util/test/CMakeLists.txt
- nav2_util/test/test_base_footprint_publisher.cpp
Required https://github.com/ros2/geometry2/pull/632
Adds a `nav2_util` to take the `base_link` and automatically publish `base_footprint` synchronized with it that has Z, Pitch, and Roll removed so that users can have 3D state estimation but have a 2D footprint to use in navigation, visualization, or other needs in SE2 space.
> adding base footprint publisher to nav2_util

- nav2_bringup/params/nav2_params.yaml
- nav2_controller/include/nav2_controller/controller_server.hpp
- nav2_controller/src/controller_server.cpp
- nav2_util/include/nav2_util/node_thread.hpp
- nav2_util/include/nav2_util/simple_action_server.hpp
- nav2_util/src/node_thread.cpp
Requires modifying `/etc/security/limits.conf` with 
```
<username> hard rtprio 99
<username> soft rtprio 99
```
to give the userspace the permissions to set thread priorities. After which, enable `use_realtime_priority` in the controller server to have it use elevated permissions to meet scheduling deadlines of the sensitive server 
Docs PR: https://github.com/ros-planning/navigation.ros.org/pull/482
> Enabling soft realtime prioritization to the Controller Server

- nav2_smac_planner/include/nav2_smac_planner/a_star.hpp
- nav2_smac_planner/include/nav2_smac_planner/node_basic.hpp
- nav2_smac_planner/include/nav2_smac_planner/node_lattice.hpp
Just some very basic fixes for outdated doxygen comments
> fix a few outdated comments in smac planners

- nav2_collision_monitor/src/collision_monitor_node.cpp
- nav2_util/include/nav2_util/node_utils.hpp
- nav2_util/include/nav2_util/simple_action_server.hpp
- nav2_util/src/node_utils.cpp
- nav2_velocity_smoother/src/velocity_smoother.cpp
Per https://github.com/ros-planning/navigation2/issues/3974
> adding soft realtime prioritization for collision monitor and velocity smoother

- nav2_dwb_controller/dwb_plugins/include/dwb_plugins/kinematic_parameters.hpp
- nav2_dwb_controller/dwb_plugins/include/dwb_plugins/xy_theta_iterator.hpp
- nav2_dwb_controller/dwb_plugins/src/xy_theta_iterator.cpp
---
---
[isValidVelocity](https://github.com/ros-planning/navigation2/blob/main/nav2_dwb_controller/dwb_plugins/src/xy_theta_iterator.cpp#L95) should not be in xy_theta_iterator. It is only related to kineamtic_parameters and should be made available for use without xy_theta_iterator. In ROS1 (robot_navigation) this also used to be in [kinematic_parameters](https://github.com/locusrobotics/robot_navigation/blob/noetic/dwb_plugins/src/kinematic_parameters.cpp#L116). 
If you decide to keep the function in xy_theta_iterator you should cherry-pick the first commit of this pr which fixes a small bug that currently has no effect.
---
> Move isValidVelocity back to kinematic_parameters

- nav2_constrained_smoother/src/constrained_smoother.cpp
- nav2_constrained_smoother/test/test_constrained_smoother.cpp
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_publisher.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_subscriber.hpp
- nav2_costmap_2d/src/costmap_2d_publisher.cpp
- nav2_costmap_2d/src/costmap_subscriber.cpp
- nav2_costmap_2d/src/footprint_collision_checker.cpp
- nav2_costmap_2d/test/integration/CMakeLists.txt
- nav2_costmap_2d/test/integration/test_costmap_subscriber.cpp
- nav2_costmap_2d/test/integration/test_costmap_topic_collision_checker.cpp
- nav2_msgs/CMakeLists.txt
- nav2_msgs/msg/CostmapUpdate.msg
- nav2_smoother/src/simple_smoother.cpp
- nav2_smoother/test/test_smoother_server.cpp
---
| Ticket(s) this addresses   | #3732  |
---
* Adding new msg type **CostmapUpdate.msg**,
* Adding **CostmapUpdate** publisher to  **Costmap2DPublisher** class,
* Re-implementation of the **CostmapSubscriber** class to support the **CostmapUpdate** msg. 
---
* I see a lot of redundancy in **Costmap2DPublisher** class while creating the msgs, adding methods that are responsible for populating msgs and return the unique ptr to msgs might improve the code readability
> 3732 costmap raw update msgs rebased (fixes github issues with PR #3948)

- nav2_costmap_2d/src/costmap_2d.cpp
This commit updates the costmap_2d.cpp file to fix a bug where the costmap size wasn't appropriately updated. Two new lines of code have been added to ensure the size of the costmap is correctly configured each time it's instantiated.
---
| Ticket(s) this addresses   | #4014 |
---
---
> Synchronize map size information during map initialization

- nav2_costmap_2d/src/costmap_2d_ros.cpp
---
| Ticket(s) this addresses   | #4005 |
| Primary OS tested on | all |
| Robotic platform tested on |  gazebo simulation of Tally |
---
As the issue #4005 showed:
If user-misconfiguration (user wrongly set the height or the width of costmap to be negative or zero) existed, the memory usage would sharply increase and even make user's equipment unable to continue working.
so I added some `if` condition in function `Costmap2DROS::getParameters()` in costmap_2d_ros to avoid such unexpected situation.
---
I noticed that here's already some similar check in `dynamicParametersCallback()` : 
[costmap_2d_ros.cppL740-L762](https://github.com/ros-planning/navigation2/blob/main/nav2_ …
> check params of costmap to avoid abnormal memory usage caused by user-misconfiguration mentioned in issue #4005

- .circleci/config.yml
- nav2_collision_monitor/include/nav2_collision_monitor/polygon.hpp
- nav2_collision_monitor/params/collision_detector_params.yaml
- nav2_collision_monitor/params/collision_monitor_params.yaml
- nav2_collision_monitor/src/polygon.cpp
- nav2_collision_monitor/test/collision_detector_node_test.cpp
- nav2_collision_monitor/test/collision_monitor_node_test.cpp
- nav2_collision_monitor/test/polygons_test.cpp
- nav2_costmap_2d/CMakeLists.txt
- nav2_costmap_2d/src/footprint.cpp
- nav2_costmap_2d/test/unit/CMakeLists.txt
- nav2_util/CMakeLists.txt
- nav2_util/include/nav2_util/array_parser.hpp
- nav2_util/src/CMakeLists.txt
- nav2_util/src/array_parser.cpp
- nav2_util/test/CMakeLists.txt
- nav2_util/test/test_array_parser.cpp
---
| Ticket(s) this addresses   | (#3959) |
| Primary OS tested on | (Ubuntu 22.04) |
| Robotic platform tested on | (Gazebo Ignition) |
---
* Changed the parameter description format polygons in `nav2_collision_monitor` to conform with the description of the footprint polygons in `nav2_costmap_2d` 
* Moved `array_parser` from `nav2_costmap_2d` to `nav2_util` 
* Added `getPolygonFromString` funtion in `nav2_collision_monitor::Polygon` namesapce to parse the Polygon's points parameter from string using the array parser
* Moved the test for `array_parser` from `nav2_costmap_2d` to `nav_util` and renamed to `test_array_parser` for consistency. 
* Would need to update the …
> Updating polygon parameter format

- nav2_simple_commander/nav2_simple_commander/costmap_2d.py
Works when the "Returns" is added. I can't say I know why exactly though but my hypothesis is that for the style with `Arg` (without colon) the Returns section is mandatory :man_shrugging: . For other places with `Args:` (with colon), the Returns section is missing and the test doesn't complain
> Bring back pep257 docstring

- nav2_mppi_controller/README.md
- nav2_mppi_controller/include/nav2_mppi_controller/critics/obstacles_critic.hpp
- nav2_mppi_controller/src/critics/obstacles_critic.cpp
---
| Robotic platform tested on | simulation |
---
The current condition passes when you have another layer that extends `InflationLayer`. 
We need to make sure it is the actual `InflationLayer` and not a derived class.
---
> Fix MPPI obstacle critic InflationLayer check

- nav2_rviz_plugins/package.xml
---
| Robotic platform tested on | Dexory build env |
---
Add dependency tag to `urdf` in `nav2_rviz_plugins` package. 
It is only problematic when building from source along urdf.
> Add missing urdf dependency to nav2_rviz_plugins package

- nav2_smac_planner/README.md
- nav2_smac_planner/include/nav2_smac_planner/analytic_expansion.hpp
- nav2_smac_planner/include/nav2_smac_planner/collision_checker.hpp
- nav2_smac_planner/include/nav2_smac_planner/node_2d.hpp
- nav2_smac_planner/include/nav2_smac_planner/node_hybrid.hpp
- nav2_smac_planner/include/nav2_smac_planner/node_lattice.hpp
- nav2_smac_planner/include/nav2_smac_planner/types.hpp
- nav2_smac_planner/src/a_star.cpp
- nav2_smac_planner/src/analytic_expansion.cpp
- nav2_smac_planner/src/collision_checker.cpp
- nav2_smac_planner/src/node_hybrid.cpp
- nav2_smac_planner/src/node_lattice.cpp
- nav2_smac_planner/src/smac_planner_hybrid.cpp
- nav2_smac_planner/src/smac_planner_lattice.cpp
- nav2_smac_planner/test/test_a_star.cpp
Generally helps reduce the shortcutting on approach to goals by setting a maximum cost for traversal for the analytic expansion module to use, multiple turning radius refinement attempts, and an optional cost override when shortcutting is OK on approach when absolutely required.
It also addresses a minor collision detector issue that was resolved in the PR 
Needs: docs update + testing from deployed users
> Prevent analytic expansions from shortcutting Smac Planner feasible paths

- nav2_amcl/src/amcl_node.cpp
---
| Ticket(s) this addresses   | #4068 |
| Primary OS tested on | Ubuntu22.04 |
| Robotic platform tested on |  gazebo simulation  |
---
make `tf_listener_.reset()` before `lase_scan_filter_.reset()`
---
> change pointer free order in amcl to avoid use-after-free bug mentioned in #4068

- nav2_costmap_2d/include/nav2_costmap_2d/inflation_layer.hpp
- nav2_smac_planner/CMakeLists.txt
- nav2_smac_planner/include/nav2_smac_planner/collision_checker.hpp
- nav2_smac_planner/include/nav2_smac_planner/node_2d.hpp
- nav2_smac_planner/include/nav2_smac_planner/node_hybrid.hpp
- nav2_smac_planner/include/nav2_smac_planner/node_lattice.hpp
- nav2_smac_planner/src/a_star.cpp
- nav2_smac_planner/src/analytic_expansion.cpp
- nav2_smac_planner/src/collision_checker.cpp
- nav2_smac_planner/src/node_2d.cpp
- nav2_smac_planner/src/node_hybrid.cpp
- nav2_smac_planner/src/node_lattice.cpp
- nav2_smac_planner/src/smac_planner_2d.cpp
- nav2_smac_planner/src/smac_planner_hybrid.cpp
- nav2_smac_planner/src/smac_planner_lattice.cpp
- nav2_smac_planner/test/test_a_star.cpp
- nav2_smac_planner/test/test_collision_checker.cpp
- nav2_smac_planner/test/test_node2d.cpp
- nav2_smac_planner/test/test_nodehybrid.cpp
- nav2_smac_planner/test/test_nodelattice.cpp
- nav2_smac_planner/test/test_smoother.cpp
@doisyg please test on the map we did onsite in Verda Park to verify this still solves the problem for you after my refactor
> [Smac Planner] Massive Improvement of Behavior for SE2 Footprint Checking (ie non-circular robots) In Confined Settings

- nav2_behaviors/README.md
- nav2_behaviors/include/nav2_behaviors/plugins/assisted_teleop.hpp
- nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
- nav2_behaviors/include/nav2_behaviors/plugins/spin.hpp
- nav2_behaviors/include/nav2_behaviors/timed_behavior.hpp
- nav2_behaviors/plugins/assisted_teleop.cpp
- nav2_behaviors/plugins/spin.cpp
- nav2_collision_monitor/README.md
- nav2_collision_monitor/include/nav2_collision_monitor/collision_monitor_node.hpp
- nav2_collision_monitor/src/collision_monitor_node.cpp
- nav2_controller/README.md
- nav2_controller/include/nav2_controller/controller_server.hpp
- nav2_controller/src/controller_server.cpp
- nav2_util/README.md
- nav2_util/include/nav2_util/robot_utils.hpp
- nav2_util/include/nav2_util/twist_publisher.hpp
- nav2_util/include/nav2_util/twist_subscriber.hpp
- nav2_util/src/robot_utils.cpp
- nav2_util/test/CMakeLists.txt
- nav2_util/test/test_twist_publisher.cpp
- nav2_util/test/test_twist_subscriber.cpp
- nav2_velocity_smoother/README.md
- nav2_velocity_smoother/include/nav2_velocity_smoother/velocity_smoother.hpp
- nav2_velocity_smoother/src/velocity_smoother.cpp
- nav2_velocity_smoother/test/test_velocity_smoother.cpp
See https://github.com/ros-planning/navigation2/pull/3775; this is the same PR but opened back up. 
Replaces https://github.com/ros-planning/navigation2/pull/4031, by pulling in all 3 commits, as well as more changes since then. 
This has been tested by backporting to humble against ArduPilot by @srmainwaring. No bugs were reported.
> 1594 twist stamped publisher

- nav2_amcl/src/amcl_node.cpp
---
| Ticket(s) this addresses   | #4078  |
| Primary OS tested on | Ubuntu22.04 |
| Robotic platform tested on |  gazebo simulation  |
---
add `map_sub_.reset()` before  `map_free(map_)` to avoid UAF&&NullPtr bug mentioned in #4078
---
> free `map_sub_` before `map_free(map_)` to avoid UAF&&NullPtr bug mentioned in #4078

- nav2_simple_commander/nav2_simple_commander/robot_navigator.py
* I  fixed a typo in nav2_simple_commander to fix AttributeError: 'BasicNavigator' object has no attribute '_BasicNavigator__getPathThroughPosesImpl' when using the BasicNavigator getPathThroughPoses() method.
> Fix typo in nav2_simple_commander

- nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp
This bug created wobbling behaviors while I was trying to optimize the performance of finding the newest path points via caching the last path point used to initialize the next. However, I missed an important condition that caused very bad static wobbles
Will need to be updated for any users, very important
> Critical fix for path tracking MPPI in new path align critic

- .circleci/config.yml
- nav2_bringup/params/nav2_multirobot_params_1.yaml
- nav2_bringup/params/nav2_multirobot_params_2.yaml
- nav2_bringup/params/nav2_multirobot_params_all.yaml
- nav2_bringup/params/nav2_params.yaml
- nav2_bringup/rviz/nav2_default_view.rviz
- nav2_bt_navigator/behavior_trees/follow_point.xml
- nav2_bt_navigator/behavior_trees/nav_to_pose_with_consistent_replanning_and_if_path_becomes_invalid.xml
- nav2_bt_navigator/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml
- nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml
- nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_goal_patience_and_recovery.xml
- nav2_bt_navigator/behavior_trees/navigate_w_recovery_and_replanning_only_if_path_becomes_invalid.xml
- nav2_bt_navigator/behavior_trees/navigate_w_replanning_distance.xml
- nav2_bt_navigator/behavior_trees/navigate_w_replanning_only_if_goal_is_updated.xml
- nav2_bt_navigator/behavior_trees/navigate_w_replanning_only_if_path_becomes_invalid.xml
- nav2_bt_navigator/behavior_trees/navigate_w_replanning_speed.xml
- nav2_bt_navigator/behavior_trees/navigate_w_replanning_time.xml
- nav2_bt_navigator/src/bt_navigator.cpp
- nav2_rviz_plugins/CMakeLists.txt
- nav2_rviz_plugins/include/nav2_rviz_plugins/selector.hpp
- nav2_rviz_plugins/plugins_description.xml
- nav2_rviz_plugins/src/selector.cpp
- nav2_system_tests/src/costmap_filters/keepout_params.yaml
- nav2_system_tests/src/costmap_filters/speed_global_params.yaml
- nav2_system_tests/src/costmap_filters/speed_local_params.yaml
- nav2_system_tests/src/gps_navigation/nav2_no_map_params.yaml
---
| Ticket(s) this addresses   | #3269) |
| Robotic platform tested on | Neobotix MPO-700 |
---
Now we can select the controller and the planner plugins on the fly
Maybe RViz plugins after all needs a documentation somewhere?
---
* Goal checkers and smoothers could be added to the selection list if needed
> Selector plugin for selecting the planner and the controller

- nav2_costmap_2d/CMakeLists.txt
- nav2_costmap_2d/test/integration/CMakeLists.txt
- nav2_costmap_2d/test/regression/CMakeLists.txt
- nav2_costmap_2d/test/unit/CMakeLists.txt
---
| Ticket(s) this addresses   |  https://github.com/ANYbotics/grid_map/issues/403 |
| Primary OS tested on |  Ubuntu 22.04  |
| Robotic platform tested on | N/A ||
---
* Switch nav2_costmap_2d to use the latest recommended usage of ament_cmake with ament_export_targets.
* Export includes directories with targets that use it
* Add support for consuming packages to link against the `nav2_costmap_2d::nav2_costmap_2d_core` target
* Use ALIAS library for internal linkage when possible on all libraries
* Don't use ament_target_dependencies when already linking to core because it's unnecessary
N/A
---
* Concerting more of NAV2 to abide by the Ament CMake recommendations.
> Use ament_export_targets for all targets in nav2_costmap_2d

- nav2_mppi_controller/include/nav2_mppi_controller/critics/cost_critic.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/critics/obstacles_critic.hpp
- nav2_mppi_controller/src/critics/cost_critic.cpp
- nav2_mppi_controller/src/critics/obstacles_critic.cpp
- nav2_smac_planner/include/nav2_smac_planner/collision_checker.hpp
- nav2_smac_planner/src/collision_checker.cpp
---
| Ticket(s) this addresses   | (#4113) |
| Primary OS tested on | (Ubuntu, Windows) |
| Robotic platform tested on | (  gazebo simulation ) |
---
*  Refactors possible_inscribed_cost to possible_circumscribed_cost in collision checker for smac_planner and mppi_controller
* Ensures text files use LF line endings for consistency, especially for Windows VSCode users.
---
> Refactors possible_inscribed_cost to possible_circumscribed_cost in collision checker for smac_planner and mppi_controller

- nav2_smac_planner/src/node_hybrid.cpp
- nav2_smac_planner/test/test_nodehybrid.cpp
---
| Ticket(s) this addresses   | #4094 |
---
* This small fix improves the behavioral consistency of the NodeHybrid::getClosestAngularBin method.
* Unit tests of the method are added.
* N/A
---
* N/A
> Added cast to float to getClosestAngularBin return for behavior consistency

- nav2_behavior_tree/include/nav2_behavior_tree/bt_utils.hpp
- nav2_collision_monitor/test/velocity_polygons_test.cpp
- nav2_costmap_2d/test/integration/test_costmap_subscriber.cpp
- nav2_rviz_plugins/src/selector.cpp
---
| Robotic platform tested on | Untested |
---
I fixed a few small issues while trying to compile this project with clang++.
---
> Fix compilation with clang

- nav2_util/include/nav2_util/simple_action_server.hpp
Fix the goal handle was not freed correctly when action server terminates goal. See #4121 for more detail
> Fix goal handle was not freed correctly

- nav2_smac_planner/src/analytic_expansion.cpp
---
| Ticket(s) this addresses   | #4141|
| Robotic platform tested on | Gazebo simulation of a Robauta robot |
---
- Prevent a possible segmentation fault in analytic_expansion at smac_planner
Defensive approach as Steve recommended in his comment on the issue. Added check if the iterator == [ vector.end(), as dereferencing ](https://en.cppreference.com/w/cpp/container/vector/end) that can lead into undefined behavior (appeared as segmentation fault in my case). Also added an early return for the case in which the vector would end up being empty, thus leading into the check previously mentioned.
---
> Prevent a possible segmentation fault (#4141)

- nav2_amcl/src/amcl_node.cpp
---
| Ticket(s) this addresses   | #4166  |
| Robotic platform tested on | gazebo  |
---
To avoid UAF during shutdown
add `executor_thread_.reset()` before `initial_pose_sub_.reset()`
---
> Completely shutdown `inital_pose_sub_` in `nav2_amcl` to avoid UAF

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
---
| Ticket(s) this addresses   | / |
| Robotic platform tested on | /  |
---
The error message for BT Action Node discovery timeout was still hardcoded to 1s. Probably an oversight from when the configuration option was introduced.
None
---
None
> chore(nav2_behavior_tree): log actual wait period in bt_action_node timeout error message

- nav2_regulated_pure_pursuit_controller/CMakeLists.txt
- nav2_regulated_pure_pursuit_controller/README.md
- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/parameter_handler.hpp
- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/path_handler.hpp
- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/regulated_pure_pursuit_controller.hpp
- nav2_regulated_pure_pursuit_controller/package.xml
- nav2_regulated_pure_pursuit_controller/src/parameter_handler.cpp
- nav2_regulated_pure_pursuit_controller/src/path_handler.cpp
- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
- nav2_regulated_pure_pursuit_controller/test/test_regulated_pp.cpp
---
| Ticket(s) this addresses   | Similar to https://github.com/ros-planning/navigation2/pull/3788#issuecomment-1958276641 |
| Does this PR contain AI generated software? | NO |
---
This is me finally contributing back after rebasing and testing with latest main the RPP tweaks that we have been using for months in production.
Warning, we only use RPP for linear paths, so caution when generalizing the usage of the added feature.
- New behavior controlled by a new parameter `interpolate_curvature_after_goal` (default false) that interpolates a carrot after the goal in order to maintain a constant curvature lookahead distance. This is to avoid …
> RPP Dexory tweaks

- nav2_amcl/src/amcl_node.cpp
Simple typo correction on warning messages in AMCL module:)
> fix typos in description messages

- nav2_amcl/src/sensors/laser/likelihood_field_model.cpp
This PR fixes unnecessary lines inside a loop: the lines should be outside a loop, trivially.
> Move lines for pre-computation to outside a loop

- nav2_smac_planner/include/nav2_smac_planner/analytic_expansion.hpp
- nav2_smac_planner/src/analytic_expansion.cpp
- nav2_smac_planner/src/collision_checker.cpp
- nav2_smac_planner/src/smac_planner_hybrid.cpp
- nav2_smac_planner/src/smac_planner_lattice.cpp
This PR updates the footprint (if different) used in the smac planner at every `create_plan` call.
| Ticket(s) this addresses   | #4179  |
| Robotic platform tested on | Our Robot |
---
- Clear `oriented_footprints_` the fix the update issue
- Call `_collision_checker.setFootprint()` in create_plan method 
---
> [SmacPlanner] Update footprint if changed

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
---
---
Fixed `wait_for_service_timeout` not loaded from the bt parameter file
- declare the parameter with `1000ms` default 
---
> fix `wait_for_service_timeout` not loaded correctly

- nav2_controller/src/controller_server.cpp
Reverts ros-planning/navigation2#4171
> Revert "nav2_controller: add loop rate log"

- nav2_graceful_controller/test/test_graceful_controller.cpp
The space_nav repo uses slightly stricter compiler flags that causes the modified lines to result in a docker build failure:
https://github.com/space-ros/docker/actions/runs/8406248510/job/23019919497
Fixing this upstream allows up to stay current with upstream repos
> Add uint suffix

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
---
| Robotic platform tested on | Inhouse AGV & Gazebo |
---
- Current state: In the current implementation of the `BtActionServer`, a new BT is not loaded if its xml name is the same as the current one. This means that if you want to change and then test a BT xml file (while keeping the same filename), you need to restart the action server each time the file changes. 
- This PR: Adds a boolean parameter `always_reload_bt_xml` (defaults to `false`) to decide if a new BT should always be loaded, even if the xml names are the same. This allows keeping the action server running while changing/developing …
> Enable reloading BT xml file with same name

- nav2_regulated_pure_pursuit_controller/CMakeLists.txt
- nav2_regulated_pure_pursuit_controller/package.xml
- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
---
| Ticket(s) this addresses   | #4185 |
---
Replaces the `nav2_amcl::angleutils` usage in RPP with `angles` and drops the dependency to `nav2_amcl`, which in this case was being used just for one angle normalization call.
---
> Remove AMCL dependency from RPP

- nav2_controller/src/controller_server.cpp
Following the format [here](https://github.com/ros-planning/navigation2/blob/c9d9b5c698d1f5aff060806481d18ba7e9b18cb2/nav2_planner/src/planner_server.cpp#L444) added loop rate logging to nav2_controller/controller_server.cpp.
has been tested with low and too-high frequencies to make sure it is not printed when not needed, and printed when needed.
I'm only not sure if defining the start_time where I did makes sense or it should've been later maybe. My logic was that all the checks being done are part of the controller loop and however long they take, it is slowing the controller down.
> nav2_controller: add loop rate log

- nav2_controller/src/controller_server.cpp
- nav2_core/include/nav2_core/controller.hpp
- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/parameter_handler.hpp
- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/regulated_pure_pursuit_controller.hpp
- nav2_regulated_pure_pursuit_controller/src/parameter_handler.cpp
- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
---
| Ticket(s) this addresses   | #4033 |
| Robotic platform tested on | Gazebo simulation of inhouse robot |
---
Ability to let controllers handle cancelations gracefully. See the discussion at https://github.com/ros-planning/navigation2/issues/4033.
I'm opening this PR for a first review of the API. I've added gracefull cancellation to one of our in-house controllers and tested that this API is sufficient. I hope the API fits the design of the core APIs. 
---
> Add API to gracefully cancel a controller

- nav2_behaviors/behavior_plugin.xml
- nav2_behaviors/src/behavior_server.cpp
- nav2_bringup/params/nav2_multirobot_params_1.yaml
- nav2_bringup/params/nav2_multirobot_params_2.yaml
- nav2_bringup/params/nav2_multirobot_params_all.yaml
- nav2_bringup/params/nav2_params.yaml
- nav2_bt_navigator/navigator_plugins.xml
- nav2_bt_navigator/src/bt_navigator.cpp
- nav2_navfn_planner/global_planner_plugin.xml
- nav2_planner/src/planner_server.cpp
- nav2_smac_planner/README.md
- nav2_smac_planner/smac_plugin_2d.xml
- nav2_smac_planner/smac_plugin_hybrid.xml
- nav2_smac_planner/smac_plugin_lattice.xml
- nav2_system_tests/src/costmap_filters/keepout_params.yaml
- nav2_system_tests/src/costmap_filters/speed_global_params.yaml
- nav2_system_tests/src/costmap_filters/speed_local_params.yaml
- nav2_system_tests/src/gps_navigation/nav2_no_map_params.yaml
- nav2_system_tests/src/planning/test_planner_plugins.cpp
- nav2_system_tests/src/system/CMakeLists.txt
- nav2_theta_star_planner/README.md
- nav2_theta_star_planner/theta_star_planner.xml
- tools/planner_benchmarking/README.md
- tools/smoother_benchmarking/README.md
Tested in Gazobo world. 
The turtle bot runs as normal.
The CI/CD process fails due to the `rosdep` issue during the Docker build stage. I encountered the same issue on my local PC and resolved it by using `apt install`.
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
dwb_msgs: No definition of [rosidl_default_runtime] for OS version [jammy]
costmap_queue: No definition of [rclcpp] for OS version [jammy]
nav2_behaviors: No definition of [pluginlib] for OS version [jammy]
nav2_common: No definition of [rclpy] for OS version [jammy] 
```
---
| Ticket(s) this addresses   | (add tickets here #4194) |
| Primary OS tested on | (Ubuntu,) |
| Robotic platform tested on | …
> Refactor plugins to use double colons for consistency

- nav2_behavior_tree/test/plugins/action/test_bt_action_node.cpp
Fixes 2x of the current 8x failures introduced during the Rolling CI outage
> Increasing test count from timeout handling changes

- nav2_mppi_controller/README.md
---
There is a merge conflict in the humble branch of the nav2_mppi_controller README. This PR attempts to clean it up.
This PR is a documentation update.
None
> Fix merge conflict in nav2_mppi_controller README (humble)

- nav2_mppi_controller/src/critics/cost_critic.cpp
---
| Robotic platform tested on | Gazebo custom robot |
---
* Cost critic's weight was not scaled by the max possible cost when dynamically updated. I'm now scaling it by 254.0 after a dynamic update
None to my knowledge
---
None to my knowledge
> Scale cost critic's weight when dynamically updated

- nav2_lifecycle_manager/src/lifecycle_manager.cpp
---
| Ticket(s) this addresses   | https://github.com/ros/diagnostics/issues/337 |
| Primary OS tested on | Ubuntu Noble |
---
Since `-Werror` is enforced in navigation2, it was unable to compile on newer cmake versions (ROS rolling, ubuntu Nobleo, cmake 3.28.3).
> Fix compiler warning ‘error_level’ may be used uninitialized

- nav2_map_server/include/nav2_map_server/map_io.hpp
- nav2_map_server/src/map_io.cpp
- nav2_map_server/test/unit/test_map_io.cpp
Add expanding the **~/** to the full home dir of user in the path to the map yaml. 
- Add implementation.
- Add unit tests.
> Add expanding the ~/ to the full home dir of user in the path to the map yaml. 

- nav2_smac_planner/CMakeLists.txt
- nav2_smac_planner/include/nav2_smac_planner/node_hybrid.hpp
- nav2_smac_planner/src/a_star.cpp
- nav2_smac_planner/src/analytic_expansion.cpp
- nav2_smac_planner/src/collision_checker.cpp
- nav2_smac_planner/src/node_hybrid.cpp
- nav2_smac_planner/test/test_nodehybrid.cpp
Removed downsampling of full costmap each iteration to opportunistic downsampling in the heuristic based on expansion of the heuristic field. Thus, this will be higher for larger maps and/or for simpler local requests where not much of the total percentage of the costmap needs to be downsample processed.
Additional modifications with minor / if any improvements that just creates more type consistency (can't hurt)
> Smac Planner Optimizations; 9.1% improvement in speed

- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d.hpp
- nav2_costmap_2d/src/costmap_2d.cpp
- nav2_smac_planner/include/nav2_smac_planner/a_star.hpp
- nav2_smac_planner/src/a_star.cpp
- nav2_smac_planner/src/smac_planner_2d.cpp
- nav2_smac_planner/src/smac_planner_hybrid.cpp
- nav2_smac_planner/src/smac_planner_lattice.cpp
* Create a `worldToMapContinous` to compute the decimals for the world to map conversion.
* Change the `setGoal` to use floats as inputs and `static_cast` to unsigned int's for the `getIndex` method.
* Do the same with setStart as well
---
| Ticket(s) this addresses   | #3955 and #4249 |
| Robotic platform tested on | sim |
---
> Set start and goal as float

- nav2_mppi_controller/CMakeLists.txt
- nav2_mppi_controller/README.md
- nav2_mppi_controller/critics.xml
- nav2_mppi_controller/include/nav2_mppi_controller/critics/velocity_deadband_critic.hpp
- nav2_mppi_controller/src/critics/velocity_deadband_critic.cpp
- nav2_mppi_controller/test/critics_tests.cpp
---
Some platforms have deadband velocity constraints and cannot move slowly. For instance, the legged robot Unitree Go2. This PR adds a critic that penalizes trajectory samples below a deadband value.
A robot with hardware limitations cannot reach the goal with a high tolerance (0.03m in my Gazebo simulation). I have attached videos comparing my feature with the 'out of the box' MPPI.
[Original MPPI](https://youtu.be/qwjZw97DLTY?si=eaMNq1cX_obHqBd5)
[With deadband critic](https://youtu.be/9_hw7ied594?si=BHS1kdlH22dkA2_x)
| Ticket(s) this addresses   | discussion in [slack](https://navigation2.slack.com/archives/C012L20NQLV/p1710932047032829) |
| Primary OS tested on | (Ubuntu 22.04) |
| Robotic platform tested on | Gazebo: …
> Implement Critic for Velocity Deadband Hardware Constraints

- nav2_bringup/launch/rviz_launch.py
- nav2_bringup/launch/tb3_simulation_launch.py
---
---
* Add use_sim_time argument to rviz launch file and use it from tb3 demo launch file
This is to fix the rviz plugins using the system time
---
> Make rviz use sim time with TB3 demo

- nav2_mppi_controller/include/nav2_mppi_controller/critic_data.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/critic_manager.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/models/control_sequence.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/models/path.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/models/state.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/models/trajectories.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/motion_models.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/optimizer.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/tools/noise_generator.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/tools/trajectory_visualizer.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp
| Ticket(s) this addresses   | Related to #4265  |
| Robotic platform tested on | Compile only |
---
* Suppress warnings (which are then treated as errors) from upstream xtensor library
* None
---
* None for this particular problem
> Ignore warnings in included xtensor library

- nav2_amcl/src/amcl_node.cpp
- nav2_costmap_2d/plugins/static_layer.cpp
- nav2_util/include/nav2_util/validate_messages.hpp
- nav2_util/test/CMakeLists.txt
- nav2_util/test/test_validation_messages.cpp
---
| Ticket(s) this addresses   | #4177  #4206 |
| Robotic platform tested on | gazebo  |
---
- Add message-validation check in `nav2_util` pkg
- Add check in `nav2_amcl` for `map` message to avoid **heap-buffer-overflow** bug mentioned in #4177 
- new file named `validate_message.hpp`, which provide a structure of message-validation-check in `nav2_util`
- add a validation check for map message of `nav2_amcl`
- add a validation check for map message of `static_layer`
---
> provide message validation check API

- nav2_waypoint_follower/include/nav2_waypoint_follower/plugins/photo_at_waypoint.hpp
---
| Ticket(s) this addresses   | No tickets. |
| Robotic platform tested on | Not tested in any robot, it is a compilation-related change. |
---
The path used for opencv includes in `nav2_waypoint_follower` was different from the one documented by opencv itself for its header, see for example:
* https://github.com/opencv/opencv/blob/4.9.0/samples/gpu/video_reader.cpp#L12
* https://github.com/opencv/opencv/blob/4.9.0/doc/tutorials/introduction/linux_gcc_cmake/linux_gcc_cmake.markdown?plain=1#L32
and from how other ROS 2 packages include opencv headers, see:
* https://github.com/ros-perception/vision_opencv/blob/4.1.0/cv_bridge/include/cv_b …
> nav2_waypoint_follower: Fix opencv includes

- nav2_rotation_shim_controller/src/nav2_rotation_shim_controller.cpp
When the path is shorter than ´forward_sampling_distance´ the rotatitonShimController would directly give control to the primary controller to navigate to the goal. This would lead to the exact behavior that was tried to be fixed by the rotationShimController: "The result is an awkward, stuttering, or whipping around behavior" [1]. It often resulted in navigation failure.
In this case, the controller should try to rotate towards the last point of the path, so that the primary controller can have a better starting orientation.
[1] https://navigation.ros.org/tuning/index.html#rotate-in-place-behavior
---
| Ticket(s) this addresses   | #4281  |
| Primary OS tested on | Ubuntu 20.04 / 22.04 |
| Robotic platform tested on | Gazebo …
> [RotationShimController] rotate also on short paths

- nav2_behavior_tree/plugins/decorator/path_longer_on_approach.cpp
---
| Ticket(s) this addresses   | #4110 |
| Primary OS tested on |(Ubuntu|
| Robotic platform tested on | Neobotix ROX |
---
* Crux of the issue seems that the status of the node is set to IDLE. Last year, when I had implemented, the status ended up to success and went IDLE only when the entire BT was IDLE. This IDLE state was blocking the logic of the intended decorator going forward. I however have found a fix, that uses the goals of the old path and the new path, to avoid the blocking.
---
> fixes the issue when the path longer on approach decorator goes to idle state

- nav2_bt_navigator/README.md
Checking the README of nav2_bt_navigator, realized that the link of the docs ([navigation.ros.org](navigation.ros.org)) are no longer valid. Updating to the valid one ([docs.nav2.org](docs.nav2.org)).
Quite sure others READMEs should be updated as well.
> Update README.md of nav2_bt_navigator

- nav2_util/include/nav2_util/simple_action_server.hpp
---------
---
| Ticket(s) this addresses   | #4283  #4175 #4180 |
| Robotic platform tested on | gazebo  |
---
To avoid UAF during shutdown
replace throw-error with error-log
---
> cherry-pick from main into humble to avoid UAF

- nav2_behavior_tree/include/nav2_behavior_tree/behavior_tree_engine.hpp
- nav2_behavior_tree/src/behavior_tree_engine.cpp
- nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
- nav2_behaviors/include/nav2_behaviors/timed_behavior.hpp
- nav2_behaviors/plugins/assisted_teleop.cpp
- nav2_behaviors/plugins/back_up.cpp
- nav2_behaviors/plugins/spin.cpp
- nav2_planner/include/nav2_planner/planner_server.hpp
- nav2_planner/src/planner_server.cpp
- nav2_smoother/include/nav2_smoother/nav2_smoother.hpp
- nav2_smoother/src/nav2_smoother.cpp
- nav2_system_tests/src/behaviors/backup/backup_behavior_tester.cpp
- nav2_system_tests/src/behaviors/backup/test_backup_behavior_launch.py
- nav2_system_tests/src/behaviors/drive_on_heading/drive_on_heading_behavior_tester.cpp
- nav2_system_tests/src/behaviors/spin/test_spin_behavior_launch.py
- nav2_system_tests/src/behaviors/wait/test_wait_behavior_launch.py
- nav2_system_tests/src/behaviors/wait/wait_behavior_tester.cpp
- nav2_velocity_smoother/src/velocity_smoother.cpp
- nav2_waypoint_follower/include/nav2_waypoint_follower/plugins/wait_at_waypoint.hpp
- nav2_waypoint_follower/plugins/wait_at_waypoint.cpp
https://github.com/open-navigation/navigation2/pull/4000/#issuecomment-2096390305
Convert all wall timers and wall rates to ROS clock respecting rates and timers (#4000)
* Convert all wall timers and wall rates to ROS clock respecting rates and timers
* linty mclint face
* WPF wait plugin respect time
* move duration metrics to use local clocks
* bumping version for cache to break it
* complete timing refactor
* remove old variable
---
| Does this PR contain AI generated software? | (No; Yes and it is marked inline in the …
> Backport to humble, Cherry-pick from 15c9be0aa5d09dd3be40bb46a66a5175464dd1a4

- nav2_util/include/nav2_util/lifecycle_node.hpp
- nav2_util/src/lifecycle_node.cpp
---
---
This PR adds the parameter `bond_heartbeat_period` to the lifecycle nodes.
The bond heart beat period of the lifecycle node was fixed to 0.1 (s). This PR doesn't change the default value but allows to customize it, and to disable the bond mechanism if <= 0.0 (so no pub/sub on `/bond`)
---
- Should we change the default to a longer period (i.e. less CPU usage on `/bond` subscribers) ?
- Should we also expose `bond_heartbeat_timeout` for `setHeartbeatTimeout` ? (I personally don't have an use case for this)
> [LifecycleNode] add bond_heartbeat_period

- nav2_behavior_tree/plugins/decorator/path_longer_on_approach.cpp
See https://github.com/ros-navigation/navigation2/issues/4326.
Fix the bug that isPathUpdated function will return false even if the new path is update for the reason that it not only compare the position between new path and old path's last pose.But also compare these two poses 's timestamped which is obviously different.
---
---
> Fix the bug that behavior tree plugin PathLongerOnApproach will not work while using smac planner.

- nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager_client.hpp
---
| Robotic platform tested on | Dexory robot |
---
I was looking at `nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager_client.hpp` and noticed 2 methods that do not seem to be used anywhere: `set_initial_pose` and `navigate_to_pose`. I guess they can be removed ?
> [LifecycleManagerClient] clean set_initial_pose and navigate_to_pose

- nav2_system_tests/src/behaviors/spin/test_spin_behavior_node.cpp
https://github.com/ros-navigation/navigation2/issues/4349 tracking its reintroduction. CC @tonynajjar
> Remove flaky spin test that needs to be rewritten

- nav2_collision_monitor/src/polygon.cpp
- nav2_collision_monitor/test/collision_monitor_node_test.cpp
| Ticket(s) this addresses   | #4355 |
| Robotic platform tested on | Our simulation |
---
* Move projectState after getPointsInside to compute time=0.0 collision
* Change comment to fit returned time. time = collision not *before* collision
---
> Move projectState after getPointsInside

- nav2_smac_planner/src/analytic_expansion.cpp
> Adding final pose in analytic expansion to check

- nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager.hpp
- nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager_client.hpp
- nav2_lifecycle_manager/src/lifecycle_manager.cpp
- nav2_lifecycle_manager/src/lifecycle_manager_client.cpp
- nav2_lifecycle_manager/test/test_lifecycle_manager.cpp
- nav2_msgs/srv/ManageLifecycleNodes.srv
---
| Ticket(s) this addresses   | #4345  |
| Robotic platform tested on | Gazebo simulation, Leo Rover, Robauta Sampo |
---
* Added CONFIGURE and CLEANUP commands for lifecycle_manager and lifecycle_manager_client
I was not able to find any documentation regarding to the available lifecycle transitions. If some exists, would need to that,
---
Might be nice to have a test which makes sure that calling shutdown when the nodes are in inactive state does the shutdown properly. I did some testing locally and seems to be working as expected. I tried to add such test into the test_lifecycle_manager.cpp but a problem there is that the shutdown …
> Add configure and cleanup transitions to lifecycle manager and client

- nav2_smac_planner/test/test_smoother.cpp
Removes tolerance so it should now work deterministically if I understand the issue correctly
> Fix flaky smoother test

- nav2_behavior_tree/plugins/decorator/path_longer_on_approach.cpp
---
| Robotic platform tested on | (Custom Robot) |
---
* We encountered a segmentation fault in the behavior tree while operating our robot. Upon investigation, we discovered that the `PathLongerOnApproach` node was causing these segmentation faults.
* When the `ComputePathToPoseAction` sets an empty path in the behavior tree port `path` due to failure or cancellation, the `path` from `PathLongerOnApproach` can be empty. Without checking its size, the node encounters segmentation faults at that time.
* Co-author: @JinyongJeong
---
> Prevent invalid accesses on paths in path_longer_on_approach

- nav2_rotation_shim_controller/README.md
- nav2_rotation_shim_controller/include/nav2_rotation_shim_controller/nav2_rotation_shim_controller.hpp
- nav2_rotation_shim_controller/include/nav2_rotation_shim_controller/tools/utils.hpp
- nav2_rotation_shim_controller/src/nav2_rotation_shim_controller.cpp
- nav2_rotation_shim_controller/test/test_shim_controller.cpp
When arriving in the goal xy tolerance, the rotation shim controller takes back the control to command the robot to rotate in the goal heading orientation.
The initial goal of the rotationShimController was to rotate the robot at the beginning of a navigation towards the paths orientation because some controllers are not good at performing in place rotations. For the same reason, the rotationShimController should be able to rotate the robot towards the goal heading.
---
| Ticket(s) this addresses   | #4289  |
| Robotic platform tested on | Gazebo simulation on custom robot |
---
* Add new feature to rotationShimController: It can rotate …
> [RotationShimController] Rotate to goal heading

- nav2_costmap_2d/src/costmap_2d_ros.cpp
---
| Ticket(s) this addresses   | #4323  |
| Primary OS tested on | ubuntu22.04 |
| Robotic platform tested on | gazebo simulation  |
---
early do `executor_thread_.reset()` to avoid  nullptr bug #4323 
---
> earlier `executor_thread_.reset()` in nav2_costmap_ros 

- nav2_rotation_shim_controller/test/test_shim_controller.cpp
* Fix rotate to goal heading tests
---
| Ticket(s) this addresses   | #4289 |
---
Fix test
N/A
---
N/A
> [RotationShimController] Fix test for rotate to goal heading (#4289)

- nav2_bringup/params/nav2_params.yaml
- nav2_mppi_controller/include/nav2_mppi_controller/models/constraints.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/models/optimizer_settings.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/motion_models.hpp
- nav2_mppi_controller/src/optimizer.cpp
- nav2_mppi_controller/test/optimizer_unit_tests.cpp
| Ticket(s) this addresses   | #3351 |
| Robotic platform tested on | gazebo simulation of tb3 |
---
* Updating MPPI controller to consider acceleration and deceleration constraints.
* Added new parameter, so need to add that to default configs and documentation page
---
> Add acceleration constraints in the MPPI controller

- nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp
Provide service_name instead of service_node_name for debugging bt_service_node
> Update bt_service_node.hpp debug msg

- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/regulated_pure_pursuit_controller.hpp
- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
---
| Robotic platform tested on | Dexory robot |
---
A draft first to discuss, I would be interested in the feedback of RPP users. cc @james-ward 
This PR adds the publisher topic `is_rotating_to_heading` in order to feedback to an external system if RPP is currently rotating to align with the path or final pose. 
A situation that happens either if `shouldRotateToGoalHeading(carrot_pose)` or `shouldRotateToPath(rotate_to_path_carrot_pose, angle_to_heading, x_vel_sign)` is true.
---
> [RPP] add is_rotating_to_heading feedback

- nav2_amcl/src/amcl_node.cpp
---
| Ticket(s) this addresses   | #4379 |
| Primary OS tested on |  Ubuntu |
---
- reset `laser_scan_filter_` before reinit it
- avoid UAF bugs mentioned in #4379
> [amcl] reset laser_scan_filter before reinit 

- nav2_docking/opennav_docking/CMakeLists.txt
- nav2_docking/opennav_docking/package.xml
The current implementation exports neither the plugins nor the `pose_filter` library for use by projects outside `opennav_docking`.
---
---
* Export `pose_filter` library and `plugins.xml` from `opennav_docking` to be used by external projects.
Nothing
---
Nothing
> Fix: export libraries and plugins from opennav_docking

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
Manual backport of https://github.com/ros-navigation/navigation2/pull/4209#issuecomment-2155106680
> Enable reloading BT xml file with same name (backport #4209)

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/bt_cancel_action_node.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp
- nav2_behavior_tree/test/plugins/action/test_assisted_teleop_action.cpp
- nav2_behavior_tree/test/plugins/action/test_assisted_teleop_cancel_node.cpp
- nav2_behavior_tree/test/plugins/action/test_back_up_action.cpp
- nav2_behavior_tree/test/plugins/action/test_back_up_cancel_node.cpp
- nav2_behavior_tree/test/plugins/action/test_bt_action_node.cpp
- nav2_behavior_tree/test/plugins/action/test_clear_costmap_service.cpp
- nav2_behavior_tree/test/plugins/action/test_compute_path_through_poses_action.cpp
- nav2_behavior_tree/test/plugins/action/test_compute_path_to_pose_action.cpp
- nav2_behavior_tree/test/plugins/action/test_controller_cancel_node.cpp
- nav2_behavior_tree/test/plugins/action/test_drive_on_heading_action.cpp
- nav2_behavior_tree/test/plugins/action/test_drive_on_heading_cancel_node.cpp
- nav2_behavior_tree/test/plugins/action/test_follow_path_action.cpp
- nav2_behavior_tree/test/plugins/action/test_navigate_through_poses_action.cpp
- nav2_behavior_tree/test/plugins/action/test_navigate_to_pose_action.cpp
- nav2_behavior_tree/test/plugins/action/test_reinitialize_global_localization_service.cpp
- nav2_behavior_tree/test/plugins/action/test_smooth_path_action.cpp
- nav2_behavior_tree/test/plugins/action/test_spin_action.cpp
- nav2_behavior_tree/test/plugins/action/test_spin_cancel_node.cpp
- nav2_behavior_tree/test/plugins/action/test_wait_action.cpp
- nav2_behavior_tree/test/plugins/action/test_wait_cancel_node.cpp
- nav2_bringup/params/nav2_multirobot_params_1.yaml
- nav2_bringup/params/nav2_multirobot_params_2.yaml
- nav2_bringup/params/nav2_multirobot_params_all.yaml
- nav2_bringup/params/nav2_params.yaml
- nav2_system_tests/src/behavior_tree/test_behavior_tree_node.cpp
Make BT nodes have configurable wait times (manual backport of #3960 with the later fixes #4178 #4203)
I truly understand the concerns of @SteveMacenski [here](https://github.com/ros-navigation/navigation2/pull/3960#issuecomment-2155114983): I checked to the best of my knowledge the [history](https://github.com/ros-navigation/navigation2/commits/main/nav2_behavior_tree) if there were any other related PRs.
I get the same failures with colcon test as on the humble branch. So let's give it a try for a review here.
> Make BT nodes have configurable wait times (Backport #3960 #4178 #4203)

- nav2_smac_planner/include/nav2_smac_planner/a_star.hpp
- nav2_smac_planner/src/a_star.cpp
We found that clearing the start made other orientations in the same pose also be "free" even though those might be in critical collision at other orientations. We know the start is "free" because it has to be definitionally since the robot is there. 
This removes the clearing to fix that issue. Conveniently, we have defensive programming elsewhere that this makes it the only required change. Within the planner plugins themselves we already interpret 1 iteration as being start occupied and thus no valid potential path solution could be found, so we keep that contextual failure mode if there's no way out from the start. 
Addresses https://github.com/ros-navigation/navigation2/issues/4271
> Remove start clear

- nav2_costmap_2d/src/costmap_2d_publisher.cpp
---
| Ticket(s) this addresses   | #4419 |
| Robotic platform tested on | Tested locally |
---
* Advertise `get_costmap` service using topic name.
---
> Use topic_name for get_costmap service

- nav2_costmap_2d/include/nav2_costmap_2d/inflation_layer.hpp
- nav2_costmap_2d/plugins/inflation_layer.cpp
- nav2_costmap_2d/test/integration/inflation_tests.cpp
---
When using very large maps ( we are talking about maps in the order of 200 Mb), we noticed that the `InflationLayer` would consume a VERY large amount of memory.
After investigation, we realized that:
- memory is never freed
- the total amount of memory consumed can be reduced (no spikes)
See the difference before and after:
The impact in terms of performance (CPU usage) should be negligible
None
---
None
> [nav2_costmap_2s]: free correctly the memory in the InflationLayer

- nav2_amcl/include/nav2_amcl/amcl_node.hpp
- nav2_amcl/include/nav2_amcl/map/map.hpp
- nav2_amcl/src/amcl_node.cpp
---
---
This is a memory optimization that should not affect realtime perfomance, but will reduce considerably the amount of memory used by AMCL.
In our large map (200 Mb) this is the memory usage **before** the change:
And **after** the changes:
The main changes are:
1. Changes in `map_cell_t`: reduction from 12 bytes to 5 bytes
2. Add a new parameter to reduce the memory used by `free_space_indices` using 1/4th of the points (equally spaced)
Describe the new parameter "freespace_downsampling"
---
To be discussed
> [AMCL] reduce the amount of memory used

- nav2_docking/opennav_docking/CMakeLists.txt
- nav2_docking/opennav_docking/include/opennav_docking/controller.hpp
- nav2_docking/opennav_docking/src/controller.cpp
- nav2_docking/opennav_docking/test/test_controller.cpp
---
| Robotic platform tested on | Clara and Morphia robots |
| Does this PR contain AI generated software? | Nop |
---
1. I added the callback for dynamic reconfigure to tune the docking controller in runtime.
2. The docking controller is a library so can be used for other packages.
I don't think so.
---
> Added dynamic reconfigure and export controller in docking

- nav2_behavior_tree/include/nav2_behavior_tree/behavior_tree_engine.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
- nav2_behavior_tree/src/behavior_tree_engine.cpp
---
| Robotic platform tested on | Dexory sim |
---
Per slack discussion. Reduce the verbosity of the bt loop rate warning to DEBUG plus throttle it to 1hz.
---
> Throttle and switch to DEBUG bt loop rate warning

- nav2_costmap_2d/plugins/inflation_layer.cpp
---
| Ticket(s) this addresses   | https://github.com/ros-navigation/navigation2/issues/4271 |
---
* Added warning if inflation_radius_ < inscribed_radius_
---
> Warn if inflation_radius_ < inscribed_radius_

- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/parameter_handler.hpp
- nav2_regulated_pure_pursuit_controller/src/parameter_handler.cpp
- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
---
| Ticket(s) this addresses   | (add tickets here #4238 ) |
---
* Added parameter for using cancel decleration in RPP (Regulated Pure Pursuit Controller) 
* Issue: #4238 
---
> Added RPP use_cancel_deceleration parameter

- nav2_docking/opennav_docking/src/docking_server.cpp
- nav2_docking/opennav_docking/test/test_docking_server_unit.cpp
- nav2_docking/opennav_docking/test/testing_dock.cpp
---
| Ticket(s) this addresses   |#4447 |
| Primary OS tested on | (Ubuntu 22.04) |
| Robotic platform tested on | Morphia robot |
---
* Check if the robot is in the charging station before try to dock / undock to prevent docking when it's already in the charging station and undocking if is not docked.
The fix just return, aborting the handle. It can be improve addind result / error code if necessary.
---
> Fix unexpected behavior of docking when already in charger

- nav2_util/CMakeLists.txt
- nav2_util/include/nav2_util/lifecycle_node.hpp
- nav2_util/package.xml
- nav2_util/src/CMakeLists.txt
- nav2_util/src/base_footprint_publisher.cpp
- nav2_util/src/base_footprint_publisher.hpp
- nav2_util/src/lifecycle_utils.cpp
- nav2_util/src/string_utils.cpp
- nav2_util/test/CMakeLists.txt
- nav2_util/test/test_base_footprint_publisher.cpp
---
| Ticket(s) this addresses   | related to #4357  |
---
1.  Switches to using target_link_libraries everywhere. This gives us finer-grained control over what dependencies are exported to downstream as public, or private.  In the particular case of nav2_util, this actually doesn't matter *too* much, but it will help for other packages.
2.  Moves the include directory down one level to include/${PROJECT_NAME}, which is best practice in ROS 2 since Humble.
3.  Makes sure to export nav2_util as a CMake target, so downstream users of it can use that target.
4.  Moves the base_footprint_publisher.hpp …
> Revamp nav2_util CMakeLists.txt to use modern idioms.

- nav2_smac_planner/include/nav2_smac_planner/a_star.hpp
- nav2_smac_planner/src/a_star.cpp
| Ticket(s) this addresses   | #4394 |
| Robotic platform tested on | no |
---
* This only computed the distance heuristics once, if Initiliaze is called multiple time
* _lookup_table_size, _motion_model, dim_3_size, and  _search_info must not change between calls
> precomputeDistanceHeuristic is now computed once

- nav2_bringup/launch/tb3_simulation_launch.py
This fixes both unique and cloned multirobot launch files by correctly name spacing gz topics via changes in  https://github.com/ros-navigation/nav2_minimal_turtlebot_simulation/pull/10
This also removes the `use_simulator` launch argument since it's not needed by `spawn_tb3.launch.py`
*Requires:* https://github.com/ros-navigation/nav2_minimal_turtlebot_simulation/pull/10
> Use xacro file to plumb namespace into gz topics

- nav2_behavior_tree/test/test_bt_utils.cpp
We did this originally with source builds but took time for those updates to make it to binaries which has now happened requiring this change in the test fixtures for incorrect syntax tests
> Fix CI with BT test from btv4.X API update

- nav2_bringup/params/nav2_params.yaml
- nav2_docking/opennav_docking/src/dock_database.cpp
- nav2_docking/opennav_docking/test/test_dock_database.cpp
---
| Ticket(s) this addresses   | #4415 |
| Robotic platform tested on | Gazebo Simulation |
---
The changes made are as follows:
* [Support for not needing to set `dock_instances`](https://github.com/ros-navigation/navigation2/commit/15b085167ae4ee7682c636c7987a66a9b94488e1)
* [Improve some log messages in `dock_database.cpp`](https://github.com/ros-navigation/navigation2/commit/24337173b228c22a963be3ae5b98760adf1e6f18)
* [Comment the dock instances out from `nav2_params`](https://github.com/ros-navigation/navigation2/commit/ec9c012e8b4dd1e62d8a0aeaac3b106f3280a984)
These changes enable the system to work in the following use cases: …
> [Docking] Feature: support for not needing to set dock instances

- nav2_msgs/action/AssistedTeleop.action
- nav2_msgs/action/BackUp.action
- nav2_msgs/action/ComputePathThroughPoses.action
- nav2_msgs/action/ComputePathToPose.action
- nav2_msgs/action/DockRobot.action
- nav2_msgs/action/DriveOnHeading.action
- nav2_msgs/action/DummyBehavior.action
- nav2_msgs/action/FollowGPSWaypoints.action
- nav2_msgs/action/FollowPath.action
- nav2_msgs/action/FollowWaypoints.action
- nav2_msgs/action/NavigateThroughPoses.action
- nav2_msgs/action/NavigateToPose.action
- nav2_msgs/action/SmoothPath.action
- nav2_msgs/action/Spin.action
- nav2_msgs/action/UndockRobot.action
- nav2_msgs/action/Wait.action
---
| Ticket(s) this addresses   | 4341 |
---
Added `string error_msg` to all action result messages and `uint16 error_code` where it was missing.  
Notify interface change.
---
Future work is to make the changes to the action implementations to populate the error_msg / error_code fields where appropriate.
> Add string error_msg to all action result messages (#4341)

- nav2_controller/src/controller_server.cpp
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp
- nav2_costmap_2d/src/costmap_2d_ros.cpp
- nav2_costmap_2d/test/unit/lifecycle_test.cpp
- nav2_planner/src/planner_server.cpp
---
| Ticket(s) this addresses   | #4436 #4437 #4438 #4464 #4466 #4468 |
| Primary OS tested on |  Ubuntu |
---
pull changes from `main` into `humble`
> cherry-pick into humble: fix multi-bugs casued by `costmap_ros_`'s early shutdown

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp
- nav2_behavior_tree/test/plugins/action/test_bt_action_node.cpp
See https://github.com/ros-navigation/navigation2/pull/4408
Test results are the same for humble:
```
$ colcon test-result
build/nav2_behavior_tree/Testing/20240624-1845/Test.xml: 57 tests, 0 errors, 4 failures, 0 skipped
build/nav2_behavior_tree/test_results/nav2_behavior_tree/cpplint.xunit.xml: 165 tests, 0 errors, 4 failures, 0 skipped
build/nav2_behavior_tree/test_results/nav2_behavior_tree/test_action_navigate_through_poses_action.gtest.xml: 1 test, 0 errors, 1 failure, 0 skipped
build/nav2_behavior_tree/test_results/nav2_behavior_tree/test_single_trigger_node.gtest.xml: 1 test, 0 errors, 1 failure, 0 skipped
build/nav2_behavior_tree/test_results/nav2_behavior_tree/uncrustify.xunit.xml: 163 tests, 0 errors, 2 failures, 0 skipped
Summary: 811 tests, 0 errors, 12 failures, 163 skipped …
```
> bt_service_node and bt_action_node: Don't block BT loop (backport #4214 + #4234)

- nav2_controller/src/controller_server.cpp
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp
- nav2_costmap_2d/src/costmap_2d_ros.cpp
- nav2_costmap_2d/test/unit/lifecycle_test.cpp
- nav2_planner/src/planner_server.cpp
---
| Ticket(s) this addresses   | #4436 #4437 #4438 #4464 #4466 #4468 |
| Primary OS tested on |  Ubuntu |
---
pull changes from `main` into `iron`
> cherry-pick into Iron: fix multi-bugs casued by `costmap_ros_`'s early shutdown

- nav2_costmap_2d/include/nav2_costmap_2d/clear_costmap_service.hpp
- nav2_costmap_2d/src/clear_costmap_service.cpp
---
| Ticket(s) this addresses   | #4489 |
---
To avoid UAF bug mentioned in #4489 
shutdown services in destructor of `ClearCostmapService`
---
> shutdown services in destructor of `ClearCostmapService`

- nav2_bt_navigator/behavior_trees/nav_to_pose_with_consistent_replanning_and_if_path_becomes_invalid.xml
- nav2_bt_navigator/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml
- nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml
- nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_goal_patience_and_recovery.xml
- nav2_bt_navigator/behavior_trees/navigate_w_recovery_and_replanning_only_if_path_becomes_invalid.xml
https://github.com/ros-navigation/navigation2/issues/4498
> adjusting backup speed to be more reasonable

- nav2_behavior_tree/CMakeLists.txt
https://github.com/ros-navigation/navigation2/issues/4387
> Remove temp BT.CPP build warning workaround

- nav2_smac_planner/include/nav2_smac_planner/utils.hpp
- nav2_smac_planner/test/test_utils.cpp
---
---
For reproducing the issue see the test I added 
We noticed that ComputePathThroughPoses with SmacPlannerHybrid when asked to generate path through poses that are on the same line (in this example: [{x: 2, y: 0}, {x: 4, y: 0}, {x: 6, y: 0}]) generates path like this: 
It is assumed that end of path1 is the start of path2, but when end of path1 is converted from map to world, and then back to map it ends up in a different costmap cell.
When we convert world to map coordinates we [add …
> Fix map to world coordinate conversion

- nav2_costmap_2d/plugins/obstacle_layer.cpp
---
| Ticket(s) this addresses   | https://github.com/ros-navigation/navigation2/issues/4465 |
| Robotic platform tested on | Turtlebot Sim|
---
- Made obstacle layer consistent with other layers and make current false after enabled is toggled. So isCurrent function of costmap will return false and require update.
---
> fix(nav2_costmap_2d): make obstacle layer not current on enabled toggle

- nav2_mppi_controller/include/nav2_mppi_controller/motion_models.hpp
- nav2_mppi_controller/src/optimizer.cpp
- nav2_mppi_controller/test/critics_tests.cpp
- nav2_mppi_controller/test/motion_model_tests.cpp
| Ticket(s) this addresses   | #4509 |
---
> min_turning_r_ getting param fix

- nav2_costmap_2d/plugins/static_layer.cpp
While implementing a costmap plugin for work that behaves similar to the `StaticLayer`, I noticed a (possibly) missing `return;` in `StaticLayer::incomingUpdate()` for when the current frame and the incoming update's frame do not match. I say possibly because the logging seems to indicate that this is necessary, but this omission could also be intentional.
---
---
---
> Return out of map update if frames mismatch in Static Layer

- nav2_smoother/src/nav2_smoother.cpp
---
| Ticket(s) this addresses   | #4538 |
---
check the result `action_server_->get_current_goal();` , avoiding nullptr error.
---
> check nullptr in smoothPlan()

- nav2_controller/src/controller_server.cpp
---
| Ticket(s) this addresses   | #4547  |
---
If the action_server_ has been inactivate, the `action_server_->get_current_goal()` would be a nullPtr.
So we need to check it . 
---
> check nullPtr in `computeControl()`

- nav2_smac_planner/include/nav2_smac_planner/node_hybrid.hpp
- nav2_smac_planner/include/nav2_smac_planner/node_lattice.hpp
- nav2_smac_planner/src/analytic_expansion.cpp
- nav2_smac_planner/src/node_hybrid.cpp
- nav2_smac_planner/src/node_lattice.cpp
- nav2_smac_planner/test/test_a_star.cpp
| Ticket(s) this addresses   | #4542 |
---
* Test added to reproduce "wiggly" headings in analytic expansions in reverse
* Previous behaviour was rounding angles down to nearest bin, so the bad behaviour appeared in reverse and not forwards
* Scaled angles are now continuous and not discretised
* Lattice planner is unchanged
None
---
* There may still be poor behaviour in the lattice planner.
* This needs backporting to actually close #4542
> Straight analytic expansions

- nav2_docking/opennav_docking/src/docking_server.cpp
---
| Ticket(s) this addresses   | #4527  https://github.com/open-navigation/opennav_docking/pull/51 |
| Robotic platform tested on | Morphia robot, Gazebo classic) |
| Does this PR contain AI generated software? | No) |
---
---
> Fix dock orientation while moving backwards

- nav2_voxel_grid/CMakeLists.txt
- nav2_voxel_grid/include/nav2_voxel_grid/voxel_grid.hpp
- nav2_voxel_grid/src/voxel_grid.cpp
---
| Ticket(s) this addresses   | Follow-up to #4357 |
---
This commit does a number of things:
1. Switches to using target_link_libraries in nav2_voxel_grid, which gives us finer-grained control over what dependencies are exported to downstream as public or private.  In the particular case of nav2_voxel_grid, this doesn't matter too much, but it will help for other packages.
2. Moves the include directory down one level to include/${PROJECT_NAME}, which is best practice in ROS 2 since Humble.
3. Makes sure to export nav2_voxel_grid as a CMake target, so downstream users of it can use that target. …
> Switch nav2_voxel_grid to use modern CMake idioms.

- nav2_map_server/CMakeLists.txt
- nav2_map_server/include/nav2_map_server/costmap_filter_info_server.hpp
- nav2_map_server/include/nav2_map_server/map_saver.hpp
- nav2_map_server/include/nav2_map_server/map_server.hpp
- nav2_map_server/package.xml
- nav2_map_server/src/map_io.cpp
- nav2_map_server/test/component/CMakeLists.txt
- nav2_map_server/test/map_saver_cli/CMakeLists.txt
- nav2_map_server/test/map_saver_cli/test_map_saver_cli.cpp
- nav2_map_server/test/unit/CMakeLists.txt
---
| Ticket(s) this addresses   | Follow up to #4357  |
---
This commit does a number of things:
1. Switches to using target_link_libraries in nav2_map_server, which gives us finer-grained control over what dependencies are exported to downstream as public or private.
2. Moves the include directory down one level to include/${PROJECT_NAME}, which is best practice in ROS 2 since Humble.
3. Makes sure to export nav2_map_server as a CMake target, so downstream users of it can use that target.
4. Adds in `lifecycle_msgs` as a dependency.
5. Possibly most controversially, changes one test.  While …
> Switch nav2_map_server to use modern CMake idioms.

- nav2_costmap_2d/test/integration/costmap_tests_launch.py
- nav2_system_tests/src/behaviors/backup/test_backup_behavior.launch.py
- nav2_system_tests/src/behaviors/drive_on_heading/test_drive_on_heading_behavior.launch.py
- nav2_system_tests/src/behaviors/spin/test_spin_behavior.launch.py
- nav2_system_tests/src/error_codes/test_error_codes_launch.py
- nav2_system_tests/src/gps_navigation/test_case_py.launch.py
- nav2_system_tests/src/updown/test_updown_launch.py
- tools/planner_benchmarking/planning_benchmark_bringup.py
- tools/smoother_benchmarking/smoother_benchmark_bringup.py
---
| Ticket(s) this addresses   | Follow-up to #4557 |
---
These arguments have been the preferred way to use things since at least Humble.  This avoids warnings when running it for the tests.
One note is that I did not know how to test the changes to the `tools` subdirectory; hopefully automation will do that, or we can verify it manually.
None needed.
---
None needed.
> Switch to new-style static_transform_publisher arguments.

- nav2_costmap_2d/CMakeLists.txt
- nav2_costmap_2d/package.xml
- nav2_costmap_2d/test/integration/CMakeLists.txt
- nav2_costmap_2d/test/regression/CMakeLists.txt
- nav2_costmap_2d/test/unit/CMakeLists.txt
---
---
This PR updates nav2_costmap_2d to use modern CMake idioms.  In particular:
1.  Switch from ament_target_dependencies to target_link_libraries everywhere, since the latter is a superset of the features.
2.  Get rid of the unnecessary ALIAS library.  This was only ever used for linking for tests in *this* package; all other one downstream libraries will get that library name from ament_export_targets()
3.  Make sure to call ament_export_include_directories and ament_export_libraries to make sure any "old" CMake projects can properly use …
> Switch nav2_costmap_2d to modern CMake idioms.

- nav2_docking/opennav_docking/include/opennav_docking/dock_database.hpp
- nav2_docking/opennav_docking/include/opennav_docking/docking_server.hpp
- nav2_docking/opennav_docking/src/dock_database.cpp
- nav2_docking/opennav_docking/src/docking_server.cpp
Reopen https://github.com/open-navigation/opennav_docking/pull/56 against nav2
> Add mutex to reloadDbCb to fail if called during docking

- nav2_core/CMakeLists.txt
- nav2_core/package.xml
- nav2_graceful_controller/CMakeLists.txt
- nav2_graceful_controller/package.xml
---
---
nav2_core exports header files, but it does not have any implementation itself.  Make sure to make an INTERFACE library so downstreams can have access to the header files.
Note that this also required a change to nav2_graceful_controller, since it was erroneously getting a visualization_msgs dependency from nav2_core.
None needed.
---
This is part of the follow-up work for #4357 ; more PRs will be following to transition more packages.
> Make nav2_core an INTERFACE library.

- nav2_behaviors/CMakeLists.txt
- nav2_behaviors/package.xml
- nav2_behaviors/test/CMakeLists.txt
---
| Ticket(s) this addresses   | Followup to #4357 |
---
This PR changes nav2_behaviors to use modern CMake idioms.  In particular:
1. Get rid of ament_target_dependencies() in favor of target_link_libraries()
2. Make sure to export the target so downstream consumers can use it.
3. Relegate rclcpp_action to a test_dependency, since it is only needed for tests.
4. Move the include directory down one level in include/${PROJECT_NAME}, which is the ROS 2 best practice since Humble.
None needed.
---
There will be additional PRs upcoming to switch more of the Navigation2 codebase over to these idioms.
> Update nav2_behaviors to use modern CMake idioms.

- nav2_bt_navigator/CMakeLists.txt
- nav2_bt_navigator/package.xml
---
---
This PR cleans up nav2_bt_navigator to use modern CMake idioms.  In particular:
1. Switch from ament_target_dependencies to target_link_libraries.
2. Make sure to export the target so downstream packages can use it.
3. Move the include directory down one directory, which is best practice since Humble.
None needed.
---
There will be follow-up PRs coming to switch more of the packages over to modern CMake idioms.
> Make nav2_bt_navigator use modern CMake idioms.

- nav2_collision_monitor/CMakeLists.txt
- nav2_collision_monitor/package.xml
- nav2_collision_monitor/test/CMakeLists.txt
- nav2_collision_monitor/test/velocity_polygons_test.cpp
---
---
Switch nav2_collision_monitor to modern CMake idioms:
1.  Change from ament_target_dependencies to target_link_libraries.
2.  Add in ament_export_target to export the target to downstreams.
3.  Move the include directories down one level, which has been best practice since Humble.
None needed.
---
This is part of a larger series of changes to update to modern CMake practices.  There will be follow-on PRs converting more packages.
> Switch nav2_collision_monitor to modern CMake idioms.

- nav2_constrained_smoother/CMakeLists.txt
- nav2_constrained_smoother/include/nav2_constrained_smoother/constrained_smoother.hpp
- nav2_constrained_smoother/package.xml
- nav2_constrained_smoother/src/constrained_smoother.cpp
- nav2_constrained_smoother/test/CMakeLists.txt
---
---
Revamp nav2_constrained smoother to use modern CMake idioms:
1. Switch all uses of ament_target_dependencies to target_link_libraries.
2. Move the include directories down one level, which is best practice since Humble.
3. Make a few dependencies PRIVATE, so we don't need to export them to downstream consumers.
None needed.
---
This is part of the wider work of #4357.  As such, there will be follow-up PRs to transition more of the packages to modern CMake.
> Revamp nav2_constrained_smoother to use modern CMake idioms.

- nav2_dwb_controller/nav_2d_utils/CMakeLists.txt
- nav2_dwb_controller/nav_2d_utils/package.xml
- nav2_dwb_controller/nav_2d_utils/src/conversions.cpp
- nav2_dwb_controller/nav_2d_utils/test/CMakeLists.txt
---
---
Change nav_2d_utils to use modern CMake idioms:
1. Switch from ament_target_dependencies() to target_link_libraries()
2. Export the target so that downstream users can link against the library
3. Move the include directories down one directory, which is best practice since Humble.
4. Cleanup the dependencies.
None needed.
---
This is part of a larger series switching Navigation2 to use modern CMake idioms; there will be follow-up PRs to change more of the packages over.
> Switch nav_2d_utils to use modern CMake idioms.

- nav2_controller/CMakeLists.txt
- nav2_controller/package.xml
- nav2_controller/plugins/test/CMakeLists.txt
- nav2_controller/test/CMakeLists.txt
---
---
Change nav2_controller to use modern CMake idioms:
1. Change from ament_target_dependencies() to target_link_libraries()
2. Export the target so that downstream consumers can use it.
3. Move the include directories down one level, which is best practice since Humble.
4. Clean up the dependencies.
None needed.
---
This is part of a larger series switching Navigation2 to modern CMake idioms.  There will be follow-up PRs changing more of the packages.
> Switch nav2_controller to modern CMake idioms.

- nav2_lifecycle_manager/CMakeLists.txt
- nav2_lifecycle_manager/package.xml
- nav2_lifecycle_manager/src/lifecycle_manager_client.cpp
- nav2_lifecycle_manager/test/CMakeLists.txt
---
---
Change nav2_lifecycle_manager to modern CMake idioms:
1. Change from ament_target_dependencies() to target_link_libraries().
2. Export the target so that downstream packages can make use of it.
3. Move the include directory down one directory, which has been best practice since Humble.
4. Cleanup the dependencies to more accurately reflect what this package needs.
None needed.
---
This is part of a larger series of PRs to update Navigation2 to modern CMake idioms.  There will be follow-up PRs to convert more of the packages to this style.
> Switch nav2_lifecycle_manager to modern CMake idioms.

- nav2_mppi_controller/CMakeLists.txt
- nav2_mppi_controller/package.xml
- nav2_mppi_controller/test/CMakeLists.txt
- nav2_mppi_controller/test/utils/utils.hpp
---
| Ticket(s) this addresses   | Follow up to #4357  |
---
Change nav2_mppi_controller to use modern CMake idioms:
1. Use target_compile_options where useful.
2. Change from ament_target_dependences() to target_link_libraries()
3. Move the header files down one subdirectory, which is best practice since Humble.
4. Export the CMake target so that downstream libraries can use it.
5. Clean up the set of dependencies.
None needed.
---
This is part of a larger series of PRs to switch Navigation2 to modern CMake idioms.  There will be follow-up PRs converting more of the packages.
> Switch nav2_mppi_controller to modern CMake idioms.

- nav2_navfn_planner/CMakeLists.txt
- nav2_navfn_planner/package.xml
- nav2_navfn_planner/test/CMakeLists.txt
---
| Ticket(s) this addresses   | Follow-up to #4357 |
---
Change nav2_navfn_planner to use modern CMake idioms:
1.  Switch from ament_target_dependences() to target_link_libraries()
2.  Push the include directories down one level, which is best practice since Humble.
3.  Make sure to export the target so that downstream users can use the library.
None needed.
---
This is part of a larger series changing Navigation2 to use modern CMake idioms.  There will be follow-up PRs to convert other packages.
> Switch nav2_navfn_planner to modern CMake idioms.

- nav2_planner/CMakeLists.txt
- nav2_planner/include/nav2_planner/planner_server.hpp
- nav2_planner/package.xml
- nav2_planner/src/planner_server.cpp
- nav2_planner/test/CMakeLists.txt
- nav2_planner/test/test_dynamic_parameters.cpp
---
---
Change nav2_planner to modern CMake idioms:
1. Switch from ament_target_dependencies() to target_link_libraries()
2. Move the header files down one directory level, which has been best practice since Humble.
3. Make sure to export the target so downstream packages can use it.
4. Cleanup the dependencies to reflect what the package actually needs.
None needed.
---
This is part of a larger work to convert all of Navigation2 to modern CMake idioms.  The full list of packages still to convert can be found in …
> Switch nav2_planner to modern CMake idioms.

- nav2_regulated_pure_pursuit_controller/CMakeLists.txt
- nav2_regulated_pure_pursuit_controller/package.xml
- nav2_regulated_pure_pursuit_controller/test/CMakeLists.txt
---
---
Change nav2_regulated_pure_pursuit_controller to use modern CMake idioms:
1.  Use target_link_libraries instead of ament_target_dependencies
2.  Push the include directory down one level, which has been best practice since Humble.
3.  Make sure to export the CMake target so downstream consumers can use it.
None needed.
---
This is part of a larger series updating the CMake logic in Navigation2.  There will be follow-up PRs changing more of the packages.
> Switch nav2_regulated_pure_pursuit_controller to modern CMake idioms.

- nav2_rotation_shim_controller/CMakeLists.txt
- nav2_rotation_shim_controller/include/nav2_rotation_shim_controller/nav2_rotation_shim_controller.hpp
- nav2_rotation_shim_controller/package.xml
- nav2_rotation_shim_controller/src/nav2_rotation_shim_controller.cpp
- nav2_rotation_shim_controller/test/CMakeLists.txt
---
---
Change nav2_rotation_shim_controller to use modern CMake idioms:
1.  Switch from target_link_libraries to ament_target_dependencies
2.  Add an export target so downstream users can use it.
None needed.
---
This is part of a larger series updating Navigation2 to modern CMake idioms.  There will be follow-up PRs to switch more of the packages over.
> Switch nav2_rotation_shim_controller to modern CMake idioms.

- nav2_rviz_plugins/CMakeLists.txt
- nav2_rviz_plugins/include/nav2_rviz_plugins/costmap_cost_tool.hpp
- nav2_rviz_plugins/include/nav2_rviz_plugins/docking_panel.hpp
- nav2_rviz_plugins/include/nav2_rviz_plugins/nav2_panel.hpp
- nav2_rviz_plugins/package.xml
- nav2_rviz_plugins/src/costmap_cost_tool.cpp
- nav2_rviz_plugins/src/docking_panel.cpp
- nav2_rviz_plugins/src/nav2_panel.cpp
In addition, make some fixes to the code to more appropriately hold on to the Node object (there were warnings from the compiler without these fixes).
---
---
Change nav2_rviz_plugins to use modern CMake idioms:
1.  Make it a "nav2_package".  This ended up adding in additional warnings, which then required some code changes to fix.  Thus, there are some additional code changes in here to more appropriately hold onto weak pointers.
2.  Switch from ament_target_dependencies to target_link_libraries.
3.  Export the target so downstream CMake …
> Switch nav2_rviz_plugins to modern CMake idioms.

- nav2_docking/opennav_docking/include/opennav_docking/docking_server.hpp
- nav2_docking/opennav_docking/include/opennav_docking/navigator.hpp
- nav2_docking/opennav_docking/src/docking_server.cpp
- nav2_docking/opennav_docking/src/navigator.cpp
- nav2_docking/opennav_docking/test/test_navigator.cpp
Reopen https://github.com/open-navigation/opennav_docking/pull/57 in nav2
> Copy fix-terminate diff from opennav_docking repo

- nav2_smoother/CMakeLists.txt
- nav2_smoother/package.xml
- nav2_smoother/test/CMakeLists.txt
---
---
Switch nav2_smoother to modern CMake idioms:
1.  Change from ament_target_dependencies to target_link_libraries
2.  Export a target so that downstream packages can use it.
None needed.
---
This is part of a larger series converting all of Navigation2 to use modern CMake idioms.  There will be follow-up PRs converting more packages.
> Switch nav2_smoother to modern CMake idioms.

- nav2_theta_star_planner/CMakeLists.txt
- nav2_theta_star_planner/package.xml
- nav2_theta_star_planner/src/theta_star.cpp
- nav2_theta_star_planner/src/theta_star_planner.cpp
---
---
Change nav2_theta_star_planner to modern CMake idioms:
1.  Switch from ament_target_dependencies to target_link_libraries
2.  Export a target so downstream packages can use it.
3.  Push the include directory down a level, which is best practice since Humble.
None needed.
---
This is part of a larger series updating Navigation2 packages to modern CMake idioms.  There will be follow-up PRs to convert more of the packages.
> Switch nav2_theta_star_planner to modern CMake idioms.

- nav2_velocity_smoother/CMakeLists.txt
- nav2_velocity_smoother/package.xml
- nav2_velocity_smoother/test/CMakeLists.txt
---
---
Update nav2_velocity_smoother to use modern CMake idioms:
1.  Switch from ament_target_dependencies to target_link_libraries
2.  Export a CMake target so that downstream packages can use it.
None needed.
---
This is part of a larger series updating Navigation2 to use modern CMake idioms.  There are approximately 11 more PRs to follow this one.
> Switch nav2_velocity_smoother to modern CMake idioms.

- nav2_behaviors/include/nav2_behaviors/timed_behavior.hpp
---
| Robotic platform tested on | (gazebo simulation) |
---
**Purpose:**
This PR fix a problem with TimedBehavior. It occurs when we run first DriveOnHeading -> cancel first DriveOnHeading -> immediately run the second  DriveOnHeading. This way we accept new goal -> requested preemption -> terminate_all goals because of cancel first DriveOnHeading -> current goal from second DriveOnHeading is empty -> second  DriveOnHeading fails.
**Changes:**
We swapped two checks in TimedBehavior. First we check if we have preemption requested and then check if we request to cancel. In this case our current goal won’t be empty and DriveOnHeading won’t …
> Fix behavior server

- nav2_graceful_controller/CMakeLists.txt
- nav2_graceful_controller/include/nav2_graceful_controller/ego_polar_coords.hpp
- nav2_graceful_controller/package.xml
- nav2_graceful_controller/src/graceful_controller.cpp
- nav2_graceful_controller/test/CMakeLists.txt
---
---
Update nav2_graceful_controller to use modern CMake idioms:
2.  Export a CMake target so downstream packages can use it.
3.  Push the include directory down, which is best practice since Humble.
None needed.
---
This is part of a larger series updating Navigation2 to modern CMake practices.  There are approximately 10 PRs left to go after this one.
> Switch nav2_graceful_controller to modern CMake idioms.

- nav2_dwb_controller/costmap_queue/CMakeLists.txt
- nav2_dwb_controller/costmap_queue/package.xml
---
---
Update the costmap_queue package to use modern CMake idioms:
1.  Switch from ament_target_dependencies to target_link_libraries
2.  Export a CMake target so downstream users can link against it.
None needed.
---
This is part of a larger series to convert all Navigation2 packages to modern CMake idioms.  There are approximately 9 PRs after this one.
> Switch costmap_queue to use modern CMake idioms.

- nav2_dwb_controller/dwb_core/CMakeLists.txt
- nav2_dwb_controller/dwb_core/package.xml
- nav2_dwb_controller/dwb_core/test/CMakeLists.txt
---
---
Update dwb_core to use modern CMake idioms:
2.  Export a CMake target so downstream consumers can use it.
3.  Push the include directories down one level, which has been best practice since Humble.
None needed.
---
This is part of a larger series updating Navigation2 packages to use modern CMake idioms.  There are approximately 8 PRs left in the series after this.
> Switch dwb_core to modern CMake idioms.

- nav2_dwb_controller/dwb_critics/CMakeLists.txt
- nav2_dwb_controller/dwb_critics/package.xml
- nav2_dwb_controller/dwb_critics/test/CMakeLists.txt
---
---
Update dwb_critics to use modern CMake idioms:
2.  Export a CMake target so downstream packages can use the libraries here.
3.  Push the include directories down one level, which is best practice since Humble.
None needed.
---
This is part of a larger series updating Navigation2 to modern CMake idioms.  There are approximately 6 packages left after this one.  However, note that I will be taking a break from this work for one or two weeks, as I am on vacation, and still …
> Switch dwb_critics to modern CMake idioms.

- nav2_bringup/launch/bringup_launch.py
- nav2_bringup/launch/tb3_loopback_simulation.launch.py
- nav2_bringup/launch/tb4_loopback_simulation.launch.py
- nav2_bringup/params/nav2_params.yaml
- nav2_loopback_sim/README.md
- nav2_loopback_sim/launch/loopback_simulation.launch.py
- nav2_loopback_sim/nav2_loopback_sim/loopback_simulator.py
- nav2_loopback_sim/nav2_loopback_sim/utils.py
- nav2_loopback_sim/package.xml
- nav2_loopback_sim/pytest.ini
- nav2_loopback_sim/setup.cfg
- nav2_loopback_sim/setup.py
- nav2_loopback_sim/test/test_copyright.py
- nav2_loopback_sim/test/test_flake8.py
- nav2_loopback_sim/test/test_pep257.py
https://github.com/ros-navigation/navigation2/issues/3924
> Adding new Nav2 loopback simulator

- nav2_collision_monitor/CMakeLists.txt
- nav2_collision_monitor/include/nav2_collision_monitor/polygon.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/source.hpp
- nav2_collision_monitor/params/collision_monitor_params.yaml
- nav2_collision_monitor/src/collision_monitor_node.cpp
- nav2_collision_monitor/src/pointcloud.cpp
- nav2_collision_monitor/src/polygon.cpp
- nav2_collision_monitor/src/range.cpp
- nav2_collision_monitor/src/scan.cpp
- nav2_collision_monitor/src/source.cpp
- nav2_collision_monitor/test/collision_monitor_node_test.cpp
- nav2_msgs/CMakeLists.txt
- nav2_msgs/msg/CollisionMonitorState.msg
| Ticket(s) this addresses   | #4612 |
| Robotic platform tested on | Custom robotic platform running ROS2 humble |
---
* Backport in nav2_collision_monitor dynamic parameters <polygon_name name>.enabled and <source name>.enabled for humble
* 
* No documentation update required as  the feature is backported and already documented 
---
* Need to adapt the test node collision_monitor_node_test.cpp to work without action_state_ (not implemented in this branch and commit)
> nav2_collision_monitor dynamic parameters polygon and source enabled for Humble

- nav2_dwb_controller/dwb_plugins/CMakeLists.txt
- nav2_dwb_controller/dwb_plugins/include/dwb_plugins/velocity_iterator.hpp
- nav2_dwb_controller/dwb_plugins/package.xml
- nav2_dwb_controller/dwb_plugins/test/CMakeLists.txt
---
| Ticket(s) this addresses   | Followup to #4357  |
---
Change dwb_plugins to modern CMake idioms:
1.  Use target_link_libraries instead of ament_target_dependencies
2.  Export a CMake target for downstream users to use.
None needed.
---
This is part of a larger series updating Navigation2 to use modern CMake idioms.  After this PR, there are 7 PRs left to finish the conversion.
> Switch dwb_plugins to modern CMake idioms.

- nav2_docking/opennav_docking_core/CMakeLists.txt
- nav2_docking/opennav_docking_core/include/opennav_docking_core/charging_dock.hpp
- nav2_docking/opennav_docking_core/package.xml
---
---
Update opennav_docking_core to modern CMake idioms:
1.  Add in an INTERFACE target that contains the header files
2.  Export a CMake target so downstream packages can use it.
3.  Reduce the exported dependencies.
4.  Push the include directory down one level, which is best practice since Humble.
None needed.
---
This is part of a larger series to convert Navigation2 to modern CMake idioms.  There are 6 PRs required after this one.
> Switch opennav_docking_core to modern CMake idioms.

- nav2_loopback_sim/nav2_loopback_sim/loopback_simulator.py
- nav2_loopback_sim/nav2_loopback_sim/utils.py
---
| Ticket(s) this addresses   | #4616 |
| Primary OS tested on | Humble |
---
* Publishes realistic laser data according to the map
---
> Added laser data from map in nav2_loopback_sim

- nav2_docking/opennav_docking_bt/CMakeLists.txt
- nav2_docking/opennav_docking_bt/package.xml
- nav2_docking/opennav_docking_bt/test/CMakeLists.txt
---
---
Update opennav_docking_bt to use modern CMake idioms:
1.  Use target_link_libraries instead of ament_target_dependencies
2.  Export a CMake target so that downstream packages can link against it.
3.  Push the include directories down one level, which is best practice since Humble.
None needed.
---
This is part of a larger series converting Navigation2 to modern CMake idioms.  There are 5 PRs after this one.
> Switch opennav_docking_bt to modern CMake idioms.

- nav2_docking/opennav_docking/CMakeLists.txt
- nav2_docking/opennav_docking/include/opennav_docking/pose_filter.hpp
- nav2_docking/opennav_docking/package.xml
- nav2_docking/opennav_docking/src/pose_filter.cpp
- nav2_docking/opennav_docking/test/CMakeLists.txt
---
---
Switch opennav_docking to modern CMake idioms:
2.  Export a CMake target so downstream users can link against it.
3.  Push the include directories down one level, which is best practice since Humble.
4. Switch this package to be a "nav2_package".
None needed.
---
This is part of a larger series converting Navigation2 to modern CMake idioms.  After this PR there are 4 PRs to go.
> Switch opennav_docking to modern CMake idioms.

- nav2_smac_planner/CMakeLists.txt
- nav2_smac_planner/include/nav2_smac_planner/a_star.hpp
- nav2_smac_planner/include/nav2_smac_planner/analytic_expansion.hpp
- nav2_smac_planner/include/nav2_smac_planner/collision_checker.hpp
- nav2_smac_planner/include/nav2_smac_planner/costmap_downsampler.hpp
- nav2_smac_planner/include/nav2_smac_planner/node_2d.hpp
- nav2_smac_planner/include/nav2_smac_planner/node_basic.hpp
- nav2_smac_planner/include/nav2_smac_planner/node_hybrid.hpp
- nav2_smac_planner/include/nav2_smac_planner/node_lattice.hpp
- nav2_smac_planner/include/nav2_smac_planner/smoother.hpp
- nav2_smac_planner/include/nav2_smac_planner/utils.hpp
- nav2_smac_planner/package.xml
- nav2_smac_planner/src/node_lattice.cpp
- nav2_smac_planner/src/smac_planner_hybrid.cpp
- nav2_smac_planner/src/smac_planner_lattice.cpp
- nav2_smac_planner/src/smoother.cpp
- nav2_smac_planner/test/CMakeLists.txt
- nav2_smac_planner/test/test_collision_checker.cpp
- nav2_smac_planner/test/test_nodebasic.cpp
---
---
Switch nav2_smac_planner to use modern CMake idioms:
1. Switch from ament_target_dependencies to target_link_libraries
2. Don't compile the common files in this package more than once.  Instead, compile those into a library, then link that library into all of the other ones.
3.  Export a CMake target so downstream packages can use it.
4.  Push the include directories down one level, which is best practice since Humble.
None needed.
---
This is part of a larger series to switch Navigation2 to modern CMake idioms.  After this PR, there 3 …
> Switch nav2_smac_planner to modern CMake idioms.

- nav2_loopback_sim/README.md
- nav2_loopback_sim/nav2_loopback_sim/loopback_simulator.py
Adding option for cmd_vel to be stamped for later migration to Twist Stamped
> Adding stamped option for loopback sim

- nav2_smac_planner/CMakeLists.txt
- nav2_smac_planner/include/nav2_smac_planner/constants.hpp
- nav2_smac_planner/include/nav2_smac_planner/node_basic.hpp
- nav2_smac_planner/include/nav2_smac_planner/thirdparty/robin_hood.h
- nav2_smac_planner/include/nav2_smac_planner/types.hpp
- nav2_smac_planner/src/analytic_expansion.cpp
- nav2_smac_planner/src/collision_checker.cpp
- nav2_smac_planner/src/costmap_downsampler.cpp
- nav2_smac_planner/src/node_2d.cpp
- nav2_smac_planner/src/node_hybrid.cpp
- nav2_smac_planner/src/smac_planner_hybrid.cpp
- nav2_smac_planner/src/smoother.cpp
- nav2_smac_planner/test/deprecated/smoother_cost_function.hpp
- nav2_smac_planner/test/test_a_star.cpp
- nav2_smac_planner/test/test_node2d.cpp
- nav2_smac_planner/test/test_nodehybrid.cpp
- nav2_smac_planner/test/test_nodelattice.cpp
---
| Ticket(s) this addresses   | Follow-up to #4634  |
---
This is a follow-up PR to #4634 where we change `nav2_smac_planner` to use `nav2_package`.  This turns on additional compiler warnings, along with `-Werror`, so it requires some fixes to go along with it.
I want to highlight one controversial change in here.  The [UNKNOWN constant in constants.hpp](https://github.com/ros-navigation/navigation2/commit/03577dc1486ef6c426370252a708fc0fdf6a9b36#diff-47d128ffcb4f25caaf908b5962cefca6558de3139d5a9a2ea03f88e04dcdfadeR62) was causing shadowing problems with `UNKNOWN` embedded inside of `enum …
> Fixes for nav2_smac_planner to build with -Werror.

- nav2_system_tests/CMakeLists.txt
- nav2_system_tests/package.xml
- nav2_system_tests/src/behavior_tree/CMakeLists.txt
- nav2_system_tests/src/behavior_tree/test_behavior_tree_node.cpp
- nav2_system_tests/src/behaviors/assisted_teleop/CMakeLists.txt
- nav2_system_tests/src/behaviors/assisted_teleop/assisted_teleop_behavior_tester.hpp
- nav2_system_tests/src/behaviors/wait/CMakeLists.txt
- nav2_system_tests/src/behaviors/wait/wait_behavior_tester.hpp
- nav2_system_tests/src/dummy_controller/CMakeLists.txt
- nav2_system_tests/src/dummy_planner/CMakeLists.txt
- nav2_system_tests/src/localization/CMakeLists.txt
- nav2_system_tests/src/localization/test_localization_node.cpp
- nav2_system_tests/src/planning/CMakeLists.txt
- nav2_system_tests/src/planning/planner_tester.hpp
- nav2_system_tests/src/planning/test_planner_is_path_valid.cpp
- nav2_system_tests/src/planning/test_planner_plugins.cpp
- nav2_system_tests/src/updown/CMakeLists.txt
- nav2_system_tests/src/updown/test_updown.cpp
---
---
Update nav2_system_tests to use modern CMake idioms:
1.  Make everything in this package a `test_depend`, since this is all tests.
2.  Along with the previous point, move everything in this package under the BUILD_TESTING conditional in CMake.
3.  Switch from ament_target_dependencies to target_link_libraries everywhere.
4.  Remove all references to Boost.
None needed.
---
This is part of a larger series updating Navigation2 to use modern CMake idioms.  After this PR, there are 2 PRs left to open.
> Switch nav2_system_tests to modern CMake idioms.

- nav2_costmap_2d/test/integration/CMakeLists.txt
- nav2_dwb_controller/nav2_dwb_controller/CMakeLists.txt
- nav2_dwb_controller/nav2_dwb_controller/package.xml
- nav2_mppi_controller/benchmark/CMakeLists.txt
- nav2_mppi_controller/benchmark/optimizer_benchmark.cpp
- nav2_smac_planner/CMakeLists.txt
- navigation2/CMakeLists.txt
- navigation2/package.xml
---
---
Just some minor fixes to various CMake problems found throughout the repository as I was reviewing things in following up for #4357.
None needed.
---
None needed.
> Various small CMake fixes.

- nav2_mppi_controller/include/nav2_mppi_controller/controller.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/tools/trajectory_visualizer.hpp
- nav2_mppi_controller/src/controller.cpp
- nav2_mppi_controller/src/trajectory_visualizer.cpp
- nav2_mppi_controller/test/trajectory_visualizer_tests.cpp
| Robotic platform tested on | Gazebo simulation of a custom robot |
---
* I publish the optimal trajectory as a `nav_msgs::msg::Path` message. Needed if we want to calculate the velocity commands ourselves.
None
---
None
> Publish optimal trajectory as a Path message

- nav2_behavior_tree/CMakeLists.txt
| Ticket(s) this addresses   | #4652 |
| Robotic platform tested on | n/a |
---
Restored installation of nav2_behaviour_tree test utils header files after cmake revamp.
These are needed to facilitate testing of custom actions/conditions etc. 
n/a
---
n/a
> Restore exported BT test utils header files after cmake revamp (#4652)

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/bt_cancel_action_node.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp
| Info | Details |
| **Ticket(s) this addresses** | #4618 |
| **Primary OS tested on** | Ubuntu 22.04 |
| **Robotic platform tested on** | Gazebo simulation, Turtlebot3 hardware |
| **Does this PR contain AI generated software?** | No |
---
- Updated `bt_action_node`, `bt_cancel_action_node`, and `bt_service_node` to use `getInputPortOrBlackboard()` for initializing `server_timeout`.
- Ensured that the `server_timeout` parameter now respects the default value from the blackboard if not explicitly set in the BT action node.
- This change addresses the issue where the `default_server_timeout` was always overridden, leading to more consistent behavior and reducing configuration overhead.
- No new parameters were added, so no updates to default configs are necessary. …
> Fix: Ensure `server_timeout` Respects Default Values Using `getInputPortOrBlackboard()`

- nav2_mppi_controller/include/nav2_mppi_controller/motion_models.hpp
- nav2_mppi_controller/test/motion_model_tests.cpp
Closes https://github.com/ros-navigation/navigation2/issues/4661
> Fixing #4661: MPPI ackermann reversing taking incorrect sign sometimes

- nav2_dwb_controller/dwb_plugins/include/dwb_plugins/standard_traj_generator.hpp
- nav2_dwb_controller/dwb_plugins/src/standard_traj_generator.cpp
---
| Ticket(s) this addresses   | Issue #3277 |
| Primary OS tested on | Ubuntu 22.04|
| Robotic platform tested on | Turtlebot3 Gazebo simulation - waffle |
---
- Added an option in the standard trajectory generator in DWB to allow the user to limit the velocity command in the trajectory 
-based on current trajectory through a new parameter (`limit_vel_cmd_in_traj_`)
- This option ensures that the acceleration constraints are respected in the event there is a large difference between the current and commanded velocity - which may be more useful when there is no velocity smoother in use
- `limit_vel_cmd_in_traj_` is set to false by default, but when set to true, would use …
> [DWB] Option to limit velocity commands in trajectory generator

- nav2_behavior_tree/plugins/decorator/path_longer_on_approach.cpp
---
| Ticket(s) this addresses   | #4110  |
| Robotic platform tested on | ROX |
---
---
> fixing path longer on approach

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
---
| Ticket(s) this addresses   | N.A. |
| Primary OS tested on | Ubuntu, MacOS, Windows |
| Robotic platform tested on | Steve's Robot, gazebo simulation of Tally, hardware turtlebot |
---
This fix would avoid the case when bt action server stills logs bt execution result even if error occurs when preparing the result. Therefore, it would be more logical to log result information after result is ready.
N.A.
---
> fix to bt action server logging before bt execution result being ready

- nav2_util/include/nav2_util/simple_action_server.hpp
Cancelling a goal is nominal behavior and therefore it should not log warning.
> fix(simple-action-server): info log instead of warn on cancel

- nav2_controller/src/controller_server.cpp
Backport of https://github.com/ros-navigation/navigation2/pull/4675
> feat(controller-server): `publish_zero_velocity` parameter jazzy backport

- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/remove_in_collision_goals_action.hpp
- nav2_behavior_tree/plugins/action/remove_in_collision_goals_action.cpp
- nav2_costmap_2d/src/costmap_2d_ros.cpp
- nav2_costmap_2d/src/layered_costmap.cpp
- nav2_costmap_2d/test/unit/costmap_cost_service_test.cpp
- nav2_msgs/srv/GetCosts.srv
- nav2_rviz_plugins/src/costmap_cost_tool.cpp
---
| Primary OS tested on | Ubuntu, |
| Robotic platform tested on | custom gazebo simulation |
---
* Change GetCosts to use PoseStamped instead of Pose2D so that we can use the frame_id to transform the pose in the costmap frame
* Added consider_unknown_as_obstacle to control whether NO_INFORMATION is treated as "in collision" or not
* Make GetCosts service return 255.0 instead of -1.0 if the coords are out of bounds
* fix rviz costmap tool to use the global fixed frame of rviz
---
> Improvements in RemoveInCollisionGoals and adjacent features

- nav2_simple_commander/nav2_simple_commander/robot_navigator.py
---
| Ticket(s) this addresses   | (add tickets here #4696 ) |
| Primary OS tested on | Ubuntu-24.04 (via Devcontainer Docker) |
---
- Added action clients to the `destroy_node` function that were preventing the `BasicNavigator` node from completely releasing its resources
---
> Added missing action clients in robot_navigator(BasicNavigator) to destroy_node

- nav2_rotation_shim_controller/include/nav2_rotation_shim_controller/nav2_rotation_shim_controller.hpp
- nav2_rotation_shim_controller/src/nav2_rotation_shim_controller.cpp
https://github.com/ros-navigation/navigation2/pull/4690
@sandeepdutta please review! I updated the default for my parameter to be half of the threshold (22.5) instead of a third (15), but you can change that in your own config file if you prefer that behavior. 
For the backport, I'll have to make the default 45 degrees so we don't change the default behavior, but you can again set it to 1/3 (or otherwise) in your configuration file to change that behavior for your application on Humble
> Adding disengagement threshold to rotation shim controller

- nav2_waypoint_follower/CMakeLists.txt
- nav2_waypoint_follower/include/nav2_waypoint_follower/plugins/photo_at_waypoint.hpp
- nav2_waypoint_follower/package.xml
- nav2_waypoint_follower/test/CMakeLists.txt
---
---
Change nav2_waypoint_follower to modern CMake idioms:
2.  Export a CMake target so downstream packages can use it.
3.  Push the include directories down one level, which has been best practice since Humble.
Note well that this will fail to compile until https://github.com/cra-ros-pkg/robot_localization/pull/895 is merged, released, and synced into Rolling.
None needed.
---
This is the last of the series to convert Navigation2 to modern CMake idioms.  One suggestion I …
> Switch nav2_waypoint_follower to modern CMake idioms.

- nav2_theta_star_planner/src/theta_star_planner.cpp
This PR resolves the issue discussed in: https://github.com/ros-navigation/navigation2/issues/4694
The planner server was crashing when attempting to plan paths outside the map bounds using the Theta* planner on Humble.
---
| Ticket(s) this addresses   | https://github.com/ros-navigation/navigation2/issues/4694 |
| Primary OS tested on | Ubuntu 20.04.6 LTS |
| Robotic platform tested on | planner playground, Gary Robot hardware |
---
* This change returns an empty path when either the goal or start coordinates are outside the map bounds, preventing the planner server from crashing.
> fix(nav2_theta_star_planner): Planner Server Crashing When Planning Outside Map Bounds with Theta* on Humble

- nav2_rotation_shim_controller/src/nav2_rotation_shim_controller.cpp
Add header data to goal for short paths.
Commit d8ae3c1f9b8233e86ed54dfbe615b1ba56b51b6d added the possibility to the rotation shim controller to rotate towards the goal when the goal was closer that the `forward_sampling_distance`. This feature was not fully working as the goal was missing proper header data, causing the rotation shim to give back the control ot the main controller.
---
| Ticket(s) this addresses   |  #4281 |
---
Fix rotation shim controller for short path (shorter than `forward_sampling_distance`)
NA
---
NA
> [RotationShimController] fix: rotate on short paths

- nav2_rviz_plugins/include/nav2_rviz_plugins/docking_panel.hpp
- nav2_rviz_plugins/src/docking_panel.cpp
- nav2_rviz_plugins/src/utils.cpp
---
| Ticket(s) this addresses   | #4689 |
| Robotic platform tested on | Morphia robot |
---
* Improved internal state machine to fix randomly RVIZ crashes.
* Improved the UI.
| ![Captura desde 2024-10-07 12-43-26](https://github.com/user-attachments/assets/47c18eed-0ad5-4b42-a09a-82d47764d1cb) | ![Captura desde 2024-10-08 11-06-38](https://github.com/user-attachments/assets/d6ce3a9d-2030-488d-a817-9cda1791b37c) |
| -------- | ------- |
| *Before* | *After* |
---
> Improve Docking panel

- nav2_rotation_shim_controller/include/nav2_rotation_shim_controller/nav2_rotation_shim_controller.hpp
- nav2_rotation_shim_controller/src/nav2_rotation_shim_controller.cpp
- nav2_rotation_shim_controller/test/test_shim_controller.cpp
---
| Robotic platform tested on | (Differential Robot, Gazebo) |
---
* Added a new dynamic parameter called `rotate_to_heading_once`.
If the parameter is set to `True`, then `Shim` aligns the robot's heading with the path only once at the very beginning.
* Added a method `bool RotationShimController::isGoalChanged(const nav_msgs::msg::Path & path)`
This function checks whether the goal in the provided path has changed compared to the current path stored in the controller.
**Returns `true`** if the current path is empty (no poses stored) or if the goal pose (last …
> `Shim Controller`: Added parameter `rotate_to_heading_once` to align a robot only at the very beginning

- nav2_rotation_shim_controller/src/nav2_rotation_shim_controller.cpp
Add frame_id to goal when rotating towards goal heading, otherwise the transform would fail. This bug was introduced in 30e2cde by not setting the frame_id.
This fix is similar to https://github.com/ros-navigation/navigation2/pull/4716
---
| Ticket(s) this addresses   | 4332 |
---
Fix a bug.
---
> [RotationShimController] fix: rotate to goal heading

- nav2_costmap_2d/plugins/obstacle_layer.cpp
- nav2_loopback_sim/README.md
- nav2_loopback_sim/nav2_loopback_sim/loopback_simulator.py
- nav2_smac_planner/README.md
---
| Robotic platform tested on | gazebo simulation of TB4 |
---
- loopback_simulator: Publish `/clock`, so there is a clock available for all other nodes. Without a clock published, the local & global costmaps are not published, so they don't appear on rviz.
- Costmap_2d: Use QoS profile from `rclcpp::SensorDataQoS()` instead of `rmw_qos_profile_t`. This solves an issue where the subscriber uses `RELIABLE` setting even when initialized from `rmw_qos_profile_sensor_data`. In addition the `Subscriber(..., rmw_qos_profile_t)` constructor is anyway deprecated in favor of `Subscriber(..., rclcpp::QoS)`
- Small …
> [loopback_sim] Publish clock, [nav2_costmap_2d] Fix Qos

- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d.hpp
* Fix incorrect doxygen comment naming params that don't exist.
> Fix incorrect doxygen comment in costmap_2d

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/assisted_teleop_action.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/back_up_action.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/remove_passed_goals_action.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/spin_action.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/wait_action.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/condition/distance_traveled_condition.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/condition/goal_reached_condition.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/condition/is_battery_low_condition.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/condition/is_path_valid_condition.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/condition/time_expired_condition.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/condition/transform_available_condition.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/decorator/rate_controller.hpp
- nav2_behavior_tree/plugins/action/assisted_teleop_action.cpp
- nav2_behavior_tree/plugins/action/back_up_action.cpp
- nav2_behavior_tree/plugins/action/remove_passed_goals_action.cpp
- nav2_behavior_tree/plugins/action/spin_action.cpp
- nav2_behavior_tree/plugins/action/wait_action.cpp
- nav2_behavior_tree/plugins/condition/distance_traveled_condition.cpp
- nav2_behavior_tree/plugins/condition/goal_reached_condition.cpp
- nav2_behavior_tree/plugins/condition/is_battery_low_condition.cpp
- nav2_behavior_tree/plugins/condition/is_path_valid_condition.cpp
- nav2_behavior_tree/plugins/condition/time_expired_condition.cpp
- nav2_behavior_tree/plugins/condition/transform_available_condition.cpp
- nav2_behavior_tree/plugins/decorator/rate_controller.cpp
| Ticket(s) this addresses   |#3988 |
| Robotic platform tested on | – |
---
* Pass IDLE state to BT action nodes (to the on_tick callback), and use that as initialize condition
* This way ports can be updated at every restart (on first start and after each halt)
* See conversation at the bottom of #3988
> Pass IDLE to on_tick, use that for initialize condition

- nav2_mppi_controller/include/nav2_mppi_controller/tools/parameters_handler.hpp
- nav2_mppi_controller/src/critics/cost_critic.cpp
- nav2_mppi_controller/src/parameters_handler.cpp
- nav2_mppi_controller/test/parameter_handler_test.cpp
The "verbose" parameter of the parameters_handler is a special case that needs registration before the
dynamic parameter handler callback is registered.
In verbose mode make the parameter handler info/warn/debug messages more expressive.
---
| Ticket(s) this addresses   |  #4704 |
| Robotic platform tested on | AOS kelpie |
---
Improve the verbose handling of the mppi parameter_handler class and make it more verbose to
help distinguish between ParameterType::Dynamic and ParameterType::Static parameters.
Key point is to treat the verbose parameter of the mppi parameter_handler class
as a special case and register it *BEFORE* the dynamic …
> mppi parameters_handler: Improve verbose handling (#4704)

- nav2_bringup/params/nav2_params.yaml
- nav2_docking/README.md
- nav2_docking/opennav_docking/include/opennav_docking/controller.hpp
- nav2_docking/opennav_docking/include/opennav_docking/docking_server.hpp
- nav2_docking/opennav_docking/src/controller.cpp
- nav2_docking/opennav_docking/src/docking_server.cpp
- nav2_docking/opennav_docking/test/test_controller.cpp
- nav2_docking/opennav_docking/test/test_docking_server.py
---
| Ticket(s) this addresses   | #4404 |
| Robotic platform tested on | Morphia |
---
* Added optional collision checking on docking / undocking.
---
> Added collision detection for docking

- nav2_smac_planner/src/node_hybrid.cpp
- nav2_smac_planner/src/smac_planner_hybrid.cpp
- nav2_smac_planner/test/test_nodehybrid.cpp
Backport of https://github.com/ros-navigation/navigation2/pull/4636 after running into an issue with the angles on humble branch described here https://github.com/ros-navigation/navigation2/issues/4755
> Update Smac Planner for rounding to closest bin rather than flooring

- .circleci/config.yml
- nav2_collision_monitor/test/collision_monitor_node_test.cpp
- nav2_docking/opennav_docking/test/test_docking_server.py
- nav2_loopback_sim/nav2_loopback_sim/loopback_simulator.py
- nav2_system_tests/src/behaviors/assisted_teleop/assisted_teleop_behavior_tester.cpp
- nav2_system_tests/src/behaviors/assisted_teleop/assisted_teleop_behavior_tester.hpp
- nav2_util/include/nav2_util/twist_publisher.hpp
- nav2_util/include/nav2_util/twist_subscriber.hpp
- nav2_util/test/test_twist_publisher.cpp
- nav2_util/test/test_twist_subscriber.cpp
- nav2_velocity_smoother/test/test_velocity_smoother.cpp
- tools/underlay.repos
https://github.com/ros-navigation/docs.nav2.org/pull/614
https://github.com/ros-navigation/nav2_minimal_turtlebot_simulation/pull/16
#1594 #3755
> Migrating twist to twiststamped in simulations for recommended default bringups

- nav2_behavior_tree/plugins/control/recovery_node.cpp
- nav2_behavior_tree/test/plugins/control/test_recovery_node.cpp
Reverts ros-navigation/navigation2#4777
> Revert "Make RecoveryNode return Running"

- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/back_up_action.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/drive_on_heading_action.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/spin_action.hpp
- nav2_behavior_tree/nav2_tree_nodes.xml
- nav2_behavior_tree/plugins/action/back_up_action.cpp
- nav2_behavior_tree/plugins/action/drive_on_heading_action.cpp
- nav2_behavior_tree/test/plugins/action/test_back_up_action.cpp
- nav2_behavior_tree/test/plugins/action/test_drive_on_heading_action.cpp
- nav2_behavior_tree/test/plugins/action/test_spin_action.cpp
- nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
- nav2_behaviors/include/nav2_behaviors/plugins/spin.hpp
- nav2_behaviors/plugins/back_up.cpp
- nav2_behaviors/plugins/spin.cpp
- nav2_msgs/action/BackUp.action
- nav2_msgs/action/DriveOnHeading.action
- nav2_msgs/action/Spin.action
- nav2_simple_commander/README.md
- nav2_simple_commander/nav2_simple_commander/robot_navigator.py
---
| Ticket(s) this addresses   | #4783 |
| Robotic platform tested on | Gazebo sim of custom robot |
---
Adds a new bool param called `no_collision_checks` to the `DriveOnHeading` and `BackUp` actions. When the param is set to `true`, collision checking is disabled on these actions. This is useful, for example, when you want to push through known obstacles.
Updated the README for the commander API to include the flag in the listed example.
The new param needs to be added to the docs page.
---
> new param to disable collision checking in DriveOnHeading and BackUp actions

- nav2_smac_planner/src/smac_planner_2d.cpp
- nav2_smac_planner/src/smac_planner_hybrid.cpp
- nav2_smac_planner/src/smac_planner_lattice.cpp
- nav2_smac_planner/test/test_smac_2d.cpp
- nav2_smac_planner/test/test_smac_hybrid.cpp
- nav2_smac_planner/test/test_smac_lattice.cpp
This case was already properly handled in the smac_planner_2d (since PR #2488), but it was still leading to an A* backtrace failure in the smac_planner_hybrid and smac_planner_lattice. Let's harmonize the handling of this case.
---
| Ticket(s) this addresses   | #4792 |
---
---
> nav2_smac_planner: handle corner case where start and goal are on the same cell

- nav2_util/include/nav2_util/lifecycle_node.hpp
- nav2_util/src/lifecycle_node.cpp
- nav2_util/test/test_lifecycle_node.cpp
seems like a useful widget for users!
> Creating auto-transition option for nav2_util::LifecycleNode nodes without the need of a lifecycle manager

- nav2_docking/opennav_docking/src/controller.cpp
---
| Robotic platform tested on | Morphia |
| Does this PR contain AI generated software? | Nope |
---
This fixes the trajectory generation for collision checking in the docking controller. Previously it used a for loop which iterated until the `projection_time_` was reached regardless of whether the last pose of the trajectory had reached the target. This generated a lot of spurious poses with the same position but different orientations.
This has been replaced, using the same approach as the graceful_controller, with a do-while loop that also checks for this distance.
| Before | After |
| -- | -- |
| …
> Fix trajectory generation bug in docking controller

- nav2_graceful_controller/include/nav2_graceful_controller/graceful_controller.hpp
- nav2_graceful_controller/include/nav2_graceful_controller/parameter_handler.hpp
- nav2_graceful_controller/src/graceful_controller.cpp
- nav2_graceful_controller/src/parameter_handler.cpp
- nav2_graceful_controller/test/test_graceful_controller.cpp
| Ticket(s) this addresses   | #4115 |
| Robotic platform tested on | UBR-1 |
| Does this PR contain AI generated software? | No, only real intelligence was used |
---
* Iteratively selects a valid target pose to use with the control law. This is done by forward simulating the control law towards the target pose and rejecting the target pose if there is a collision detected.
* Adds collision checking to the "final_rotation". If this fails, we will attempt to roll out further movement via the control law (this is especially important for non-circular robots!). With this in mind, the parameter `final_rotation` has been renamed to `prefer_final_rotation`.
* Modifies how `final_rotation` is done a …
> graceful_controller: implement iterative selection of control points

- nav2_graceful_controller/src/graceful_controller.cpp
- nav2_graceful_controller/test/test_graceful_controller.cpp
As I was pulling the documentation together for #4795 - I noticed this logic was backwards. I added test first (which failed of course) and then fixed the bug.
| Robotic platform tested on | UBR-1 |
| Does this PR contain AI generated software? |No |
> fix bug in use of v_angular_min_in_place

- nav2_graceful_controller/include/nav2_graceful_controller/graceful_controller.hpp
- nav2_graceful_controller/include/nav2_graceful_controller/utils.hpp
- nav2_graceful_controller/src/graceful_controller.cpp
- nav2_graceful_controller/src/utils.cpp
- nav2_graceful_controller/test/test_graceful_controller.cpp
---
Change motion target publisher from PointStamped to PoseStamped - this allows to actually visualize if the headings are correct:
> publish motion target as pose

- nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
Until now, the NONE error code was returned when exceeding the time allowance. Let's return the more appropriate TIMEOUT error code instead.
---
| Ticket(s) this addresses   | / |
| Robotic platform tested on |/ |
---
---
> drive_on_heading: return TIMEOUT error code when exceeding time allowance

- nav2_graceful_controller/src/graceful_controller.cpp
| Ticket(s) this addresses   | N/A|
| Robotic platform tested on | Turtlebot sim |
| Does this PR contain AI generated software? |No |
---
Some global planners output all zeros for orientation, however the plan is in the global frame. When transforming to the local frame, the orientation is no longer zero. Instead of comparing to zero, we simply check if all the orientations in the middle of the plan are equal.
---
> fix bug in orientation filtering

- nav2_msgs/CMakeLists.txt
| Does this PR contain AI generated software? | No) |
---
`-Wno-error=deprecated` is a option supported by GCC and Clang, so it should only be passed when GCC or Clang is used.
None
None
> nav2_msgs: Fix compilation on Windows

- nav2_smac_planner/include/nav2_smac_planner/collision_checker.hpp
- nav2_smac_planner/include/nav2_smac_planner/node_hybrid.hpp
- nav2_smac_planner/src/collision_checker.cpp
- nav2_smac_planner/src/node_hybrid.cpp
- nav2_smac_planner/test/test_collision_checker.cpp
Resolves https://github.com/ros-navigation/navigation2/issues/4808  and https://github.com/ros-navigation/navigation2/issues/4314
The optimization was added to allow non-circular robots to use their full footprint costs in the traversibility function and heuristic function formulations. However, in confined settings, it doesn't work very well and its better to collision check using the full footprint **but** continue to use the center point costs for the traversal function / heuristic function formulations. 
Metrics outlined in https://github.com/ros-navigation/navigation2/issues/4808#issuecomment-2580686801 show that this not only fixes the issue but also doesn't impact speeds in open areas - but faster in confined areas due to the ambiguation of inscribed costs. 
TODO
> Fixes smac planner non-circular footprint search issue

- nav2_mppi_controller/include/nav2_mppi_controller/critic_data.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/optimizer.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/tools/path_handler.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp
- nav2_mppi_controller/src/controller.cpp
- nav2_mppi_controller/src/critics/cost_critic.cpp
- nav2_mppi_controller/src/critics/goal_angle_critic.cpp
- nav2_mppi_controller/src/critics/goal_critic.cpp
- nav2_mppi_controller/src/critics/obstacles_critic.cpp
- nav2_mppi_controller/src/critics/path_align_critic.cpp
- nav2_mppi_controller/src/critics/path_angle_critic.cpp
- nav2_mppi_controller/src/critics/path_follow_critic.cpp
- nav2_mppi_controller/src/critics/prefer_forward_critic.cpp
- nav2_mppi_controller/src/critics/twirling_critic.cpp
- nav2_mppi_controller/src/optimizer.cpp
- nav2_mppi_controller/src/path_handler.cpp
- nav2_mppi_controller/test/controller_state_transition_test.cpp
- nav2_mppi_controller/test/critic_manager_test.cpp
- nav2_mppi_controller/test/critics_tests.cpp
- nav2_mppi_controller/test/optimizer_smoke_test.cpp
- nav2_mppi_controller/test/optimizer_unit_tests.cpp
- nav2_mppi_controller/test/utils_test.cpp
> Mppi goal to critic

- nav2_mppi_controller/include/nav2_mppi_controller/critic_data.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/optimizer.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/tools/path_handler.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp
- nav2_mppi_controller/src/controller.cpp
- nav2_mppi_controller/src/critics/cost_critic.cpp
- nav2_mppi_controller/src/critics/goal_angle_critic.cpp
- nav2_mppi_controller/src/critics/goal_critic.cpp
- nav2_mppi_controller/src/critics/obstacles_critic.cpp
- nav2_mppi_controller/src/critics/path_align_critic.cpp
- nav2_mppi_controller/src/critics/path_align_legacy_critic.cpp
- nav2_mppi_controller/src/critics/path_angle_critic.cpp
- nav2_mppi_controller/src/critics/path_follow_critic.cpp
- nav2_mppi_controller/src/critics/prefer_forward_critic.cpp
- nav2_mppi_controller/src/critics/twirling_critic.cpp
- nav2_mppi_controller/src/optimizer.cpp
- nav2_mppi_controller/src/path_handler.cpp
- nav2_mppi_controller/test/controller_state_transition_test.cpp
- nav2_mppi_controller/test/critic_manager_test.cpp
- nav2_mppi_controller/test/critics_tests.cpp
- nav2_mppi_controller/test/optimizer_smoke_test.cpp
- nav2_mppi_controller/test/optimizer_unit_tests.cpp
- nav2_mppi_controller/test/utils_test.cpp
---
| Ticket(s) this addresses   | (add tickets here #4809 ) |
| Robotic platform tested on | custom gazebo simulation, custom hardware |
---
* Added goal pose to MPPI CriticData
* Now all critics can activate based on distance from *global* goal pose instead of pruned
* Bugfix, usage doesn't change
---
> Add goal pose to CriticData

- nav2_mppi_controller/include/nav2_mppi_controller/tools/path_handler.hpp
- nav2_mppi_controller/src/controller.cpp
- nav2_mppi_controller/src/path_handler.cpp
Follow-up on #4822
* There was a bug in the previous PR: the MPPI critics goal pose now uses stamp from global_path, which gets outdated by the TF buffer, and then fails to transform the goal pose.
* This doesn't come up if the plan is replanned frequently.
* As a solution, this PR uses the `robot_pose.stamp`, which gets updated frequently.
* None required
* In a custom simulation and on real robot, on the `humble` branch.
---
> Fix goal pose stamp

- nav2_waypoint_follower/plugins/photo_at_waypoint.cpp
| Ticket(s) this addresses   | No ticket. |
| Robotic platform tested on | Not tested on any robotic platform. |
On Linux and macOS `std::filesystem::path` is implicitly convertible to `std::string`, while on Windows it is convertible to `std::wstring`, see https://en.cppreference.com/w/cpp/filesystem/path and https://stackoverflow.com/questions/57377349/implicit-conversion-between-stdfilesystempath-and-stdstring-should-it-hap . If we want to convert `std::filesystem::path` to `std::string` in a Windows-compatible way, it is then necessary to explicitly call the `.string()` method.
I checked if the program compiled.
> Explicit convert from std::filesystem::path to std::string for Windows compatibility

- nav2_rviz_plugins/include/nav2_rviz_plugins/costmap_cost_tool.hpp
| Ticket(s) this addresses   | No ticket. |
| Robotic platform tested on | Not tested on a robot |
I was experiencing a strange linking error on Windows:
~~~
costmap_cost_tool.obj : error LNK2019: unresolved external symbol "public: static struct QMetaObject const rviz_default_plugins::tools::PointTool::staticMetaObject" (?sta
ticMetaObject@PointTool@tools@rviz_default_plugins@@2UQMetaObject@@B) referenced in function "public: static class QString __cdecl rviz_default_plugins::tools::PointTool:
:tr(char const *,char const *,int)" (?tr@PointTool@tools@rviz_default_plugins@@SA?AVQString@@PEBD0H@Z) …
> nav2_rviz_plugins: Remove unused rviz_common_plugins include

- nav2_rviz_plugins/include/nav2_rviz_plugins/goal_tool.hpp
| Ticket(s) this addresses   | No ticket. |
| Robotic platform tested on | None, linker problem.  |
| Does this PR contain AI generated software? | No. |
---
The `RVIZ_DEFAULT_PLUGINS_PUBLIC` macro is meant for code contained in the `rviz_default_plugins` repos. Using it in another repo create linking errors on Windows, as the linker expects the `GoalTool` class to be defined somewhere else, as it is annotated with the `dllexport` decorator.
None.
I compiled on Windows with this fix.
---
> Remove RVIZ_DEFAULT_PLUGINS_PUBLIC macro from nav2 rviz plugin

- nav2_constrained_smoother/include/nav2_constrained_smoother/smoother.hpp
- nav2_constrained_smoother/include/nav2_constrained_smoother/smoother_cost_function.hpp
- nav2_constrained_smoother/test/test_smoother_cost_function.cpp
| Ticket(s) this addresses   | No ticket. |
| Primary OS tested on | Windows. |
| Robotic platform tested on | This is just a compilation fix, no runtime changes. |
| Does this PR contain AI generated software? | No. |
---
`u_char` is not a standard C or C++ data type, while `unsigned char` is equivalent to `u_char` and is a standard data type. This change permits to compile `nav2_constrained_smoother` on Windows.
None.
I checked if the compilation was successful.
> nav2_constrained_smoother: Use unsigned char instead of non-standard u_char type

- nav2_smoother/include/nav2_smoother/simple_smoother.hpp
- nav2_smoother/src/simple_smoother.cpp
- nav2_smoother/test/test_simple_smoother.cpp
| Ticket(s) this addresses   | #4710 |
| Primary OS tested on | Ubuntu (osrf/ros:jazzy-desktop-full) |
| Robotic platform tested on | my own custom simulated robot  |
---
* modified smoother server's simple_smoother plugin to not throw FailedToSmoothPath when the robot is approaching the end of path
I can alter this behavior if requested. My only requirement for this patch is that no error will be thrown when the path is ending and the last and only segment is too short to be processed, causing `segments_smoothed` to be zero.
> fix simple smoother failing during final approach

- nav2_route/CMakeLists.txt
- nav2_route/include/nav2_route/edge_scorer.hpp
- nav2_route/include/nav2_route/interfaces/edge_cost_function.hpp
- nav2_route/include/nav2_route/plugins/edge_cost_functions/adjust_edges_scorer.hpp
- nav2_route/include/nav2_route/plugins/edge_cost_functions/costmap_scorer.hpp
- nav2_route/include/nav2_route/plugins/edge_cost_functions/distance_scorer.hpp
- nav2_route/include/nav2_route/plugins/edge_cost_functions/goal_orientation_scorer.hpp
- nav2_route/include/nav2_route/plugins/edge_cost_functions/penalty_scorer.hpp
- nav2_route/include/nav2_route/plugins/edge_cost_functions/semantic_scorer.hpp
- nav2_route/include/nav2_route/plugins/edge_cost_functions/time_scorer.hpp
- nav2_route/include/nav2_route/route_planner.hpp
- nav2_route/plugins.xml
- nav2_route/src/edge_scorer.cpp
- nav2_route/src/plugins/edge_cost_functions/adjust_edges_scorer.cpp
- nav2_route/src/plugins/edge_cost_functions/costmap_scorer.cpp
- nav2_route/src/plugins/edge_cost_functions/distance_scorer.cpp
- nav2_route/src/plugins/edge_cost_functions/goal_orientation_scorer.cpp
- nav2_route/src/plugins/edge_cost_functions/penalty_scorer.cpp
- nav2_route/src/plugins/edge_cost_functions/semantic_scorer.cpp
- nav2_route/src/plugins/edge_cost_functions/time_scorer.cpp
- nav2_route/src/route_planner.cpp
- nav2_route/src/route_server.cpp
- nav2_route/test/test_edge_scorers.cpp
- nav2_route/test/test_route_planner.cpp
---
| Robotic platform tested on | (Gazebo simulation of an agricultural client) |
---
- Modified `route_server.cpp` and `route_planner.cpp` to pass the goal pose down to `getTraveralCost` method
- `edge_cost_function` base method `score` modified to take in the goal pose and also a bool indicating if its the final edge
- All edge scorers modified to accommodate those new arguments
- Added a new edge scorer `GoalOrientationScorer` that rejects a route if the route's final edge does not align to some angular threshold to the desired pose orientation
- Added a new test to test `GoalOrientationScorer`
- …
> Nav2 route server goal orientation scorer

- nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
- nav2_bringup/params/nav2_params.yaml
---
| Ticket(s) this addresses   | NA
| Robotic platform tested on | own robot hardware |
---
Added two params: `acceleration_limit` and `deceleration_limit` for DriveOnHeading and BackUp behaviors.
Added new parameter, so need to add that to default configs and documentation page
---
> Add acceleration limits to DriveOnHeading and BackUp behaviors

- nav2_rotation_shim_controller/src/nav2_rotation_shim_controller.cpp
- nav2_rotation_shim_controller/test/test_shim_controller.cpp
---
| Ticket(s) this addresses   | NA
| Robotic platform tested on | own robot hardware |
---
Currently we don't do the deceleration as a function of its target orientation with RotationShimController. This PR implements this behavior using the `max_angular_accel` param. 
The parameter description has to be updated.
---
> Add acc limit consideration to avoid overshooting in RotationShimController

- nav2_docking/opennav_docking/test/test_docking_server.py
Call publish() (odom -> base_link tf) at startup to kick things off and spin 10 times(1 second) TF, so that it has a chance to propogate to the docking_server so that it will accept an action request.
Previously it was only spinning once, hoping the timer would fire and call publish fast enough for it to propogate to the docking_server so that it is able to accept the first 'dock_robot' action request
---
| Ticket(s) this addresses   | #4878 |
| Robotic platform tested on | dev laptop |
---
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble …
```
> Fix flaky ness of opennav_docking test_docking_server (#4878)

- nav2_bringup/launch/rviz_launch.py
- nav2_rviz_plugins/include/nav2_rviz_plugins/selector.hpp
- nav2_rviz_plugins/src/selector.cpp
- nav2_rviz_plugins/src/utils.cpp
---
| Info                                        | Please fill out this column |
| ------------------------------------------- | --------------------------- |
| Ticket(s) this addresses                    | #4754                       |
| Primary OS tested on                        | Ubuntu 24.04                |
| Robotic platform tested on                  | turtlebot 3 simulation      |
| Does this PR contain AI generated software? | No                          |
---
Revival of #4871 targeting the main branch with improved code 
- Open a new thread to load plugins, to ensure that `get_parameter()` would not block the main thread. The combo box will now have value if it successfully gets the parameter, otherwise empty
None
Extensively tested on tb3 simulation and all tests passed
---
> Fix rviz crash if launch later

- nav2_behavior_tree/include/nav2_behavior_tree/plugins/condition/is_path_valid_condition.hpp
- nav2_behavior_tree/nav2_tree_nodes.xml
- nav2_behavior_tree/plugins/condition/is_path_valid_condition.cpp
- nav2_msgs/srv/IsPathValid.srv
- nav2_planner/src/planner_server.cpp
- nav2_system_tests/src/planning/planner_tester.cpp
- nav2_system_tests/src/planning/planner_tester.hpp
- nav2_system_tests/src/planning/test_planner_is_path_valid.cpp
---
| Ticket(s) this addresses   | #4756 |
| Robotic platform tested on | Custom simulation environment |
---
- Add max cost as described in the issue 
- Add corresponding test
Add new parameter description https://docs.nav2.org/configuration/packages/bt-plugins/conditions/IsPathValid.html
Wrote a new test to test this and also tested on custom simulation env
---
> Add ispathvalid maxcost

- nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
- nav2_bringup/params/nav2_params.yaml
Backport of #4810 to humble
---------
---
---
---
> Add acceleration limits to DriveOnHeading and BackUp behaviors (backport #4810)

- nav2_costmap_2d/plugins/static_layer.cpp
In the StaticLayer costmap2d_plugin , the parameter `footprint_clearing_enabled` was never changed dynamically in the callback, because the `else if` condition has a duplicated condition (same as in [line 490](https://github.com/ros-navigation/navigation2/blob/dcc5db5eae4566c30dfa886920e43d2acc01af7b/nav2_costmap_2d/plugins/static_layer.cpp#L490) and [line 500](https://github.com/ros-navigation/navigation2/blob/dcc5db5eae4566c30dfa886920e43d2acc01af7b/nav2_costmap_2d/plugins/static_layer.cpp#L500)), so it never executed setting that parameter.
---
---
- Fixes …
> Fix for setting dynamically the footprint_clearing_enabled parameter in the StaticLayer costmap_2d plugin

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp
---
| Ticket(s) this addresses   ||
| Primary OS tested on |Ubuntu 24.04|
| Robotic platform tested on | Dexory robot |
---
In `BtActionNode` and `BtServiceNode`, the `goal_`, `result_` and `request_` objects were not cleared between 2 calls. Hence keeping an old value if any field of these was not explicitly set by a BT node inheriting `BtActionNode` or `BtServiceNode`.
I realized it while using `ComputePathToPose` and not understanding why the action was using a previous `start` pose when actually making a new call without a `start` parameter (where it is expected that the current pose of the robot will be used): …
> [BtActionNode] [BtServiceNode] clear between calls

- nav2_dwb_controller/dwb_critics/test/obstacle_footprint_test.cpp
---
| Ticket(s) this addresses   | (#4884) |
| Robotic platform tested on | laptop |
---
There is no protection/checks in the pathway from lineCost to costmap_2d::getIndex(mx, my) for grid coordinates that exceed the of bounds of the allocated costmap. (presumably for speed)
This test was triggering an off by one error attempting to read the the 2500 byte costmap at byte 2503
costmap size 50x50.
getIndex(3, 50)
= my * size_x_ + mx;
= 50 * 50 + 3;
= 2503
n/a
gdb -ex run --args build/dwb_critics/test/obstacle_footprint_tests --gtest_break_on_failure --gtest_catch_exceptions=0 --gtest_repeat=1000
---
The costmap_2d could use a vector rather …
> dwb_critics flaky test - lineCost coordinates must be within costmap 

- nav2_rotation_shim_controller/include/nav2_rotation_shim_controller/nav2_rotation_shim_controller.hpp
- nav2_rotation_shim_controller/src/nav2_rotation_shim_controller.cpp
- nav2_rotation_shim_controller/test/test_shim_controller.cpp
---
| Ticket(s) this addresses   | NA
| Robotic platform tested on | own robot hardware |
---
New parameter description needed and migration guide.
---
> Add option to use open-loop control with Rotation Shim

- nav2_rotation_shim_controller/include/nav2_rotation_shim_controller/nav2_rotation_shim_controller.hpp
- nav2_rotation_shim_controller/src/nav2_rotation_shim_controller.cpp
- nav2_rotation_shim_controller/test/test_shim_controller.cpp
Backport of https://github.com/ros-navigation/navigation2/pull/4880 to humble
---
| Ticket(s) this addresses   | NA
| Robotic platform tested on | own robot hardware |
---
---
> Add option to use open-loop control with Rotation Shim (backport #4880)

- nav2_util/include/nav2_util/simple_action_server.hpp
- nav2_util/test/test_actions.cpp
---
| Ticket(s) this addresses   | #4893  |
| Primary OS tested on | Ubuntu24.04 |
| Robotic platform tested on | Custom env |
---
Fix unstable test as mentioned in the issue, this is due to the inactiveness of the server that causes the goal handle to be a nullptr, which is throwing the exception of `C++ exception with description "Goal handle is not known to this client.`. Thus, I am adding an `EXPECT_NE` for the goal handle, and add a short delay before we activate the server
None
Running the test for 1000 times independently
---
> Fix unstable test in nav2 util

- nav2_mppi_controller/src/parameters_handler.cpp
- nav2_mppi_controller/test/parameter_handler_test.cpp
---
| Info | Theres a bug when setting params from other plugins when using mppi|
---
Currently, the parameters handler library in the MPPI will return failure when trying to set a parameter in the controller server node that does not belong to the MPPI plugin. This is because rclcpp will stop processing dynamic params callbacks when one of them returns falure, see https://github.com/ros2/rclcpp/pull/2735 for details 
---
> MPPI: Do not set params success in dynamic params callback to allow changing params in other plugins

- nav2_costmap_2d/src/costmap_2d_publisher.cpp
---
| Info |  |
| Ticket(s) this addresses   | #4914  |
---
* I modified the loop that was being used to copy raw costmap by using a memcpy instead 
* None would be required as it is just an enhancement 
---
* Further profiling costmap related functionalities to identify which processes are costing us the most.
> removed the deep copy for the costmap_raw_ data using memcpy in prepareCostmap under costmap_2d_publisher.cpp

- nav2_mppi_controller/test/trajectory_visualizer_tests.cpp
---
| Ticket(s) this addresses   | #4934 |
---
- Fix bug as described in the issue
Unit test run around 10000 rounds, no error occured
---
> Fix uninitialized element used in mppi trajectory test

- nav2_collision_monitor/test/polygons_test.cpp
---
| Robotic platform tested on | ) |
---
- Add a short delay to make sure the transform is published, otherwise it might lookup for the wrong transform, related failing CI is https://app.circleci.com/pipelines/github/ros-navigation/navigation2/13673/workflows/a383cfc4-dbe8-429b-9828-5ee3f18a19e7/jobs/40769/tests#failed-test-0
run repeatedly for 1000 rounds
---
> Add short delay before lookup transform in polygon test

- nav2_costmap_2d/test/integration/CMakeLists.txt
- nav2_costmap_2d/test/integration/costmap_tests_launch.py
---
| Ticket(s) this addresses   | #4929  |
| Does this PR contain AI generated software? |  |
---
- Fixes the issue, only publish static transform for tests that need it 
None
Tested the buggy tests independently for 1000 rounds, and run colcon test for 10 rounds
---
> Remove duplicate tf for costmap tests

- nav2_velocity_smoother/src/velocity_smoother.cpp
---
---
* Populate the header stamp of the TwistStamped message with the actual time, in the case that the velocity command times out and sends zero velocities to stop the robot.
* Not needed
* Checked in simulation using `ros2 topic echo /cmd_vel_smoothed` , that the `header.stamp` is always populated by a timestamp and not zero at the end of a path or after cancelling a path
---
> Fix the message header timestamp of the velocity_smoother, when the input timed out

- nav2_mppi_controller/test/noise_generator_test.cpp
---
| Ticket(s) this addresses   | #4932  |
| Robotic platform tested on | gazebo sim |
---
- Fixed the flaky test as mentioned in the issue, added a new one for non-regenerate noise
Unit test, run around 10000 rounds
---
Currently in noise generator we have 3 tests, the first test `NoiseGeneratorLifecycle` is actually covered by my new one, should we delete this test or keep it?
> Fix flaky mppi test

- nav2_system_tests/src/planning/test_planner_plugins.cpp
---
---
[Costmap node](https://github.com/ros-navigation/navigation2/blob/353319f02e86205346a0352cb00e9c2a71638b40/nav2_smac_planner/include/nav2_smac_planner/smac_planner_lattice.hpp#L105) should be released after the test.
However, it's held by the [static variable costmap_ros](https://github.com/ros-navigation/navigation2/blob/353319f02e86205346a0352cb00e9c2a71638b40/nav2_smac_planner/include/nav2_smac_planner/node_hybrid.hpp#L482) in `class NodeHybrid` after calling [resetObstacleHeuristic](https://github.com/ros-navigation/navigation2/blob/353319f02e86205346a0352cb00e …
> Clean up the planner in test_planner_plugins

- nav2_simple_commander/nav2_simple_commander/robot_navigator.py
Many Nav2 users initially assume that the only available option is to clear the entire costmap. To raise awareness and highlight additional costmap clearing options already available
> Integrate ClearCostmapExceptRegion and ClearCostmapAroundRobot Services into the API

- nav2_costmap_2d/src/costmap_2d_publisher.cpp
- nav2_costmap_2d/test/integration/test_costmap_subscriber.cpp
---
| Ticket(s) this addresses   | Related ticket is #4914  |
| Robotic platform tested on | gazebo sim |
---
Motivated by the ticket, I did a quick profiling and tried to optimize the performance, for those loops using translation maps, I suggest to use std::transform, it is a 2-5x speed up, for the update ones, I suggest to get the costmap pointer instead of calling `getcost(x,y)`, also a `copy_n` is used in the inner loop, which is around 10x speed up
Run on the unit test and my simulation
---
> Optimize costmap2d publisher performance

- nav2_rviz_plugins/include/nav2_rviz_plugins/costmap_cost_tool.hpp
- nav2_rviz_plugins/include/nav2_rviz_plugins/docking_panel.hpp
---
| Ticket(s) this addresses   | none so far |
| Primary OS tested on | Nix |
---
Without this change, when compiled for Jazzy with Nix using gcc14 and qt-5.15, loading the plugins to rviz fails with the following error:
[rviz2]: PluginlibFactory: The plugin for class
'nav2_rviz_plugins/Navigation 2' failed to load. Error: Failed to
load library /nix/store/...-ros-env/lib/libnav2_rviz_plugins.so.
Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in
the library code, and that names are consistent between this macro
and your XML. Error string: Could not load library dlopen error: …
> nav2_rviz_plugins: Remove slots without implementation

- nav2_mppi_controller/include/nav2_mppi_controller/motion_models.hpp
- nav2_mppi_controller/src/critics/cost_critic.cpp
- nav2_mppi_controller/src/optimizer.cpp
| Robotic platform tested on | Optimizer Benchmark |
| Does this PR contain AI generated software? |No |
---
* Addressed a few comments from the previous PR for better code readability.
* Optimized functions which were major hotspots in the profiler data.
* Computation time improved by 15-21%. 21% for Omni-Drive, 15% for Diff-drive and 17% for Ackermann.
* Minor optimizations, such as reducing division operation and caching values.
* Testes it on Optimizer benchmark with multiple runs.
---
> MPPI Controller improvements(15-21% performance gain).

- nav2_behavior_tree/include/nav2_behavior_tree/plugins/condition/are_error_codes_present_condition.hpp
- nav2_behavior_tree/test/plugins/condition/test_are_error_codes_present.cpp
The getInput method does not support std::set<uint16_t> parsing. So, let's replace the type of the input port by std::vector<int> which is supported, and convert the list to a std::set<uint16_t>.
This commit fixes issue #4985.
---
---
---
> nav2_behavior_tree: fix input port parsing error in AreErrorCodesPresent

- nav2_controller/plugins/simple_goal_checker.cpp
- nav2_controller/plugins/test/goal_checker.cpp
- nav2_controller/plugins/test/progress_checker.cpp
| Robotic platform tested on | GTest |
| Does this PR contain AI generated software? | Yes (GH Copilot) |
---
* While writing unit tests for #4942, fixed discrepancy in goal checker orientation, which was checking for `< tolerance` instead of `<= tolerance`, as all the other limit checks are.
* Reduced tolerance time for the progress checker unit tests to 0.1 seconds, to reduce test runtime from ~17 to ~7 seconds.
* Added edge case unit tests
* I think no documentation update is needed.
* Only unit tests
---
* Other performance improvements that I can see, reduced copying values from const references
> Change to goal checker orientation for yaw angle

- nav2_bringup/README.md
---
| Ticket(s) this addresses   | #5000  |
---
* Updated the `nav2_bringup` docs to include the updated robot string.
* The documented change is currently in a [PR](https://github.com/ros-navigation/docs.nav2.org/pull/659) at the docs repository.
* The command mentioned in the README was pasted on the terminal to check if any formatting issues was present and verified.
---
> Update nav2_bringup docs to include updated robot string.

- nav2_behavior_tree/plugins/action/follow_path_action.cpp
---
| Ticket(s) this addresses   | #4964  |
| Robotic platform tested on | My robot, gz simulation |
---
- Prevent the `navigate_to_pose` from failing due to a global planner failure while the local planner is running.
Trigger a situation where the global path cannot be generated by updating the global path through the RateController while the local planner is running.
I recreated this scenario by creating a narrow passage that is just wide enough not to be considered an obstacle due to cost, and attempted to make the robot pass through it.
---
> I'm also thinking we could adjust the return value of the RecoveryNode / RateController in …
> Verify that the updated path is not empty or placeholder.

- nav2_rviz_plugins/src/costmap_cost_tool.cpp
The definition of the slot was removed in commit e6f500e5 ("nav2_rviz_plugins: Remove slots without implementation (#4974)", 2025-03-10), because it had no implementation. But we forgot to remove the reference to this slot, because the compiler cannot detect it.
We remove the reference now. Without this, rviz shows warnings like:
QObject::connect: No such slot nav2_rviz_plugins::CostmapCostTool::updateAutoDeactivate()
QObject::connect:  (sender name:   'Single click')
@mini-1235 Are you able to check that this removes the warnings for you?
---
| Robotic platform tested on | (Steve's Robot, gazebo simulation of Tally, …
> nav2_rviz_plugins: Don't use non-existent slot

- nav2_graceful_controller/include/nav2_graceful_controller/parameter_handler.hpp
- nav2_graceful_controller/src/graceful_controller.cpp
- nav2_graceful_controller/src/parameter_handler.cpp
- nav2_graceful_controller/test/test_graceful_controller.cpp
| Ticket(s) this addresses   | (add tickets here #5005 ) |
| Primary OS tested on | (Ubuntu 24.04 running Jazzy) |
| Robotic platform tested on | (Simulation of a custom diff-drive robot) |
---
* I added a parameter to nav2_graceful_controller to enable/disable collision checking
* Added new parameter, so need to add that to default configs and documentation page.
* I ran the test with a huge robot radius in the local_costmap to always have collision in the controller's path. The parametrization worked to enable/disable it.
> * Parametrize collision checking in nav2_graceful_controller

- .github/workflows/lint.yml
- nav2_smac_planner/lattice_primitives/generate_motion_primitives.py
- nav2_smac_planner/lattice_primitives/helper.py
- nav2_smac_planner/lattice_primitives/lattice_generator.py
- nav2_smac_planner/lattice_primitives/tests/test_lattice_generator.py
- nav2_smac_planner/lattice_primitives/tests/test_trajectory_generator.py
- nav2_smac_planner/lattice_primitives/tests/trajectory_visualizer.py
- nav2_smac_planner/lattice_primitives/trajectory.py
- nav2_smac_planner/lattice_primitives/trajectory_generator.py
---
---
I saw #4916 to add ament_mypy to type check. I noticed there were some errors raised by ament_mypy so i resolved the ones in `nav2_smac_planner`.
I ran `ament_mypy nav2_smac_planner/` and got no errors.
---
> Update smac planner types

- nav2_navfn_planner/src/navfn_planner.cpp
---
| Ticket(s) this addresses   | #4945 |
| Robotic platform tested on | reality |
---
`squared_distance(p, goal)` should be calculate when `potential < POT_HIGH`.
none.
test in reality.
---
none
> navfn : fix performance issue

- .github/workflows/lint.yml
- nav2_common/package.xml
- nav2_smac_planner/lattice_primitives/generate_motion_primitives.py
- nav2_smac_planner/lattice_primitives/lattice_generator.py
- nav2_smac_planner/lattice_primitives/tests/test_lattice_generator.py
- nav2_smac_planner/lattice_primitives/tests/test_trajectory_generator.py
- nav2_smac_planner/lattice_primitives/trajectory.py
- nav2_smac_planner/lattice_primitives/trajectory_generator.py
- tools/pyproject.toml
---
---
* Added a mypy configuration file to ignore missing libraries and to treat each package independently, due to conflicting files.
* Restructured `nav2_smac_planner` for strict mypy.
* N/A
* Ran `colcon build` and `colcon test` to test the changes.
---
* N/A
> Configured mypy strict for nav2_smac_planner

- .github/workflows/lint.yml
- nav2_common/nav2_common/launch/has_node_params.py
- nav2_common/nav2_common/launch/replace_string.py
- nav2_common/nav2_common/launch/rewritten_yaml.py
- tools/pyproject.toml
---
---
* Restructured `nav2_common` for strict mypy.
* N/A
* Ran `colcon build` and `colcon test` to test the changes.
---
> Mypy nav2 common

- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d.hpp
- nav2_costmap_2d/src/clear_costmap_service.cpp
- nav2_costmap_2d/src/costmap_2d.cpp
- nav2_costmap_2d/src/costmap_layer.cpp
- nav2_costmap_2d/test/unit/CMakeLists.txt
- nav2_costmap_2d/test/unit/coordinate_transform_test.cpp
---
| Ticket(s) this addresses   | #4995  |
| Robotic platform tested on | Turtlebot3 simulation in Gazebo |
---
* Shifted bound checking in the clearArea function, so that the STVL layer can safely override and implement voxel clearing for `reset_distance` greater than costmap width.
* Added `mapToWorldNoBounds` function for STVL overrides.
* N/A
* Add an STVL layer to global costmap, and use a depthimage to pointcloud converter node for the turtlebot4 example provided.
* Launch the turtlebot3 simulation with nav2 and gazebo:
```bash
ros2 launch nav2_bringup tb4_simulation_launch.py headless:=False
```
* View the costmap behaviour in RViz …
> Clear costmap if reset distance exceeds costmap bounds.

- nav2_bringup/params/nav2_params.yaml
- nav2_mppi_controller/include/nav2_mppi_controller/critics/cost_critic.hpp
- nav2_mppi_controller/src/critics/cost_critic.cpp
- nav2_mppi_controller/src/critics/obstacles_critic.cpp
- nav2_mppi_controller/test/critics_tests.cpp
- nav2_system_tests/src/gps_navigation/nav2_no_map_params.yaml
---
| Ticket(s) this addresses   | #4361  |
| Robotic platform tested on | tb3 |
---
Fix dead code as discussed in the issue
None
Tested on sim, cost of 253 works
---
> Add near collision cost and warnings for misaligned parameter settings in MPPI critics

- nav2_mppi_controller/src/critics/cost_critic.cpp
- nav2_mppi_controller/src/critics/obstacles_critic.cpp
- nav2_mppi_controller/test/critics_tests.cpp
> Backport #4996 (Humble)

- nav2_rotation_shim_controller/README.md
- nav2_rotation_shim_controller/include/nav2_rotation_shim_controller/nav2_rotation_shim_controller.hpp
- nav2_rotation_shim_controller/src/nav2_rotation_shim_controller.cpp
- nav2_rotation_shim_controller/test/test_shim_controller.cpp
---
| Ticket(s) this addresses   | None|
---
- With this PR, rotation shim controller optionally use orientations from the path so the robot rotates to pose orientation. This allows it to be usable with reverse driving.
- Tested in simulation.
---
- I would like to backport this to jazzy.
> feat(nav2_rotation_shim_controller): add use_path_orientations

- nav2_behavior_tree/plugins/control/recovery_node.cpp
Resolves #4737
@tonynajjar  @FrGrQuim can you review?
> Halt recovery action when main action succeeds to reset status

- .github/workflows/lint.yml
- nav2_docking/opennav_docking/test/test_docking_server.py
- nav2_msgs/action/__init__.py
- nav2_msgs/msg/__init__.py
- nav2_msgs/srv/__init__.py
- tools/pyproject.toml
---
---
* Corrected unsafe fixes using `ruff` - `ruff check --select UP --fix --unsafe-fixes opennav_docking`
* Restructured `opennav_docking` for strict mypy.
* N/A
---
* N/A
> Mypy opennav_docking

- nav2_behavior_tree/include/nav2_behavior_tree/bt_utils.hpp
- nav2_behavior_tree/test/test_bt_utils.cpp
---
| Ticket(s) this addresses   | #4985 |
---
The std::set type used as an input port was removed in #4986, so this conversion is no longer necessary.
---
> Remove unused code in BT utils

- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/drive_on_heading_action.hpp
- nav2_behavior_tree/plugins/action/drive_on_heading_action.cpp
---
| Primary OS tested on | ubuntu |
| Robotic platform tested on | gazebo sim |
| Does this PR contain AI generated software? | no |
---
linting and sim testing
In #3988 we moved initialization for BT nodes to a separate step. In #4744 this was modified. In #4887 goal-clearing between calls was introduced which is only compatible with the version from #4744 . However, somehow the drive on heading node was not adapted and still uses logic from #3988 .
Thus, from the second goal on it will use an empty goal and become a no-op.
5: [behavior_server-27] [INFO] [1743743039.305621213] [behavior_server]: Initial position: (16.49, -1.37), Current position: (16.49, -1.27), Distance: 0.10; cmd …
> correctly initialize drive on heading action node

- .github/workflows/lint.yml
- nav2_loopback_sim/launch/loopback_simulation.launch.py
- nav2_loopback_sim/nav2_loopback_sim/loopback_simulator.py
- nav2_loopback_sim/nav2_loopback_sim/utils.py
- nav2_loopback_sim/test/test_copyright.py
- nav2_loopback_sim/test/test_flake8.py
- nav2_loopback_sim/test/test_pep257.py
- tools/pyproject.toml
---
---
* Corrected unsafe fixes using `ruff` - `ruff check --select UP --fix --unsafe-fixes nav2_loopback_sim`
* Restructured `nav2_loopback_sim` for strict mypy.
* N/A
---
* N/A
> Mypy nav2 loopback sim

- nav2_bringup/params/nav2_params.yaml
- nav2_mppi_controller/include/nav2_mppi_controller/models/constraints.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/models/optimizer_settings.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/motion_models.hpp
- nav2_mppi_controller/src/optimizer.cpp
- nav2_mppi_controller/test/optimizer_unit_tests.cpp
- nav2_system_tests/src/gps_navigation/nav2_no_map_params.yaml
---
| Ticket(s) this addresses   | #4601  |
| Robotic platform tested on | gazebo sim |
| Does this PR contain AI generated software? | NO |
---
- Fix the acceleration and deceleration when going backward as mentioned in the issue, mostly copied from #3529 
- Regarding the performance issue mentioned in the issue, I ran benchmark and observed no significant difference from the original(tested with different parameters)
None
Tested on sim, wrote some new unit tests 
---
Maybe more unit tests? Looking for some suggestions before proceeding
> Fix mppi bidirectional settings

- nav2_system_tests/src/system/CMakeLists.txt
---
---
Github Actions
- There remained a duplicate test with test_system_launch after Groot monitoring was removed, added in PR #1958 and removed in PR #2696 after which it was exactly the same as `test_bt_navigator_with_dijkstra`. This should reduce the time to run the nav2_system_tests
N/A
Github Actions
---
Further inspecting long-duration tests.
> Remove duplicate test

- .github/workflows/lint.yml
- nav2_simple_commander/launch/assisted_teleop_example_launch.py
- nav2_simple_commander/launch/follow_path_example_launch.py
- nav2_simple_commander/launch/inspection_demo_launch.py
- nav2_simple_commander/launch/nav_through_poses_example_launch.py
- nav2_simple_commander/launch/nav_to_pose_example_launch.py
- nav2_simple_commander/launch/picking_demo_launch.py
- nav2_simple_commander/launch/recoveries_example_launch.py
- nav2_simple_commander/launch/security_demo_launch.py
- nav2_simple_commander/launch/waypoint_follower_example_launch.py
- nav2_simple_commander/nav2_simple_commander/costmap_2d.py
- nav2_simple_commander/nav2_simple_commander/demo_inspection.py
- nav2_simple_commander/nav2_simple_commander/demo_picking.py
- nav2_simple_commander/nav2_simple_commander/demo_recoveries.py
- nav2_simple_commander/nav2_simple_commander/demo_security.py
- nav2_simple_commander/nav2_simple_commander/example_assisted_teleop.py
- nav2_simple_commander/nav2_simple_commander/example_follow_path.py
- nav2_simple_commander/nav2_simple_commander/example_nav_through_poses.py
- nav2_simple_commander/nav2_simple_commander/example_nav_to_pose.py
- nav2_simple_commander/nav2_simple_commander/example_waypoint_follower.py
- nav2_simple_commander/nav2_simple_commander/footprint_collision_checker.py
- nav2_simple_commander/nav2_simple_commander/line_iterator.py
- nav2_simple_commander/nav2_simple_commander/robot_navigator.py
- nav2_simple_commander/nav2_simple_commander/utils.py
- nav2_simple_commander/test/test_copyright.py
- nav2_simple_commander/test/test_flake8.py
- nav2_simple_commander/test/test_footprint_collision_checker.py
- nav2_simple_commander/test/test_line_iterator.py
- nav2_simple_commander/test/test_pep257.py
- tools/pyproject.toml
---
---
* Corrected unsafe fixes using `ruff` - `ruff check --select UP --fix --unsafe-fixes nav2_simple_commander`
* Restructured `nav2_simple_commander` for strict mypy.
* N/A
---
* N/A
> Mypy nav2 simple commander

- nav2_behavior_tree/plugins/action/controller_selector_node.cpp
- nav2_behavior_tree/plugins/action/planner_selector_node.cpp
- nav2_behavior_tree/plugins/action/smoother_selector_node.cpp
- nav2_behavior_tree/plugins/condition/is_battery_charging_condition.cpp
- nav2_behavior_tree/plugins/condition/is_battery_low_condition.cpp
- nav2_behavior_tree/plugins/decorator/goal_updater_node.cpp
> Backport Jazzy #5055

- nav2_costmap_2d/src/costmap_2d.cpp
- nav2_smac_planner/include/nav2_smac_planner/utils.hpp
- nav2_smac_planner/test/test_smoother.cpp
The conversion between world and map continuous (!) coordinates do not require a +/-0.5. This offset is only required when converting discrete map cell indexes to the coordinates of its center.
---
| Ticket(s) this addresses   | #4735 |
| Robotic platform tested on | Custom robot |
---
---
> Fix incorrect world <-> map coordinates conversions

- nav2_amcl/src/map/map_cspace.cpp
---
| Robotic platform tested on | Dexory robot|
---
On VERY big maps, the method `map_update_cspace` of AMCL takes ages. Which makes AMCL long to start, or reset (when for instance changing a dynamic parameter needing `reinit_laser = true`)
3 tricks by order of impact:
- using `std::queue` instead of `std::priority_queue`. But this is why this is a draft, I cannot understand why `std::priority_queue` was needed in the first place (and which criteria it used for ordering), so I am not sure.
- avoiding one `CellData` copy with `emplace` instead of push.
- computing MAP_INDEX(map, i, j) once instead of twice. …
> [AMCL] 50% initialisation (and reset) speed improvement 

- nav2_behavior_tree/include/nav2_behavior_tree/bt_utils.hpp
- nav2_behavior_tree/test/test_bt_utils.cpp
---
| Robotic platform tested on | Only testing|
| Does this PR contain AI generated software? | no |
---
---
> Added WaypointStatus to bt_utils

- .github/workflows/lint.yml
- .pre-commit-config.yaml
- tools/bt2img.py
- tools/planner_benchmarking/metrics.py
- tools/planner_benchmarking/planning_benchmark_bringup.py
- tools/planner_benchmarking/process_data.py
- tools/pyproject.toml
- tools/smoother_benchmarking/metrics.py
- tools/smoother_benchmarking/process_data.py
- tools/smoother_benchmarking/smoother_benchmark_bringup.py
- tools/update_readme_table.py
---
---
* Corrected unsafe fixes using `ruff` - `ruff check --select UP --fix --unsafe-fixes tools`
* Restructured `tools` for strict mypy.
* Simplified linting workflow to include all packages.
* N/A
---
* N/A
> Configure the entire nav2 stack with mypy

- .circleci/config.yml
- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/parameter_handler.hpp
- nav2_regulated_pure_pursuit_controller/src/parameter_handler.cpp
---
| Ticket(s) this addresses   | #4907  |
---
---
@SteveMacenski I hope I understood the ticket correctly. I will continue to work on the rest of the codebase if these changes are the expected ones :).
> Dynamic param patterns

- nav2_navfn_planner/src/navfn_planner.cpp
---
| Primary OS tested on | (~~Ubuntu, MacOS, Windows~~) |
| Robotic platform tested on | (Jeeves) |
---
Tested on Humble branch on Jeeves & by inspecting the topic via "ros2 topic echo"
* Merged this from Humble branch
---
> Merged Fix navfn_planner from humble PR #5087

- nav2_mppi_controller/src/optimizer.cpp
---
| Ticket(s) this addresses   | #5021 |
| Robotic platform tested on | My own robot platform |
---
As described in the issue, this PR protects from the NaN values
---
> Support zero value for std_wz in mppi controller

- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
Related issue: https://github.com/ros-navigation/navigation2/issues/5098
---
| Ticket(s) this addresses   | #5098 |
| Robotic platform tested on | Loopback Simulation |
---
Limit fixed curvature lookahead distance to distance to cusp if the latter is smaller.
Is only relevant if both `allow_reversing` and `use_fixed_curvature_lookahead` is true, as otherwise there will be no cusps in the path, or lookahead will automatically be adjusted correctly already.
Bugfix: no change required.
Test run in TB4 Loopback Simulation.
> Make sure fixed curvature lookahead distance doesn't overshoot distance to cusp with RPP controller

- nav2_rviz_plugins/src/nav2_panel.cpp
---
---
When we enter the paused mode in the nav2_rviz_plugin, there are currently three buttons appearing, resume, reset and start navigation. Apparently start navigation button does not have any use and looks to be bit misleading. Therefore removing that and also have disabled the button. 
---
> removing the start navigation msg in the paused state from rviz button

- nav2_smac_planner/src/node_lattice.cpp
| Ticket(s) this addresses   | https://github.com/ros-navigation/navigation2/issues/5133 |
| Robotic platform tested on |  gazebo simulation  |
---
This is a fix of an issue with backward flag in lattice node, which sometimes lead to 180 degree plan error. See details in the [issue](https://github.com/ros-navigation/navigation2/issues/5133)
* No documentation updates required as it is a bug-fix
* I run existing unit tests for smac planner
---
> Fix lattice backward 180 deg issue

- nav2_mppi_controller/src/critics/cost_critic.cpp
- nav2_smac_planner/include/nav2_smac_planner/utils.hpp
---
| Ticket(s) this addresses   | https://github.com/ros-navigation/navigation2/4271 |
| Robotic platform tested on | Custom simulation |
---
* Add Error message if inflation radius is smaller than the circumscribed radius
* Set the inflation radius smaller than the circumscribed radius and verify that the error is triggered
---
> Show error if inflation radius is smaller than circumscribed radius

- nav2_mppi_controller/include/nav2_mppi_controller/optimizer.hpp
- nav2_mppi_controller/src/controller.cpp
- nav2_mppi_controller/src/optimizer.cpp
---
| Robotic platform tested on | Turtlebot4 Gazebo simulation|
---
* Added a default parameter to the MPPI controller that prevents it from resetting speed limits whenever a goal is reached/terminated.
* N/A
* The turtlebot now begins the movement in a speed limit zone with its speed reduced to the speed limit of the zone.
---
* N/A
> Prevent MPPI controller from resetting speed limits upon goal execution.

- nav2_docking/README.md
- nav2_docking/opennav_docking/include/opennav_docking/controller.hpp
- nav2_docking/opennav_docking/include/opennav_docking/docking_server.hpp
- nav2_docking/opennav_docking/src/controller.cpp
- nav2_docking/opennav_docking/src/docking_server.cpp
- nav2_docking/opennav_docking/src/simple_charging_dock.cpp
- nav2_docking/opennav_docking/src/simple_non_charging_dock.cpp
- nav2_docking/opennav_docking/test/CMakeLists.txt
- nav2_docking/opennav_docking/test/docking_params.yaml
- nav2_docking/opennav_docking/test/test_controller.cpp
- nav2_docking/opennav_docking/test/test_docking_server.py
- nav2_docking/opennav_docking/test/test_docking_server_unit.cpp
- nav2_docking/opennav_docking/test/test_simple_charging_dock.cpp
- nav2_docking/opennav_docking/test/test_simple_non_charging_dock.cpp
- nav2_docking/opennav_docking_core/include/opennav_docking_core/charging_dock.hpp
---
| Ticket(s) this addresses   | #4403, [#68](https://github.com/open-navigation/opennav_docking/issues/68) and [PR4749](https://github.com/ros-navigation/navigation2/pull/4749)
| Primary OS tested on | Ubuntu 24.04|
| Robotic platform tested on | Morphia robot |
---
* Enhanced the docking server to allow backward docking without continuous pose refinement, using only the initially detected docking pose.
* Added a parameter ```backward_blind``` to the SimpleChargingDock and SimpleNonChargingDock.
---
> Backward docking without sensors 

- .github/workflows/build_main_against_distros.yml
have the vast majority of the dependencies preinstalled from our nightly docker builds in `nav2_docker`
> Speed up CI builds for released distros

- .github/workflows/build_main_against_distros.yml
We're building and not running tests anyway, this is just checking API compatibility, so we can skip some packages that won't yield us helpful information. So anything fully Python3 can be removed and the `nav2_system_tests` can be removed
> Save 2 minutes in Main-Jazzy build times to align with other CI job lengths

- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/parameter_handler.hpp
- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/regulated_pure_pursuit_controller.hpp
- nav2_regulated_pure_pursuit_controller/src/parameter_handler.cpp
- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
- nav2_regulated_pure_pursuit_controller/test/test_regulated_pp.cpp
---
| Ticket(s) this addresses   | (N/A) |
| Robotic platform tested on | (gazebo simulation and my own robot) |
---
*  Added  stateful  parameter, to the RPP controller
* Updated Doc [Here](https://github.com/ros-navigation/docs.nav2.org/pull/690)
* Tested this feature on a real robot
---
> Add stateful to regulated pure pursuit controller

- nav2_util/include/nav2_util/node_utils.hpp
- nav2_util/test/test_node_utils.cpp
| Robotic platform tested on | Independent |
---
The added utility tackles 2 issues:
- Reduces the amount of boilerplate code required to declare and get parameters, and consequently makes it less likely to introduce typos: it combines declare_parameter_if_not_declared and get_parameter in a single instruction.
Example:
```
nav2_util::declare_parameter_if_not_declared(
node,
"max_rotational_vel", rclcpp::ParameterValue(1.0));
node->get_parameter("max_rotational_vel", max_rotational_vel_);
```
Can be rewritten as
`max_rotational_vel_ = nav2_util::declare_or_get_param(node, "max_rotational_vel", 1.0);`
- Helps tracking typos / mismatching …
> Adding parameter util to node utils

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
- nav2_behaviors/include/nav2_behaviors/timed_behavior.hpp
- nav2_bringup/params/nav2_params.yaml
- nav2_controller/src/controller_server.cpp
- nav2_docking/opennav_docking/src/docking_server.cpp
- nav2_planner/src/planner_server.cpp
- nav2_smoother/src/nav2_smoother.cpp
- nav2_system_tests/src/system/nav2_system_params.yaml
- nav2_waypoint_follower/src/waypoint_follower.cpp
Reverts #3787 which was introduced to add a configurable timeout for action servers to retain request information due to ROS 2 bug. This resulted in actions being dropped mid-execution when those actions were long running. This has since been fixed (reported ticket https://github.com/ros-navigation/navigation2/issues/3765).
Fixes and related work:
- https://github.com/ros2/rcl/pull/1012
- https://github.com/ros2/rcl/issues/1103
- https://github.com/ros2/rcl/pull/1121
This resolves https://github.com/ros-navigation/navigation2/issues/4670 leading into a Kilted release and docs PR https://github.com/ros-navigation/docs.nav2.org/pull/694
> Removing action server timeout duration after fixes to ROS 2, Reverts 3787

- nav2_util/include/nav2_util/node_utils.hpp
- nav2_util/test/test_node_utils.cpp
| Primary OS tested on | Ubuntu,) |
---
As previously discussed in https://github.com/ros-navigation/navigation2/pull/5154, as most of the parameters in the stack are associated to default values, it is currently difficult for code maintainers to spot parameters that are not loaded because of typos, wrong namespaces, or because of code changes.
The problem can be solved associating a full definition of the parameters in the yaml configuration files with a mechanism that warns when an association fails.
As this would likely result in a lot of spam for users without a full yaml definition, the current change proposes optionally enabling …
> Adding parameter warn_when_defaulting_parameters to control default parameter warnings

- tools/underlay.repos
Reverts ros-navigation/navigation2#5200 Seems that it is still necessary due to BT.CPP binaries not in Rolling still
> Revert "Removing underlay workspace from Main"

- nav2_controller/src/controller_server.cpp
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp
- nav2_costmap_2d/src/costmap_2d_ros.cpp
- nav2_planner/src/planner_server.cpp
---
Currently it is impossible to remap the publishers and subscribers of the costmap objects, because the node options of the controller server are not passed to the child node.
The change allows the child costmap node to inherit the node options of the parent, while still using customized options for the name, namespace and use_sim_time.
- verified that the costmap nodes retain the expected name and namespace
- verified that the costmap topics retain the expected name and namespace
- verified that the costmap services retain the expected name and namespace
- verified that it's possible to remap …
> Pass node options to costmap node

- nav2_bringup/params/nav2_params.yaml
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_filters/keepout_filter.hpp
- nav2_costmap_2d/plugins/costmap_filters/keepout_filter.cpp
This resolves https://github.com/ros-navigation/navigation2/issues/5139
In it, we check if we're in a lethal keepout zone. If optionally enabled (default off, but on in `nav2_params.yaml`), we reduce the lethal cost to a very high but navigable cost (252) in order to allow the robot to leave on its own but in a very efficient way. 
This cost can be tuned by users to weight the incentives to continue towards the goal (lower cost) with incentives to leave the keepout zone immediately (252 max). 
We update the costmap in the full window size during this mode in order to make sure we set all cells as lethal again once exiting the keepout zone (to keep them in update scope).
> Option to Reduce Lethal to High-Cost Navigable To Get Out of Keepout Zones if Wandered In

- nav2_bringup/launch/tb3_loopback_simulation_launch.py
- nav2_bringup/launch/tb3_simulation_launch.py
- nav2_smac_planner/include/nav2_smac_planner/analytic_expansion.hpp
- nav2_smac_planner/src/analytic_expansion.cpp
- nav2_smac_planner/test/test_a_star.cpp
> Prototype solving #5192 Issue 2: Reeds-Shepp reduce small reverse expansions

- .circleci/config.yml
- Dockerfile
---
| Ticket(s) this addresses   | #5236 |
---
This reverts the changes to the Dockerfile done in 1345c226bcf73068127b2e2efaee91a637d2f351.
None
None
> Revert "Fix Ci from key signing (#5220)"

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server.hpp
---
| Robotic platform tested on | Dexory simulation|
---
Since https://github.com/ros-navigation/navigation2/pull/5065, groot monitoring is enabled by default for all `BtActionServer`s : https://github.com/ros-navigation/navigation2/blob/7f561b0f5aa8e229334bb6f71a7a99e6074efd75/nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server.hpp#L288
This causes issue for users of simple `BtActionServer`s that by default are not calling `setGrootMonitoring`: https://github.com/ros-navigation/navigation2/blob/7f561b0f5aa8e229334bb6f71a7a99e6074efd75/nav2_behavior_tree/include/nav2_behavior …
> [BtActionServer] default enable_groot_monitoring_ to false to solve `Original error: Address already in use` migration error

- nav2_amcl/include/nav2_amcl/amcl_node.hpp
- nav2_amcl/src/amcl_node.cpp
- nav2_costmap_2d/include/nav2_costmap_2d/obstacle_layer.hpp
- nav2_costmap_2d/plugins/obstacle_layer.cpp
> Fixing builds for message filters API change while retaining Jazzy, Kilted, and Rolling support

- nav2_costmap_2d/plugins/obstacle_layer.cpp
| Robotic platform tested on | Simulation and Hardware |
---
Setting a tf filter tolerance != 0 might be undesired as it increases the chance of the messages being delayed or even discarded if the tf_timeout tolerance associated with the buffer is not big enough. Hence the option to set it to a different value through a parameter.
Also note that this tolerance is not set for pointcloud sources.
Added new parameter
Simulation and hardware -> it was verified that setting the parameter to 0.0 with a transform tolerance of 100ms prevents the filter from dropping messages, while a bigger tolerance is required with the default value of 0.05.
---
> Parametrizing obstacle layer tf filter tolerance

- nav2_bringup/params/nav2_params.yaml
- nav2_mppi_controller/include/nav2_mppi_controller/models/constraints.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/models/optimizer_settings.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/motion_models.hpp
- nav2_mppi_controller/src/optimizer.cpp
- nav2_mppi_controller/test/optimizer_unit_tests.cpp
---
| Ticket(s) this addresses   | https://github.com/ros-navigation/navigation2/issues/4601 |
| Robotic platform tested on | gazebo simulation, our mobile robot hardware |
---
> - Fix the acceleration and deceleration when going backward as mentioned in the issue, mostly copied from https://github.com/ros-navigation/navigation2/pull/3529
> - Regarding the performance issue mentioned in the issue, I ran benchmark and observed no significant difference from the original(tested with different parameters)
Tested on sim and my hardware, wrote some new unit tests
---
> Maybe more unit tests? Looking for some suggestions before proceeding
> Backport bidirectional settings #4954 to Jazzy

- nav2_loopback_sim/nav2_loopback_sim/loopback_simulator.py
- nav2_simple_commander/nav2_simple_commander/demo_security.py
- nav2_simple_commander/nav2_simple_commander/robot_navigator.py
- nav2_system_tests/src/behaviors/backup/backup_tester.py
- nav2_system_tests/src/behaviors/drive_on_heading/drive_tester.py
- nav2_system_tests/src/behaviors/spin/spin_tester.py
- nav2_system_tests/src/costmap_filters/tester_node.py
- nav2_system_tests/src/gps_navigation/tester.py
- nav2_system_tests/src/route/tester_node.py
- nav2_system_tests/src/system/nav_through_poses_tester_error_msg_node.py
- nav2_system_tests/src/system/nav_through_poses_tester_node.py
- nav2_system_tests/src/system/nav_to_pose_tester_node.py
- nav2_system_tests/src/system_failure/tester_node.py
- nav2_system_tests/src/waypoint_follower/tester.py
- tools/pyproject.toml
---
| Ticket(s) this addresses   | #5085  |
---
* Fix the additional `[var-annotated]` errors on subsequent runs of ament_mypy
* N/A
* Ran local pre-commits before publishing.
---
* I am unsure as to why ament_mypy fails on the current branch. I was under the impression that `ament_mypy` got recently updated, so that would be the cause.
* Failure on `ament_mypy` on [`0.20.0`](https://github.com/ros-navigation/navigation2/actions/runs/15697324501/job/44224829089?pr=5266#step:5:92)   
* Pass on `ament_mypy` on [`0.19.1`](https://github.com/ros-navigation/navigation2/actions/runs/14424045368/job/40450162225?p …
> Fix ament mypy

- nav2_map_server/src/map_io.cpp
---
| Robotic platform tested on |  gazebo simulation , Jazzy |
---
Supersedes #5138 
This PR uses fixed values for the threshold saved to the yaml file, in Trinary mode. Similarly to [ROS 1](https://github.com/ros-planning/navigation/blob/9ad644198e132d0e950579a3bc72c29da46e60b0/map_server/src/map_saver.cpp#L95-L116).
With this change, Trinary maps loaded created and loaded with the map_server, will now load correctly. This is because the pixel values saved in this mode are constants, so when loading the map the thresholds must lie between the pixel values for correct loading. The thresholds supplied by …
> Use fixed thresholds for Trinary yaml

- nav2_rviz_plugins/src/route_tool.cpp
| Does this PR contain AI generated software? | None |
---
The `unistd.h` header seems unused, and removing it permit to compile the project on Windows.
None.
Tested if compilation was successful.
None
> Remove unused unistd.h include from route_tool.cpp

- nav2_smac_planner/CMakeLists.txt
- nav2_smac_planner/include/nav2_smac_planner/node_hybrid.hpp
- nav2_smac_planner/include/nav2_smac_planner/node_lattice.hpp
| Robotic platform tested on | None, compilation fix. |
| Does this PR contain AI generated software? | No. |
---
`navigation2` uses the `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` to build shared libraries on Windows, see https://github.com/ros-navigation/navigation2/pull/1704 for more details. However, `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` can't automatically export public static members, see https://www.kitware.com/create-dlls-on-windows-without-declspec-using-new-cmake-export-all-feature/ . 
In case that public static members are needed, it is necessary to manually annotate them with visibility macros. This PR does that for the static members that are actually …
> Fix compilation of nav2_smac_planner on Windows

- nav2_bringup/params/nav2_params.yaml
- nav2_ros_common/include/nav2_ros_common/node_utils.hpp
- nav2_ros_common/test/test_service_client.cpp
- nav2_ros_common/test/test_service_server.cpp
- nav2_smac_planner/src/smac_planner_2d.cpp
- nav2_smac_planner/src/smac_planner_hybrid.cpp
---
---
Introspection mode now supports for both action and service, so rename it to introspection_mode to avoid ambiguity
---
> Rename service_introspection_mode to introspection_mode

- nav2_costmap_2d/plugins/voxel_layer.cpp
---
| Ticket(s) this addresses   | (add tickets here #5099) |
| Robotic platform tested on | (gazebo simulation of tb3 simulation) |
---
- Check if the points in the point cloud exceed the boundary of the cost map.
- If it exceeds the boundary, bring the point closer to the observation source to ensure that the target point is within the boundary.
- Launch tb3_simulation_launch.py and show the pointcloud of topic `/local_costmap/clearing_endpoints` in rviz2.
- The endpoints are always whithin the local_costmap.
---
> Adding epsilon for voxel_layer precision loss

- nav2_bringup/params/nav2_params.yaml
- nav2_velocity_smoother/include/nav2_velocity_smoother/velocity_smoother.hpp
- nav2_velocity_smoother/src/velocity_smoother.cpp
- nav2_velocity_smoother/test/test_velocity_smoother.cpp
---
| Ticket(s) this addresses   | #5238 |
---
https://github.com/ros-navigation/docs.nav2.org/pull/706
---
> Add 6dof support for velocity smoother

- nav2_bringup/params/nav2_params.yaml
- nav2_mppi_controller/CMakeLists.txt
- nav2_mppi_controller/benchmark/optimizer_benchmark.cpp
- nav2_mppi_controller/include/nav2_mppi_controller/optimal_trajectory_validator.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/optimizer.hpp
- nav2_mppi_controller/package.xml
- nav2_mppi_controller/src/controller.cpp
- nav2_mppi_controller/src/critics/obstacles_critic.cpp
- nav2_mppi_controller/src/optimizer.cpp
- nav2_mppi_controller/src/trajectory_validators/optimal_trajectory_validator.cpp
- nav2_mppi_controller/test/optimizer_smoke_test.cpp
- nav2_mppi_controller/test/optimizer_unit_tests.cpp
- nav2_mppi_controller/test/utils/factory.hpp
- nav2_mppi_controller/trajectory_validators.xml
This creates a new plugin interface to MPPI which takes in the control request, optimal trajectory, and outputs if this is valid. 
This is performed after the optimization process is completed to receive a final trajectory for smoothing - so we should already be applying kinematic and dynamic constraints to the output to make sure its valid in that regard. It should also be known collision free since that would trigger a soft and then hard reset if no trajectories are valid. 
This can be used to validate the trajectory based on application specific constraints, constraints on control due to standards or multi-robot coordination, via point achievement, and so forth. 
TODO
On implementation, we could add in:
- Parameter for max deviation from a path
- Additional non-collision margin from …
> Adding initial prototype for a MPPI trajectory validator

- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/footprint.hpp
- nav2_costmap_2d/src/costmap_2d_ros.cpp
- nav2_costmap_2d/src/footprint.cpp
- nav2_costmap_2d/src/footprint_subscriber.cpp
---
| Robotic platform tested on | Propreitary |
---
* This PR adds a parameter to choose between `Polygon`/`PolygonStamped` subscriber for receiving the footprint in the `Costmap2DROS`.
* By default `Costmap2DROS` subscribes to `Polygon` footprints
* `PolygonStamped` footprints can be subscribed to by setting the `subscribe_to_stamped_footprint` parameter to True
* Also includes some cleanup, tiny optimizations, and minor refactoring to parts of code in the vicinity of the above changes
None
Tested that the `Costmap2DROS` can receive and properly process `PolygonStamped` footprint messages on a proprietary robot
---
N/A
> Support stamped footprints in costmap_2d

- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
- nav2_regulated_pure_pursuit_controller/test/test_regulated_pp.cpp
This is notably missing while included in the rotation shim controller, docking, spin, backup, and drive on heading behaviors
> Adding slow down at target heading to RPP Controller

- nav2_collision_monitor/include/nav2_collision_monitor/pointcloud.hpp
- nav2_collision_monitor/src/pointcloud.cpp
---
| Robotic platform tested on | Dexory Robot|
---
This PR adds the ability to dynamically reconfigure min_height and max_height in the Collision Monitor pointcloud source. (by @doisyg )
---
> Dynamic reconfigure CM pointcloud `min_height` and `max_height`

- .devcontainer/devcontainer.json
- Dockerfile
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/navigate_through_poses_action.hpp
- nav2_behavior_tree/test/plugins/decorator/test_single_trigger_node.cpp
- nav2_mppi_controller/test/utils_test.cpp
---
| Ticket(s) this addresses   | (add tickets here #5230) |
---
Backports bug fixes from main to humble:
- https://github.com/ros-navigation/navigation2/pull/3674/commits/1de4cd21bcd1552ff8450c005c4a3382df6d031c
- https://github.com/ros-navigation/navigation2/pull/3605/commits/7d5e93c5704647055ef8a14636373b4f997de76b
Also fixes the devcontainer setup for humble (as I used it for testing and ran into those issues).
Ran `colcon test`, which fixes the some of the test …
> Humble backport fixes

- nav2_bringup/params/nav2_params.yaml
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_filters/keepout_filter.hpp
- nav2_costmap_2d/plugins/costmap_filters/keepout_filter.cpp
> Backport "Option to Reduce Lethal to High-Cost Navigable To Get Out of Keepout Zones if Wandered In"

- nav2_amcl/src/amcl_node.cpp
- nav2_ros_common/include/nav2_ros_common/lifecycle_node.hpp
---
| Ticket(s) this addresses   | #5299 |
---
Related to #5299
Use `declare_or_get_param` API instead of  `declare_parameter` - `get_parameter`
- nav2_amcl
Nothing
- Unit tests
---
Nothing
> Use declare_or_get_param API

- nav2_route/README.md
Extended SWAGGER for easy Nav2 integration via https://github.com/nvidia-isaac/SWAGGER/pull/2
> Adding SWAGGER for Nav2 Route

- nav2_dwb_controller/costmap_queue/package.xml
- nav2_dwb_controller/dwb_critics/package.xml
- nav2_dwb_controller/dwb_msgs/package.xml
- nav2_dwb_controller/dwb_plugins/package.xml
- nav2_dwb_controller/nav_2d_msgs/package.xml
- nav2_dwb_controller/nav_2d_utils/package.xml
Just changing where buildfarm emails go.
> Change David's Email Address

- nav2_route/include/nav2_route/node_spatial_tree.hpp
---
| Ticket(s) this addresses   | #5419 |
---
Add IndexType definition for Nanoflann KDTree in `node_spatial_tree`.
---
> Add IndexType definition for Nanoflann KDTree in `node_spatial_tree`.

- nav2_behavior_tree/include/nav2_behavior_tree/plugins/control/pause_resume_controller.hpp
- nav2_behavior_tree/plugins/control/pause_resume_controller.cpp
- nav2_behavior_tree/test/plugins/control/test_pause_resume_controller.cpp
- nav2_behavior_tree/test/utils/get_node_from_tree.hpp
Fix https://github.com/ros-navigation/navigation2/pull/5247#discussion_r2260084205
> Make pause resume controller use nav2::LifecycleNode

- nav2_costmap_2d/plugins/costmap_filters/costmap_filter.cpp
---
| Robotic platform tested on | Proprietary |
---
* Fixed a bug with KeepoutFilter on robots that use ARM-based computers
* ARM by default considers `char` type as **unsigned** as described [here](https://developer.arm.com/documentation/den0013/0400/Porting/Miscellaneous-C-porting/unsigned-char-and-signed-char?lang=en)
* Using a `char` instead of `signed char` when reading the data from `nav_msgs::msg::OccupancyGrid` results in misinterpretation of `-1` values  representing UNKNOWN cells in the filter mask.
N/A
Keepout filter was tested on a …
> Fix KeepoutFilter on the ARM architecture

- nav2_costmap_2d/include/nav2_costmap_2d/costmap_filters/keepout_filter.hpp
- nav2_costmap_2d/plugins/costmap_filters/keepout_filter.cpp
---
| Ticket(s) this addresses   | https://github.com/ros-navigation/navigation2/issues/5410#issuecomment-3161140182 |
---
As requested in https://github.com/ros-navigation/navigation2/issues/5410#issuecomment-3161140182
My current implementation will always prioritize map update, if there is a map update, it will skip checking "is_pose_lethal", and …
> Add option to override lethal cost in keepout zone

- nav2_costmap_2d/plugins/costmap_filters/binary_filter.cpp
- nav2_costmap_2d/test/unit/binary_filter_test.cpp
| Ticket(s) this addresses   | Related to #5368 |
| Robotic platform tested on | Hello Robot Stretch (hardware)|
---
Backporting the fix in #5370 to jazzy
> backport the fix for setting binary_state as the default

- nav2_route/src/path_converter.cpp
- nav2_route/test/test_path_converter.cpp
| Robotic platform tested on | Polymath Autonomy System |
---
When a zero-length edge in a route graph is in a calculated route, the `densify` function for the resulting path would go into an infinite loop pushing points to a vector until running out of memory and crashing.
None
Added a unit test that definitely fails before adding the fix.
I've been running it on simulation examples with a route graph that has zero length edges.
N/A
> Return early from edge interpolation for zero-length edges

- nav2_bt_navigator/src/navigators/navigate_through_poses.cpp
- nav2_bt_navigator/src/navigators/navigate_to_pose.cpp
---
| Ticket(s) this addresses   | -|
---
Move the `xx_blackboard_id` parameters to each navigator's namespace. This avoids clashes with other navigators which have the same parameter, but uses a different ID -> Not all navigators must use the same blackboard ID.
Yes, need to update the bt_navigator configuration page
- use `ros2 param dump /bt_navigator` to check the params have moved inside the navigators' namespace
- try to use different values (need to adapt in the BT xml) and see if feedback works correctly
---
> make Blackboard IDs private to the navigators

- nav2_smac_planner/src/node_lattice.cpp
I noticed that some parameters from SmacPlannerLattice were only being dynamically set successfully once, more attempts wouldn't change anything. The issue to my understanding is that it was exiting early because the `lattice_filepath` hadn't changed.
To be honest I didn't look for side-effects but looks relatively safe. Any risks you see of updating the parameters without  re-populating the primitives?
> Fix dynamic param SmacPlannerLattice 

- nav2_navfn_planner/src/navfn_planner.cpp
---
| Ticket(s) this addresses   | https://github.com/ros-navigation/navigation2/issues/4755#issuecomment-3228998773 |
---
---
> Replace last pose if only orientation differs in Navfn

- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/controller_selector_node.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/goal_checker_selector_node.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/planner_selector_node.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/progress_checker_selector_node.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/smoother_selector_node.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/condition/is_battery_charging_condition.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/condition/is_battery_low_condition.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/decorator/goal_updater_node.hpp
- nav2_behavior_tree/plugins/action/controller_selector_node.cpp
- nav2_behavior_tree/plugins/action/goal_checker_selector_node.cpp
- nav2_behavior_tree/plugins/action/planner_selector_node.cpp
- nav2_behavior_tree/plugins/action/progress_checker_selector_node.cpp
- nav2_behavior_tree/plugins/action/smoother_selector_node.cpp
- nav2_behavior_tree/plugins/condition/is_battery_charging_condition.cpp
- nav2_behavior_tree/plugins/condition/is_battery_low_condition.cpp
- nav2_behavior_tree/plugins/decorator/goal_updater_node.cpp
- nav2_behavior_tree/test/plugins/action/test_controller_selector_node.cpp
- nav2_behavior_tree/test/plugins/action/test_goal_checker_selector_node.cpp
- nav2_behavior_tree/test/plugins/action/test_planner_selector_node.cpp
- nav2_behavior_tree/test/plugins/action/test_progress_checker_selector_node.cpp
- nav2_behavior_tree/test/plugins/action/test_smoother_selector_node.cpp
- nav2_behavior_tree/test/plugins/condition/test_is_battery_charging.cpp
- nav2_behavior_tree/test/plugins/condition/test_is_battery_low.cpp
- nav2_behavior_tree/test/plugins/decorator/test_goal_updater_node.cpp
- nav2_route/test/test_graph_loader.cpp
- nav2_route/test/test_graph_saver.cpp
---
| Ticket(s) this addresses   | https://github.com/ros-navigation/navigation2/issues/4567 |
---
- Revert double spin, this has been solved in the latest release
- Change spin some to spin all, to make sure the node has the latest message update
None
Tested in different node's unit tests
---
> Revert double spin

- nav2_mppi_controller/package.xml
> Removing openMP dep on MPPI

- nav2_controller/src/controller_server.cpp
- nav2_dwb_controller/dwb_core/src/dwb_local_planner.cpp
- nav2_route/src/goal_intent_extractor.cpp
---
| Ticket(s) this addresses   | https://github.com/ros-navigation/navigation2/pull/5414#issuecomment-3234909263 |
---
- Fix pose timestamp when using transformPoseInTargetFrame
---
> Fix pose timestamp when using transformPoseInTargetFrame

- nav2_theta_star_planner/CMakeLists.txt
---
| Primary OS tested on | Ubuntu 22.04 LTS |
| Robotic platform tested on | N/A (build fix) |
| Does this PR contain AI generated software? | (No, just a newline really) |
---
* I fixed a typo in the CMakeLists.txt file from the `nav2_theta_star_planner` package where the `nav2_costmap_2d` and `nav2_util` were written together (without a newline).
N/A
* Performed a clean build using colcon build --symlink-install.
---
N/A
> fix(nav2_theta_star_planner): Correct typo in CMakeLists ament_export_dependencies

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
- nav2_core/include/nav2_core/behavior_tree_navigator.hpp
---
| Robotic platform tested on | Dexory sim |
| Was this PR description generated by AI software? |No|
---
In relation to https://github.com/ros-navigation/navigation2/pull/5426#issuecomment-3271837259
Make `search_directories` optional to not break external use of `BtActionServer` (without a migration step).
cc @Jad-ELHAJJ 
---
> [BtActionServer] default empty search_directories in constructor

- nav2_mppi_controller/include/nav2_mppi_controller/critic_data.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/optimizer.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/tools/path_handler.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp
- nav2_mppi_controller/src/controller.cpp
- nav2_mppi_controller/src/critics/cost_critic.cpp
- nav2_mppi_controller/src/critics/goal_angle_critic.cpp
- nav2_mppi_controller/src/critics/goal_critic.cpp
- nav2_mppi_controller/src/critics/obstacles_critic.cpp
- nav2_mppi_controller/src/critics/path_align_critic.cpp
- nav2_mppi_controller/src/critics/path_align_legacy_critic.cpp
- nav2_mppi_controller/src/critics/path_angle_critic.cpp
- nav2_mppi_controller/src/critics/path_follow_critic.cpp
- nav2_mppi_controller/src/critics/prefer_forward_critic.cpp
- nav2_mppi_controller/src/critics/twirling_critic.cpp
- nav2_mppi_controller/src/optimizer.cpp
- nav2_mppi_controller/src/path_handler.cpp
- nav2_mppi_controller/test/controller_state_transition_test.cpp
- nav2_mppi_controller/test/critic_manager_test.cpp
- nav2_mppi_controller/test/critics_tests.cpp
- nav2_mppi_controller/test/optimizer_smoke_test.cpp
- nav2_mppi_controller/test/optimizer_unit_tests.cpp
- nav2_mppi_controller/test/utils_test.cpp
Reverting https://github.com/ros-navigation/navigation2/commit/ad2f9602f03ba688c34df7f903a118b6898ef0ce on Humble due to bug that was fixed on Main but is not backward compatible with Humble, so the entire feature should be removed. 
FYI @redvinaa
Closes https://github.com/ros-navigation/navigation2/issues/5503
> Reverting ad2f9602f03ba688c34df7f903a118b6898ef0ce on Humble

- nav2_docking/opennav_docking/test/test_simple_charging_dock.cpp
- nav2_docking/opennav_docking/test/test_simple_non_charging_dock.cpp
| Primary OS tested on | Linux |
---
- Restore the executor-based spinning for docking tests that #5521 introduced so we keep the executor driving callbacks instead of rclcpp::spin_some.
- Update the detector-focused unit tests added in #5218 to follow the same executor pattern for consistent coverage.
> restore executor-based spinning in opennav_docking

- nav2_behavior_tree/nav2_tree_nodes.xml
| Robotic platform tested on | not applicable, groot2 1.6.1 |
---
* add bt nodes GetCurrentPose, ConcatenatePaths, WouldARouteRecoveryHelp, ArePosesNear to nav2_tree_nodes.xml, descriptions taken from corresponding C++ classes
none
opened `navigate_on_route_graph_w_recovery.xml` in groot2, no warnings of undefined BT nodes are observed anymore
---
* Some autogeneration of this description from the C++ classes would be nice, i guess
> add route planning BT nodes to nav2_tree_nodes.xml

- nav2_smac_planner/include/nav2_smac_planner/smoother.hpp
- nav2_smac_planner/src/smoother.cpp
- nav2_smac_planner/test/test_smoother.cpp
- nav2_smoother/include/nav2_smoother/savitzky_golay_smoother.hpp
- nav2_smoother/include/nav2_smoother/simple_smoother.hpp
- nav2_smoother/src/savitzky_golay_smoother.cpp
- nav2_smoother/src/simple_smoother.cpp
- nav2_smoother/test/test_savitzky_golay_smoother.cpp
- nav2_smoother/test/test_simple_smoother.cpp
- nav2_util/CMakeLists.txt
- nav2_util/include/nav2_util/smoother_utils.hpp
- nav2_util/package.xml
- nav2_util/test/CMakeLists.txt
- nav2_util/test/test_smoother_utils.cpp
---
| Ticket(s) this addresses   | #5425 |
| Does this PR contain AI generated software? | Some of the test cases are written by AI|
---
---
> Refactor common functions in smoother and planner

- nav2_bringup/params/nav2_params.yaml
- nav2_collision_monitor/params/collision_monitor_params.yaml
- nav2_collision_monitor/src/collision_monitor_node.cpp
- nav2_collision_monitor/test/collision_monitor_node_test.cpp
---
| Ticket(s) this addresses   | #5493 |
| Robotic platform tested on | Turtlebot 3 Loopback Simulation |
---
* Added a parameter to set the initial state for for the collision monitor to start in enabled/disabled state. 
* Need to add this parameter to the [collision monitor node documentation](https://docs.nav2.org/configuration/packages/collision_monitor/configuring-collision-monitor-node.html)
* This change was tested in the TB3 Loopback simulation to check if it actually works. I kept an eye on the console log to see if the correct message was printed during node …
> Add a parameter to set initial enabled state for the collision monitor

- nav2_collision_monitor/test/collision_monitor_node_test.cpp
---
| Ticket(s) this addresses   | #5230 |
---
- Removes usages of the collision monitor state as this is not published in humble, only in Iron+;
---
> Fix collision monitor test suite for humble

- nav2_route/test/test_goal_intent_extractor.cpp
- nav2_route/test/test_route_tracker.cpp
---
| Ticket(s) this addresses   | Fixes the `system_build` [job](https://app.circleci.com/pipelines/github/ros-navigation/navigation2/16253/workflows/415fc0bc-a6c0-4788-ad75-e32d5f002e4a/jobs/47505) |
| Does this PR contain AI-generated software? | No|
---
* Migrated to use the heap allocation over stack due to the new NodeInterfaces API for `TransformBroadcaster` enforced in [ros2/geometry2](https://github.com/ros2/geometry2/pull/714/files#diff-5bbc53dd6b24edebe2ad5c06f9659ed7387ebcdc638384552f66785950211c45R93-R100).
* N/A
* The local build of `nav2_route` now passes locally - `colcon build …
> Migrate TransformBroadcaster to use shared_ptr

- nav2_system_tests/src/behaviors/wait/test_wait_behavior_launch.py
> Fix CI regression

- nav2_mppi_controller/src/controller.cpp
The cmd is wrt to the base frame while the optimal_trajectory is wrt to global frame.  Fix the frame id for the trajectory_msg. 
---
| Ticket(s) this addresses   | / |
| Robotic platform tested on | Custom simulation |
---
> Fix optimal plan frame id

- nav2_rviz_plugins/CMakeLists.txt
- nav2_rviz_plugins/include/nav2_rviz_plugins/docking_panel.hpp
- nav2_rviz_plugins/include/nav2_rviz_plugins/nav2_panel.hpp
- nav2_rviz_plugins/src/nav2_panel.cpp
---
| Ticket(s) this addresses   | closes https://github.com/ros-navigation/navigation2/issues/5570|
| Robotic platform tested on | Tested on Jazzy, Rolling |
---
Add Qt6 support for nav2_rviz_plugins
Tested both in Jazzy and Rolling, works fine
---
> Add Qt6 support for nav2_rviz_plugins

- nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
- nav2_behaviors/plugins/assisted_teleop.cpp
- nav2_behaviors/plugins/spin.cpp
- nav2_behaviors/src/behavior_server.cpp
- nav2_behaviors/test/test_behaviors.cpp
---
| Ticket(s) this addresses   | #5299  |
| Does this PR contain AI-generated software? | No |
| Was this PR description generated by AI software? | N/A |
---
* Migrated the `get_parameter` and `declare_parameter` fields to use the new `declare_or_get_parameter` API for nav2_behaviors.
* N/A
* Performed linting validation using `pre-commit run --all` and testing locally using `colcon test`
---
> Use the new declare_or_get_parameter API for nav2_behaviors.

- nav2_smac_planner/include/nav2_smac_planner/a_star.hpp
- nav2_smac_planner/src/a_star.cpp
Until now, a path computation timeout would systematically lead to a nav2_core::PlannerTimedOut error, even though a path was found within the tolerance.
This commit makes the A* return the best path found if it's within the tolerance.
---
| Ticket(s) this addresses   | #5577 |
| Robotic platform tested on | Custom simulation |
---
---
> nav2_smac_planner: make A* return closest path found in case of timeout
