- src/nav2_localization/amcl/src/amcl_node.cpp
Once our folder structure is ready, I will move the strutils class to util folder.
> temporarily fixed the build issue

- src/libs/nav2_util/src/map/map_draw.c
- src/libs/nav2_util/src/pf/pf_draw.c
- src/localization/nav2_amcl/src/amcl_node.cpp
- src/localization/nav2_amcl/src/amcl_node.hpp
Addressing issue's #79 and #88.
Note: Since the dynamic reconfigure is not enabled, I manually changed the default values to match turtlebot launch file default values.
TODO: Create issue to make sure formatting is correct. In this PR, I've only fixed the format in one place.
> Amcl refactorization

- .travis.yml
Add Travis CI capability by adding a .travis.yml file
> Add Travis CI ability

- src/control/nav2_dwa_controller/CMakeLists.txt
> Fixing ament_lint_cmake linter failure in nav2_dwa_controller

- src/libs/costmap_2d/CHANGELOG.rst
- src/libs/costmap_2d/CMakeLists.txt
- src/libs/costmap_2d/include/costmap_2d/costmap_2d_publisher.h
- src/libs/costmap_2d/include/costmap_2d/costmap_2d_ros.h
- src/libs/costmap_2d/include/costmap_2d/layer.h
- src/libs/costmap_2d/include/costmap_2d/observation.h
- src/libs/costmap_2d/include/costmap_2d/observation_buffer.h
- src/libs/costmap_2d/include/costmap_2d/obstacle_layer.h
- src/libs/costmap_2d/include/costmap_2d/testing_helper.h
- src/libs/costmap_2d/include/costmap_2d/voxel_layer.h
- src/libs/costmap_2d/launch/example_params.yaml
- src/libs/costmap_2d/package.xml
- src/libs/costmap_2d/plugins/obstacle_layer.cpp
- src/libs/costmap_2d/plugins/static_layer.cpp
- src/libs/costmap_2d/plugins/voxel_layer.cpp
- src/libs/costmap_2d/src/costmap_2d_node.cpp
- src/libs/costmap_2d/src/costmap_2d_ros.cpp
- src/libs/costmap_2d/src/layer.cpp
- src/libs/costmap_2d/src/observation_buffer.cpp
- src/libs/costmap_2d/test/costmap_params.yaml
- src/libs/costmap_2d/test/costmap_tester.cpp
- src/libs/costmap_2d/test/footprint_tests.cpp
- src/libs/costmap_2d/test/inflation_tests.cpp
- src/libs/costmap_2d/test/module_tests.cpp
- src/libs/costmap_2d/test/obstacle_tests.cpp
- src/libs/costmap_2d/test/static_tests.cpp
Move the base costmap_2d package in repo onto the melodic-devel branch
> Put base costmap_2d on melodic-devel branch 

- src/control/costmap_queue/include/costmap_queue/costmap_queue.h
- src/control/costmap_queue/src/costmap_queue.cpp
- src/control/costmap_queue/test/utest.cpp
- src/control/dwb_critics/src/alignment_util.cpp
- src/control/dwb_critics/src/map_grid.cpp
- src/control/dwb_plugins/src/kinematic_parameters.cpp
- src/control/dwb_plugins/src/stopped_goal_checker.cpp
- src/control/dwb_plugins/test/twist_gen.cpp
- src/control/nav_2d_utils/src/path_ops.cpp
The dwb build is broken on Ubuntu 18.04 and docker.
It seems some upstream header file fixed it's cmath namespace
pollution. This fix brings in the appropriate header and functions
> Fixing undeclared functions.

- src/control/nav2_controller_example/include/nav2_controller_example/dwa_controller.hpp
- src/control/nav2_controller_example/src/dwa_controller.cpp
When the example controller gets a plan, it will send the
robot straight forward for ten iterations of the loop.
This simple implementation can be used for integration testing.
> Make the example controller send the robot forward

- src/libs/nav2_util/include/nav2_util/map/map.h
- src/libs/nav2_util/include/nav2_util/pf/eig3.h
- src/libs/nav2_util/include/nav2_util/pf/pf.h
- src/libs/nav2_util/include/nav2_util/pf/pf_kdtree.h
- src/libs/nav2_util/include/nav2_util/pf/pf_pdf.h
- src/libs/nav2_util/include/nav2_util/pf/pf_vector.h
- src/libs/nav2_util/include/nav2_util/sensors/laser.h
- src/libs/nav2_util/include/nav2_util/sensors/odom.h
- src/libs/nav2_util/include/nav2_util/sensors/sensor.h
- src/libs/nav2_util/package.xml
- src/libs/nav2_util/src/map/map.c
- src/libs/nav2_util/src/map/map_cspace.cpp
- src/libs/nav2_util/src/map/map_draw.c
- src/libs/nav2_util/src/map/map_range.c
- src/libs/nav2_util/src/map/map_store.c
- src/libs/nav2_util/src/pf/eig3.c
- src/libs/nav2_util/src/pf/pf.c
- src/libs/nav2_util/src/pf/pf_draw.c
- src/libs/nav2_util/src/pf/pf_kdtree.c
- src/libs/nav2_util/src/pf/pf_pdf.c
- src/libs/nav2_util/src/pf/pf_vector.c
- src/libs/nav2_util/src/sensors/laser.cpp
- src/libs/nav2_util/src/sensors/odom.cpp
- src/libs/nav2_util/src/sensors/sensor.cpp
Addressing issue #133.
This PR fixes all the linter issues in nav2_util directory except warnings for map_loader and costmap.
TODO(mhpanah): Find original source file for eig3.h and put a correct license file in it.
Question:  What to do with map_loder and costmap that are residing inside nav2_util?
> Amcl ctest fix

- src/localization/nav2_amcl/test/maps/test_map.yaml
This should make the test_map.yaml work on other systems.
> Making the path to the test_map.pgm relative to the yaml file

- .travis.yml
- Dockerfile
This fixes the Dockerfile to work in the new repo structure. 
In the process I discovered that the BRANCH variable change I had made previously wasn't working, so I fixed that also by adding the REMOTE before checking out the branch.
> Fix dockerfile for new repo structure

- nav2_amcl/src/amcl_node.cpp
This is a a workaround. The current AMCL code frequently fails to
transform data and generate a pose. The current hypothesis is that
this is a result of the message filter code having been removed.
This change works around the problem by adding a 1 second timeout
on each transform, meaning there is now a 1 second window from
when the data is received till the transform can become available.
It's not clear whether this workaround has any unintended
consequences. Specfically I'm concerned about performance and
latency.
> Adding timeouts to AMCL transform calls

- .travis.yml
- Dockerfile
Don't merge this yet, will update when ready.
> Ability to build Pull Requests in Travis

- nav2_simple_navigator/README.md
A basic readme for the simple navigator directory. There's more to say, but this is a start.
> Simple navigator readme

- nav2_tasks/msg/TaskStatus.msg
fixing as assumed git merge error after refactor
> Removing the task status message from the tasks package

- nav2_amcl/README.md
First draft for AMCL readme file.
> AMCL Readme

- nav2_robot/test/test_robot_class.cpp
Addressing issue #181.
TestRobotClass checks the following methods from RosRobot Class:
- getCurrentPose()
- getCurrentVelocity()
- getRobotName()
- sendVelocity()
> Factoring out duplicated initialization code and addressing ROS naming convention violation

- .travis.yml
@mkhansen-intel @crdelsey @mhpanah @bpwilcox @mhpanah @mjeronimo 
Added all major contributors to email notifications if production (master) fails to build in CI. I just added everyone but if you don't want those emails ping me and I'll adjust the PR.
Steve
> adding all contributors for email production failure emails

- README.md
Points to `master` branch.
This is how it is going to look:
> Add Travis CI build status image

- nav2_amcl/src/amcl_node.cpp
- nav2_util/include/nav2_util/sensors/odom.h
- nav2_util/src/sensors/odom.cpp
- Removed old ODOM_MODEL _DIFF and _OMNI code.
- Renamed ODOM_MODEL_DIFF_CORRECTED to ODOM_MODEL_DIFF and ODOM_MODEL_OMNI_CORRECTED to ODOM_MODEL_OMNI
> Removed  _CORRECTED suffix from ODOM_MODEL

- nav2_mission_executor/README.md
First cut at the mission executor readme. Still lots more that can be added, but something to get started with.
> Mission execution readme

- nav2_amcl/src/amcl_node.cpp
> Addressing lint error

- Dockerfile
- nav2_amcl/src/amcl_node.cpp
- nav2_controller/nav2_controller_dwb/src/dwb_controller.cpp
- nav2_costmap_2d/src/costmap_2d_node.cpp
- nav2_map_server/CMakeLists.txt
- nav2_map_server/package.xml
Fixing issues - will update when ready to review
> Dockerfile update to fix build fails

- nav2_amcl/src/amcl_node.cpp
- nav2_controller/nav2_controller_dwb/src/dwb_controller.cpp
- nav2_costmap_2d/src/costmap_2d_node.cpp
- nav2_map_server/CMakeLists.txt
- nav2_map_server/package.xml
Here are a few changes needed to build using the latest ROS2 code.
> Build using the tip of master

- nav2_amcl/CMakeLists.txt
- nav2_amcl/src/amcl_node.cpp
> Amcl remove boost

- nav2_costmap_2d/CMakeLists.txt
- nav2_costmap_2d/costmap_plugins.xml
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_publisher.h
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.h
- nav2_costmap_2d/include/nav2_costmap_2d/inflation_layer.h
- nav2_costmap_2d/include/nav2_costmap_2d/layer.h
- nav2_costmap_2d/include/nav2_costmap_2d/static_layer.h
- nav2_costmap_2d/package.xml
- nav2_costmap_2d/plugins/inflation_layer.cpp
- nav2_costmap_2d/plugins/static_layer.cpp
- nav2_costmap_2d/src/costmap_2d_node.cpp
- nav2_costmap_2d/src/costmap_2d_publisher.cpp
- nav2_costmap_2d/src/costmap_2d_ros.cpp
- nav2_costmap_2d/src/footprint.cpp
- nav2_costmap_2d/src/layer.cpp
This PR addresses changes to get the Costmap2DROS class fully functional in ROS2. There are dependencies on dynamic parameters and callbacks which have been addressed in PR #196.
> Costmap2DROS fixes 

- nav2_costmap_world_model/include/nav2_costmap_world_model/costmap_world_model.hpp
- nav2_costmap_world_model/src/costmap_world_model.cpp
After merging PR #222, master became broken due to a previous PR #138 using an outdated function signature. This PR fixes this problem
> fix broken build with nav2_costmap_world_model

- tools/ros2_dependencies.repos
One line change to repos file to update gazebo_ros_pkgs to ros2 branch
> Update gazebo_ros_pkgs branch to ros2

- nav2_util/src/costmap.cpp
> adding warning when lethal threshold is outside expected range

- nav2_bringup/launch/core.launch.py
- nav2_controller/dwb_core/src/dwb_core.cpp
- nav2_controller/dwb_plugins/include/dwb_plugins/kinematic_parameters.h
- nav2_controller/dwb_plugins/src/kinematic_parameters.cpp
- nav2_controller/nav2_controller_dwb/include/nav2_controller_dwb/dwb_controller.hpp
- nav2_controller/nav2_controller_dwb/src/dwb_controller.cpp
- nav2_controller/nav2_controller_dwb/src/main.cpp
- nav2_costmap_2d/plugins/static_layer.cpp
- nav2_costmap_2d/src/costmap_2d_ros.cpp
This change gets the robot moving using the DWB controller. There are some hacky workarounds that should addressed - maybe before this change can go into master, however, I'm adding the PR to give everyone a chance to start playing with it.
This change depends on #196 #222 so can't go in until those go into master. They are merged into this PR branch right now, so you can pull the branch and have everything you need to get the robot moving. I'll rebase and clean up the branch after they go in.
> Integrate costmap with DWB- Make robot move

- nav2_msgs/README.md
I figure it doesnt hurt to give folks a little bit of help in the nav2_msgs readme
> nav2_msgs readme

- nav2_world_model/CMakeLists.txt
- nav2_world_model/include/nav2_world_model/world_model.hpp
- nav2_world_model/package.xml
- nav2_world_model/src/main.cpp
- nav2_world_model/src/world_model.cpp
- navigation2/package.xml
The original idea was that we might have different world model implementations. However, as it turns out, we will likely only have the one implementation that evolves over time. So, we don't necessarily want to emphasize that the current/default implementation is costmap-based, but want to allow for other representations going forward. Hence the name change.
This doesn't preclude alternative implementations, but the way. Just what we're naming this one.
> Rename the costmap_world_model

- nav2_dwb_controller/dwb_controller/include/dwb_controller/dwb_controller.hpp
- nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp
- nav2_dwb_controller/dwb_controller/src/main.cpp
#242 undoes some of the changes introduced in #235.
This PR restores the missing changes. This change is required to make
the robot move.
> Fixing merge issues that break DWB.

- nav2_dwb_controller/nav_2d_utils/package.xml
- navigation2/package.xml
---
| Ticket(s) this addresses   | #99 |
| Primary platform tested on | N/A |
--- 
* resolving some of the rosdep keys toget successful build farm
--- 
* Finish rest of the keys
---
> Bloom dep resolve

- nav2_amcl/package.xml
- nav2_costmap_2d/package.xml
| Primary OS tested on | None |
| Primary platform tested on | None |
--- 
* I've never understood amcl well enough to maintain it, and nav2_costmap_2d is not my creation.
---
> Remove Davidvlu from amcl and costmap packages

- doc/BUILD.md
- tools/build_all.sh
- tools/initial_ros_setup.sh
- tools/ros1_dependencies.repos.melodic
---
| Ticket(s) this addresses   | #287  |
--- 
* removed all ros1 dependencies (vcs, build)
---
> remove ros1

- nav2_amcl/CMakeLists.txt
- nav2_amcl/package.xml
- nav2_amcl/src/amcl_node.cpp
- nav2_amcl/src/amcl_node.hpp
---
| Ticket(s) this addresses   | (#209 ) |
| Primary platform tested on | (HP Desktop) |
--- 
- created `initAmclParams` and moved all the parameters from constructor to `initAmclParams`
- Enabled dynamic reconfigure option to be able to change parameter values dynamically
- Removed the `runFromBag` function.
- Since currently we don't have parameter server, I disabled `updatePoseFromServer` method and opened ticket #290 to address this issue.  
--- 
---
We need to address #290 which is important for some applications.
> AMCL: Enabling dynamic reconfigure #209

- nav2_amcl/src/amcl_node.hpp
---
| Ticket(s) this addresses   | NA|
| Primary platform tested on | HP Desktop |
--- 
--- 
- Removed unused codes from amcl header file.
> Cleaned amcl_node header file

- nav2_costmap_2d/CMakeLists.txt
- nav2_costmap_2d/include/nav2_costmap_2d/voxel_layer.hpp
- nav2_costmap_2d/package.xml
- nav2_costmap_2d/plugins/voxel_layer.cpp
- nav2_msgs/CMakeLists.txt
- nav2_msgs/msg/VoxelGrid.msg
- nav2_voxel_grid/CMakeLists.txt
- nav2_voxel_grid/include/nav2_voxel_grid/voxel_grid.hpp
- nav2_voxel_grid/src/voxel_grid.cpp
- nav2_voxel_grid/test/voxel_grid_tests.cpp
---
| Ticket(s) this addresses   | #193  |
| Primary platform tested on | NUC |
--- 
- Adding port of voxel layer
- renamed namespaces in nav2_voxel_grid
- added voxel grid msg in nav2_msgs
- depends on obstacle layer, so only to be merged after PR #318 is merged
--- 
- Everything compiles but I haven't run-time tested the voxel_layer port
- there are no unit/component tests written for voxel layer in the original costmap_2d test code
---
> Voxel Layer Port

- nav2_bringup/launch/nav2_bringup_launch.py
Reverts ros-planning/navigation2#338
Sorry. I forgot this wasn't supposed to go in yet. I saw the two approvals and merged.
> Revert "Remapping fixes for the lastest Turtlebot 3 models"

- .travis.yml
---
| Primary platform tested on | Travis CI |
--- 
Added colcon test to travis for currently passing packages
--- 
More packages need to be added
---
> Enable colcon-test in travis for passing packages

- .github/PULL_REQUEST_TEMPLATE.md
---
| Primary OS tested on | NA |
| Primary platform tested on | NA |
--- 
* Changing the wording of the primary test platform field to better convey that we are interested in knowing what robot the PR has been tested on and whether it was tested in simulation or real hardware.
> Fixing wording in PR template to better clarify intent.

- .travis.yml
- Dockerfile
---
| Ticket(s) this addresses   | #334 |
---
* Before the change `colcon test` in Travis CI run in a wrong environment
* After fixing the environment, skip only packages that have test failures.  There are 11 such packages now
* Adding verbose output to `colcon test-result` so Travis CI log has errors
---
* I'll check issues on package by package basis and see what else I can fix.
---
> Update how 'colcon test' runs in Travis CI

- nav2_bt_navigator/behavior_trees/parallel.xml
- nav2_bt_navigator/behavior_trees/simple_sequential.xml
- nav2_bt_navigator/include/nav2_bt_navigator/bt_navigator.hpp
- nav2_bt_navigator/include/nav2_bt_navigator/navigate_to_pose_behavior_tree.hpp
- nav2_bt_navigator/src/bt_navigator.cpp
- nav2_bt_navigator/src/navigate_to_pose_behavior_tree.cpp
- nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp
- nav2_navfn_planner/src/navfn_planner.cpp
- nav2_simple_navigator/src/simple_navigator.cpp
- nav2_tasks/include/nav2_tasks/behavior_tree_engine.hpp
- nav2_tasks/include/nav2_tasks/bt_action_node.hpp
- nav2_tasks/include/nav2_tasks/compute_path_to_pose_action.hpp
- nav2_tasks/include/nav2_tasks/follow_path_action.hpp
- nav2_tasks/include/nav2_tasks/rate_controller_node.hpp
- nav2_tasks/include/nav2_tasks/task_client.hpp
- nav2_tasks/include/nav2_tasks/task_server.hpp
- nav2_tasks/src/behavior_tree_engine.cpp
* Run planning and control in parallel using the BtNavigator
* Read the BT XML from an external file to facilitate easy updates of the BT
* Introduce a parameter to the BtNavigator to specify the BT XML file to use
* Add a BT XML file that implements recovery behaviors
> Parallel planning and control

- nav2_amcl/CMakeLists.txt
- nav2_amcl/include/nav2_amcl/amcl_node.hpp
- nav2_amcl/package.xml
- nav2_amcl/src/amcl_node.cpp
- nav2_amcl/src/main.cpp
- nav2_amcl/test/integration/test_localization_node.cpp
---
| Ticket(s) this addresses   | NA|
| Primary OS tested on |Ubuntu 18.04|
|Robotic platform tested on |HP Desktop |
---
---
- Moved amcl_node header file to include directory
- Updated amcl package.xml 
- Updated amcl CMakeLists to export dependencies
> Added include directory to amcl

- nav2_costmap_2d/CMakeLists.txt
- nav2_costmap_2d/src/costmap_2d_cloud.cpp
- nav2_costmap_2d/src/costmap_2d_markers.cpp
- nav2_voxel_grid/include/nav2_voxel_grid/voxel_grid.hpp
---
| Ticket(s) this addresses   | #326  |
| Primary OS tested on |Ubuntu|
--- 
* ported the last 2 visualization nodes in costmap 2d
--- 
* This was just a direct port. In the future I hope to put into classes and have those classes utilized in the voxel_layer itself
> Port voxel grid, 2D markers and 2D cloud to ROS2

- nav2_amcl/package.xml
- nav2_bringup/package.xml
- nav2_bt_navigator/package.xml
- nav2_costmap_2d/package.xml
- nav2_dwb_controller/costmap_queue/package.xml
- nav2_dwb_controller/dwb_controller/package.xml
- nav2_dwb_controller/dwb_core/package.xml
- nav2_dwb_controller/dwb_critics/package.xml
- nav2_dwb_controller/dwb_msgs/package.xml
- nav2_dwb_controller/dwb_plugins/package.xml
- nav2_dwb_controller/nav2_dwb_controller/package.xml
- nav2_dwb_controller/nav_2d_msgs/package.xml
- nav2_dwb_controller/nav_2d_utils/package.xml
- nav2_dynamic_params/package.xml
- nav2_map_server/package.xml
- nav2_mission_executor/package.xml
- nav2_msgs/package.xml
- nav2_navfn_planner/package.xml
- nav2_robot/package.xml
- nav2_simple_navigator/package.xml
- nav2_system_tests/package.xml
- nav2_tasks/package.xml
- nav2_util/package.xml
- nav2_voxel_grid/package.xml
- nav2_world_model/package.xml
- navigation2/package.xml
Hi, please approve ASAP so I can mess with bloom for Crystal
> bump versions

- nav2_system_tests/maps/map_circular.yaml
- nav2_system_tests/src/localization/test_localization_launch.py
- nav2_system_tests/src/localization/test_localization_node.cpp
- nav2_system_tests/src/planning/CMakeLists.txt
- nav2_system_tests/src/planning/planner_tester.cpp
---
---
---
- Fixed nav2_system_tests linter issues
> Fixing nav2_system_tests linter issues

- .travis.yml
- nav2_util/include/nav2_util/angleutils.hpp
- nav2_util/src/costmap.cpp
| Ticket(s) this addresses   | Resolves #219. Partially addresses #334 |
---
* Fixes uncrustify issues in nav2_utils
* Verifies copyright test is disabled.
* Enables nav2_utils testing in travis.
> Make nav2_utils pass colcon test.

- nav2_tasks/include/nav2_tasks/service_client.hpp
---
| Ticket(s) this addresses   | (#426 ) |
---
---
- Added optional timeout to `service_client` addressing issue #426.
> adding timeout to service_client

- nav2_amcl/CMakeLists.txt
- nav2_amcl/include/nav2_amcl/amcl_node.hpp
- nav2_amcl/src/amcl_node.cpp
- nav2_amcl/src/main.cpp
---
| Ticket(s) this addresses   | (#339 ) |
| Primary OS tested on | (Ubuntu 18/04) |
---
---
- Re-enabling message filter in AMCL and removing all the workarounds.
> Amcl: enable msg filter

- nav2_amcl/include/nav2_amcl/amcl_node.hpp
- nav2_amcl/src/amcl_node.cpp
---
| Ticket(s) this addresses   | (NA) |
---
---
Fixed AMCL linter issue.
> fixed linter issues

- nav2_amcl/src/amcl_node.cpp
- nav2_bringup/config/nav2_default_view.rviz
- nav2_costmap_2d/plugins/static_layer.cpp
- nav2_map_server/src/occ_grid_loader.cpp
- nav2_tasks/include/nav2_tasks/map_service_client.hpp
---
| Ticket(s) this addresses   | #197 |
| Robotic platform tested on | simulation|
---
Changes `/occ_grid` topic to `/map` to be consistent with ROS Navigation.
> Change /occ_grid topic to /map for ROS compatibility

- nav2_tasks/CMakeLists.txt
- nav2_tasks/include/nav2_tasks/is_stuck_condition.hpp
- nav2_tasks/package.xml
Fixed a bug that causes the robot to run two consecutive recovery runs.
Also made a few simplifications to the code.
> Simplifying is_stuck condition detection

- navigation2/package.xml
---
| Robotic platform tested on | NA  |
---
* We were missing a couple of new packages in the metapackage. I've added those. They should be there for the release.
* I removed the system test package, because that doesn't seem like something we want getting installed by default with the nav stack.
* removed incorrect maintainer email address.
---
> Adding missing packages to metapackage

- nav2_motion_primitives/include/nav2_motion_primitives/motion_primitive.hpp
---
Attempting to fix the build farm CI in #473
> Fix motion primitives CI fail

- nav2_system_tests/CMakeLists.txt
- nav2_system_tests/src/planning/CMakeLists.txt
- nav2_system_tests/src/planning/planner_tester.cpp
- nav2_system_tests/src/planning/planner_tester.hpp
- nav2_system_tests/src/planning/test_planner_node.cpp
- nav2_util/src/costmap.cpp
Global Planner tests now pass `colcon test`.
> Enabling global planner tester

- .travis.yml
| Robotic platform tested on | Docker |
---
Enabled tests for:
* nav2_dynamic_params
* nav2_map_server
* nav2_navfn_planner
* nav2_robot
* nav2_system_tests
I think system_tests is only passing because everything is commented out, but it's still worth enabling IMHO.
> More tests are passing. Enabling them in Travis.

- nav2_navfn_planner/src/navfn_planner.cpp
---
| Ticket(s) this addresses   | #494  |
| Robotic platform tested on | gazebo simulation of turtlebot) |
---
* Reduced marker size and duration
> Adjusted path endpoint markers size and duration

- .travis.yml
Adding @crdelsey and removing @bpwilcox from the travis email notification list.
> Updating travis build email list.

- nav2_motion_primitives/include/nav2_motion_primitives/back_up.hpp
- nav2_motion_primitives/include/nav2_motion_primitives/motion_primitive.hpp
- nav2_motion_primitives/src/back_up.cpp
- nav2_tasks/include/nav2_tasks/back_up_action.hpp
---
| Ticket(s) this addresses   | #380 |
| Primary OS tested on | Ubuntu 18.04|
| Robotic platform tested on |gazebo simulation of  Turtlebot |
---
- This method is not based on any control theory and overshoot is expected to happen
- If the given distance is positive, robot moves in +x direction. If the given distance is negative, robot moves in -x direction
- Deleted time based method, since its no longer required
- Added loop rate to motion_primitives
---
---
> Implemented Backup by a given distance 

- .travis.yml
- README.md
Along with deploying versions as zips, we can add this to the mix so that people can docker pull the latest software or a specific tagged release that's available as a deb in apt
to be squash merged
> uploading and tagging docker images to pull

- .travis.yml
Addresses issue I noticed where the image we built doesnt match the push repo name. It may work but it's good to be explicit and one of those things you can only test after being merged. Master is still failing due to a system test failure
> tag docker container so it registers to the repo

- nav2_bringup/launch/nav2_params.yaml
- nav2_costmap_2d/plugins/obstacle_layer.cpp
---
| Ticket(s) this addresses   | #544 |
| Robotic platform tested on | gazebo simulation of turtlebot |
---
* Some important code was commented out in the obstacle layer by mistake
* Changed params to use obstacle layer by default.
> Enabling dynamic obstacle detection

- nav2_costmap_2d/package.xml
- nav2_dwb_controller/costmap_queue/CMakeLists.txt
- nav2_dwb_controller/costmap_queue/package.xml
- nav2_dwb_controller/dwb_controller/CMakeLists.txt
- nav2_dwb_controller/dwb_controller/package.xml
| Ticket(s) this addresses   | NA  |
| Robotic platform tested on | nav2_system_test |
---
* Removed boost and pcl dependencies that weren't used.
> Removing unneeded dependencies.

- nav2_motion_primitives/README.md
Updated the `nav2_motion_primitives` documentation.
> Motion Primitives Readme

- nav2_tasks/include/nav2_tasks/bt_action_node.hpp
* In debugging the BT segfault issue, I discovered that the BT library now has a Coroutine-based base class for long-running actions and that this is the recommended class to use for ROS Actions. So, I've switched to use this as the base class instead. 
* This may or may not fix the segfault issue, but it is a chance we should make as it is the recommended way for ROS Action-like behavior and uses fewer threads.
> Use the new Coroutine-based BTActionNode base class 

- tools/run_test_suite.bash
---
* Despite all my efforts, I've failed to get the dyanmic_params test to pass 100% of the time in CI.
* Till I've got more time for this, I'm giving up and just retrying the test like we do the system tests. :-(
> Adding retries to dynamic params test

- Dockerfile.crystal
- nav2_bringup/launch/nav2_params.yaml
- nav2_costmap_2d/include/nav2_costmap_2d/inflation_layer.hpp
- nav2_costmap_2d/plugins/inflation_layer.cpp
- nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp
- nav2_dwb_controller/dwb_critics/include/dwb_critics/oscillation.hpp
- nav2_dwb_controller/dwb_critics/src/oscillation.cpp
- nav2_system_tests/params/nav2_params.yaml
This consists of various bug fixes and workarounds on `master` that seemed worthwhile to merge to `crystal-devel`.
This PR will hopefully kick of the ROS build farm CI to verify everything still builds ok in crystal.
> Fixes and workarounds for crystal-devel 0.1.6

- nav2_system_tests/CMakeLists.txt
- nav2_system_tests/src/planning/planner_tester.cpp
- nav2_system_tests/src/planning/planner_tester.hpp
- nav2_system_tests/src/planning/test_planner_node.cpp
Fixed some linter fails, cleaned ROS logging, removed code related to parsing yaml as it's not currently suppported.
> Improvements to Global Planner testing

- nav2_amcl/src/amcl_node.cpp
---
| Ticket(s) this addresses   | (fixes #591 ) |
---
Checking for NAN in AMCL before publishing pose.
> Checking for NAN before publishing AMCL pose

- nav2_bringup/launch/nav2_params.yaml
| Robotic platform tested on | TB2 |
---
* Adding to yaml file some parameters I find I felt the need to tweak.
* The only actual change to the parameters is the ObstacleFootprint.scale. The others are just restating their default values.
> Param tweaks

- nav2_dwb_controller/dwb_core/src/dwb_core.cpp
---
* Neither the goal oriented critics, nor the path oriented critics do a very good job of getting the robot to follow the plan provided by the global planner. This PR changes the goal pose to be a short distance away on the path rather than at the very end of the path. This has the result of encouraging the robot to follow the plan rather than let DWB decide for itself how it wants to get to the goal.
* This PR takes care of the prune_plan functionality already in DWB to prune away all parts of the plan that are beyond the prune_distance from the robot. This leaves the furthest point on the plan that's within the …
> Prune start and end of plan

- nav2_bringup/launch/nav2_bringup_2nd_launch.py
- nav2_bringup/launch/nav2_bringup_launch.py
Reverts ros-planning/navigation2#632
It's too soon. We need to work out some more issues with this tree before it goes in master.
> Revert "Add parallel planning and obstacle layer."

- nav2_map_server/CMakeLists.txt
- nav2_map_server/include/nav2_map_server/map_server.hpp
- nav2_map_server/include/nav2_map_server/occ_grid_loader.hpp
- nav2_map_server/package.xml
- nav2_map_server/src/main.cpp
- nav2_map_server/src/map_server.cpp
- nav2_map_server/src/occ_grid_loader.cpp
- nav2_map_server/test/component/test_occ_grid_node.cpp
- nav2_map_server/test/unit/test_occ_grid.cpp
* Port the map server to lifecycle nodes
* A bit of cleanup/reorg on the parameter-related code
> Port the map server to lifecycle nodes

- nav2_world_model/CMakeLists.txt
- nav2_world_model/include/nav2_world_model/world_model.hpp
- nav2_world_model/package.xml
- nav2_world_model/src/main.cpp
- nav2_world_model/src/world_model.cpp
* Port the world model to lifecycle nodes
> Port the world model lifecycle to lifecycle nodes

- nav2_navfn_planner/CMakeLists.txt
- nav2_navfn_planner/include/nav2_navfn_planner/navfn.hpp
- nav2_navfn_planner/include/nav2_navfn_planner/navfn_planner.hpp
- nav2_navfn_planner/package.xml
- nav2_navfn_planner/src/main.cpp
- nav2_navfn_planner/src/navfn.cpp
- nav2_navfn_planner/src/navfn_planner.cpp
* Port the global planner to lifecycle nodes
> Port the navfn global planner to lifecycle nodes

- nav2_simple_navigator/CMakeLists.txt
- nav2_simple_navigator/include/nav2_simple_navigator/simple_navigator.hpp
- nav2_simple_navigator/package.xml
- nav2_simple_navigator/src/main.cpp
- nav2_simple_navigator/src/simple_navigator.cpp
* Ported the Simple Navigator to ROS2 actions.
> Port the simple navigator to ROS2 actions

- tools/ros2_dependencies.repos
| Robotic platform tested on | Gazebo TB3 |
---
* These upstream repos have taken the fixes I provided and build against the latest ROS2 code now. This change uses the official repos instead of my forks.
> Restoring proper upstream repos.

- navigation2/package.xml
* Update and sort the package list to account for the recent changes for lifecycle nodes
> Update the Navigation2 meta package for lifecycle changes

- nav2_msgs/CMakeLists.txt
- nav2_msgs/action/BackUp.action
- nav2_msgs/action/ComputePathToPose.action
- nav2_msgs/action/ExecuteMission.action
- nav2_msgs/action/FollowPath.action
- nav2_msgs/action/NavigateToPose.action
- nav2_msgs/action/Spin.action
- nav2_msgs/package.xml
- nav2_util/include/nav2_util/simple_action_server.hpp
- nav2_util/test/CMakeLists.txt
- nav2_util/test/test_actions.cpp
* Patch a few things so that the lifecycle branch builds. 
* The action code has already been reviewed as part of another PR, but was incorrectly submitted to master (and subsequently reverted; Oops). Included instead in this patch.
> Patch the build for the lifecycle branch

- nav2_rviz_plugins/include/nav2_rviz_plugins/navigation_dialog.hpp
- nav2_rviz_plugins/src/nav2_panel.cpp
- nav2_rviz_plugins/src/navigation_dialog.cpp
- nav2_simple_navigator/src/simple_navigator.cpp
- nav2_tasks/include/nav2_tasks/bt_action_node.hpp
- nav2_util/test/test_actions.cpp
* The ROS2 action client interface has changed to allow for providing callbacks for result, feedback, etc. at the point of calling async_send goal using SendGoalOptions. This PR adapts to the recent changes.
* Cleans up some dead code in the navigation_dialog.
> Adapt to recent changes with the ROS2 Action client interface

- nav2_bt_navigator/src/bt_navigator.cpp
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp
- nav2_costmap_2d/plugins/static_layer.cpp
- nav2_costmap_2d/plugins/voxel_layer.cpp
- nav2_costmap_2d/src/costmap_2d_cloud.cpp
- nav2_costmap_2d/src/costmap_2d_markers.cpp
- nav2_costmap_2d/src/costmap_2d_publisher.cpp
- nav2_costmap_2d/src/costmap_2d_ros.cpp
- nav2_dwb_controller/nav_2d_utils/include/nav_2d_utils/odom_subscriber.hpp
- nav2_lifecycle_manager/src/lifecycle_manager_client.cpp
- nav2_map_server/src/map_generator.cpp
- nav2_map_server/src/occ_grid_loader.cpp
- nav2_robot/src/robot.cpp
- nav2_robot/test/test_robot_class.cpp
- nav2_simple_navigator/src/simple_navigator.cpp
- nav2_system_tests/src/localization/test_localization_node.cpp
- nav2_tasks/include/nav2_tasks/is_stuck_condition.hpp
* Adapt to changes in the ROS2 API regarding QoS settings having moved from rmw to rcl
* Remove a bit of code that was inadvertantly included previously (related to rate monitoring)
* This PR doesn't include AMCL since that module us currently under review. Once that PR is done, I'll open a separate, smaller PR just for the QoS changes w/ AMCL
> Adapt to recent ROS2 API changes for QoS settings

- nav2_experimental/README.md
> adding warning readme to the nav2_experimental package

- nav2_robot/README.md
- nav2_util/README.md
- nav2_voxel_grid/README.md
- nav2_world_model/README.md
---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/176 |
| Primary OS tested on | N/A |
---
* Filled out the last packages requiring readmes from ticket #176 (wow, that's an old one).
---
> Last readmes

- nav2_amcl/include/nav2_amcl/amcl_node.hpp
- nav2_amcl/src/amcl_node.cpp
- nav2_costmap_2d/include/nav2_costmap_2d/clear_costmap_service.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d.hpp
- nav2_costmap_2d/src/observation_buffer.cpp
- nav2_dwb_controller/dwb_core/src/dwb_core.cpp
- nav2_dwb_controller/dwb_critics/include/dwb_critics/map_grid.hpp
- nav2_dynamic_params/include/nav2_dynamic_params/dynamic_params_client.hpp
- nav2_motion_primitives/src/spin.cpp
- nav2_tasks/include/nav2_tasks/task_server.hpp
- nav2_util/CMakeLists.txt
- nav2_util/src/CMakeLists.txt
- nav2_util/src/map/CMakeLists.txt
- nav2_util/src/map_loader/CMakeLists.txt
- nav2_util/src/motion_model/CMakeLists.txt
- nav2_util/src/pf/CMakeLists.txt
- nav2_util/src/pf/eig3.c
- nav2_util/src/sensors/CMakeLists.txt
---
| Clang version | clang version 6.0.0-1ubuntu2 |
---
* Fixing miscellaneous errors detected by clang. Many real defects. Some just unused variables.
> Cleaning up warnings and errors detected by clang.

- nav2_amcl/CMakeLists.txt
- nav2_amcl/include/nav2_amcl/amcl_node.hpp
- nav2_amcl/package.xml
- nav2_amcl/src/amcl_node.cpp
- nav2_amcl/src/main.cpp
* Port AMCL to lifecycle nodes
* Extensive reorganization in order to cleanly work with the lifecycle node callback structure
> Port AMCL to lifecycle nodes

- nav2_dwb_controller/nav_2d_utils/include/nav_2d_utils/odom_subscriber.hpp
> Bug fix in DWB rotation critic

- nav2_tasks/include/nav2_tasks/bt_action_node.hpp
- nav2_tasks/include/nav2_tasks/goal_reached_condition.hpp
- nav2_tasks/include/nav2_tasks/is_localized_condition.hpp
---
| Robotic platform tested on | (TB3 Gazebo simulation) |
---
---
-Port GoalReached BT node to lifecycle
-Port IsLocalizedCondition BT node to lifecycle
> Port goalReachedCondition node and isLocalizedCondition node to lifecycle

- nav2_bt_navigator/behavior_trees/recovery_test.xml
- nav2_costmap_2d/include/nav2_costmap_2d/inflation_layer.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/layer.hpp
- nav2_costmap_2d/plugins/inflation_layer.cpp
- nav2_costmap_2d/plugins/obstacle_layer.cpp
- nav2_costmap_2d/plugins/static_layer.cpp
- nav2_costmap_2d/plugins/voxel_layer.cpp
- nav2_costmap_2d/src/layer.cpp
- nav2_costmap_2d/test/integration/costmap_tests_launch.py
- nav2_costmap_2d/test/integration/obstacle_tests.cpp
Solution to #714 
Future Tasks:
- We might need to do something different for the Obstacle and Voxel plugins as these don't execute onInitialize() upon reset()  #757.
> Fixed costmap plugins parameter re-declaration bug

- nav2_bringup/launch/nav2_bringup_launch.py
- nav2_bringup/launch/nav2_default_view.rviz
- Updating the RVIZ (nav2) default config file (.rviz) to show the new navigation panel (for starting/pausing/resuming) and the navigation goal plugin (for setting the destination), plus some other minor display improvements.
- Providing the configuration file at launch time, once RVIZ loads, it's all set to start navigation.
> Updating the RVIZ default view

- nav2_bringup/launch/nav2_bringup_launch.py
Fixes extra brace syntax error in launch file
> Fix launch bringup syntax

- nav2_system_tests/CMakeLists.txt
---
| Robotic platform tested on | () |
---
-Enabling localization test to make sure it is passing CI. 
-We should merge this once we have the fixes for CI
> Enable localization test

- nav2_lifecycle_manager/src/lifecycle_manager.cpp
- nav2_lifecycle_manager/src/lifecycle_manager_client.cpp
- nav2_tasks/include/nav2_tasks/bt_action_node.hpp
Also checked nav2_bt_navigator and nav2_robot, which are clean.
> Run lint tools on nav2_lifecycle_manager and nav2_tasks

- nav2_bringup/launch/nav2_default_view.rviz
| Ticket(s) this addresses   | #814 |
---
- update topic names for rviz visualization
> update global plan and footprint topic names in rviz

- nav2_costmap_2d/CMakeLists.txt
- nav2_costmap_2d/include/nav2_costmap_2d/obstacle_layer.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/testing_helper.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/voxel_layer.hpp
- nav2_costmap_2d/plugins/inflation_layer.cpp
- nav2_costmap_2d/plugins/obstacle_layer.cpp
- nav2_costmap_2d/plugins/static_layer.cpp
- nav2_costmap_2d/plugins/voxel_layer.cpp
- nav2_costmap_2d/src/clear_costmap_service.cpp
- nav2_costmap_2d/src/costmap_2d_cloud.cpp
- nav2_costmap_2d/src/costmap_2d_publisher.cpp
- nav2_costmap_2d/src/costmap_2d_ros.cpp
- nav2_costmap_2d/src/footprint.cpp
- nav2_costmap_2d/src/layer.cpp
- nav2_costmap_2d/src/observation_buffer.cpp
- nav2_costmap_2d/test/integration/footprint_tests.cpp
- nav2_costmap_2d/test/integration/inflation_tests.cpp
- nav2_costmap_2d/test/unit/array_parser_test.cpp
| Ticket(s) this addresses   | #535 |
- Re-enables and passes warnings in nav2_costmap_2d
> Re-enable nav2_costmap_2d warnings

- nav2_costmap_2d/plugins/static_layer.cpp
- nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp
- nav2_navfn_planner/src/navfn_planner.cpp
- nav2_world_model/src/world_model.cpp
- To clean the user terminal, removed unnecessary info messages and replaced them with Debug. 
- These messages are meant for debugging purposes and they don't provide valuable information to the user.
> Removed unnecessary info messages

- nav2_amcl/src/amcl_node.cpp
- nav2_costmap_2d/plugins/static_layer.cpp
- nav2_map_server/src/map_server.cpp
- nav2_map_server/src/occ_grid_loader.cpp
---
* Addresses build errors when `-Werror=catch-value=` is specified.
* Tested with: `gcc (GCC) 9.1.1 20190503 (Red Hat 9.1.1-1)`
> Catch polymorphic exceptions by reference

- nav2_util/src/map/map_cspace.cpp
Fixed nav2_util uncrustify issue.
> Fixed nav2_util uncrustify issue

- nav2_bt_navigator/src/bt_navigator.cpp
- nav2_util/include/nav2_util/simple_action_server.hpp
Addressing #870. 
---
* Added `activate()` and `deactivate()` to action server.
---
* Action server should also be enabled and disabled in Navfn and DWB.
> Addressing bt_navigator crash

- nav2_amcl/src/amcl_node.cpp
- nav2_map_server/src/occ_grid_loader.cpp
---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/659 |
| Primary OS tested on | (N/A |
---
* Catch exception by references across stack
* print exceptions as needed
---
---
> catch exceptions by reference and print relevent information

- nav2_amcl/package.xml
- nav2_costmap_2d/package.xml
does what it says so we're not blasting unwilling participants  #372
> removing old maintainers from navigation1

- nav2_recoveries/include/nav2_recoveries/recovery.hpp
Fixes #939 along with #947 
| Ticket(s) this addresses   | #939 |
---
- stop robot when cancel is requested during recovery
> Stop robot on cancel in recovery

- tools/build_all.sh
- tools/initial_ros_setup.sh
---
| Robotic platform tested on ||
---
* updated build_all and initial ros setup scripts.
* it was checking if the ros2 distrubution variable is set to bouncy.
* now it checks if it is dashing.
---
* I am not sure if we need to do this check at all. I will test the scripts without checking the ROS2_DISTRO variable. If it doesn't cause any issues during build, I will do another commit for the scripts.
---
> Build scripts update for ROS2 Dashing

- nav2_bringup/launch/nav2_default_view.rviz
Signed-off-by: Mikael Arguedas <mikael.arguedas@gmail.com>
---
| Robotic platform tested on | Gazebo simulation of Turtlebot3 |
---
AMCL publishes it's particlecloud as Unreliable/SensorDataQoS.
https://github.com/ros-planning/navigation2/blob/675574f382c015d9901f81dc6761fcf17a67986a/nav2_amcl/src/amcl_node.cpp#L1098
So the `Unreliable` box need to be checked for RViz to receive and display the messages.
> amcl particlecloud is best effort

- .github/PULL_REQUEST_TEMPLATE.md
> removing extra PR template field in application no one uses

- nav2_bt_navigator/src/bt_navigator.cpp
---
| Ticket(s) this addresses   | #1008  |
---
* added deprecation warning for topic based navigation, giving folks in the community a few weeks (months?) to speak up if they have a problem with it
---
---
> adding deprecation warning for topic-based goal navigation

- nav2_bringup/launch/nav2_bringup_launch.py
- nav2_bringup/launch/nav2_simulation_launch.py
---
* Providing the correct path to the default map on `nav2_bringup_launch.py`.
> Provide correct path to default map on `bringup_launch`.

- nav2_costmap_2d/test/integration/CMakeLists.txt
- nav2_map_server/test/component/CMakeLists.txt
- nav2_map_server/test/test_launch_files/map_server_node.launch.py
- nav2_recoveries/src/spin.cpp
- nav2_util/include/nav2_util/lifecycle_node.hpp
- nav2_world_model/src/world_model.cpp
Fixing linter failures on master.
I'm just going to merge this one as soon as it passes CI, without waiting for review unless you object quickly :-)
> Fixing linter failures introduced in master

- nav2_bt_navigator/src/bt_navigator.cpp
- nav2_system_tests/src/system/test_system_node.py
Reflecting the fact move base doesnt exist and this ticket in RVIZ https://github.com/ros2/rviz/issues/444
> changing pose topics to goal_pose

- nav2_bt_navigator/src/bt_navigator.cpp
- nav2_costmap_2d/src/costmap_2d_ros.cpp
- nav2_lifecycle_manager/src/lifecycle_manager.cpp
- nav2_system_tests/src/system/test_system_node.py
- nav2_system_tests/worlds/turtlebot3_ros2_demo.world
- nav2_util/src/lifecycle_node.cpp
- nav2_util/src/node_utils.cpp
---
Fixes system test
- Adds new <argument> tags for --ros-args and -r flags in turtlebot3 world file
- Fixes QoS setting in system test
- Fixes namespace for the "clear costmaps" services
Namespaces may need more looking at for global_costmap topics, didn't do that in this PR as it isn't blocking the system tests
> Fix System tests for new argument parsing

- .circleci/config.yml
- Dockerfile
- Dockerfile.full_ros_build
- Dockerfile.release_branch
- nav2_system_tests/src/system/README.md
Context: https://github.com/ros2/ros_buildfarm_config/pull/38#issuecomment-530117611
> Remove COLCON_IGNORE from nav2_system_tests

- nav2_costmap_2d/src/costmap_2d_ros.cpp
Adds ros args flag to NodeOptions on costmap.
> add ros args flag to costmap

- nav2_core/include/nav2_core/global_planner.hpp
- nav2_navfn_planner/include/nav2_navfn_planner/navfn_planner.hpp
- nav2_navfn_planner/src/navfn_planner.cpp
- nav2_planner/src/planner_server.cpp
Turns out the issues were from other things that I had to fix along the way. All good now
> move costmap in nav2_planner to shared_ptr and node to rclcpp lifecycle

- nav2_bt_navigator/src/bt_navigator.cpp
> Rematch dashing topics with rviz

- doc/use_cases/navigation_with_cartographer.md
Navigation 2 with Cartographer documentation.
#1134
> Navigation 2 with SLAM Documentation

- nav2_bt_navigator/src/bt_navigator.cpp
---
---
Fix CI failing due to a linter error.
> Fix linter errors

- nav2_core/include/nav2_core/recovery.hpp
Changed "GlobalPlanner" to "Recovery" in file recovery.hpp
---
| Ticket(s) this addresses   | #1170 |
---
* Fixed a documentation typo in nav2_core/include/nav2_core/recovery.hpp
---
> Fixed documentation typo.

- .circleci/config.yml
- Dockerfile
WIP, waiting on:
* https://github.com/colcon/colcon-ros/pull/79
* https://github.com/osrf/docker_images/pull/323
> Use ament index to resolve rosdep install

- doc/use_cases/navigation_with_slam.md
- nav2_bringup/bringup/README.md
- Updated Navigation 2 Bringup documentation
- Renamed the Navigation 2 with Slam tutorial
> Documentation Updates - Bringup, Nav 2 with Slam

- nav2_experimental/nav2_rl/nav2_turtlebot3_rl/coach_navigator_ddpg.py
- nav2_experimental/nav2_rl/nav2_turtlebot3_rl/navigation_task_env.py
- nav2_experimental/nav2_rl/nav2_turtlebot3_rl/navigator_ddpg.py
- nav2_experimental/nav2_rl/nav2_turtlebot3_rl/setup.py
- nav2_experimental/nav2_rl/nav2_turtlebot3_rl/turtlebot3_environment.py
---
| Robotic platform tested on | (TB3 in Gazebo) |
---
---
Making the environment to work with the coach library.
> Integrate coach

- nav2_bringup/launch/nav2_navigation_launch.py
- nav2_bringup/launch/nav2_params.yaml
- nav2_costmap_2d/include/nav2_costmap_2d/static_layer.hpp
- nav2_costmap_2d/plugins/static_layer.cpp
- nav2_costmap_2d/src/costmap_2d_ros.cpp
- nav2_costmap_2d/src/costmap_layer.cpp
This is the same change as PR #1057, which is in master.
This is a simple enough change to back port and it was requested for integrating into the dev kit.
> Backport Nav with SLAM to Dashing

- nav2_lifecycle_manager/src/lifecycle_manager.cpp
One thing needed to be changed for parameter-less successful bringup
> Adding recoveries lifecycle server to defaults

- nav2_bringup/bringup/CMakeLists.txt
- nav2_bringup/bringup/launch/nav2_bringup_launch.py
- nav2_bringup/bringup/launch/nav2_localization_launch.py
- nav2_bringup/bringup/launch/nav2_multi_tb3_simulation_launch.py
- nav2_bringup/bringup/launch/nav2_navigation_launch.py
- nav2_bringup/bringup/launch/nav2_tb3_simulation_launch.py
- nav2_bringup/bringup/launch/spawn_robot_launch.py
---
| Robotic platform tested on | NA|
---
* Enable linters in nav2_bringup package
* Fix linter failures
> Enable Linters in nav2_bringup package

- nav2_map_server/src/map_saver.cpp
> if no map name given to map saver, add unix timestamp to ensure uniqueness

- nav2_map_server/include/nav2_map_server/map_mode.hpp
- nav2_map_server/include/nav2_map_server/map_saver.hpp
- nav2_map_server/include/nav2_map_server/map_server.hpp
- nav2_map_server/include/nav2_map_server/occ_grid_loader.hpp
Add doxygen documentation to nav2_map_server header files 
---
| Ticket(s) this addresses   | #1256 |
---
* Added relevant doxygen style description to classes and its methods.
---
* Need comments on my documentation.
> Doc map server

- nav2_controller/include/nav2_controller/nav2_controller.hpp
- nav2_controller/include/nav2_controller/progress_checker.hpp
- Add doxygen doc to nav2_controller.hpp
- Add doxygen doc to progress_checker.hpp
---
| Ticket(s) this addresses   | #1256 |
---
* Added doxygen  doc block in nav2_controller header files
---
* Need comments on the doc
> Add doxygen doc to nav2_controller

- nav2_dwb_controller/README.md
- Removed plans which are already been taken care off
---
---
---
> Refactored nav2_dwb_controller README.md

- nav2_bt_navigator/include/nav2_bt_navigator/bt_navigator.hpp
---
| Ticket(s) this addresses   | #1256 |
---
---
* Need feedback!
> Add doxygen doc in nav2_bt_navigator header files

- nav2_planner/include/nav2_planner/planner_server.hpp
---
| Ticket(s) this addresses   | #1256 |
---
---
* Need feedback!
> Add doxygen doc to nav2_planner header file.

- .circleci/config.yml
Context: https://github.com/ros-planning/navigation2/issues/1271
I'm not sure what retry value would be preferred. I just copied what was used in:
https://github.com/ros-planning/navigation2/blob/67a92be87f8a00470313c232b1462d45379273e8/tools/run_test_suite.bash#L22
> Enable retest until passing with limit

- README.md
- sphinx_doc/README.md
---
---
Updating paths to NAV2 documentation website on multiple READMEs.
> Minor updates to documentation paths in READMEs

- nav2_controller/README.md
- nav2_core/README.md
- nav2_core/include/nav2_core/local_planner.hpp
Added a short documentation for nav2_controller, and nav2_core packages since it has none right now.
> nav2_core and nav2_controller short documentation

- tools/run_test_suite.bash
---
| Ticket(s) this addresses   | #1308 |
---
Addressing #1308, tests have been consistently passing on my machine so I think we can enable them.
> Run multi-robot tests on Travis

- nav2_costmap_2d/src/costmap_2d_publisher.cpp
---
| Ticket(s) this addresses   | #1028 |
| Primary OS tested on | Ubuntu) |
---
* Added `count_subscriber()` check before publishing costmap.
---
* I have locally tested it on my system but some unit and integration test might help.
> Add subscriber count checker before publishing costmap.

- nav2_system_tests/package.xml
Remove duplicate exec_depend in `package.xml`
> Remove duplicate exec_depend

- sphinx_doc/howtos/index.rst
- sphinx_doc/howtos/tunning/index.rst
- sphinx_doc/howtos/tunning/params/tunable-params.rst
- sphinx_doc/substitutions.txt
---
| Ticket(s) this addresses   | #951 |
---
Addressing #951: Adding to the documentation site a list of all tunable nav2 parameters.
> Provide a list of all tunable parameters

- nav2_bringup/bringup/rviz/nav2_namespaced_view.rviz
---
| Primary OS tested on | Ubuntu
---
* Change to enable Navigation2 Goal button in rviz
---
* NA
> Add GoalTool to the MultiRobot rviz file

- nav2_bringup/bringup/launch/spawn_tb3_launch.py
- nav2_bringup/nav2_gazebo_spawner/nav2_gazebo_spawner/nav2_gazebo_spawner.py
- nav2_bringup/nav2_gazebo_spawner/package.xml
- nav2_bringup/nav2_gazebo_spawner/setup.cfg
- nav2_bringup/nav2_gazebo_spawner/setup.py
- nav2_bringup/spawn_robot/setup.cfg
- nav2_system_tests/src/system/test_multi_robot_launch.py
#1304 
navigation2 gazebo spawner since robot_spawner is going to be problematic
> robot_spawner -> nav2_gazebo_spawner

- tools/run_sanitizers
| Ticket(s) this addresses   | fixes #850 |
---
* This is a script to run the thread and address sanitizers on the navstack, as described in https://github.com/colcon/colcon-sanitizer-reports/blob/master/README.rst
* I didn't see any serious concerns, but I've uploaded the results to the ticket. #850
* We should run this manually from time to time to see if there are any interesting results.
> Script to run the thread and address sanitizers.

- tools/code_coverage_report.bash
- tools/run_test_suite.bash
---
| Ticket(s) this addresses   | fixes #973 |
| Primary OS tested on | NA |
| Robotic platform tested on | CI |
---
* Add filtering rules to remove any files in the _msg packags, so they don't affect coverage results.
* Also, reduce the number of tests that Travis runs to improve the odds of completing in time.
> Attempt to filter out generated message files from code coverage.

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
- nav2_lifecycle_manager/src/lifecycle_manager_client.cpp
- nav2_recoveries/test/test_recoveries.cpp
---
| Ticket(s) this addresses   | #923 |
---
Addressing #923.
> Use action client (instead of goal handle) to get result

- .travis.yml
- Dockerfile
- Dockerfile.full_ros_build
- tools/ros2_dependencies.repos
Switch dependencies to dashing branches
> Update Dashing ros2_dependencies.repos

- nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager.hpp
- nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager_client.hpp
---
---
* Add doc to nav2_lifecycle_manager
---
* Need review!
* Its kinda hard for me to put into words whats happening in both the classes, so need suggestions for the class brief
> Add doxygen doc in nav2_lifecycle_manager header files

- doc/BUILD.md
---
---
Minor typo fix for broken link
---
> Minor fix for broken link in build.md file

- nav2_behavior_tree/include/nav2_behavior_tree/compute_path_to_pose_action.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/follow_path_action.hpp
- nav2_bt_navigator/README.md
- nav2_bt_navigator/behavior_trees/navigate_w_replanning.xml
- nav2_bt_navigator/behavior_trees/navigate_w_replanning_and_recovery.xml
- nav2_controller/include/nav2_controller/nav2_controller.hpp
- nav2_controller/src/nav2_controller.cpp
- nav2_msgs/action/ComputePathToPose.action
- nav2_msgs/action/FollowPath.action
- nav2_planner/include/nav2_planner/planner_server.hpp
- nav2_planner/src/planner_server.cpp
---
| Ticket(s) this addresses   | #1330  |
---
* changing `properties` for `ids`
* Mostly to open for discussion to get this over the line
---
> planner/controller properties to IDs

- nav2_costmap_2d/include/nav2_costmap_2d/layered_costmap.hpp
- nav2_costmap_2d/src/costmap_2d_ros.cpp
- nav2_costmap_2d/src/layered_costmap.cpp
> adding warning when robot is out of costmap bounds

- nav2_core/include/nav2_core/recovery.hpp
- nav2_recoveries/include/nav2_recoveries/recovery.hpp
- nav2_recoveries/include/nav2_recoveries/recovery_server.hpp
- nav2_recoveries/src/recovery_server.cpp
- nav2_recoveries/test/test_recoveries.cpp
---
| Ticket(s) this addresses   | #1239 |
---
* reduce duplication of subscriber and resources
---
> move collision checker as an input to the configure method of recoveries

- nav2_system_tests/src/updown/test_updown_launch.py
- nav2_system_tests/worlds/turtlebot3_ros2_demo.world
- nav2_system_tests/worlds/turtlebot3_ros2_demo_obstacle.world
#1258 
Changing TB3 from burger to waffle, that we actually modeled and used
> changing TB3 burger to waffle

- doc/design/ROS_COMPARISON.md
- nav2_bringup/bringup/rviz/nav2_default_view.rviz
- nav2_bringup/bringup/rviz/nav2_namespaced_view.rviz
- nav2_bt_navigator/README.md
- nav2_controller/README.md
- nav2_controller/include/nav2_controller/nav2_controller.hpp
- nav2_controller/package.xml
- nav2_controller/src/nav2_controller.cpp
- nav2_core/README.md
- nav2_core/include/nav2_core/controller.hpp
- nav2_dwb_controller/dwb_core/include/dwb_core/dwb_local_planner.hpp
- nav2_dwb_controller/dwb_core/local_planner_plugin.xml
- nav2_dwb_controller/dwb_core/src/dwb_local_planner.cpp
- nav2_system_tests/README.md
---
| Ticket(s) this addresses   | #1325 |
---
* changing all references from Local Planner to Controller outside of DWB
* DWB is ignored because, frankly, its so embedded I can't get rid of it. 
---
> changing references from local planner to controller outside of DWB

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
- nav2_behavior_tree/plugins/action/back_up_action.cpp
- nav2_behavior_tree/plugins/action/compute_path_to_pose_action.cpp
- nav2_behavior_tree/plugins/action/follow_path_action.cpp
- nav2_behavior_tree/plugins/action/navigate_to_pose_action.cpp
- nav2_behavior_tree/plugins/action/random_crawl_action.cpp
- nav2_behavior_tree/plugins/action/spin_action.cpp
- nav2_behavior_tree/plugins/action/wait_action.cpp
- nav2_bt_navigator/src/bt_navigator.cpp
- nav2_controller/src/nav2_controller.cpp
- nav2_experimental/nav2_rl/nav2_turtlebot3_rl/random_crawl_action.py
- nav2_planner/src/planner_server.cpp
- nav2_recoveries/src/recovery_server.cpp
---
| Ticket(s) this addresses   | #1373 |
---
* Fixed cases for FP, CP, NTP, and recoveries
---
Whoop, this is also my 100th PR. Do I win a realsense camera or something now @mkhansen-intel :wink: ?
> Correct CamelCase with snake_case action server names

- nav2_bringup/bringup/launch/nav2_bringup_launch.py
- nav2_bringup/bringup/launch/nav2_navigation_launch.py
- nav2_lifecycle_manager/src/lifecycle_manager.cpp
- nav2_msgs/CMakeLists.txt
- nav2_msgs/action/FollowWaypoints.action
- nav2_rviz_plugins/include/nav2_rviz_plugins/nav2_panel.hpp
- nav2_rviz_plugins/src/nav2_panel.cpp
- nav2_system_tests/CMakeLists.txt
- nav2_system_tests/src/waypoint_follower/CMakeLists.txt
- nav2_system_tests/src/waypoint_follower/README.md
- nav2_system_tests/src/waypoint_follower/test_case_py.launch
- nav2_system_tests/src/waypoint_follower/tester.py
- nav2_waypoint_follower/CMakeLists.txt
- nav2_waypoint_follower/README.md
- nav2_waypoint_follower/include/nav2_waypoint_follower/waypoint_follower.hpp
- nav2_waypoint_follower/package.xml
- nav2_waypoint_follower/src/main.cpp
- nav2_waypoint_follower/src/waypoint_follower.cpp
- navigation2/package.xml
In response to #1327 #803 
This is untested but to continue the discussion on the how I think is best to approach this problem. If we like this, I'll test and make example demos launching from a set of given yaml waypoints
> Nav2 wp follower

- nav2_dwb_controller/README.md
Handles #1316 just giving some more flavor to the readme for DWB.
Also makes some assumptions on the merging of #1377 which I don't think is a controversial topic
> update dwb plugin pkg readme

- .circleci/config.yml
- sphinx_doc/Makefile
---
| Robotic platform tested on |  NA |
---
* This change will cause CircleCI to commit the generated sphinxdocs into the gh-pages branch
* This causes the actual website to be updated.
* This will only happen when a commit is merged to master. All other branches are ignored.
> Enable auto publishing of the docs on the master branch.

- nav2_controller/src/nav2_controller.cpp
- nav2_waypoint_follower/src/waypoint_follower.cpp
---
---
Fixing build error introduced by #1356.
> Fix build error

- nav2_dwb_controller/dwb_plugins/include/dwb_plugins/kinematic_parameters.hpp
- nav2_dwb_controller/dwb_plugins/src/kinematic_parameters.cpp
Signed-off-by: Francisco Martin Rico <fmrico@gmail.com>
---
| Ticket(s) this addresses   | #1455 |
---
* I added the option of changing the speed of the robot at runtime. Actually, this PR lets to change any parameter of the DWB controller
---
> Change robot speed at runtime

- nav2_behavior_tree/plugins/action/navigate_to_pose_action.cpp
- nav2_bt_navigator/src/bt_navigator.cpp
---
| Ticket(s) this addresses   | #1450 |
| ~Primary OS tested on~ |  |
| ~Robotic platform tested on~ |  |
Note: I don't have a platform at hand to test and system tests are failing for me, even on plain `eloquent-devel`.
---
- Fixed inconsistent `NavigateToPose` action names (camel case vs. snake case).
> Use NavigateToPose action name everywhere.

- nav2_system_tests/README.md
- nav2_system_tests/src/updown/README.md
---
| Ticket(s) this addresses   | #1092  |
---
---
Adds documentation for running the `updown` test.
Updown test is not run as part of CI, that could be added, but I think it's a low priority since it won't add coverage
> Add README for Updown test

- nav2_costmap_2d/CMakeLists.txt
- nav2_dwb_controller/dwb_critics/CMakeLists.txt
- nav2_dwb_controller/dwb_plugins/CMakeLists.txt
- nav2_navfn_planner/CMakeLists.txt
- nav2_recoveries/CMakeLists.txt
fixes: https://github.com/ros-planning/navigation2/issues/1480
> store shared files in share/{PROJECT_NAME} rather than share/

- nav2_system_tests/src/system/tester_node.py
- nav2_system_tests/src/waypoint_follower/tester.py
---
| Ticket(s) this addresses   | #1514 |
---
* Attempting to fix nightly builds
* Only Connext and Cyclone are failing while shutting down from a success due to an unhandled exception 
---
> fixing nightly builds with exception handling

- nav2_bt_navigator/src/bt_navigator.cpp
---
| Ticket(s) this addresses   | #1523 |
---
* Provide a reasonable set of default plugin libs for cli run commands
> adding full list of default plugins

- sphinx_doc/about/index.rst
- sphinx_doc/about/ros1_comparison.rst
> optimized sizes and table dimensions

- sphinx_doc/tutorials/docs/navigation2_with_slam.rst
Update topic name in documentation from `/move_base_simple/goal` to the updated one `/goal_pose`
> Update topic name to set a goal pose

- nav2_dwb_controller/dwb_core/CMakeLists.txt
- nav2_dwb_controller/dwb_core/include/dwb_core/trajectory_critic.hpp
- nav2_dwb_controller/dwb_core/include/dwb_core/trajectory_utils.hpp
- nav2_dwb_controller/dwb_core/src/publisher.cpp
- nav2_dwb_controller/dwb_core/src/trajectory_utils.cpp
- nav2_dwb_controller/dwb_core/test/CMakeLists.txt
- nav2_dwb_controller/dwb_core/test/utils_test.cpp
- nav2_dwb_controller/dwb_critics/include/dwb_critics/base_obstacle.hpp
- nav2_dwb_controller/dwb_critics/include/dwb_critics/map_grid.hpp
- nav2_dwb_controller/dwb_critics/src/base_obstacle.cpp
- nav2_dwb_controller/dwb_critics/src/map_grid.cpp
- nav2_dwb_controller/dwb_critics/src/rotate_to_goal.cpp
---
---
* Added publisher checks
* Name change from addGridScores to addCriticVisualization
* Added unit test for trajectory_utils
---
> Dwb minimal updates

- sphinx_doc/contribute/index.rst
- description of process to get involved
- description of resources and websites to be involved
- simplify the DCO text
> adding getting involved page

- sphinx_doc/tutorials/docs/navigation2_with_slam.rst
- sphinx_doc/tutorials/docs/navigation2_with_stvl.rst
similar to creating a costmap layer tutorial which i found really helpful.
* Added videos to tutorial using STVL and tutorial using SLAM Toolbox
> Add ROSCon talks to other tutorials which might be relevant

- nav2_dwb_controller/dwb_plugins/test/goal_checker.cpp
- nav2_system_tests/src/system/test_system_launch.py
- nav2_voxel_grid/test/voxel_grid_tests.cpp
Mostly me toying around with how codecov computes values but adding a little bit of coverage while I'm at it
> A couple test updates to add a little more test coverage

- nav2_costmap_2d/plugins/obstacle_layer.cpp
- nav2_costmap_2d/src/costmap_2d_ros.cpp
---
| Ticket(s) this addresses   | #949 |
| Robotic platform tested on |  gazebo simulation of TB3 |
---
* Removed all nav stack message filter dropped messages
* N/A
---
* RViz still produces them
> removing the filter message warnings

- sphinx_doc/index.rst
- sphinx_doc/migration/Dashing.rst
- sphinx_doc/migration/Eloquent.rst
- sphinx_doc/migration/index.rst
- sphinx_doc/plugins/index.rst
Adding migration guides for Dashing and Eloquent to the website
> adding migration guides to website for new distributions

- nav2_system_tests/CMakeLists.txt
- nav2_system_tests/src/planning/planner_tester.cpp
- nav2_system_tests/src/planning/test_planner_costmaps_launch.py
- nav2_system_tests/src/planning/test_planner_random_launch.py
---
| Ticket(s) this addresses   | #1512|
| Primary OS tested on | ubuntu |
| Robotic platform tested on | CI |
---
* Trying to reenable planner system tests
* N/A
---
* N/A
> reenable planner tests

- nav2_system_tests/src/system/tester_node.py
- nav2_system_tests/src/waypoint_follower/tester.py
Next steps for bugging the nightly builds - also just more logging is required.
> adding logging for nightly tests

- sphinx_doc/index.rst
- sphinx_doc/migration/index.rst
Adding robots from the experiments with @fmrico
> [website] add more cool videos from real robots

- sphinx_doc/concepts/index.rst
- sphinx_doc/index.rst
- sphinx_doc/tutorials/docs/navigation2_with_slam.rst
- sphinx_doc/tutorials/docs/navigation2_with_stvl.rst
Adding concepts page to explain the role of the various components and standards in the navigation stack.
> Adding Concepts page to website

- nav2_map_server/src/map_saver_cli.cpp
It made segfault when running map_saver using option param without value.
Ignore the param and continue the process.
Signed-off-by: Koeun Choi <gony0206@gmail.com>
---
| Ticket(s) this addresses   | #1592  |
---
Please look the issue ticket.
> Fix segfault when second argv is none in map_saver

- nav2_costmap_2d/src/collision_checker.cpp
Signed-off-by: Aitor Miguel Blanco <aitormibl@gmail.com>
---
| Ticket(s) this addresses   | #1404 |
---
* Modified CollisionChecker to detect collision with inscribed radius, occupied or unknown state cells in costmap for a given pose.
---
> Corrected check to detect collision (#1404)

- nav2_costmap_2d/src/collision_checker.cpp
---
| Ticket(s) this addresses   | (#1404 #1603 ) |
| Robotic platform tested on | gazebo simulation of turtlebot3) |
---
* Changed check in collision detector to be triggered only with lethal or unknown cells.
---
* We need to look into how to deal with the clear footprint function to allow the robot to detect obstacles during spin recovery. Thanks to this function, at the moment the robot won't be able to detect any obstacles inside its footprint.
> Spin recovery

- sphinx_doc/migration/Eloquent.rst
Adding "Map Server Re-Work" part in Foxy Migration Guide
---
| Info | |
| Ticket(s) this addresses   | #1010 |
| PR this addresses   | #1624 |
> Map Server docs update for Foxy

- nav2_dwb_controller/dwb_core/src/publisher.cpp
Signed-off-by: Francisco Martin Rico <fmrico@gmail.com>
---
| Ticket(s) this addresses   | No ticket |
---
* I have found a small bug while I was trying developing a controller plugin, trying to debug the local plan
* The local plan wasn't published because the count subscriber condition was wrong.
* This small PR fix this bug
None
---
None
> Fix bug in the condition to publish local plan

- nav2_behavior_tree/include/nav2_behavior_tree/behavior_tree_engine.hpp
- nav2_behavior_tree/plugins/control/pipeline_sequence.cpp
- nav2_behavior_tree/plugins/control/recovery_node.cpp
- nav2_behavior_tree/plugins/control/round_robin_node.cpp
- nav2_behavior_tree/plugins/decorator/rate_controller.cpp
- nav2_behavior_tree/src/behavior_tree_engine.cpp
- nav2_bt_navigator/src/bt_navigator.cpp
- nav2_bt_navigator/src/ros_topic_logger.cpp
- tools/ros2_dependencies.repos
> update for BT.cpp master

- nav2_bringup/bringup/params/nav2_params.yaml
Resolves ros-planning/navigation2#938
The forward_point_distance used in the GoalAlign and PathAlign critics projects the current pose forward a default 0.325 meters before scoring the trajectory. This can cause velocities that create sharp turns into obstacles to be chosen (reproducible with the Turtlebot3 simulation).
For TB3, which is small in size, 0.325 meters is too far. Instead, enable GoalAlign and PathAlign critics in the DWB controller and shorten the critics' forward_point_distance (how far the current pose is project given the current orientation before scoring the trajectory) from the default 0.325 meters to 0.1 meters which improves stability when running with TB3.
Signed-off-by: Jack Pien <jack@jackpien.com>
---
| ------ | ----------- …
> Enable Goal/PathAlign DWB critics, reduce forward_point_distance

- nav2_dwb_controller/dwb_critics/src/twirling.cpp
Removed an if condition that never gets executed which mentioned in #1766.
> Removed unused condition in twirling.cpp

- nav2_behavior_tree/plugins/condition/goal_reached_condition.cpp
- nav2_dwb_controller/nav_2d_utils/include/nav_2d_utils/odom_subscriber.hpp
| Ticket(s) this addresses   | #1763 |
| Primary OS tested on | Ubuntu 18.04|
---
* Added declare_parameter_if_not_declared calls so that parameters are read from yaml.
* None
> Added use of declare_parameter_if_not_declared.

- doc/parameters/param_list.md
This should contain a list of all the declared parameters in the stack #1589.
Was thinking of having each parameter in it's package readme, let me know what you think of the best format and location for this data.
> List of parameters in the stack 

- doc/parameters/param_list.md
Adding complete descriptions for all parameters in the stack.
Currently missing 
Need to review some notes to add those, but the rest are here
> Add complete parameter description documentation

- tools/build_all.sh
- tools/initial_ros_setup.sh
---
---
* Removed eloquent and added foxy in the install scripts as foxy is released.
---
> Replace eloquent with foxy in the install scripts

- nav2_core/include/nav2_core/goal_checker.hpp
---
| Ticket(s) this addresses   | #1810 |
---
* Make GoalChecker::reset() a pure virtual function
> Make GoalChecker::reset() a pure virtual function

- nav2_util/CMakeLists.txt
- nav2_util/src/dump_params.cpp
- nav2_util/test/CMakeLists.txt
- nav2_util/test/test_dump_params/dump_params_default.txt
- nav2_util/test/test_dump_params/dump_params_error.txt
- nav2_util/test/test_dump_params/dump_params_help.txt
- nav2_util/test/test_dump_params/dump_params_md.txt
- nav2_util/test/test_dump_params/dump_params_md_verbose.txt
- nav2_util/test/test_dump_params/dump_params_multiple.txt
- nav2_util/test/test_dump_params/dump_params_yaml.txt
- nav2_util/test/test_dump_params/dump_params_yaml_verbose.txt
- nav2_util/test/test_dump_params/test_dump_params.launch.py
- nav2_util/test/test_dump_params/test_dump_params_node.py
---
| Ticket(s) this addresses   | #1810, #1818 |
| Robotic platform tested on | Turtlebot3 Gazebo Simulation |
---
* Added `dump_params` integration tests
* Fixed error in `dump_params` for array type parameters
> Add dump_params integration tests

- nav2_behavior_tree/include/nav2_behavior_tree/behavior_tree_engine.hpp
- nav2_behavior_tree/plugins/control/pipeline_sequence.cpp
- nav2_behavior_tree/plugins/control/recovery_node.cpp
- nav2_behavior_tree/plugins/control/round_robin_node.cpp
- nav2_behavior_tree/plugins/decorator/rate_controller.cpp
- nav2_behavior_tree/src/behavior_tree_engine.cpp
- nav2_bt_navigator/src/ros_topic_logger.cpp
---
| Ticket(s) this addresses   | #1828 |
---
* Fix BT.CPP API changes for eloquent devel
N/A
---
* Release new eloquent binaries
> [eloquent] fix API changes from BT.CPP

- nav2_amcl/package.xml
- nav2_behavior_tree/package.xml
- nav2_bringup/bringup/package.xml
- nav2_bringup/nav2_gazebo_spawner/package.xml
- nav2_bt_navigator/package.xml
- nav2_common/package.xml
- nav2_controller/package.xml
- nav2_core/package.xml
- nav2_costmap_2d/package.xml
- nav2_dwb_controller/costmap_queue/package.xml
- nav2_dwb_controller/dwb_core/package.xml
- nav2_dwb_controller/dwb_critics/package.xml
- nav2_dwb_controller/dwb_msgs/package.xml
- nav2_dwb_controller/dwb_plugins/package.xml
- nav2_dwb_controller/nav2_dwb_controller/package.xml
- nav2_dwb_controller/nav_2d_msgs/package.xml
- nav2_dwb_controller/nav_2d_utils/package.xml
- nav2_experimental/nav2_rl/nav2_turtlebot3_rl/package.xml
- nav2_lifecycle_manager/package.xml
- nav2_map_server/package.xml
- nav2_msgs/package.xml
- nav2_navfn_planner/package.xml
- nav2_planner/package.xml
- nav2_recoveries/package.xml
- nav2_rviz_plugins/package.xml
- nav2_system_tests/package.xml
- nav2_util/package.xml
- nav2_voxel_grid/package.xml
- nav2_waypoint_follower/package.xml
- navigation2/package.xml
For release of new BT.CPP v3 library version
> bump to 0.3.5 [eloquent]

- nav2_amcl/package.xml
- nav2_behavior_tree/package.xml
- nav2_bringup/bringup/package.xml
- nav2_bringup/nav2_gazebo_spawner/package.xml
- nav2_bt_navigator/package.xml
- nav2_common/package.xml
- nav2_controller/package.xml
- nav2_core/package.xml
- nav2_costmap_2d/package.xml
- nav2_dwb_controller/costmap_queue/package.xml
- nav2_dwb_controller/dwb_core/package.xml
- nav2_dwb_controller/dwb_critics/package.xml
- nav2_dwb_controller/dwb_msgs/package.xml
- nav2_dwb_controller/dwb_plugins/package.xml
- nav2_dwb_controller/nav2_dwb_controller/package.xml
- nav2_dwb_controller/nav_2d_msgs/package.xml
- nav2_dwb_controller/nav_2d_utils/package.xml
- nav2_lifecycle_manager/package.xml
- nav2_map_server/package.xml
- nav2_msgs/package.xml
- nav2_navfn_planner/package.xml
- nav2_planner/package.xml
- nav2_recoveries/package.xml
- nav2_rviz_plugins/package.xml
- nav2_system_tests/package.xml
- nav2_util/package.xml
- nav2_voxel_grid/package.xml
- nav2_waypoint_follower/package.xml
- navigation2/package.xml
Syncing new foxy-devel with master versions
> bump master to 0.4.0

- nav2_amcl/package.xml
- nav2_behavior_tree/package.xml
- nav2_bringup/bringup/package.xml
- nav2_bringup/nav2_gazebo_spawner/package.xml
- nav2_bt_navigator/package.xml
- nav2_common/package.xml
- nav2_controller/package.xml
- nav2_core/package.xml
- nav2_costmap_2d/package.xml
- nav2_dwb_controller/costmap_queue/package.xml
- nav2_dwb_controller/dwb_core/package.xml
- nav2_dwb_controller/dwb_critics/package.xml
- nav2_dwb_controller/dwb_msgs/package.xml
- nav2_dwb_controller/dwb_plugins/package.xml
- nav2_dwb_controller/nav2_dwb_controller/package.xml
- nav2_dwb_controller/nav_2d_msgs/package.xml
- nav2_dwb_controller/nav_2d_utils/package.xml
- nav2_lifecycle_manager/package.xml
- nav2_map_server/package.xml
- nav2_msgs/package.xml
- nav2_navfn_planner/package.xml
- nav2_planner/package.xml
- nav2_recoveries/package.xml
- nav2_rviz_plugins/package.xml
- nav2_system_tests/package.xml
- nav2_util/package.xml
- nav2_voxel_grid/package.xml
- nav2_waypoint_follower/package.xml
- navigation2/package.xml
Releasing ROS2 Foxy Navigation2. All PRs wanted for Foxy have been resolved and we're ready for an initial release!
> Release for ROS2 Foxy & bump to 0.4.0

- nav2_amcl/package.xml
- nav2_behavior_tree/package.xml
- nav2_bringup/bringup/package.xml
- nav2_bringup/nav2_gazebo_spawner/package.xml
- nav2_bt_navigator/package.xml
- nav2_common/package.xml
- nav2_controller/package.xml
- nav2_core/package.xml
- nav2_costmap_2d/package.xml
- nav2_dwb_controller/costmap_queue/package.xml
- nav2_dwb_controller/dwb_core/package.xml
- nav2_dwb_controller/dwb_critics/package.xml
- nav2_dwb_controller/dwb_msgs/package.xml
- nav2_dwb_controller/dwb_plugins/package.xml
- nav2_dwb_controller/nav2_dwb_controller/package.xml
- nav2_dwb_controller/nav_2d_msgs/package.xml
- nav2_dwb_controller/nav_2d_utils/package.xml
- nav2_lifecycle_manager/package.xml
- nav2_map_server/package.xml
- nav2_msgs/package.xml
- nav2_navfn_planner/package.xml
- nav2_planner/package.xml
- nav2_recoveries/package.xml
- nav2_rviz_plugins/package.xml
- nav2_system_tests/package.xml
- nav2_util/package.xml
- nav2_voxel_grid/package.xml
- nav2_waypoint_follower/package.xml
- navigation2/package.xml
> Adding missing deps to nav2_util

- nav2_amcl/package.xml
- nav2_behavior_tree/package.xml
- nav2_bringup/bringup/package.xml
- nav2_bringup/nav2_gazebo_spawner/package.xml
- nav2_bt_navigator/package.xml
- nav2_common/package.xml
- nav2_controller/package.xml
- nav2_core/package.xml
- nav2_costmap_2d/package.xml
- nav2_dwb_controller/costmap_queue/package.xml
- nav2_dwb_controller/dwb_core/package.xml
- nav2_dwb_controller/dwb_critics/package.xml
- nav2_dwb_controller/dwb_msgs/package.xml
- nav2_dwb_controller/dwb_plugins/package.xml
- nav2_dwb_controller/nav2_dwb_controller/package.xml
- nav2_dwb_controller/nav_2d_msgs/package.xml
- nav2_dwb_controller/nav_2d_utils/package.xml
- nav2_lifecycle_manager/package.xml
- nav2_map_server/package.xml
- nav2_msgs/package.xml
- nav2_navfn_planner/package.xml
- nav2_planner/package.xml
- nav2_recoveries/package.xml
- nav2_rviz_plugins/package.xml
- nav2_system_tests/package.xml
- nav2_util/package.xml
- nav2_voxel_grid/package.xml
- nav2_waypoint_follower/package.xml
- navigation2/package.xml
> sync master from foxy version updates

- README.md
Relates to https://github.com/ros-planning/navigation.ros.org/pull/44
> Add citation for IROS paper

- nav2_bringup/bringup/launch/bringup_launch.py
- nav2_bringup/bringup/launch/localization_launch.py
- nav2_bringup/bringup/launch/navigation_launch.py
| Ticket(s) this addresses   | #1865  |
| Primary OS tested on |  Ubtuntu 20.04 |
| Robotic platform tested on | TB3 robot in simulation |
---
Updated set env command in launch files to add buffering to RCUTILS logging.
> Updated the line buffering command

- nav2_util/test/CMakeLists.txt
- nav2_util/test/test_dump_params/test_dump_params_default.test.py
- nav2_util/test/test_dump_params/test_dump_params_md.test.py
- nav2_util/test/test_dump_params/test_dump_params_multiple.test.py
- nav2_util/test/test_dump_params/test_dump_params_yaml.test.py
---
| Ticket(s) this addresses   | #1836 |
---
* Fix `dump_params` unit tests
> Fix nav2_util/dump_params unit tests

- nav2_recoveries/plugins/back_up.cpp
Signed-off-by: Marwan Taher <marokhaled99@gmail.com>
---
| Ticket(s) this addresses   | #1878 |
| Robotic platform tested on |  Turtlebot gazebo simulation |
---
* Resolved the simulated moved distance into its x and y components instead of assuming the motion is done in the x-axis only.
> Considering robot orientation during back up recovery 

- nav2_amcl/include/nav2_amcl/amcl_node.hpp
- nav2_amcl/src/amcl_node.cpp
- nav2_bt_navigator/include/nav2_bt_navigator/bt_navigator.hpp
- nav2_bt_navigator/src/bt_navigator.cpp
- nav2_controller/include/nav2_controller/nav2_controller.hpp
- nav2_controller/src/nav2_controller.cpp
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp
- nav2_costmap_2d/src/costmap_2d_ros.cpp
- nav2_map_server/include/nav2_map_server/map_saver.hpp
- nav2_map_server/include/nav2_map_server/map_server.hpp
- nav2_map_server/src/map_saver/map_saver.cpp
- nav2_map_server/src/map_server/map_server.cpp
- nav2_planner/include/nav2_planner/planner_server.hpp
- nav2_planner/src/planner_server.cpp
- nav2_recoveries/include/nav2_recoveries/recovery_server.hpp
- nav2_recoveries/src/recovery_server.cpp
- nav2_util/include/nav2_util/lifecycle_node.hpp
- nav2_waypoint_follower/include/nav2_waypoint_follower/waypoint_follower.hpp
- nav2_waypoint_follower/src/waypoint_follower.cpp
> remove on_errors in specific servers in favor of a general lifecycle warning

- nav2_controller/src/nav2_controller.cpp
- nav2_map_server/src/map_saver/main_server.cpp
- nav2_map_server/src/map_saver/map_saver.cpp
- nav2_map_server/src/map_server/main.cpp
- nav2_navfn_planner/src/navfn.cpp
> simply nodes some nodes to remove dead code

- nav2_waypoint_follower/src/waypoint_follower.cpp
> spin_some in cancel to allow result callback

- nav2_navfn_planner/include/nav2_navfn_planner/navfn.hpp
- nav2_navfn_planner/src/navfn.cpp
- nav2_navfn_planner/src/navfn_planner.cpp
- nav2_planner/src/planner_server.cpp
- nav2_system_tests/src/planning/CMakeLists.txt
- nav2_system_tests/src/planning/test_planner_plugins.cpp
> [testing sprint] remove dead code not used in 10 years from navfn

- nav2_waypoint_follower/src/waypoint_follower.cpp
To fix cpplint
See: https://app.circleci.com/pipelines/github/ros-planning/navigation2/3602/workflows/c6d8b916-c656-4f75-a89b-381d44b02903/jobs/14110
> Add #include <vector> for vector<>

- doc/parameters/param_list.md
- nav2_costmap_2d/src/costmap_2d_ros.cpp
> adding clearable layers to defaults

- nav2_map_server/src/map_saver/map_saver.cpp
---
| Ticket(s) this addresses   | #1966 |
| Primary OS tested on | CI |
| Robotic platform tested on | CI |
---
* Adding bond connection for map_saver 
N/A
---
N/A
> Adding bond to map_saver

- nav2_costmap_2d/test/unit/footprint_collision_checker_test.cpp
| Ticket(s) this addresses   | (#1810 ) |
| Primary OS tested on | (Ubuntu 20.04) |
| Robotic platform tested on | (n.a.) |
---
Added some basic tests to increase test coverage.
> Add footprint tests

- Dockerfile
> Fixed typo in Dockerfile: Ture -> True

- nav2_costmap_2d/test/integration/test_costmap_topic_collision_checker.cpp
---
| Ticket(s) this addresses   | #1954|
---
* Increase the sleep time to 1 second from 50 milliseconds
---
> [WIP] Collision Checker test bug

- nav2_waypoint_follower/include/nav2_waypoint_follower/waypoint_follower.hpp
- nav2_waypoint_follower/src/waypoint_follower.cpp
---
| Ticket(s) this addresses   | #1997 |
| Robotic platform tested on | TurtleBot3 Gazebo Simulation |
---
> Fix nav2_waypoint_follower bugs due to upstream ROS2 changes

- doc/BUILD.md
- tools/ros2_dependencies.repos
---
| Ticket(s) this addresses   | #2013 |
| Robotic platform tested on | gazebo simulation) |
---
- Updating instructions to build from source under ROS2 - eloquent
- Addition of a "quick test" after building from source
---
> Updating instructions to build from source - ros2 Eloquent

- doc/BUILD.md
- tools/ros2_dependencies.repos
---
| Ticket(s) this addresses   | #2013  |
---
- Just fixing the format of .md from the previous PR #2018
> Eloquent devel

- nav2_dwb_controller/nav_2d_utils/CMakeLists.txt
- nav2_dwb_controller/nav_2d_utils/package.xml
- nav2_dwb_controller/nav_2d_utils/src/path_ops.cpp
- nav2_dwb_controller/nav_2d_utils/test/2d_utils_test.cpp
- nav2_dwb_controller/nav_2d_utils/test/CMakeLists.txt
- nav2_dwb_controller/nav_2d_utils/test/path_ops_test.cpp
| Primary OS tested on | (Ubuntu in VM) |
---
* Added tests for nav_2d_utils in dwb_controller.
The test `AdjustResolutionSimple` in `path_ops_test.cpp` should be completed. What is the expected behavior of `adjustPlanResolution`? I expected that the gaps between points would not be bigger than the resolution.
> Add dwb tests

- nav2_dwb_controller/nav_2d_utils/test/CMakeLists.txt
- nav2_dwb_controller/nav_2d_utils/test/tf_help_test.cpp
---
---
* I added a test for `tf_help.cpp` in the `nav_2d_utils` package.
> Add test for tf_help.

- nav2_bt_navigator/include/nav2_bt_navigator/bt_navigator.hpp
- nav2_bt_navigator/src/bt_navigator.cpp
- tools/underlay.repos
This temporarily resolves issues while gazebo ros plugins are being fixed.
Also fixes issues introduced by https://github.com/ros2/geometry2/pull/325
> [WIP fixing CI] changing gazebo base to my fork for testing

- tools/underlay.repos
Fixes build in CI for ros-simulation again
> Reverting to ros-simulation from stevemacenski after patch merged

- nav2_system_tests/src/waypoint_follower/tester.py
- nav2_util/test/test_node_utils.cpp
---
| Ticket(s) this addresses   | #2043 |
---
* Fixes `nav2_util/node_utils` test ([relevant CI artifact](https://circle-production-customer-artifacts.s3.amazonaws.com/picard/5b21c78bcfe8df0013110d01/5f86f8d3a0485e4ca37063f3-0-build/artifacts/opt/overlay_ws/test_results/nav2_util/test_node_utils.gtest.xml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20201016T164024Z&X-Amz-SignedHeaders=host&X-Amz-Expires=60&X-Amz-Credential=AKIAJR3Q6CR467H7Z55A%2F20201016%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=26b101aa801a8e56a2f06950cc86c1c815386fea996dd023dd928b6d412cfafc))
* Fixed `nav2_system_tests/test_waypoint_follower` which …
> Fix flaky tests

- tools/ros2_dependencies.repos
| Ticket(s) this addresses   | #2061  |
---
* Fixed underlying BehaviorTree.CPP tag
* None
> Updated incorrect BehaviorTree.CPP tag to API compatible 3.5.3

- smac_planner/src/a_star.cpp
Analog to https://github.com/ros-planning/navigation2/pull/2068
> adding looping fix to foxy

- nav2_map_server/test/component/test_map_saver_node.cpp
- nav2_map_server/test/component/test_map_server_node.cpp
> Fix for double free issue in map server testcases

- nav2_lifecycle_manager/test/test_lifecycle_manager.cpp
> Swap startup and timeout check on lifecycle manager tests

- nav2_controller/src/nav2_controller.cpp
- nav2_costmap_2d/include/nav2_costmap_2d/clear_costmap_service.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_filters/costmap_filter.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_layer.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/inflation_layer.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/layer.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/obstacle_layer.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/range_sensor_layer.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/static_layer.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/voxel_layer.hpp
- nav2_costmap_2d/plugins/costmap_filters/costmap_filter.cpp
- nav2_costmap_2d/plugins/inflation_layer.cpp
- nav2_costmap_2d/plugins/obstacle_layer.cpp
- nav2_costmap_2d/plugins/range_sensor_layer.cpp
- nav2_costmap_2d/plugins/static_layer.cpp
- nav2_costmap_2d/plugins/voxel_layer.cpp
- nav2_costmap_2d/src/clear_costmap_service.cpp
- nav2_costmap_2d/src/costmap_layer.cpp
- nav2_costmap_2d/test/unit/declare_parameter_test.cpp
- nav2_msgs/srv/ClearCostmapAroundRobot.srv
- nav2_planner/src/planner_server.cpp
Continuance of #2044  I think I hit a weird CI bug so rebased and trying a fresh PR trigger
> Current_ costmap2D updates & fixing recovery-straight-path issues

- nav2_dwb_controller/dwb_critics/CMakeLists.txt
- nav2_dwb_controller/dwb_critics/test/CMakeLists.txt
- nav2_dwb_controller/dwb_critics/test/prefer_forward_test.cpp
---
* Added tests for the prefer forward dwb critic.
> Add prefer forward critic test

- nav2_costmap_2d/README.md
This is a trivial change that only fixed the markdown format of README.md.
> Fix README format

- doc/parameters/param_list.md
- nav2_bringup/bringup/params/nav2_multirobot_params_1.yaml
- nav2_bringup/bringup/params/nav2_multirobot_params_2.yaml
- nav2_bringup/bringup/params/nav2_params.yaml
- nav2_lifecycle_manager/src/lifecycle_manager.cpp
- nav2_lifecycle_manager/test/launch_lifecycle_test.py
- nav2_map_server/launch/map_saver_server.launch.py
- nav2_map_server/src/map_saver/map_saver.cpp
- nav2_map_server/test/map_saver_params.yaml
- nav2_smac_planner/README.md
- nav2_smac_planner/src/smac_planner.cpp
- nav2_smac_planner/src/smac_planner_2d.cpp
- nav2_system_tests/src/costmap_filters/keepout_params.yaml
Addressing #2096.
Is "migration guide updates" referring to https://navigation.ros.org/migration/Foxy.html?
> Standardize time units per REP-103

- nav2_costmap_2d/plugins/voxel_layer.cpp
> Move voxel publisher activation into conditional that its on

- nav2_dwb_controller/dwb_critics/test/CMakeLists.txt
- nav2_dwb_controller/dwb_critics/test/base_obstacle_test.cpp
---
* I added tests for the DWB critic: base obstacle critic.
> Add DWB base obstacle critic test

- nav2_costmap_2d/test/testing_helper.hpp
---
| Ticket(s) this addresses   | #2130 |
---
Remove useless function
None
---
> costmap_2d: remove useless and buggy testing helper function (#2130)

- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
Thanks @shrijitsingh99 @fmrico for finding this so quickly. Always 1 bug after release :-)
> Fixing control_frequency to controller_frequency typo in RPP controller

- nav2_bt_navigator/README.md
minor readme fixes. Update 1 broken link and delete reference to unknown README.md markdown section.
> fix broken links in README

- nav2_smac_planner/src/a_star.cpp
> [SMAC] ensure the index also isn't the goal's (continuing 2159)

- nav2_recoveries/plugins/back_up.cpp
- nav2_recoveries/plugins/spin.cpp
---
| Ticket(s) this addresses   | #2189  |
| Robotic platform tested on | Turtlebot simulation|
---
Fix collision check in back_up.cpp and also spin.cpp.
None
---
> Fix recovery action collision check.

- nav2_bringup/bringup/params/nav2_params.yaml
---
| Robotic platform tested on | Turtlebot3 simulation |
---
Fix an issue where using the "back up" action in the behavior tree caused the bt_navigator node to not initialize.
---
> Fix back up action behavior tree node name issue

- nav2_behavior_tree/test/plugins/action/test_clear_costmap_service.cpp
Fix https://github.com/ros-planning/navigation2/pull/2204#issuecomment-793035051
> Fix nav2_behavior_tree action plugin test

- nav2_regulated_pure_pursuit_controller/README.md
I figured I wouldn't use the fancy feature/bug fix template as it's really just a documentation fix...
Hope it's alright and I didn't need to create an issue for it :) 
Thanks!
> Fix typo in nav2_regulated_pure_pursuit_controller/README.md

- nav2_smac_planner/include/nav2_smac_planner/node_se2.hpp
- nav2_smac_planner/src/node_se2.cpp
Speeds up planning by 10%!!!
https://github.com/ros-planning/navigation2/issues/2014
> adding precomputations of trig and offsets for SMAC planner

- nav2_smac_planner/include/nav2_smac_planner/collision_checker.hpp
https://github.com/ros-planning/navigation2/issues/2207
> fixing smac collision on footprints

- nav2_behavior_tree/CMakeLists.txt
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/decorator/single_trigger_node.hpp
- nav2_behavior_tree/plugins/decorator/single_trigger_node.cpp
- nav2_behavior_tree/test/plugins/decorator/CMakeLists.txt
- nav2_behavior_tree/test/plugins/decorator/test_single_trigger_node.cpp
- nav2_bringup/bringup/params/nav2_multirobot_params_1.yaml
- nav2_bringup/bringup/params/nav2_multirobot_params_2.yaml
- nav2_bringup/bringup/params/nav2_params.yaml
- nav2_bt_navigator/src/bt_navigator.cpp
- nav2_system_tests/src/behavior_tree/test_behavior_tree_node.cpp
Per https://github.com/ros-planning/navigation2/issues/2197
Requires
- testing DONE
- migration guide, nav2 plugins list, and param guide updates DONE
> new behavior tree node for triggering just once

- nav2_util/include/nav2_util/clear_entirely_costmap_service_client.hpp
- nav2_util/include/nav2_util/costmap.hpp
- nav2_util/include/nav2_util/geometry_utils.hpp
- nav2_util/include/nav2_util/lifecycle_node.hpp
- nav2_util/include/nav2_util/line_iterator.hpp
- nav2_util/include/nav2_util/node_thread.hpp
- nav2_util/include/nav2_util/odometry_utils.hpp
- nav2_util/include/nav2_util/robot_utils.hpp
- nav2_util/include/nav2_util/service_client.hpp
- nav2_util/include/nav2_util/simple_action_server.hpp
- nav2_util/include/nav2_util/string_utils.hpp
https://github.com/ros-planning/navigation2/issues/2155
> adding doxygen for nav2-utils

- nav2_bringup/bringup/launch/slam_launch.py
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/2240|
| Robotic platform tested on | simulated turtlebot |
---
* Use renamed slam_toolbox param-file
> Use different param name for slam_toolbox param_file

- nav2_recoveries/include/nav2_recoveries/recovery.hpp
- nav2_recoveries/include/nav2_recoveries/recovery_server.hpp
- nav2_recoveries/plugins/back_up.hpp
- nav2_recoveries/plugins/spin.hpp
- nav2_recoveries/plugins/wait.hpp
https://github.com/ros-planning/navigation2/issues/2155
> adding doxygen to recoveries

- nav2_controller/include/nav2_controller/plugins/simple_progress_checker.hpp
- nav2_controller/include/nav2_controller/plugins/stopped_goal_checker.hpp
- nav2_controller/plugins/simple_progress_checker.cpp
- nav2_controller/plugins/stopped_goal_checker.cpp
---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/956 |
| Robotic platform tested on | Wyca Elodie Sim |
---
Similar to https://github.com/ros-planning/navigation2/pull/2248, turns out I also need **SimpleProgressChecker** to have dynamic parameters and took care of **StoppedGoalChecker** along the way.
This is SO nice these are plugins and there are very convenient. It makes me very happy architecturally.
> [nav2_controller] Dynamic parameters for the reminding plugins

- nav2_regulated_pure_pursuit_controller/package.xml
Found in foxy release binary run
> adding missing test dependencies to regulated pure pursuit 

- nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager_client.hpp
- nav2_lifecycle_manager/src/lifecycle_manager_client.cpp
- nav2_util/include/nav2_util/lifecycle_node.hpp
- nav2_util/src/lifecycle_node.cpp
---
| Robotic platform tested on | Wyca Elodie Sim |
---
When using a **LifecycleManagerClient** it is currently impossible to connect to a **LifecycleManager** that is on a namespace due to the use of the **LifecycleManager** node address for the **LifecycleManagerClient** service client node naming. For instance `my_namespace/my_lifecycle_manager` will result in the incorrect creation of an **LifecycleManagerClient** service client node with the name `my_namespace/my_lifecycle_manager_service_client` (a node name cannot have '/' characters).
This PR replaces `/` characters with `_`
This could have been solved also by putting the **LifecycleManagerClient** …
> [nav2_lifecycle_manager] Support namespaced LifecycleManagers

- nav2_bringup/nav2_gazebo_spawner/nav2_gazebo_spawner/nav2_gazebo_spawner.py
---
| Primary OS tested on |  Ubuntu 20.04 LTS |
---
fix a launch error in nav2_gazebo_spawner
Traceback :
```
[nav2_gazebo_spawner-2] Traceback (most recent call last):
[nav2_gazebo_spawner-2]   File "/home/kaven/code/ros2_master/ros2_rolling/install/rclpy/lib/python3.8/site-packages/rclpy/__init__.py", line 221, in spin_until_future_complete
[nav2_gazebo_spawner-2]     executor.add_node(node)
[nav2_gazebo_spawner-2] AttributeError: 'float' object has no attribute 'add_node'
[nav2_gazebo_spawner-2]
[nav2_gazebo_spawner-2] During handling of the above exception, another exception occurred:
[nav2_gazebo_spawner-2]
[nav2_gazebo_spawner-2] …
```
> fix AttributeError in nav2_gazebo_spawner

- .dockerhub/debug/hooks/build
- .dockerhub/distro.Dockerfile
- .dockerhub/release/hooks/build
- Dockerfile
- tools/underlay.repos
> Move CI from ROS2 master to Rolling

- .github/workflows/trigger_dockerhub.yaml
Fixes dockerhub action from https://github.com/ros-planning/navigation2/pull/2353
> Fix dockerhub action

- nav2_dwb_controller/nav_2d_utils/src/conversions.cpp
This was being done accidentally by tf2 before, but we should
make sure to include what we use.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
---
| Ticket(s) this addresses   | https://github.com/ros2/geometry2/pull/420 |
---
* Fixed navigation2 build against nightly/Rolling
None.
> Make sure to add in necessary includes for conversions.

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
- nav2_bringup/nav2_gazebo_spawner/nav2_gazebo_spawner/nav2_gazebo_spawner.py
https://github.com/ros-planning/navigation2/issues/2379
> Galactic syncing recent master PRs

- .github/workflows/trigger_dockerhub.yaml
Missing from https://github.com/ros-planning/navigation2/pull/2348
> Update image tag name for CI action

- nav2_bt_navigator/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml
Deal with issue with default params of TB3 sometimes not getting close enough and causing issues.
> Increasing nav through poses remove point tolerance to 0.7

- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
---
| Ticket(s) this addresses   | Requested change from PR #2375  |
| Primary OS tested on | macOS |
---
Moves changes from PR #2375 that haven't been fixed in the past into main.
> Move unmerged changes from #2375 into main

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
To resolve https://github.com/ros-planning/navigation2/issues/2386
> Setting default groot monitoring to false

- nav2_costmap_2d/include/nav2_costmap_2d/observation.hpp
---
This is a followup to PR #2413 for a `main` branch.
> Followup to PR 2413 for main branch (fix for operator= in observation.hpp)

- nav2_costmap_2d/include/nav2_costmap_2d/observation.hpp
This is a followup to PR #2413 for a `galactic` branch.
> Followup to PR 2413 for galactic branch (fix for operator= in observation.hpp)

- nav2_smac_planner/src/smac_planner_2d.cpp
- nav2_smac_planner/src/smac_planner_hybrid.cpp
---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/2476 |
| Robotic platform tested on | Wyca sim|
---
Fix https://github.com/ros-planning/navigation2/issues/2476
> Fix Smac cleanup

- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
> Update regulated_pure_pursuit_controller.cpp (#2484)

- .github/workflows/update_ci_image.yaml
to fix conner cases like this:
https://github.com/ros-planning/navigation2/runs/3277796714?check_suite_focus=true
https://stackoverflow.com/a/4709921
> Use regex anchors when checking for updates

- nav2_amcl/src/amcl_node.cpp
---
| Robotic platform tested on | (gazebo simulation of turtlebot) |
---
Fix null pointer in amcl on_cleanup
---
> Fix null pointer in amcl on_cleanup

- nav2_system_tests/src/system/CMakeLists.txt
- nav2_system_tests/src/system/test_multi_robot_launch.py
---
fixes multi_robot test  in nav2_system_tests. 
---
> fix multi robot  system test

- nav2_system_tests/src/system/nav_to_pose_tester_node.py
---
| Robotic platform tested on | Personal laptop |
---
* Fixed test_bt_navigator_with_groot_monitoring
> Fixed test_bt_navigator_with_groot_monitoring

- nav2_costmap_2d/plugins/costmap_filters/keepout_filter.cpp
While `or` is in the C++ standard as far as I know, it's not supported by MSVC ..
> Windows fix

- nav2_amcl/include/nav2_amcl/amcl_node.hpp
- nav2_amcl/src/amcl_node.cpp
Functions unused from initial port
> removing dead code from AMCL

- nav2_smac_planner/src/smac_planner_hybrid.cpp
https://github.com/ros-planning/navigation2/issues/2686
> If not downsampling costmap, default factor to 1

- nav2_smac_planner/README.md
- nav2_smac_planner/include/nav2_smac_planner/types.hpp
- nav2_smac_planner/src/analytic_expansion.cpp
- nav2_smac_planner/src/smac_planner_hybrid.cpp
- nav2_smac_planner/src/smac_planner_lattice.cpp
- nav2_smac_planner/test/test_a_star.cpp
- nav2_smac_planner/test/test_smac_hybrid.cpp
- nav2_smac_planner/test/test_smac_lattice.cpp
https://github.com/ros-planning/navigation2/issues/2659
> adding max analytic expansion length

- nav2_smac_planner/README.md
- nav2_smac_planner/src/node_hybrid.cpp
- nav2_smac_planner/src/smac_planner_hybrid.cpp
Docs PR https://github.com/ros-planning/navigation.ros.org/pull/241
@afrixs an OK on this would be great just to verify this meets your needs too to put this admissibility topic behind us
> changing formulation of Hybrid-A* to be admissible and retune

- nav2_bt_navigator/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml
- nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml
https://github.com/ros-planning/navigation2/issues/2738
> increasing backup distance and speed

- Dockerfile
> Update colcon and install lld

- .circleci/config.yml
- Dockerfile
- tools/distro.Dockerfile
- tools/source.Dockerfile
To speed up CI builds.
cc @tylerjw
Related:
* https://github.com/colcon/colcon-mixin-repository/pull/28
* https://github.com/ros-planning/moveit2/pull/914
> Use LLD linker

- README.md
Signed-off-by: Adam Aposhian <aposhian.dev@gmail.com>
---
| Ticket(s) this addresses   | #2742  |
| Primary OS tested on | N/A |
---
Avoid implying on README that container images are ready to run the nav2 stack
N/A
---
Eventually, there could be a tutorial on how to use the Nav2 container images for development, although it seems to be a small enough use-case to not be urgent.
> docs: clarify that container images are for building, not deploying

- .circleci/config.yml
Experiment to see if coverage report differs when tested with just a release build with compiled optimizations.
> Simplify coverage jobs for CI

- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/regulated_pure_pursuit_controller.hpp
- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
https://github.com/ros-planning/navigation2/issues/2766
> Revert footprint based collision checking for Galactic (2766) 

- nav2_costmap_2d/src/costmap_layer.cpp
---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/2770 |
| Robotic platform tested on | Wyca Elodie |
---
As discussed here https://github.com/ros-planning/navigation2/issues/2770
Mention in migration guide update
---
> [CostmapLayer] Fix clearArea invert param logic

- nav2_amcl/include/nav2_amcl/amcl_node.hpp
- nav2_amcl/src/amcl_node.cpp
Backports #2712 to foxy
---
| Ticket(s) this addresses   | #2711  |
---
> Backport #2712 to foxy

- nav2_costmap_2d/src/costmap_2d_ros.cpp
- nav2_costmap_2d/test/integration/dyn_params_tests.cpp
---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/956 and https://github.com/ros-planning/navigation2/pull/2592|
| Robotic platform tested on | Wyca Elodie simulation |
---
Turns out than in addition to the previously added dynamic parameters https://github.com/ros-planning/navigation2/pull/2592, I needed also the robot_base_frame param to be dynamic
Mention in migration guide
---
> [costmap2d] make robot_base_frame param dynamic

- nav2_behavior_tree/nav2_tree_nodes.xml
---
| Ticket(s) this addresses   | (-) |
| Robotic platform tested on | (turtlebot simulation) |
---
> BT nodes xml naming fix

- nav2_simple_commander/README.md
- nav2_simple_commander/nav2_simple_commander/robot_navigator.py
---
| Ticket(s) this addresses   | Part of [2415](https://github.com/ros-planning/navigation2/issues/2415) |
| Robotic platform tested on | Gazebo simulation of Waffle |
---
* Added possibility to wait for custom navigator and localizer in waitUntilNav2Active
https://github.com/ros-planning/navigation.ros.org/pull/275
---
> Add optional node names to wait

- nav2_costmap_2d/plugins/static_layer.cpp
---
| Info | Static Layer updates are ignored |
| Ticket(s) this addresses   | No |
| Robotic platform tested on | Custom Gazebo robot simulation |
---
* removed resizing on update message callback as it blocks updates that are out of bounds of the very first one
---
> Static Layer updates are ignored 

- nav2_bt_navigator/include/nav2_bt_navigator/bt_navigator.hpp
- nav2_bt_navigator/src/bt_navigator.cpp
---
| Ticket(s) this addresses   | #2785  |
| Primary OS tested on | ubuntu |
---
refer #2800 
---
> smoother fix

- nav2_behavior_tree/src/behavior_tree_engine.cpp
- nav2_bt_navigator/src/navigators/navigate_through_poses.cpp
- nav2_bt_navigator/src/navigators/navigate_to_pose.cpp
---
| Ticket(s) this addresses   |  #2847 ||
| Robotic platform tested on | Our Robot - but this doesn't require moving. I'll test on Steve's simulation later this week |
---
* Transitioning bt_navigator to the unconfigured state crashed in haltAllActions because the XML file path was wrong. When cleaning up one of the navigators, an empty root node was accessed which crashed the node.
* If the root node is an empty pointer I considered that nothing has to be alted - tell me if you also want the transition to fail?
* When we do manage to clean up the node, if we try to configure it again the node will crash because we're redeclaring an existing parameter without checking if it exists.
* When …
> Fix: bt_navigator crashes on lc transitions

- nav2_bringup/params/nav2_params.yaml
- nav2_core/include/nav2_core/smoother.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/cost_values.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_subscriber.hpp
- nav2_smoother/CMakeLists.txt
- nav2_smoother/include/nav2_smoother/simple_smoother.hpp
- nav2_smoother/plugins.xml
- nav2_smoother/src/nav2_smoother.cpp
- nav2_smoother/src/simple_smoother.cpp
- nav2_smoother/test/CMakeLists.txt
- nav2_smoother/test/test_simple_smoother.cpp
- navigation2/package.xml
Based on the Nav2 Smac Planner smoother without boundary enforcements for a simple and independent path smoother 
Docs needed before merge
> Adding Simple Path Smoother Plugin

- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d.hpp
- nav2_costmap_2d/test/CMakeLists.txt
- nav2_costmap_2d/test/regression/CMakeLists.txt
- nav2_costmap_2d/test/regression/costmap_bresenham_2d.cpp
Cherry picked #2857  and #2862 from main into galactic
---
| Ticket(s) this addresses   | #2835 |
| Robotic platform tested on | gazebo simulation where the original issue was found |
---
> Backporting #2857 and #2862 into galactic

- nav2_system_tests/src/planning/CMakeLists.txt
- nav2_system_tests/src/planning/planner_tester.cpp
- nav2_system_tests/src/planning/planner_tester.hpp
- nav2_system_tests/src/planning/test_planner_is_path_valid.cpp
---
---
Add in a test for is path valid. 
---
> Is path valid test

- nav2_costmap_2d/plugins/obstacle_layer.cpp
> Fix build issue on obstacle layer

- nav2_costmap_2d/src/costmap_2d_publisher.cpp
Fixes #2897 
| Ticket(s) this addresses   | #2897  |
| Primary OS tested on | Ubuntu20.04 |
| Robotic platform tested on | Gazebo simulation|
---
> Fix: real clock time to costmaps

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server.hpp
---
| Ticket(s) this addresses   | #2905 |
| Robotic platform tested on | gazebo & RMUA AI Robot |
---
- fixed `nav2_bt_navigator` compatible problem with `clang-15`
None
---
None
> fix bt potential risk problem

- nav2_bringup/params/nav2_multirobot_params_1.yaml
- nav2_bringup/params/nav2_multirobot_params_2.yaml
- nav2_regulated_pure_pursuit_controller/README.md
- nav2_rotation_shim_controller/README.md
- nav2_system_tests/src/costmap_filters/keepout_params.yaml
- nav2_system_tests/src/costmap_filters/speed_global_params.yaml
- nav2_system_tests/src/costmap_filters/speed_local_params.yaml
> updating goal_checker_plugin to goal_checker_plugins

- nav2_controller/src/controller_server.cpp
> adding linting fix

- nav2_system_tests/src/planning/planner_tester.cpp
- nav2_system_tests/src/planning/test_planner_is_path_valid.cpp
---
---
Fixing flaky isPathValid test.  
---
> fixed is path valid test

- nav2_system_tests/src/costmap_filters/keepout_params.yaml
- nav2_system_tests/src/costmap_filters/speed_global_params.yaml
- nav2_system_tests/src/costmap_filters/speed_local_params.yaml
Stand back up costmap filter tests
> goal checker plugins in CI system tests correct type

- nav2_simple_commander/nav2_simple_commander/robot_navigator.py
---
| Ticket(s) this addresses   | #2980 |
---
- Removes a dangling reference in nav2_simple_commander (galactic backport)
---
> Remove reference to smoother_client

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
fix linting issue caused by https://github.com/ros-planning/navigation2/pull/3004.
> linting fix

- nav2_util/include/nav2_util/robot_utils.hpp
---
Removed extra includes
---
---
> removed extra includes

- navigation2/package.xml
---
---
* Fix missing dependency on nav2_velocity_smoother
N/A
---
N/A
> Fix missing dependency on nav2_velocity_smoother

- nav2_collision_monitor/src/collision_monitor_node.cpp
> build fix - constructor fix for collision monitor

- nav2_map_server/src/map_io.cpp
- nav2_system_tests/src/costmap_filters/keepout_params.yaml
- nav2_system_tests/src/costmap_filters/speed_global_params.yaml
- nav2_system_tests/src/costmap_filters/speed_local_params.yaml
- nav2_system_tests/src/costmap_filters/test_keepout_launch.py
- nav2_system_tests/src/costmap_filters/test_speed_launch.py
https://github.com/ros-planning/navigation2/pull/3098 Continued... trying to see if I make the branch and cherry pick the commit from @AlexeyMerzlyakov 's branch
See #3098 for the extended discussion of changes
> Fix Costmap Filters system tests

- nav2_smac_planner/src/node_hybrid.cpp
https://github.com/ros-planning/navigation2/issues/3104
> Finding distance H if obstacle H is <= 0

- nav2_bringup/params/nav2_multirobot_params_1.yaml
- nav2_bringup/params/nav2_multirobot_params_2.yaml
---
| Tickets  | #3136  |
| Primary OS tested on | Ubuntu 22.04/20.04 |
| Robotic platform tested on | Multi robot gazebo simulation |
---
* Fixed goal_checker_plugin parameter format. See #3136 
None
---
None
> Fix goal_checker_plugin parameter format

- nav2_collision_monitor/CMakeLists.txt
- nav2_collision_monitor/README.md
- nav2_collision_monitor/include/nav2_collision_monitor/circle.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/collision_monitor_node.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/kinematics.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/polygon.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/range.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/scan.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/source.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/types.hpp
- nav2_collision_monitor/launch/collision_monitor_node.launch.py
- nav2_collision_monitor/src/circle.cpp
- nav2_collision_monitor/src/collision_monitor_node.cpp
- nav2_collision_monitor/src/kinematics.cpp
- nav2_collision_monitor/src/main.cpp
- nav2_collision_monitor/src/pointcloud.cpp
- nav2_collision_monitor/src/polygon.cpp
- nav2_collision_monitor/src/range.cpp
- nav2_collision_monitor/src/source.cpp
- nav2_collision_monitor/test/collision_monitor_node_test.cpp
- nav2_collision_monitor/test/kinematics_test.cpp
- nav2_collision_monitor/test/polygons_test.cpp
- nav2_collision_monitor/test/sources_test.cpp
---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/pull/2982 |
| Robotic platform tested on | colcon test |
---
Adding the range sensors support to the Collision Monitor, requested in https://github.com/ros-planning/navigation2/pull/2982#issuecomment-1150548172
* Added the support of IR/Sonar `sensor_msgs/Range` sensors to Collision Monitor
* Adjusted testcases for new type of sensors
* Adjust README.md. [No further updates needed](https://navigation.ros.org/configuration/packages/configuring-collision-monitor.html?highlight=range) for official pages documentation.
> Add the support of range sensors to Collision Monitor

- nav2_bringup/nav2_gazebo_spawner/nav2_gazebo_spawner/nav2_gazebo_spawner.py
https://github.com/ros-planning/navigation2/issues/3160
> removing timeout from py spins in Foxy

- nav2_bt_navigator/behavior_trees/navigate_w_recovery_and_replanning_only_if_path_becomes_invalid.xml
---
---
Added names to bt. This allows for better debugging and understanding of the behavior tree. 
---
> clear names for bt nodes

- nav2_simple_commander/nav2_simple_commander/robot_navigator.py
https://github.com/ros-planning/navigation2/issues/3191
> Remove time_allowance from simple navigator API for Galactic

- nav2_smac_planner/src/a_star.cpp
> [Smac] check if a node exists before creating

- nav2_controller/src/controller_server.cpp
---
| Robotic platform tested on | Custom skid steer drive robot under gazebo  |
---
* We identified that when trying to change the controller and the goal checker on a FollowPath action, only the controller was updated.
* We tracked down this to a function in the controller server in which only the controller was updated. 
* After doing the changes included in this PR, we confirmed that the goal checker change was actually done.
* No documentation is required.
---
* No future work is required.
> Update controller server goal checker

- nav2_theta_star_planner/test/test_theta_star.cpp
> adding reconfigure test to thetastar

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
https://github.com/ros-planning/navigation2/issues/3210
> Migrate to createTreeFromFile for loading BTs

- nav2_system_tests/src/error_codes/test_error_codes.py
---
---
Check that the node is active before making a action request though the python api. 
---
> Fix error code test

- nav2_regulated_pure_pursuit_controller/README.md
---
| Robotic platform tested on | Gazebo Simulation of TurtleBot3 |
---
Minor addition to (#2701) and (#3047)
---
> Remove unused velocity scaling config from example xml

- nav2_simple_commander/nav2_simple_commander/costmap_2d.py
Copyrights for the implemented function (World2MapValidated) in costmap_2d and email correction.
---
| Ticket(s) this addresses   | #3151 |
| Primary OS tested on | Ubuntu 22.04.01 |
---
* This PR is to fix the wrong email in previous PR  Added Footprint Collision Checker (Simple Commander API) #3280 
* Also, I added the copyright in `costmap_2d.py` for the modified function `world2MapValidated`
---
> Copyrights+Email Correction

- nav2_bringup/worlds/waffle.model
https://github.com/ros-planning/navigation2/issues/3346
> Changing waffle's minimum laser range to 0

- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/regulation_functions.hpp
https://github.com/ros-planning/navigation2/issues/3289
> fixing cost formula in RPP controller 

- nav2_rviz_plugins/src/nav2_panel.cpp
Really an awkward miss from my side from https://github.com/ros-planning/navigation2/pull/3165. 
Discourse post coming soon..
> fixing pose orientations while loading

- nav2_controller/src/controller_server.cpp
- nav2_smoother/src/nav2_smoother.cpp
Per https://github.com/ros-planning/navigation2/issues/3361
> catch general exceptions

- nav2_simple_commander/nav2_simple_commander/robot_navigator.py
---
| Ticket(s) this addresses   | `None` |
| Robotic platform tested on | InDro Robotics - Sentinel |
---
If you were to spawn up multiple Simple Commanders, you will receive a `Publisher already registered for provided node name`. This would allow you to have different nodes that can log separately.
- Possibiliy mention this is now an option for users?
---
- None
> node_name change during initialization

- nav2_behavior_tree/nav2_tree_nodes.xml
Added the following conditions to nav2_tree_nodes:
WouldAControllerRecoveryHelp
WouldAPlannerRecoveryHelp
WouldASmootherRecoveryHelp
AreErrorCodesPresent
> Added missing conditions to nav2_tree_nodes

- nav2_costmap_2d/plugins/voxel_layer.cpp
| Ticket(s) this addresses   | #3415 |
---
Fixes wrong coordinates.
> Fix wrong warning message format (Closes #3415)

- nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp
- nav2_lifecycle_manager/src/lifecycle_manager.cpp
- nav2_util/include/nav2_util/service_client.hpp
- nav2_waypoint_follower/plugins/photo_at_waypoint.cpp
---
| Ticket(s) this addresses   | #3447  |
---
* Fixed issue with previous pull #3439 
---
> fix ServicesQoS error

- nav2_amcl/src/amcl_node.cpp
---
| Ticket(s) this addresses   | #3451 |
---
* Correct the parameter description for nav2_amcl
> Correct the parameter description for AMCL

- nav2_mppi_controller/src/path_handler.cpp
https://github.com/ros-planning/navigation2/issues/3351#issuecomment-1460801456
CC @doisyg
> hot patch to fix transform error in MPPI caused by #3425

- nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp
---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/3456 |
| Robotic platform tested on | custom gazebo simulation |
---
* Fix vector size
---
> Fix out of bound vector

- nav2_simple_commander/launch/warehouse.world
https://github.com/ros2-gbp/navigation2-release/issues/2
> updating world in simple commander for TB3 package change

- .github/workflows/update_ci_image.yaml
using Pre-Defined Annotation Keys
as defined by The OpenContainers Annotations Spec
- https://specs.opencontainers.org/image-spec/annotations/#pre-defined-annotation-keys
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
- https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#get-a-repository
> Add labels to pushed image versions

- nav2_smac_planner/README.md
Typo in README
---
Fixed typo in README
> Typo README.md

- nav2_simple_commander/nav2_simple_commander/robot_navigator.py
| Ticket(s) this addresses   | #3558 |
---
* Fixed a recurring bug where parameter values were ignored, and overridden by trying to set default values
N/A
> Fix overridden parameter values

- README.md
---
---
* I've replaced the link to the contributing guidelines with a different link that looks most relevant.
* The original URL (https://navigation.ros.org/contribute/index.html) seems broken, returning an HTTP 404
* Not required!
---
* We may need to have a look for additional broken links in the README file.
> Fix broken link to contributing guidelines

- nav2_rviz_plugins/src/nav2_panel.cpp
https://github.com/ros-planning/navigation2/issues/3586
> Fixing 3586: rviz panel operating in multiple non-standard frames

- nav2_theta_star_planner/src/theta_star.cpp
https://github.com/ros-planning/navigation2/issues/3532
> Resolve #3532: reset i

- nav2_mppi_controller/src/path_handler.cpp
For `enforce_path_inversion: false`
> Fix default behavior

- nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp
- nav2_mppi_controller/src/critics/path_angle_critic.cpp
> fixing path angle critic's non-directional bias

- nav2_collision_monitor/src/range.cpp
| Ticket(s) this addresses   | #3648 |
| Robotic platform tested on | our robot |
---
* Reduce out-of-range log to debug level.
> Reduce out-of-range log to DEBUG

- nav2_collision_monitor/include/nav2_collision_monitor/collision_monitor_node.hpp
- nav2_collision_monitor/src/collision_monitor_node.cpp
- nav2_util/include/nav2_util/robot_utils.hpp
- nav2_util/src/robot_utils.cpp
- nav2_util/test/test_robot_utils.cpp
- nav2_velocity_smoother/include/nav2_velocity_smoother/velocity_smoother.hpp
- nav2_velocity_smoother/src/velocity_smoother.cpp
> Adding nan twist rejection for velocity smoother and collision monitor

- nav2_common/cmake/nav2_package.cmake
- nav2_rviz_plugins/CMakeLists.txt
@Ryanf55 does this meet your intent? 
https://github.com/ros-planning/navigation2/issues/3646
> Resolves 3646: Update CMAKE_COMPILER_IS_GNUCXX

- nav2_msgs/action/NavigateThroughPoses.action
- nav2_msgs/action/NavigateToPose.action
---
---
Remove empty message in result definition of navigate to pose and navigate through pose. 
---
> remove empty message

- nav2_costmap_2d/include/nav2_costmap_2d/inflation_layer.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/range_sensor_layer.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/static_layer.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/voxel_layer.hpp
Per https://github.com/ros-planning/navigation2/issues/3721
> changing costmap layers private to protected

- nav2_behavior_tree/CMakeLists.txt
---
| Ticket(s) this addresses   | [#3683](https://github.com/ros-planning/navigation2/issues/3683) |
| Robotic platform tested on | Built with --cmake-args "-DBUILD_TESTING=OFF" and verified that install/nav2_behavior_tree/include contains the utils folder |
---
- The original PR https://github.com/ros-planning/navigation2/pull/3692 only worked if `--merge-install` wasn't used to build. Moving the test utils to it's own test/include/<package name> folder not only makes it comply with ros2 package standards, but also make this work with and without `--merge-install`
- Back port to iron is needed.
---
> Move nav2_behavior_tree test utils into the right folder

- nav2_common/nav2_common/launch/rewritten_yaml.py
---
| Primary OS tested on | Ubuntu 22.04.2 LTS |
---
* Added support for YAML source files with lists in RewrittenYaml
* In a YAML file with a list, you can access each item in the list with it's index. For example:
`testfile.yaml`
```
list1:
- item0: 'a'
param00: 'b' 
param01: 'c'
param02: 'd'
- item1:
param10: 'g'
param11: 'f'
``` 
To rewrite param10: 
```
RewrittenYaml(
source_file=/path/to/testfile.yaml,
param_rewrites= {'list1.1.param10': 'e'}
)
```
---
> Update RewrittenYaml to support list rewrites

- nav2_common/nav2_common/launch/rewritten_yaml.py
Resolves https://github.com/ros-planning/navigation2/issues/3478
> [nav2_common] allowing leaf key rewrites that aren't dicts

- nav2_smac_planner/src/smac_planner_hybrid.cpp
- nav2_smac_planner/src/smac_planner_lattice.cpp
Per https://github.com/ros-planning/navigation2/pull/3244#issuecomment-1662477820
> adding tolerance back in for smac lattice and hybrid-A* planners

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
> fixing external users of the BT action node template

- nav2_mppi_controller/README.md
> Update README.md: fix typo

- nav2_smac_planner/lattice_primitives/lattice_generator.py
| Ticket(s) this addresses   | #3858 |
| Primary OS tested on | -- Not tested -- |
| Robotic platform tested on | -- Not tested -- |
---
* Simplification of equation to compute the max_value/outer edge of the lattice based on number of headings.
* Further information provided in #3858 
-- N.A --
---
-- N.A --
> simplification of lattice_generator.py, fixes #3858

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
Docs PR https://github.com/ros-planning/navigation.ros.org/pull/482
> Fixing subtree issues with blackboard shared resources (3640)

- nav2_mppi_controller/src/critics/path_align_critic.cpp
Per https://github.com/ros-planning/navigation2/issues/3939
> Fix NaN in Updated PathAlign

- nav2_velocity_smoother/src/velocity_smoother.cpp
---
| Robotic platform tested on | Dexory's sim |
---
Setting a negative `max_velocity` parameter field or a positive `min_velocity` parameter field is dangerous as it will cause a robot runaway.
As I don't think anybody would do it intentionally, it is very easy to make a sign error. This PR protects against that.
---
> [velocity smoother] Protect against invalid max_velocity or min_velocity

- nav2_simple_commander/nav2_simple_commander/robot_navigator.py
---
| Ticket(s) this addresses   | (#4018) |
| Primary OS tested on | (Ubuntu 22.04) |
| Robotic platform tested on | (hardware neobotix) |
---
* Added missing DriveOnHeading method in Simple Commander
* New entry in https://navigation.ros.org/commander_api/index.html#id1
---
> Add DriveOnHeading

- nav2_util/include/nav2_util/simple_action_server.hpp
| Ticket(s) this addresses   | #4024 |
| Robotic platform tested on | simulation |
---
* Add check before calling completion_callback_
> Fix SimpleActionServer nullprt callback

- nav2_planner/include/nav2_planner/planner_server.hpp
- nav2_planner/src/planner_server.cpp
---
| Ticket(s) this addresses   | 3954 |
---
Originally the pr was 
https://github.com/ros-planning/navigation2/pull/3990. The suggested way of rebasing and to sign off caused lots of problems. 
This pr adds functionality to invalidate a path based based on footprint checks. This functionality was added to the isPathValid service. A new parameter called is_path_valid_check_footprint was added to turn on/off the full footprint checks.
---
> footprint checks

- nav2_planner/src/planner_server.cpp
---
---
Added comment for isPathValid.
---
> Is path valid doc

- nav2_planner/src/planner_server.cpp
- nav2_smac_planner/README.md
- nav2_smac_planner/include/nav2_smac_planner/smac_planner_lattice.hpp
- nav2_smac_planner/src/smac_planner_lattice.cpp
- nav2_smac_planner/test/test_smac_hybrid.cpp
- nav2_smac_planner/test/test_smac_lattice.cpp
> debug visualizations for lattice planner

- nav2_mppi_controller/src/optimizer.cpp
---
| Ticket(s) this addresses   | Any |
| Robotic platform tested on | (Real and gazebo-simulated robot) |
---
* As in the other controller, I added the possibility to handle the parameter changes for the MPPI controller. At this moment some parameters such as visualize are updated and their new value is changing something in the code and the robot behavior. For others such as maximum velocities, it did not happen.  
I'd like to add it to all the parameters, so we can dynamically reconfigure the MPPI controller, however, I am not sure if this controller was thought to change any parameter when a user sends a `ros2 param set` command. So, …
> Handle dynamically changes in parameters.

- nav2_mppi_controller/src/critics/obstacles_critic.cpp
- nav2_smac_planner/include/nav2_smac_planner/utils.hpp
---
| Ticket(s) this addresses   | #4066 |
| Primary OS tested on | Ubuntu 22.04 (Dev Container) |
---
Replaced redundant code with the introduction of the `getInflationLayer()` method.
---
> Updated code to use getInflationLayer() method

- nav2_dwb_controller/costmap_queue/CMakeLists.txt
---
| Ticket(s) this addresses   | None|
---
* Fixed static library link error in dwb-critics
---
> Change costmap_queue to shared library

- nav2_msgs/msg/CollisionMonitorState.msg
https://github.com/ros-planning/navigation2/issues/4052
> Update CollisionMonitorState.msg #4052

- nav2_bringup/launch/navigation_launch.py
Per discussion in slack with Jorge
> remap behavior cmd_vel to cmd_vel_nav to not bypass cmd pipeline

- nav2_system_tests/src/behaviors/spin/test_spin_behavior_node.cpp
- nav2_system_tests/src/waypoint_follower/tester.py
> Fix flaky system tests

- nav2_behavior_tree/src/generate_nav2_tree_nodes_xml.cpp
> Fix BT.CPP import

- nav2_smac_planner/src/node_hybrid.cpp
> Fixing a typo in Smac Heuristic

- nav2_smac_planner/include/nav2_smac_planner/smac_planner_hybrid.hpp
- nav2_smac_planner/src/smac_planner_hybrid.cpp
- nav2_smac_planner/test/test_smac_hybrid.cpp
Addresses https://github.com/ros-planning/navigation2/issues/3991
> allowing costmap to change with new costmap resolutions

- nav2_amcl/src/pf/CMakeLists.txt
---
---
When I build `nav2_amcl` with `-Wl,--no-undefined` I noticed `libpf_lib.so` has undefined symbols. This PR correctly links `libpf_lib.so` to `libm` so all symbols can be found.
You can verify this by executing the following command:
```
ldd -r ./build/nav2_amcl/src/pf/libpf_lib.so
linux-vdso.so.1 (0x00007ffd1f8c0000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x000074e909a00000)
/lib64/ld-linux-x86-64.so.2 (0x000074e909e60000)
undefined symbol: ceil	(./build/nav2_amcl/src/pf/libpf_lib.so)
undefined symbol: atan2	(./build/nav2_amcl/src/pf/libpf_lib.so)
undefined …
```
> Fix undefined symbols in `libpf_lib.so`

- nav2_mppi_controller/src/optimizer.cpp
To fix https://github.com/open-navigation/navigation2/issues/4315
---
| Ticket(s) this addresses   | [#4315] |
| Robotic platform tested on | Customized gazebo robot model |
---
> Add dynamic parameter

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/bt_cancel_action_node.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp
> Fix error messages for `wait_for_service_timeout`

- Dockerfile
---
| Ticket(s) this addresses   | #4461  |
| Primary OS tested on | Docker |
---
- fixed Dockerfile for the empty continuation line warning
> Fixed DockerFile build warning

- nav2_system_tests/CMakeLists.txt
- nav2_system_tests/src/behaviors/spin/CMakeLists.txt
- nav2_system_tests/src/behaviors/spin/test_spin_behavior_fake_launch.py
- nav2_system_tests/src/behaviors/spin/test_spin_behavior_launch.py
---
---
* Port spin behavior to new gazebo.
* Related issue https://github.com/ros-navigation/navigation2/issues/4455
---
> port spin behavior to new gazebo

- nav2_behavior_tree/package.xml
- nav2_behaviors/package.xml
- nav2_bt_navigator/package.xml
- nav2_dwb_controller/dwb_core/package.xml
- nav2_navfn_planner/package.xml
- nav2_planner/package.xml
- nav2_system_tests/package.xml
- nav2_util/package.xml
#4435 to give debians a description field
> Adding descriptions to package.xmls

- .github/mergify.yml
> Add mergify backport bot for Jazzy

- nav2_docking/README.md
- nav2_docking/opennav_docking/include/opennav_docking/simple_charging_dock.hpp
- nav2_docking/opennav_docking/include/opennav_docking/types.hpp
- nav2_docking/opennav_docking/include/opennav_docking/utils.hpp
- nav2_docking/opennav_docking/src/docking_server.cpp
- nav2_docking/opennav_docking/src/simple_charging_dock.cpp
- nav2_docking/opennav_docking/test/test_dock_file.yaml
- nav2_docking/opennav_docking/test/test_simple_charging_dock.cpp
- nav2_docking/opennav_docking/test/test_utils.cpp
- nav2_docking/opennav_docking/test/testing_dock.cpp
- nav2_docking/opennav_docking_core/include/opennav_docking_core/charging_dock.hpp
Opening https://github.com/open-navigation/opennav_docking/pull/46 for navigation2 as well
> Add dock id

- nav2_bringup/launch/cloned_multi_tb3_simulation_launch.py
- nav2_bringup/launch/tb3_simulation_launch.py
- nav2_bringup/launch/tb4_simulation_launch.py
- nav2_bringup/launch/unique_multi_tb3_simulation_launch.py
- nav2_system_tests/src/behaviors/assisted_teleop/test_assisted_teleop_behavior_launch.py
- nav2_system_tests/src/behaviors/spin/test_spin_behavior_launch.py
- nav2_system_tests/src/costmap_filters/test_keepout_launch.py
- nav2_system_tests/src/costmap_filters/test_speed_launch.py
- nav2_system_tests/src/localization/test_localization_launch.py
- nav2_system_tests/src/system/test_system_launch.py
- nav2_system_tests/src/system/test_system_with_obstacle_launch.py
- nav2_system_tests/src/system/test_wrong_init_pose_launch.py
- nav2_system_tests/src/system_failure/test_system_failure_launch.py
- nav2_system_tests/src/waypoint_follower/test_case_py.launch
> Replacing gz sim launch file with gz directly to avoid zombie processes

- nav2_docking/opennav_docking_bt/include/opennav_docking_bt/dock_robot.hpp
- nav2_docking/opennav_docking_bt/include/opennav_docking_bt/undock_robot.hpp
Reopening https://github.com/open-navigation/opennav_docking/pull/50
> Fix error_code_id

- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/get_pose_from_path_action.hpp
- nav2_behavior_tree/plugins/action/get_pose_from_path_action.cpp
- nav2_behavior_tree/test/plugins/action/test_get_pose_from_path_action.cpp
#4525 broke humble because of wrong include paths.
> Make #4525 compile on humble

- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/get_pose_from_path_action.hpp
- nav2_behavior_tree/plugins/action/get_pose_from_path_action.cpp
- nav2_behavior_tree/test/plugins/action/test_get_pose_from_path_action.cpp
Iron version of https://github.com/ros-navigation/navigation2/pull/4526, thanks @christophfroehlich
> Fixing iron for backport of get pose from path action addition

- nav2_graceful_controller/include/nav2_graceful_controller/ego_polar_coords.hpp
- nav2_graceful_controller/include/nav2_graceful_controller/smooth_control_law.hpp
- nav2_graceful_controller/src/smooth_control_law.cpp
- nav2_graceful_controller/test/test_egopolar.cpp
---
| Robotic platform tested on | Gazebo classic |
---
- Fix computation of linear and angular velocities to allow correct backward motion.
- It can be backported to other branches.
---
> Fix backward motion for graceful controller

- nav2_amcl/src/amcl_node.cpp
Resolves https://github.com/ros-navigation/navigation2/issues/4537
> Fix race condition in AMCL for #4537

- nav2_bringup/rviz/nav2_namespaced_view.rviz
Per https://github.com/ros-navigation/navigation2/issues/4623
> readding namespaced rviz config

- nav2_smac_planner/src/node_hybrid.cpp
- nav2_smac_planner/src/smac_planner_hybrid.cpp
- nav2_smac_planner/test/test_nodehybrid.cpp
Closing https://github.com/ros-navigation/navigation2/issues/4596
Thanks @corot!
> Update Smac Planner for rounding to closest bin rather than flooring

- nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp
- nav2_smoother/src/savitzky_golay_smoother.cpp
Closes https://github.com/ros-navigation/navigation2/issues/4665
> Fixing and refactoring Sovitsky-Golay Filter in MPPI and Smoother

- nav2_mppi_controller/src/trajectory_visualizer.cpp
- nav2_mppi_controller/test/trajectory_visualizer_tests.cpp
---
| Robotic platform tested on | Husarion UGV Panther|
---
* Added namespace to `trajectory` MarkerArray topic to nav2_mppi_controller
* Changed the root of the topic name, so need to add that to default configs and documentation page
> Namespaced MPPI Trajectories visualizer

- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/remove_passed_goals_action.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/condition/goal_reached_condition.hpp
- nav2_behavior_tree/nav2_tree_nodes.xml
- nav2_bringup/params/nav2_params.yaml
- nav2_bt_navigator/include/nav2_bt_navigator/bt_navigator.hpp
- nav2_bt_navigator/src/bt_navigator.cpp
- nav2_system_tests/src/gps_navigation/nav2_no_map_params.yaml
- nav2_system_tests/src/system/nav2_system_params.yaml
---
---
- Modified nav2_tree_nodes.xml to stay consistent with the code 
I have raised a PR for the docs https://github.com/ros-navigation/docs.nav2.org/pull/648
---
2 questions here:
- We have a condition called GlobalUpdatedGoal in some places and GloballyUpdatedGoal in others. Should we maintain consistency in the naming, or is this discrepancy intentional? https://docs.nav2.org/configuration/packages/bt-plugins/conditions/GloballyUpdatedGoal.html
- For [speed controller](https://docs.nav2.org/configuration/packages/bt-plugins/decorators/SpeedController.html), there used …
> Edit bt nodes ports to stay consistent with the docs

- nav2_behavior_tree/nav2_tree_nodes.xml
| Robotic platform tested on | Not needed |
| Does this PR contain AI generated software? | Nope |
---
-  Fix formatting.
- Added DockRobot and UndockRobot to nav2_tree_nodes.xml
---
> Added docking to BT xml

- nav2_docking/opennav_docking/src/navigator.cpp
- nav2_docking/opennav_docking/test/test_navigator.cpp
---
---
* Replaced "declare_parameter("navigator_bt_xml")" with declare_parameter_if_not_declared in the docking_server navigator. This change allows the docking server to be deactivated and activated again.
* Added a new test to navigator.
---
> Declare_parameter_if_not_declared in docking navigator

- nav2_bringup/params/nav2_params.yaml
- nav2_mppi_controller/include/nav2_mppi_controller/critics/cost_critic.hpp
- nav2_mppi_controller/src/critics/cost_critic.cpp
- nav2_mppi_controller/src/critics/obstacles_critic.cpp
- nav2_mppi_controller/test/critics_tests.cpp
> Backport #4996 (Jazzy)

- .github/workflows/lint.yml
- nav2_collision_monitor/launch/collision_detector_node.launch.py
- nav2_collision_monitor/launch/collision_monitor_node.launch.py
---
---
* Corrected unsafe fixes using `ruff` - `ruff check --select UP --fix --unsafe-fixes nav2_collision_monitor`
* Restructured `nav2_collision_monitor` for strict mypy.
* N/A
---
* N/A
> Mypy nav2_collision_monitor

- .github/workflows/lint.yml
- nav2_costmap_2d/test/integration/costmap_tests_launch.py
- nav2_costmap_2d/test/test_launch_files/costmap_map_server.launch.py
- tools/pyproject.toml
---
---
* Corrected unsafe fixes using `ruff` - `ruff check --select UP --fix --unsafe-fixes nav2_costmap_2d`
* Restructured `nav2_costmap_2d` for strict mypy.
* N/A
---
* N/A
> Mypy nav2 costmap 2d

- .github/workflows/lint.yml
- nav2_lifecycle_manager/test/launch_bond_test.py
- nav2_lifecycle_manager/test/launch_lifecycle_test.py
---
---
* Corrected unsafe fixes using `ruff` - `ruff check --select UP --fix --unsafe-fixes nav2_lifecycle_manager`
* Restructured `nav2_lifecycle_manager` for strict mypy.
* N/A
---
* N/A
> Mypy nav2 lifecycle manager

- .github/workflows/lint.yml
- nav2_map_server/launch/map_saver_server.launch.py
- nav2_map_server/test/component/test_map_saver_launch.py
- nav2_map_server/test/component/test_map_server_launch.py
- nav2_map_server/test/test_launch_files/map_saver_node.launch.py
- nav2_map_server/test/test_launch_files/map_server_node.launch.py
---
---
* Corrected unsafe fixes using `ruff` - `ruff check --select UP --fix --unsafe-fixes nav2_map_server`
* Restructured `nav2_map_server` for strict mypy.
* N/A
---
* N/A
> Mypy nav2 map server

- nav2_behavior_tree/plugins/action/controller_selector_node.cpp
- nav2_behavior_tree/plugins/action/planner_selector_node.cpp
- nav2_behavior_tree/plugins/action/smoother_selector_node.cpp
- nav2_behavior_tree/plugins/condition/is_battery_charging_condition.cpp
- nav2_behavior_tree/plugins/condition/is_battery_low_condition.cpp
- nav2_behavior_tree/plugins/decorator/goal_updater_node.cpp
---
| Ticket(s) this addresses   | #5041 |
| Robotic platform tested on | Morphia robot |
| Does this PR contain AI generated software? | Nope |
---
* Added a double spin_some in is_battery_charging_condition , is_battery_low_condition and XYZ_selector_node to temporary fix a rclcpp regression.
---
> Add double spin_some in some BT nodes

- nav2_bringup/params/nav2_params.yaml
Resolves: https://github.com/ros-navigation/navigation2/issues/5066
> Remove docking absolute topic namespaces

- nav2_behavior_tree/include/nav2_behavior_tree/behavior_tree_engine.hpp
- nav2_behavior_tree/src/behavior_tree_engine.cpp
---
---
* Fix name consistency for Groot 2 monitoring.
---
> Consistency in Groot 2

- nav2_msgs/action/__init__.py
- nav2_msgs/msg/__init__.py
- nav2_simple_commander/launch/route_example_launch.py
- nav2_simple_commander/nav2_simple_commander/example_route.py
- nav2_simple_commander/nav2_simple_commander/robot_navigator.py
- tools/pyproject.toml
---
| Ticket(s) this addresses   |#5056 |
---
* Corrected unsafe fixes using `ruff` - `ruff check --select UP --fix --unsafe-fixes nav2_simple_commander`
* Restructured `nav2_simple_commander` for strict mypy.
* N/A
---
* N/A
> Configuring nav2_route_server branch to be mypy compliant

- nav2_system_tests/src/behaviors/assisted_teleop/test_assisted_teleop_behavior_launch.py
- nav2_system_tests/src/behaviors/wait/test_wait_behavior_launch.py
- nav2_system_tests/src/gps_navigation/test_case_py.launch.py
- nav2_system_tests/src/route/test_route_launch.py
- nav2_system_tests/src/route/tester_node.py
- tools/pyproject.toml
---
| Ticket(s) this addresses   |#5056 |
---
* Corrected unsafe fixes using `ruff` - `ruff check --select UP --fix --unsafe-fixes nav2_system_tests`
* Restructured `nav2_system_tests` for strict mypy.
* N/A
---
* N/A
> Configuring nav2_route_server branch to be mypy compliant - Iteration 2

- nav2_smac_planner/include/nav2_smac_planner/utils.hpp
---
---
Precompute value, minor changes, not big optimization
---
> Precompute yaw trigonometric values in smac planner

- .github/workflows/update_ci_image.yaml
precursor to https://github.com/ros-navigation/navigation2/pull/5119
> Update update_ci_image.yaml to include jazzy build

- .circleci/config.yml
- .github/workflows/lint.yml
- .github/workflows/update_ci_image.yaml
- Dockerfile
- tools/distro.Dockerfile
- tools/underlay.repos
Updating files for Jazzy's CI to turn over
> Adding CI to Jazzy branch 

- nav2_amcl/include/nav2_amcl/amcl_node.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/obstacle_layer.hpp
- nav2_costmap_2d/plugins/obstacle_layer.cpp
---
---
Compilation
```
/opt/ros/rolling/include/message_filters/message_filters/synchronizer.h:18:2: warning: #warning This header is obsolete, please include message_filters/synchronizer.hpp instead [-Wcpp]
18 | #warning This header is obsolete, please include message_filters/synchronizer.hpp instead
|  ^~~~~~~
```
These headers are backported to humble so this works.
How is this section different from "Description of testing performed"?
---
> message_filters hpp headers have been backported

- README.md
---
---
* N/A
* Shifted citation text to be within the bullet points.
* Formatted bibtex snippets according to the [Bibtex](https://bibtex.eu/types/proceedings/) documentation example.
* N/A
* N/A
---
* N/A
> Bibtex formatting

- nav2_mppi_controller/src/optimizer.cpp
---
---
- Fix a bug where the motion_model is not reset when the optimizer is reset. This causes parameters changes to not be updated in the motion model, even though they are updated in the optimizer.
- I noticed the MPPI behavior getting worse when dynamically changing control constraints (in my case `az_max`)
None
The old fashion way - using prints:
Added this print after the line changed in this PR.
```
std::cout << "Optimizer::reset: " << "\n settings_.constraints.az_max: "
<< settings_.constraints.az_max
<< "\n settings_.base_constraints.az_max: " << …
```
> [nav2_mppi_controller] Reset motion model with optimizer (for param change)

- nav2_docking/opennav_docking/src/docking_server.cpp
Resolves https://github.com/ros-navigation/navigation2/issues/5144
> Fixing docking server when already docked at the requested dock

- nav2_route/include/nav2_route/plugins/edge_cost_functions/goal_orientation_scorer.hpp
- nav2_route/include/nav2_route/plugins/edge_cost_functions/start_pose_orientation_scorer.hpp
Small change, CI will catch issues with it.
> tf2 uses hpp headers in rolling (and is backported)

- nav2_mppi_controller/test/parameter_handler_test.cpp
Got confused by reading this test. Adapting for better readability.
> Nav2Controller Increase Readability of one test

- nav2_controller/include/nav2_controller/controller_server.hpp
- nav2_controller/src/controller_server.cpp
---
| Robotic platform tested on | ([Arter](https://robotik.dfki-bremen.de/de/forschung/robotersysteme/arter)) |
---
* We need to have a smooth transition in between segments of a path without the linear and angular velocities resetted to zero. I copied the change from the main to the humble branch.
AS-IS:
The humble branch currently resets the cmd_vel to zero upon goal exit. This results in unwanted /cmd_vel jumps to 0 for robots which required a piece-wise path following approach over a segmented global path.
TO-BE:
After the parameter is added and set to false the cmd's have smooth transitions in …
> Add parameter publish_zero_velocity from branch main->humble

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
- nav2_behavior_tree/plugins/action/get_pose_from_path_action.cpp
- nav2_behavior_tree/plugins/decorator/speed_controller.cpp
- nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
- nav2_bringup/launch/bringup_launch.py
- nav2_bringup/launch/cloned_multi_tb3_simulation_launch.py
- nav2_collision_monitor/include/nav2_collision_monitor/polygon.hpp
- nav2_collision_monitor/src/polygon.cpp
- nav2_collision_monitor/test/collision_monitor_node_test.cpp
- nav2_costmap_2d/include/nav2_costmap_2d/denoise/image_processing.hpp
- nav2_costmap_2d/src/costmap_2d_ros.cpp
- nav2_costmap_2d/test/unit/denoise_layer_test.cpp
- nav2_costmap_2d/test/unit/image_processing_test.cpp
- nav2_mppi_controller/include/nav2_mppi_controller/critic_manager.hpp
- nav2_mppi_controller/include/nav2_mppi_controller/motion_models.hpp
- nav2_rotation_shim_controller/src/nav2_rotation_shim_controller.cpp
- nav2_smac_planner/src/a_star.cpp
- nav2_util/include/nav2_util/robot_utils.hpp
---
| Ticket(s) this addresses   | ( #5230) |
| Robotic platform tested on | (none) |
---
I tried to modified some files about lint issues that occurred after using `colcon test` in humble branch.
After modifying these files, there are no lint issues when I run `colcon test` .
> fix some lint issues for humble branch

- nav2_amcl/src/motion_model/differential_motion_model.cpp
| Ticket(s) this addresses   | None  |
---
The `differential_motion_model.cpp` file uses `std::min`, so it needs to include the `algorithm` header, see https://en.cppreference.com/w/cpp/algorithm/min.html .
None.
It test if it compiled.
---
None.
> Add missing include of algorithm in differential_motion_model.cpp

- nav2_docking/opennav_docking/src/docking_server.cpp
> Eexception rethrow in dockRobot method

- nav2_loopback_sim/nav2_loopback_sim/loopback_simulator.py
- nav2_simple_commander/nav2_simple_commander/robot_navigator.py
- nav2_system_tests/src/behaviors/backup/backup_tester.py
- nav2_system_tests/src/behaviors/drive_on_heading/drive_tester.py
- nav2_system_tests/src/behaviors/spin/spin_tester.py
- nav2_system_tests/src/costmap_filters/tester_node.py
- nav2_system_tests/src/gps_navigation/tester.py
- nav2_system_tests/src/route/tester_node.py
- nav2_system_tests/src/system/nav_through_poses_tester_node.py
- nav2_system_tests/src/system/nav_to_pose_tester_node.py
- nav2_system_tests/src/system_failure/tester_node.py
- nav2_system_tests/src/waypoint_follower/tester.py
---
| Ticket(s) this addresses   | #5370    |
| Does this PR contain AI-generated software? | No |
---
* Migrated [RcutilsLogger](https://github.com/ros2/rclpy/blob/rolling/rclpy/rclpy/impl/rcutils_logger.py#L422) to use `warning` instead of `warn` as a member.
* Removed redundant `attr-defined` mypy comments.
* N/A
* Ran local pre-commits before publishing.
* N/A
> Added fixes for ament_mypy

- nav2_costmap_2d/plugins/voxel_layer.cpp
---
| Ticket(s) this addresses   | related to https://github.com/ros-navigation/navigation2/pull/3211 |
---
Added global min obstacle height in voxel layer
---
> Add global min obstacle height in voxel layer

- .circleci/config.yml
Attempting to get CI to kick over due to hitting build limits
> CI Limits: Moving MPPI, Smac to secondary job

- nav2_util/include/nav2_util/lifecycle_node.hpp
- nav2_util/src/lifecycle_node.cpp
> Fix bad_weak_ptr in createBond() by using shared_ptr (backport #5341)
